### PR TITLE
Adds T5 and T6 parts. (Sprites from Fulpstation)

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request
Bluespace parts are T5 parts, but they have better stats.
Adds new T4 parts (same strength as previous bluespace parts.)
Adds new T6 Quantum parts. Sprites were ported from Fulpstation.
Rebalances research.

## Why It's Good For The Game
This balances the progression of science/research to more reasonable values and also allows for some pretty crazy things. The goal is that T4 parts should be obtained at normal rates while T5 and T6 are meant for very late game (Maybe an hour into the round, depends on how good research is) so there can be some pretty interesting projects.

## Changelog
:cl:
add: Adds T5 and T6 parts.
balance: Moves research costs around to support T5 and T6 parts.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Im actually quite interested in how these will pan out, although I think it should definitely be a testmerge before considering a fullmerge. Hopefully this will help to solve the current issue regarding materials, and the constant shortages that occur because of Citadel's incompetence.

**Comment by BurgerLUA** [comment]
Probably best to testmerge this as it changes a lot and players are going to either be complaining they're too easy to get or too hard to get.

**Comment by LimblessLayabout** [comment]
My atmosian roommate (not a skyrat player) brings up concerns with higher efficiency freezers and heaters. Reaching sub-zero kelvin with these new stock parts may break the gamestate (rolling the integer under and setting space on fire).
Additionally, having heaters that can ignite fusion all by themselves may be... desirable? Maybe not? I'm going to see about testing a local instance for these specific cases.

**Comment by EldritchSigma** [comment]
Semantics are shit I know but.. Femto manipulator is called femto manipulator because it manipulates at the following scale: 1*10^-15 [SI unit], Mega is 1*10^6 [SI unit]. So basicly calling the new T4 manipulator "mega manipulator" wouldn't make much sense in that way I dunno. Yeah its just semantics but I still find that a bit off for a name

**Comment by davidchan13** [comment]
http://2.bp.blogspot.com/_8zkA5b3U2s0/R6mOW8L_-7I/AAAAAAAAAUs/YiUwuTvlgZ4/s1600/prefixesunites.png

T4 manips should be called femto regardless to stay with the theme of each upgrade operating 1 magnitute smaller than the previous. T5 would be Atto Manips and T6 would be Zepto.

Also naming everything in a tier 'Mega' is just lazy and breaks the convention that each part tree has going.

**Comment by BurgerLUA** [comment]
The need universal names. I will change it from mega but I'm not going to be using old standards because old standards are dumb. All parts should be.

Basic
Advanced
Super
Hyper
Bluespace
Quantum

**Comment by jjpark-kb** [comment]
Science is too easy with no drawbacks. Even higher tier parts could cause unseen issues. Closing for now.

**Comment by BurgerLUA** [comment]
weird reason to close a PR but okay

**Pull request closed without merging**
