### PR TITLE
[WIP] [DNM] Small characters can now fit inside pet carriers.

### PR DESCRIPTION
**Pull request by Weblure**
**TODO:**

- [ ] Fix pet carriers suffocating inhabitants
- [ ] Allow players to insert themselves into pet carriers (drag & drop self, ideally)
- [ ] Consider potential abuse scenarios and balance accordingly (faster breakout time?)
- [ ] Convince admins that they should lower the minimum sprite size once the [small strides fix PR](./2742) gets merged

## About The Pull Request

Allows players to be placed into a pet carrier if their sprite size is small enough.

## Why It's Good For The Game

_Uuuuuuuuuuuuh_

## Changelog
:cl:
add: Players with a sprite size at or below 75% can enter or be placed into pet carriers.
/:cl:

### CODE REVIEW

**Comment by frontline03** [comment]
Noone can go below 85% sprite size

**Comment by Owai-Seek** [comment]
There is a companion PR that changes the way sprite size works so it's no longer based on thresholds. @frontline03 

https://github.com/Skyrat-SS13/Skyrat13/pull/2742

**Comment by Weblure** [comment]
> Noone can go below 85% sprite size

> - [ ] Convince admins that they should lower the minimum sprite size once the [small strides fix PR](./2742) gets merged

I'm aware

**Comment by Weblure** [comment]
> There is a companion PR that changes the way sprite size works so it's no longer based on thresholds. 

Nah, that PR just fixes the formula to make it work as intended. But once it works as intended, I'm going to try convincing the admins to start testing different config settings, such as removing (or at least increasing) the threshold and also lowing the minimum sprite size since smaller sprites will now properly be proportionately slower.

**Comment by Akrilla** [comment]
status of this?

**Comment by Weblure** [comment]
I forgot drafts were a thing

**Comment by Weblure** [comment]
How can a draft go stale?

**Pull request closed without merging**
