### PR TITLE
Adds new languages

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request
Humans, Shadowpeeps, Plasmemes, and podpeople now get their own unique language, with a special icon and all!

## Why It's Good For The Game
HUMAN GANG HUMAN GANG

Also new languages out the ass

## Changelog
:cl:
add: New language for humans, moth, shadowpeople, plasmemes, and podpeople
imageadd: icons for each language

/:cl:

### CODE REVIEW

**Comment by PersianXerxes** [comment]
smh Latin instead of Esperanto? My immersion is shattered

**Comment by Sir-Lagsalot** [comment]
Racial languages BAD

**Comment by KathrinBailey** [comment]
We really need an option for second languages in character creation to be honest. It's going to suck when you're the one race that doesn't have a meta-clique language.

**Comment by Useroth** [comment]
I like this, if we can pick 1-2 other languages to speak, a'la some bay-derivative codebases

**Comment by ForrestWick** [comment]
> I like this, if we can pick 1-2 other languages to speak, a'la some bay-derivative codebases

Merge them for now until we have that system

**Comment by Useroth** [comment]
I think I'm gonna agree with Azarak that it would be nice to have a system in place to pick an extra language or two.

**Pull request closed without merging**
