### PR TITLE
adds kudzu turf, nerfs venus

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
small port of: https://github.com/tgstation/tgstation/pull/51512
adds a kudzu turf that is created when kudzu spreads into space
halved the timer for the plant to spawn venus plants
changed venus plants stun to a knockdown
added thermal and xray to venus plants so they can see through their vines
venus now heal on all vines
venus will no longer get hurt by thorny

## Why It's Good For The Game
venus plants are oppressive and need a bit of a nerf, especially with bobmed.
having turfs for kudzu makes fighting it in space easier.

## Changelog
:cl:
add: Added kudzu turf that is created when kudzu spreads into space
add: Added thermal and xray to venus plants so they can see through their vines
add: Venus heal on all vines
balance: halved the timer for the plant to spawn venus plants
balance: changed venus plants stun to a knockdown
fix: Venus no longer take damage from thorny
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
consider fixing the bug where thorny and agressive spread damages the venus traps

**Comment by ThatGuyFromThatPlace** [comment]
Damage nerf and hard stun removal is a pretty good idea. (Though, honestly, you could live with just the stun being change to knockdown.)
After the buffs to make venus plants player controlled, and, the fact that plants spawn much earlier, Kudzu has become _almost_ blob tier, with the only thing stopping it from being as strong as a blob that it isn't player controlled itself, and, can't _directly_ end the round (Though, it has _indirectly_ ended the round since its buffs)

The ability to see through their own vines, is, quite honestly, fine as compensation, as, the issue is damage and stuns, giving them QOL to compensate for that is beyond fine, and, in TG's PR, that's **all** they did

**However**, I'd say lowering their damage from 25 to 10 is, **overkill**.
That's lowering from very mildly **overpowered**, to extremely _underpowered_, especially with the combo of removing their stun. A kitchen knife does 10 damage. A hatchet or shortsword 12. A butchers cleaver, makeshift sword or circular saw 15. This makes it weaker than the average assistant who just visited an autolathe, and, god forbid they went to Xenoarch and picked up an explorer suit to reduce the damage by 35% (Down to 6.5 damage). Not to mention the Chaplain or any security member in Riot armour reducing it by 50% (Down to 5), and, getting weapons that can do considerably more than 15 (Chaplain can get a weapon that does 30 damage, and, most of his weapons do 18)

Honestly, if I had to suggest any changes past this, CM alien style inability to hit corpses, so, they can't fuck someone over further than necessary. Once they're dead, hitting them further is just keeping them out of the round and making medbay's job unnecessarily harder

**Comment by NotRanged** [comment]
Also, how would the kudzu turf be able to be removed?

**Comment by Echopsychotic** [comment]
Can I ask that something is added to this PR about flytraps being damaged by their own thorns?

**Comment by jjpark-kb** [comment]
got approved, shamelessly merging.

**Pull request merged**
