### PR TITLE
Reworks Wormholes

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Wormholes no longer shift their location every 3 seconds. The wormholes that start during the event are wormholes that will always stay.

Wormholes now have persistent/consistent teleport locations.

Wormholes now have animation effects.

## Why It's Good For The Game

Wormholes are pretty shit. This hasn't happened to me but I don't think it's good game design that you can easily space yourself because you walked into a tile that spawned directly in front of you while moving and without much warning. This PR makes it so you can easily save yourself that this occurs, so it doesn't remove the danger of it.

## Changelog
:cl: BurgerBB
balance: Reworks/rebalances wormholes.
/:cl:

### CODE REVIEW

**Comment by Afya212** [comment]
Looks good.

**Comment by KathrinBailey** [comment]
Wormholes that don't move are considerably worse. If a wormhole spawns blocking a door, you're just done for. You can't really get out.
Blacklist space and nearspace to prevent most instances of spacing yourself if that's what you want. Keeping wormholes stationary will quickly become incredibly annoying when half of your department is rwall and you aren't carrying a full toolbelt and welder to break out.

**Comment by BurgerLUA** [comment]
> Wormholes that don't move are considerably worse. If a wormhole spawns blocking a door, you're just done for. You can't really get out.
> Blacklist space and nearspace to prevent most instances of spacing yourself if that's what you want. Keeping wormholes stationary will quickly become incredibly annoying when half of your department is rwall and you aren't carrying a full toolbelt and welder to break out.

Clicking on wormholes lets you go in them. You won't be able to be stuck in r_walls with this as you'll just go back in the way you came.

**Comment by ForrestWick** [comment]
I'd prefer current wormholes. This not only feels like a hugbox, but it'll result in a lot of frustration tbh. People gotta learn to either stop moving or be VERY careful with it. It's not hard in the slightest to count seconds as you take slow steps

**Comment by AsaiasWolffe** [comment]
Wormholes are already stupid easy to be safe from, just stand still and you're fine. It's literally the only event that can be completely thwarted by NOT MOVING! Hugboxing something that you can counter simply by taking your hands off the keyboard is in my opinion, moronic.

**Comment by BurgerLUA** [comment]
>hugbox

"anything I don't like is a hugbox"

Current wormhole events pauses gameplay for 2 minutes. As you said literally everyone stops moving during this happening, so it pretty much pauses gameplay for an entire 2 minutes while other people test their luck with shitty RNG wormholes.

The criticism about how only idiots die from this is extremely dumb and comes from a mind not understanding of what the wormhole event does.

It spawns wormholes randomly on the station.
Rarely someone walks into it, but it does happen.
It waits ~6 seconds.
It alerts the crew of the wormholes.
Everyone waits 2 or so minutes until it disappears. Some enter the wormhole.
It disappears.

The primary issue is that it puts everything on pause, like the old scrubbers event which I reworked for the same reasons. Average killcount from this event is about 3-6 people on highpop depending on the day of the week. That's out of like 100 so it's no big deal. I don't care if events kill people but it's kinda dumb that the wormhole event has an actual chance to space you randomly without possible return to the station because you got extremely unlucky. This PR fixes that by making the wormholes persistent.

**Comment by Akrilla** [comment]
Make this a separate kind of wormhole event

**Comment by Azarak** [comment]
I like those changes

**Comment by Weblure** [comment]
> Wormholes that don't move are considerably worse. If a wormhole spawns blocking a door, you're just done for. You can't really get out.
> Blacklist space and nearspace to prevent most instances of spacing yourself if that's what you want. Keeping wormholes stationary will quickly become incredibly annoying when half of your department is rwall and you aren't carrying a full toolbelt and welder to break out.

Considering that it currently grinds the entire station to a halt and has the chance of randomly teleporting someone into space, into a wall, or worst of all, _2 blocks deep into an asteroid_, this problem pales in comparison. 

Also, a door being blocked is not really a problem, since you can just step into the wormhole and then -- since wormholes are permanently linked to one another -- just click on the wormhole to return to that spot, and then step through to the other side of the door. Most departments and areas also have multiple doors to escape through, so I don't see that happening very often.

I guess an alternative to this PR would be to announce a warning about wormholes well in advance to when they spawn (so people don't randomly walk into a wormhole just as they first spawn out of sheer bad luck), keep them linked to each other like what this PR does, and have them continue to move at random, though at a much slower rate.

**Comment by hugmeorelse** [comment]
> Wormholes are already stupid easy to be safe from, just stand still and you're fine. It's literally the only event that can be completely thwarted by NOT MOVING! Hugboxing something that you can counter simply by taking your hands off the keyboard is in my opinion, moronic.

You could have said that without the toxicity. Consider this a warning. You can state your opinion honestly without being rude.

**Comment by Azarak** [comment]
@BurgerLUA Make this a seperate event instead and I'd love to merge it

**Comment by hugmeorelse** [comment]
> Wormholes are already stupid easy to be safe from, just stand still and you're fine. It's literally the only event that can be completely thwarted by NOT MOVING! Hugboxing something that you can counter simply by taking your hands off the keyboard is in my opinion, moronic.

I commented just now on how rude you were being, but I realized you were calling the idea "moronic", not the person. The comma threw me off. My mistake!

**Comment by hugmeorelse** [comment]
On a separate note, I do think this being a separate event could be interesting. Variation is always fun. 

Anyways, I can see both side's arguments. They're both very good, but I think there are tweaks that can be done to satisfy both sides.

**Comment by BurgerLUA** [comment]
A separate event would honestly be really dumb and defeats the purpose of this PR.
There shouldn't be events that halt the flow of gameplay. Events should give some benefits to traitors or give the crew something to do. This PR prevents the first and does the second and third.

**Comment by TheSpaghetti** [comment]
salt

**Comment by Akrilla** [comment]
A rare event that does slows/halts the overall flow of the round isn't that crazy of an idea. Giving wormholes the animation effects, and then splitting this and the current version into two separate events seems reasonable. You can decide how rare/common you make each variation.

**Comment by Weblure** [comment]
> A rare event that does slows/halts the overall flow of the round for a moment isn't that crazy of an idea. Giving wormholes the animation effects, and then splitting this and the current version into two separate events seems reasonable. You can decide how rare/common you make each variation.

We don't need two different wormhole events, that's just pointlessly redundant. This is the same exact thing, just less game-halting. Also, this event isn't nearly rare enough considering that it affects the entire station and there's 0 defense against it other than just... having the entire station sit on their ass for 5 minutes. And no, making it less common is not a good solution. It's a nice event to have around for antags, but there's no good reason to keep it how it currently is, and even less reason to keep it alongside this edited version.

**Comment by Akrilla** [comment]
> > A rare event that does slows/halts the overall flow of the round for a moment isn't that crazy of an idea. Giving wormholes the animation effects, and then splitting this and the current version into two separate events seems reasonable. You can decide how rare/common you make each variation.
> 
> We don't need two different wormhole events, that's just pointlessly redundant. This is the same exact thing, just less game-halting. Also, this event isn't nearly rare enough considering that it affects the entire station and there's 0 defense against it other than just... having the entire station sit on their ass for 5 minutes. And no, making it less common is not a good solution. It's a nice event to have around for antags, but there's no good reason to keep it how it currently is, and even less reason to keep it alongside this edited version.

If you're gonna make an argument, at least don't lie. The event lasts for 40-80 seconds. I've also never seen the entire station just stand still, most people go on their way - it's not like the game pauses for a minute. I personally see a place for two versions of the event, it can literally just be the same announce message, just a randomly selected variant. Another maintainer can overrule me on that, I don't see a need to completely replace moving wormholes when this could just be a version alongside it.

**Comment by Weblure** [comment]
> > > A rare event that does slows/halts the overall flow of the round for a moment isn't that crazy of an idea. Giving wormholes the animation effects, and then splitting this and the current version into two separate events seems reasonable. You can decide how rare/common you make each variation.
> > 
> > 
> > We don't need two different wormhole events, that's just pointlessly redundant. This is the same exact thing, just less game-halting. Also, this event isn't nearly rare enough considering that it affects the entire station and there's 0 defense against it other than just... having the entire station sit on their ass for 5 minutes. And no, making it less common is not a good solution. It's a nice event to have around for antags, but there's no good reason to keep it how it currently is, and even less reason to keep it alongside this edited version.
> 
> If you're gonna make an argument, at least don't lie. The event lasts for 40-80 seconds. I've also never seen the entire station just stand still, most people go on their way - it's not like the game pauses for a minute. I personally see a place for two versions of the event, it can literally just be the same announce message, just a randomly selected variant. Another maintainer can overrule me on that, I don't see a need to completely replace moving wormholes when this could just be a version alongside it.

With our server's horrid time dilation and lag, it easily ends up lasting for several minutes IRL. Those people that 'go on their way' occasionally end up having to be extracted from a wall or recovered as a husk from space; any movement during this event runs the risk of being randomly teleported with no way of returning. Having 2 versions of wormholes completely defeats the purpose of this PR, as stated multiple times.

**Comment by Akrilla** [comment]
Taking this off life support, I've asked for the changes I want, other maintainers can overrule me.

**Pull request closed without merging**
