### PR TITLE
[MIRROR] Updating ID Icons

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12535
--------------------

## About The Pull Request

Nothing to see, just better ID icons from /tg/. Also, BS emag now has it's own blue sprite!

## Why It's Good For The Game

This sprites are much better than those old ones. 

## Changelog
:cl:
add: New ID icons
/:cl:

### CODE REVIEW

**Comment by Afya212** [comment]
>:C But our pretty department-sprites. *scream

**Comment by ShadeAware** [comment]
Oh God, I hate this. This is awful.

**Comment by ShadeAware** [comment]
God these cards are fucking ugly as SIN

**Comment by KathrinBailey** [comment]
image
image
 Missing icons. This only affects roundstart IDs and doesn't change them with job changes.
This all works upstream, looking into it but until it's ready I'm chucking DNM on.

**Comment by KathrinBailey** [comment]
image
**Time to document what's happened here.**
**What has been changed from the original PR?**
IDs were referencing a modular skyrat dmi. References have been removed.
Jobs no longer check for a specific modular ID and instead just spawn the correct ones with the correct sprites and overlay.
Added brig phys + blueshield overlays for their IDs.

**Testing:**
Spawned as HoS and Blueshield, blueshield being a modular job.
Used the HoP terminal to change IDs and test that the sprite overlays work.
Spawned pretty much every ID there is to look at them and make sure they're using the overlays right.
ATMs are fully functional with the IDs.

**DMI change:**
Either an edit to a core dmi file happens or the entire ID cards and overlay system requires modularisation. It's much more 'modular' and compatible to change the core DMI file.
A comment has been made. Anyone who gets a conflict with a DMI should very easily be able to solve this, it'll take two minutes.
image

**Pull request merged**
