### PR TITLE
[small] Emagging training bombs

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Emag the training bomb and it becomes a real bomb.

## Why It's Good For The Game

"Don't worry captain, it seems like it's just a training bo-"

## Changelog
:cl:
add: You can now emag the training bomb. You can guess what that does...
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
How on earth do you hack a bomb into going from having no explosive in it to being explosives?
It doesn't make sense.
The emag is **SYNDICATE** item, **not a Wizard Federation item**. It's not magical. It can't turn an airlock into a dragon. You can't emag a wall into giving you a medkit. You can't emag someone's shoes and turn make them magically turn into some sort of iron man rocket boots. You can't emag a bomb with no payload into having a payload.

**Comment by NotRanged** [comment]
> How on earth do you hack a bomb into going from having no explosive in it to being explosives?
> It doesn't make sense.
> The emag is **SYNDICATE** item, **not a Wizard Federation item**. It's not magical. It can't turn an airlock into a dragon. You can't emag a wall into giving you a medkit. You can't emag someone's shoes and turn make them magically turn into some sort of iron man rocket boots. You can't emag a bomb with no payload into having a payload.
> 
> I appreciate trying to add stuff into the game but we don't need emags to start having functions for every object in the game. It's an emag, not a wizard staff.

While I get where you're coming from, an emagged game of minesweeper generates dozens of powerful explosions all around it on loss. An emagged geiger counter begins irradiating people. An emagged firebot suddenly synthesizes liquid chlorine trifluoride. An emagged goat plush starts throwing itself at people.

Is an emagged training bomb having it's core go live that far fetched?

**Comment by BobJoga** [comment]
> > How on earth do you hack a bomb into going from having no explosive in it to being explosives?
> > It doesn't make sense.
> > The emag is **SYNDICATE** item, **not a Wizard Federation item**. It's not magical. It can't turn an airlock into a dragon. You can't emag a wall into giving you a medkit. You can't emag someone's shoes and turn make them magically turn into some sort of iron man rocket boots. You can't emag a bomb with no payload into having a payload.
> > I appreciate trying to add stuff into the game but we don't need emags to start having functions for every object in the game. It's an emag, not a wizard staff.
> 
> While I get where you're coming from, an emagged game of minesweeper generates dozens of powerful explosions all around it on loss. An emagged geiger counter begins irradiating people. An emagged firebot suddenly synthesizes liquid chlorine trifluoride. An emagged goat plush starts throwing itself at people. The wizard federation didn't make emags, but they sure helped a hand in designing them.
> 
> Is an emagged training bomb having it's core go live that far fetched?

The problem isn't exactly the logic in this, which i think is fine since there is a lot of silly crap emags can do. The problem is... it's pretty much a free bomb...

**Comment by Azarak** [comment]
Emags do make some silly things, comparable to this is the minesweeper explosions, but its much smaller, could justify it with the arcade violently overloading. Putting a real payload is a bit too much and doesn't make all that much sense.

**Pull request closed without merging**
