### PR TITLE
Blaurung - Ash Drake Varient/RP Drake

### PR DESCRIPTION
**Pull request by DarkWolfInsanity**
_Github is such bullshit. Why is this so hard?_

"Ghost role" - Blaurung

An admin spawned Ash Drake with no agression unless attacked. Mostly used for Admemery roleplay. Blaurung acts much like a standard megafauna, with AI when not possessed, a gps beacon, and loot when killed.

-Blaurung has 2000 hp compared to a standard Ash Drake's 2500.
-He will never do a Swoop attack.
-He shoots fire in a straight line for 20 tiles, instead of the Ash Drake's cross for 6.
-Can actually see in darkness, with senses akin to the Eye of God item (they have six eyes, i mean come on)
-Melee damage range from 20-40 brute
-Moves faster than the standard drake to account for lack of swoop
-Dragon Language_Holder: Common, Draconic, Dwarf

To-do when I figure it out:
-Different loot on death
-Fire Line on a spell trigger so possessing players don't shoot fire trying to turn

### CODE REVIEW

**Comment by LimblessLayabout** [comment]
I actually dealt with manipulating a Space Dragon just last night, in order to provide for a roleplayer. This will be a much less fiddly solution, and safer to have around the station in general.

Sugg;
If you can reduce the length of the fire spray, so it doesn't fly beyond the borders of the screen (in all likelihood hitting unwanted targets), so much the better for safety.
In a perfect world I'd like to give specifically the RP-dragon a full set of organs (eyes, sex, and vore organs) as well as hands to work with, but babysteps.

**Comment by BobJoga** [comment]
> I actually dealt with manipulating a Space Dragon just last night, in order to provide for a roleplayer. This will be a much less fiddly solution, and safer to have around the station in general.
> 
> Sugg;
> If you can reduce the length of the fire spray, so it doesn't fly beyond the borders of the screen (in all likelihood hitting unwanted targets), so much the better for safety.
> In a perfect world I'd like to give specifically the RP-dragon a full set of organs (eyes, sex, and vore organs) as well as hands to work with, but babysteps.

To do that would require making another mob entirely,most probably a carbon one. And it wouldn't be very easy.

**Comment by DarkWolfInsanity** [comment]
> 
> 
> > I actually dealt with manipulating a Space Dragon just last night, in order to provide for a roleplayer. This will be a much less fiddly solution, and safer to have around the station in general.
> > Sugg;
> > If you can reduce the length of the fire spray, so it doesn't fly beyond the borders of the screen (in all likelihood hitting unwanted targets), so much the better for safety.
> > In a perfect world I'd like to give specifically the RP-dragon a full set of organs (eyes, sex, and vore organs) as well as hands to work with, but babysteps.
> 
> To do that would require making another mob entirely,most probably a carbon one. And it wouldn't be very easy.

I'll give it a look over at some point, but not at the moment. It would involve basically making a "pseudo-human" species, and that's beyond my capabilities at the moment.

**Comment by BobJoga** [comment]
Also
>not naming the ghost role Alduin or some other skyrim dragon

**Comment by DarkWolfInsanity** [comment]
> 
> 
> Also
> 
> > not naming the ghost role Alduin or some other skyrim dragon
> 
> fake ass glaurung smh

Bitch, I AM GLAURUNG
_like why else would i try to make this_

**Pull request merged**
