### PR TITLE
[READY]Surgeon Simulator 2560

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds a "heal" option for organ manipulation. By using 3 stacks of ointment or bruise packs on the organ manipulation step, you can heal all organs in the targeted zone completely.

## Why It's Good For The Game

Fuck synthgraft. No one ever uses that shit, no one knows how to make it. This is easier and gives a more viable option for doctors rather than simply directly going for clooning, and makes organ rotting not nearly as much of a punishment as before.

## Changelog
:cl:
tweak: Organ manipulation can now also be used to heal organs, using ointment or bruise packs.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
What the fuck is up with these changelogs jesus christ?

**Comment by ShadeAware** [comment]
**o oo o oo oooo oo  gh hh **
### Yes

**Comment by IronEleven** [comment]
I'd suggest making it its own surgery.  Synthtissue is braindead easy and doctors can't figure it out, so maybe letting the operating computer hold a doctor's hand would help some.

**Comment by BobJoga** [comment]
> I'd suggest making it its own surgery. Synthtissue is braindead easy and doctors can't figure it out, so maybe letting the operating computer hold a doctor's hand would help some.

I think this is honestly betterr and causes less bloat. You're "manipulating" organs, so honestly healing them should be in that category. And i'm sure with enough time, people will get used to it.

**Comment by xXPawnStarrXx** [comment]
While I would rather is be something more costly than bruise packs, I do like this idea.
I would also rather it only work on Living persons, my only issue is the meds for healing organs are less useful than ever before.

**Pull request merged**
