### PR TITLE
[Not ready][Removal] Comments out teleporter species fuckery

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Comments out the amazing feature that sometimes just fucks you over and turns you into a fly.

## Why It's Good For The Game

It legit makes people want to cryo or ahelp for a magic mirror to fix it, it just sucks.

## Changelog
:cl:
del: Teleporter won't turn you into a fly anymore.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Ah yes, more hugbox.

Just upgrade the teleporter FFS. Being a fly is supposed to discourage you just hopping through an teleporter that hasn't calibrated yet. **Calibrate your teleporter and it wont be an issue.**

**Comment by Owai-Seek** [comment]
A feature that makes you just want to quit the round is not a good feature. I'd rather the teleporter do something that doesn't force a character change, such as a potential loss of a limb.

**Comment by NotRanged** [comment]
I greatly increased the radiation, but yes haha hugbox xd.

I can add loss of limb or something similar like big organ damage too if you feel it's not punishing enough, but the permanent species change can fuck right off

**Comment by SpookyTheFox** [comment]
It's not hard at all to negate this in game. Calibrate it, or upgrade it. Getting turned into a fly because you skipped a critical step is one of the least punishing failures in this game. Teleporting without calibration is supposed to be a desperate gamble, and having a small chance of becoming a fly person is pretty hugbox as is. There's a reason it's behind a command door, too.

**Comment by Owai-Seek** [comment]
It's not about it being punishing, it's about it being a furry RP server, and having yourself permanently turned into a fly does not make most people want to continue roleplaying.

**Comment by ShadeAware** [comment]
Contrary to popular belief it would seem, a roleplaying game is still a **game.** Therefore, challenges and _punishments_ are supposed to exist. This "I shouldn't be changed or punished for not doing something right, waaaaah!" mentality is just going to change us from a game codebase to a chatroom with sprites.

**Comment by Owai-Seek** [comment]
Other than a mostly cosmetic change, what kind of punishment is being a flyperson? The only "downside" associated with it is having to eat vomit, and getting hurt more by flyswatters, neither of which are a punishment beyond being mildly annoying. I'd wager it's not an enjoyable "feature" for many of the players here.

There are viable alternatives that could be put in place instead of changing people irreversibly into a race they don't want to play as, considering many people don't know it's a risk of teleportation -at all-.

**Comment by Rayfod** [comment]
Just give 80 genetic damage unupgraded to the person that dares to use it, that would punish the person heavily for trying to use it and force them to a direct trip to the medbay 👍

**Comment by Moostard** [comment]
Oh yes...
Soon someone will be banned for "altering someones appearance".
Also noone stops you from ahelping.
And also noone stops you from calibrating the tele or even upgrading it.

**Comment by KathrinBailey** [comment]
I'm liking the radiation damage. That's a way more fun punishment than species swap.
Once some of the backlog starts getting thinned out I'll come back to this. 👍

**Comment by ShadeAware** [comment]
The species swap is the punishment because it fucks with your appearance. You don't want to be a fly person? **Calibrate the fucking teleporter.** Stop trying to hugbox every little aspect of the game because _uwu i don't want my pwecious OC to be altered nuuuu_. 🙄

**Comment by KathrinBailey** [comment]
> The species swap is the punishment because it fucks with your appearance. You don't want to be a fly person? **Calibrate the fucking teleporter.** Stop trying to hugbox every little aspect of the game because _uwu i don't want my pwecious OC to be altered nuuuu_. 🙄

Read the PR changes before posting and cut the attitude.

**Comment by ShadeAware** [comment]
Oh hey wow I read it and you know what it said?
image

**Comment by KathrinBailey** [comment]
> Oh hey wow I read it and you know what it said?
> image

image
Read this.

**Comment by ShadeAware** [comment]
Yeah, I did read it.
### It doesn't change my point whatsoever.

**Comment by ShadeAware** [comment]
You want to know why the species change was put into place in the first place? To discourage people from just chain-using the thing. To provide incentive to actually calibrate it or upgrade it and use it **properly.** If this change goes through, theres no incentive to not just gamertime the fucking teleporter ad-nausem that can't be cured by a 50u Penetric pill or a trip to your local sleeper. **Increasing the radiation output will do nothing to prevent this either.** You're hugboxing a _critical balance feature_ because you can't stand having your OC messed with for a single round. **There are Green Slime Extract Reactions that can reset your species too, you know.**

**Comment by NotRanged** [comment]
A species change into a fly is permanent without an admin spawning you a magic mirror, or cryoing. I can make the teleporter well and truly fuck you up with clone damage, delimbing, and rads, but a permanent species change (into a fucking fly) on a roleplay server is not something most people want to deal with.

JuST CalIBRatE tHe tElEpoRTeR

**Comment by ShadeAware** [comment]
If you don't want to deal with it, literally calibrate or upgrade it. Using mocking letter choices isn't going to diminish the most basic of actions. Calibration takes like 20 seconds. And, again,
### You can reset your species using green slime extracts.

**Comment by NotRanged** [comment]
If your issue with it is that people can chain it, I can make it so that it would ruin them. But it isnt, though I don't get what your problem is dude. Do you not understand why many players don't appreciate near permanent character aesthetic fuckery, *on a roleplay server*?

**Comment by ShadeAware** [comment]
it doesn't exactly matter that they don't **appreciate it.** Its a _balance feature_ for the **VIDEO GAME.** I don't much "appreciate" that I can be stunned by a stun baton. But if you saw me making a PR to remove stun batons, I'd be laughed out of the room (and rightfully so). The token balance you introduced in this braindead PR is just that. _Token_ balance that can be cured instantly by 2 pills. And you **know** it can be cured by two pills, because radiation and mutations in this game are a joke and always have been.
If you really want to remove the fly-personing, fine. But you need to actually
### Introduce proper balancing features that are just as devastating IF NOT MORE.

**Comment by Weblure** [comment]
> Getting turned into a fly because you skipped a critical step is one of the least punishing failures in this game.

Exactly why it should be removed. Being a fly doesn't give you any mechanical disadvantage, which means this 'punishment' only hurts people that care about roleplaying. Harming a player's ability to roleplay on an HRP server is not a good idea.

Being heavily irradiated is a mechanical disadvantage, which is balancing. **Being turned into a fly is not a means of balance in any way whatsoever.** It's just a major nuisance to roleplayers that serves no purpose other than to be annoying and provide a "haha flyman funny" joke for TG's LRP players to laugh at. It serves no purpose here and thus has no place here.

Please reconsider your definition of 'balance'.

**Comment by Rayfod** [comment]
@ShadeAware We could just make it genetic damage tbh, way more punishing than radiation damage in terms that you have to go to the medbay to get it fixed

**Comment by Ghommie** [comment]
Did you guys forget about the feature freeze?

**Comment by Azarak** [comment]
turning someone into a different species and fucking them up for the entire round is a wrong idea for a punishment. more rads is better

**Pull request merged**
