### PR TITLE
Makes Cling Hivemind free

### PR DESCRIPTION
**Pull request by IrkallaEpsilon**
## About The Pull Request

Lowers DNA cost of Cling Hivemind, Hive Channel and Hive absorb to 0. 

## Why It's Good For The Game

Hive Channel is essentially cloud storage for genomes. It allows lings to store infinite genomes via DNA extraction sting. How to: Channel initial form. Go DNA sting people till at capacity. Change form. Channel all the forms. Reabsorb/Hive absorb your initial form. Free disguises, good for frame jobs and causing chaos. Hopefully should entice a less murderbony advance on "getting more genomes"

## Changelog
:cl:
balance: Shitlings can now get their hive absorb, hive channel and hivetalk ability for free again.
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
I wouldn't have liked this if ling hivemind wasn't literally useless tbh. No joke, there's absolutely no reason to buy this because it just puts a big target on your back for any lings that gotta kill other lings, so making it free isn't a buff

**Comment by CameronWoof** [comment]
Potentially turning something that is balanced to be a very powerful solo antagonist into a very, very powerful team antagonist should come at a cost. The risk of betrayal is not a high enough cost; the DNA cost should stay.

**Comment by ForrestWick** [comment]
Cameron has clearly not played as a ling nearly enough to understand how insanely useless and even detrimental hivemind can be

**Comment by CameronWoof** [comment]
When it works, it's devastating to the round. When it doesn't, it's devastating to you. Lings teaming up when they're already very capable of taking on multiple people at once is incredibly powerful. I'm not interested in arguing the point further, but I am asking maintainers to consider just *how incredibly dangerous* to round health a team of unstoppable supervillains can be.

**Pull request closed without merging**
