### PR TITLE
Removes Pistols from Shoes

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Pistols cant be stored in shoes.

## Why It's Good For The Game

Less power is sometimes good!

## Changelog
:cl:
balance: removed pistols from shoes
/:cl:

### CODE REVIEW

**Comment by CoreFlare** [comment]
nooooooo i need my usp in my boot
the 🅱️risoners are gonna 🅱️ick🅱️ocket my sidearm

**Comment by CinderWC** [comment]
I dont think that this is an issue of being abused. I like the idea of people having the possibility to hide small firearms like pistols in their boots.

However there needs to be rules, you cant just asspull a gun like that without an emote.

**Comment by ShadeAware** [comment]
Add a small delay, don't remove it broje

**Comment by Useroth** [comment]
Honestly. I'd be entirely willing to merge this and likely will unless we get a better solution. Gonna leave it hanging for a bit.

**Comment by CinderWC** [comment]
I brought up the idea of a unholstering delay for the boots as well. Maybe a 3 second umholster time plus a red text along the lines of "X is reaching for their boots"

**Pull request merged**
