### PR TITLE
New chem recipes and /tg/ misc chems 

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
This is a couple of added reagents and reactions both the reagents are from /tg/ so it goes a bit more inline with the wiki and same thing for the reactions plus some extra

## Why It's Good For The Game
Since we don't have a wiki I found it important to port some of the nice changes to make it more reliable and most of the reactions are just for extra interactions. Also the liquid electricity description was wrong due to the absence of ethereals on this codebase.

## Changelog
:cl:
add: ethanol recipe
add: sulphuric acid recipe
add: electrolysis recipe
add: monkey powder
add: cellulose
add: stable plasma recipe
add: butterflium recipe
tweak:changed grind reagents to new reagents
fix: liquid electricity description
/:cl:

### CODE REVIEW

**Comment by Commandersand** [comment]
does cellulose do anything since we don't have their nerfed bandaids?

**Comment by jjpark-kb** [comment]
Try to make your stuff modular.

**Comment by spessbro** [comment]
> does cellulose do anything since we don't have their nerfed bandaids?

no but it opens the window for more opportunities in the future and also it turns into ash which is find more tasteful than carbon.

**Comment by spessbro** [comment]
ok nvm i gotta put this in modular

**Pull request closed without merging**
