### PR TITLE
Added a new traitor item

### PR DESCRIPTION
**Pull request by DeezNyas**
## About The Pull Request

Added a new melee weapon to the traitor uplink under the 'dangerous item category'
a 35 damage melee weapon that doesn't fit in anything other than your belt or back.
Does burn damage and nothing else, with a small block chance and theoretically can delimb, but not without doing serious damage first

## Why It's Good For The Game

Always fun to have new non-ballistic Syndicate items on the uplinks, and it's just a fun sword with not too many unique status points outside of being able to do burn rather than brute damage.

That and block chances on swords are cool as shit

## Changelog
:cl:
add: Added the "Burning Sword" (known as stigma in the workshop bc its a non-clever reference to library of ruina lol)
add: Added the Burning sword into the Traitor uplink for 10 TC
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
I'm pretty sure burn damage outright dusts limbs.

**Comment by YakumoChen** [comment]
yeah you can dust someone's head off with that, kind of a bad time

**Comment by Funce** [comment]
You need to add your new file to the `.dme`
Make sure its ticked in Dream Maker

**Comment by DeezNyas** [comment]
Burn damage was an intentional choice to to the lack of existing option. Dusting any limbs leaves all organ side behind relatively undamaged, however this weapon is a specific buy for that purpose. It doesn’t round remove, but does significantly “deform” targets, offset by its utter lack of conceal ability. As it’s only able to be worn on a belt or bag, it’s definitely something you pick to go outright “loud”

**Comment by BobJoga** [comment]
> I'm pretty sure burn damage outright dusts limbs. Not a fan.

It does, but you cannot satisfy the requirements for delimbing without using another weapon first, thus this is void.

**Pull request closed without merging**
