### PR TITLE
buffs chemmaster epipens

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

upped their reagent limit to 15u instead of 10u
they now pierce hardsuits etc

## Why It's Good For The Game

they got nerfed and can't toxin anymore might as well

## Changelog
:cl:
balance: Chem master medipens can now hold 15u.
balance: Chem master medipens now pierce through clothing.
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
I don't think buffing them this way is wise. They're already an instant-inject vector for self-applying chem mixes, giving them a bunch of extra capacity is going to make them problematic.

**Comment by BobJoga** [comment]
> I don't think buffing them this way is wise. They're already an instant-inject vector for self-applying chem mixes, giving them a bunch of extra capacity is going to make them problematic.

they only do medicine might as well use a patch instead if they're gonna be shit

**Comment by CameronWoof** [comment]
You can apply these to yourself while wearing a mask and hardsuit.

**Comment by BobJoga** [comment]
> You can apply these to yourself while wearing a mask and hardsuit.

You can't. The flags don't allow for it. Are you blind?

**Comment by CameronWoof** [comment]
This looks good.

**Comment by Owai-Seek** [comment]
This raises some balance concerns with me. You can craft a bunch of medipens, stick them in your bag (or biobag) and then get free healing in hardsuits without needing to stop to heal yourself.

The danger of space is that if you get hit, you need to find somewhere to chill to slap a patch on or pop a pill. This PR would make it so you can spacetide forever and heal on the go without making yourself vulnerable, or just fullheal people who are in hardsuits without having to pop them off.

**Comment by BobJoga** [comment]
> This raises some balance concerns with me. You can craft a bunch of medipens, stick them in your bag (or biobag) and then get free healing in hardsuits without needing to stop to heal yourself.
> 
> The danger of space is that if you get hit, you need to find somewhere to chill to slap a patch on or pop a pill. This PR would make it so you can spacetide forever and heal on the go without making yourself vulnerable, or just fullheal people who are in hardsuits without having to pop them off.

Good. Gives this otherwise awful addition some purpose.

**Pull request closed without merging**
