### PR TITLE
Partially removes lavaland RNG megafauna spawns

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Title. Also makes sure that lavaland always has at least one legion tendril.
Basically, you always get at least one of each megafauna spawned and one legion tendril spawned - the rest are purely chance, like it was before.

Also changes it so lavaland can have more than one bubblegum. Because it's the only megafauna with this stupid restriction.

## Why It's Good For The Game

Being cockblocked by bad RNG is yucky.

## Changelog
:cl:
balance: Lavaland now always has at least one legion tendril and at least one of each megafauna.
balance: More than one bubblegum can now exist at the same time.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
@BobJoga the bubblegum restriction is fine. There's actually reasons for it (the special escape shuttle being one) and there's alternative ways to spawn bubblegum (the runic puzzle)

**Comment by BobJoga** [comment]
> @BobJoga the bubblegum restriction is fine. There's actually reasons for it (the special escape shuttle being one) and there's alternative ways to spawn bubblegum (the runic puzzle)

It's hardcoded. There literally cannot exist two bubblegums at the same time. This restriction seems arbitrary and just, not fun.

**Comment by YakumoChen** [comment]
I don't see what's the problem with it? It's not like you see miners fighting two Bubblegums. 

As I said, there happens to be reasons the hardcode exists.

**Comment by BobJoga** [comment]
> I don't see what's the problem with it? It's not like you see miners fighting two Bubblegums. The items he drops are also kind of griefy.
> 
> As I said, there happens to be reasons the hardcode exists as well. Bubblegum needs to be checked as dead to order The Arena.

Then the way he was coded is inefficient and needs to be rewritten. Besides, the fact you cannot spawn more than one bubblegum severely hampers adminbus.

**Comment by YakumoChen** [comment]
I dont think the ability to multispawn a megafauna is a good reason to disable hardcode and potentially break other features

**Comment by BobJoga** [comment]
> I dont think the ability to use admin fuckery to spam a megafauna is a good reason to disable hardcode and potentially break other features.
> 
> Is there a tangible reason multiple bubblegums is good for the game as opposed to one at a time?

There really are none. But the way that the locking of one bubblegum at a time was implemented is terrible and just could have been done better. This won't break any features of real importance as far as i am aware, besides a dumb shuttle that no one ever used in my playtime on the server.

**Pull request merged**
