### PR TITLE
fuck your spreading nanite bullshit

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

Removes spreading nanites from the research techweb

## Why It's Good For The Game

Prevents: 
Weaponizing Nanites via mass spread then detonation code to mass grief
Weaponizing Nanites via mass spread then mass corruption
Weaponizing Nanites via mass spread
Like literally why the fuck is this allowed
Literal fucking ban bait
Like jesus fuck so much ban bait
Like Virology gets yelled at for using airborne viruses to make people black and bearded
But science can literally just outright make weaponized nanites
Also because _**SOMEONE**_ used them to spread some disgusting shit stating people to call them mommy
Gross
Like atleast now you have to rely on getting people to ACTUALLY GET INTO THE CHAMBER to mass brainwash
_**D I S G U S T A N G**_

> 
> 
> While the tone in my typing is reminiscent of salt, There is genuine concern about Infectious nanites.
> 
> 1: There's no real way to deal with it. You can install nanite chambers to uninstall them, Or use Nanite bane, But the time and effort needed to fully get rid of them would only be trumped by the clean up crew fixing the station. (Edit: Also, You'd have to make a rather large chamber to do this, And once it starts to spread again you'd have to do it ALL OVER)
> 
> 2: Infectious nanites spread through _Sight_ at a radius of i _Believe_ five, meaning they can spread through windows and (Potentially) walls
> 
> 3: There isn't much, if any, Escalation that can be done with nanites.
> 
> 4: Again, Virology **Cant** even utilize airborne viruses without getting noticed and bwoinked
> 
> 5: There's no Immunity outside of another nanite cloud (If the infectious one has no nanite-takeover code) or distancing yourself from literally everyone else who has it.
> 
> 6: Weaponizing this _**Is**_ something that would lead to many more bwoinks than really needed. Literally 1 person deciding to make a spreading set up with no tell (No buttons, no displays, nothing) then running mass paralysis then poisoning the station would cause the admins to get **Flooded** by ahelps.

## Changelog
:cl:
del: Removed spreading nanites from tech node
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
its only obtainable by abductor tech , and only tators can buy abductor tech disks , you'd make that item pointless if you decide to remove this . Was it misused sometimes , maybe . Does that warrant its removal ? not in my opinion.

**Comment by SarmentiCampbell** [comment]
That sound like you are salty, is it?

**Comment by Zenitheevee** [comment]
While the tone in my typing is reminiscent of salt, There is genuine concern about Infectious nanites.

1: There's no real way to deal with it. You can install nanite chambers to uninstall them, Or use Nanite bane, But the time and effort needed to fully get rid of them would only be trumped by the clean up crew fixing the station. 

2: Infectious nanites spread through _Sight_ at a radius of i _Believe_ five, meaning they can spread through windows and (Potentially) walls

3: There isn't much, if any, Escalation that can be done with nanites. 

4: Again, Virology **Cant** even utilize airborne viruses without getting noticed and bwoinked

5: There's no Immunity outside of another nanite cloud (If the infectious one has no nanite-takeover code) or distancing yourself from literally everyone else who has it. 

6: Weaponizing this _**Is**_ something that would lead to many more bwoinks than really needed. Literally 1 person deciding to make a spreading set up with no tell (No buttons, no displays, nothing) then running mass paralysis then poisoning the station would cause the admins to get **Flooded** by ahelps.

Should I have not taken my points off the rails? Yes
Should I have worded the Title to not sound salty? Yes.
Will i? No. Not because i dont care, But because down to it, This is, truly, TRULY Disgusting, and i feel that my words should reflect on that tone.

**Comment by Yawet330** [comment]
+1 ban the person who did that 'mommy' shit aswell.

**Comment by Zenitheevee** [comment]
Also, To anyone who _REALLY_ hates the idea of not having to lose the ability of non-consentual nanite spreading (that sounds much worse than i wanted it to)

You can opt in to enable Nanite sting, A much shorter distance, **ACTIVATED** ability

**Comment by Owai-Seek** [comment]
I don't think it's only available with the disk? That's just a quicker way to get it. Otherwise, you can get abductor tech via a (random) lavaland ruin, or by working as a xenoarcheologist. (Abductor tools are like, at least 50% of the loot pool from the better-tier strange rocks.))

**Comment by Zenitheevee** [comment]
> 
> 
> I don't think it's only available with the disk? That's just a quicker way to get it. Otherwise, you can get abductor tech via a (random) lavaland ruin, or by working as a xenoarcheologist. (Abductor tools are like, at least 50% of the loot pool from the better-tier strange rocks.))

Yes, The Lavaland Ruin + Xenoarcheologist are actually probably more common for Alien tech than the disk is, Atleast it would be in consideration of the fact that usually Traitors dont want to waste like... 2TC i think it is?

**Comment by Zenitheevee** [comment]
OK HOLD UP!

It isn't actually removed from the tech node

**Comment by Zenitheevee** [comment]
That should be a full removal

**Comment by MLGTASTICa** [comment]
> While the tone in my typing is reminiscent of salt, There is genuine concern about Infectious nanites.
> 
> 1: There's no real way to deal with it. You can install nanite chambers to uninstall them, Or use Nanite bane, But the time and effort needed to fully get rid of them would only be trumped by the clean up crew fixing the station.
> 
> 2: Infectious nanites spread through _Sight_ at a radius of i _Believe_ five, meaning they can spread through windows and (Potentially) walls
> 
> 3: There isn't much, if any, Escalation that can be done with nanites.
> 
> 4: Again, Virology **Cant** even utilize airborne viruses without getting noticed and bwoinked
> 
> 5: There's no Immunity outside of another nanite cloud (If the infectious one has no nanite-takeover code) or distancing yourself from literally everyone else who has it.
> 
> 6: Weaponizing this _**Is**_ something that would lead to many more bwoinks than really needed. Literally 1 person deciding to make a spreading set up with no tell (No buttons, no displays, nothing) then running mass paralysis then poisoning the station would cause the admins to get **Flooded** by ahelps.
> 
> Should I have not taken my points off the rails? Yes
> Should I have worded the Title to not sound salty? Yes.
> Will i? No. Not because i dont care, But because down to it, This is, truly, TRULY Disgusting, and i feel that my words should reflect on that tone.

1.Nanite bane can be mass-produced and applied, just because 1 round they were barely removeable it doesn't mean they aren't always like this
2.Bugs should be fixed , not used as an argument to remove a whole feature
3.There can be plenty of escalation , the escalation depends on the reason why they were released in the first place , not during the release itself . You can't just decide to wordlesslly kill the station.
4.They can as long as they properly escalate with command/security , and if their demands are not met
5.Removing the nanite's then installing nanites with takeover themselves would count as immunity . as long as they out-replicate the infectious ones
6.Bwoinks doesn't mean they are actual issues,  Admins bwoink people all the time to ask for their reasoning , especially AI , Virology and scientist traitors .  They can also straight up close bwoinks instantly if they relate to a case where nanites have been reasonfully released.

The antag abductor disk costs 14 TC , this is a big percentage of their initial TC and as such their entire gimmick will likely be run around the techs unlocked by the disk.

While abductor surgery tools and engineering tools make a high percentage of the ultimate artifact list of the strange rocks , strange rocks with them are still EXTREMLY rare, since they need a 1 in a 100  for it to even possibly contain said item.

There is a lavaland ruin , but it does not spawn every round and miner's usually don't get to always find it.

**Comment by Zenitheevee** [comment]
> 
> 1.Nanite bane can be mass-produced and applied, just because 1 round they were barely removeable it doesn't mean they aren't always like this
> 2.Bugs should be fixed , not used as an argument to remove a whole feature
> 3.There can be plenty of escalation , the escalation depends on the reason why they were released in the first place , not during the release itself . You can't just decide to wordlesslly kill the station.
> 4.They can as long as they properly escalate with command/security , and if their demands are not met
> 5.Removing the nanite's then installing nanites with takeover themselves would count as immunity . as long as they out-replicate the infectious ones
> 6.Bwoinks doesn't mean they are actual issues, Admins bwoink people all the time to ask for their reasoning , especially AI , Virology and scientist traitors . They can also straight up close bwoinks instantly if they relate to a case where nanites have been reasonfully released.
> 
> The antag abductor disk costs 14 TC , this is a big percentage of their initial TC and as such their entire gimmick will likely be run around the techs unlocked by the disk.
> 
> While abductor surgery tools and engineering tools make a high percentage of the ultimate artifact list of the strange rocks , strange rocks with them are still EXTREMLY rare, since they need a 1 in a 100 for it to even possibly contain said item.
> 
> There is a lavaland ruin , but it does not spawn every round and miner's usually don't get to always find it.

While i'd love to make points against a lot of these, There's some that come down to issues outside of code.

1: Nanite bane is a fermichem. Yes, you **_Can_** theoretically mass produce it, But you would need an insane amount to get enough to get rid of all the nanites, and even then, any level of re-infection will undo your progress
2: while i cant say its _NOT_ a bug, Leaving it at "Its a bug, it should be fixed instead of removed" Becomes problematic when the feature as a whole is quite... Unpleasant
3: i'm going to be straight honest here, I hate having to make this point. But _I just dont trust the people using this to escalate properly_. And this isn't something that can be remedied by good policy changes alone. Both there's no real way to mass cure it, nor people willing to do it, either IC or OoC Adminbussing wise. This also applies to the Fourth point, But i'm not arguing to remove airborne disease elements, as that would actually break a bit of actual viro-code
5: While this may be true, Its problematic to do this in the same vain as nanite chamber removal, just without a high reinfection rate, and also with the fact that it would imply giving these to everyone, even people that just dont want nanites as a whole.
6: The fact of this matter is that, It doesn't matter if its _problematic_ or not on a policy standpoint, If a large proportion (Keywords If and proportion) of people complain about something, it becomes something people necessarily agree isn't good or fun to deal with. It'd be like starting the round in various damage states and asking people to not get upset over getting wordlessly disabled at the round start because medical isn't prepared to deal with you missing a leg or having a broken arm. 

As for the actual disk, its 12 (I actually bothered checking this time) and comes with alien pre-researched, and i believe this was made back when it gave **Everything** alien related. Honestly, i feel like the TC should be substantially lowered to compensate for the lack of utility in this.

 While Infectious nanites as a whole are great, The problem comes down to the fact there are other things you can do with this, including mass brainwashing (Another thing that is bwoinkable due to lack of buildup/escalation) and just the idea of mass paralysis or poisoning as a whole. 

I dont know how to say this as a whole, more than **I am being extremely biased against infectious nanites**, And its because with how stuff is currently in the server, i _cannot_ feel safe trusting people in good faith to escalate it properly.

**Comment by Zenitheevee** [comment]
Shit's going stale, But with our Recent incursion into a /TG/ rebase, i'm not _Too_ too scared about it getting closed. I understand maintainers have more to worry about.

**Comment by Arturlang** [comment]
Problem is, I dont think nanite sting can operate on its own, so itll be only usefull for manual use, perhaps rework nanite spreading to be obvious and or direct proximity based?

**Comment by Zenitheevee** [comment]
https://i.imgur.com/5qD0QXS.png

**Comment by Zenitheevee** [comment]
[](https://cdn.discordapp.com/attachments/148132732948578304/817156634089357342/5qD0QXS.png)

**Pull request closed without merging**
