### PR TITLE
Techfab Research

### PR DESCRIPTION
**Pull request by Afya212**
## About The Pull Request

You can not research the ability to make new techfab circuit boards. Removed the techfab circuit from all heads except research.

## Why It's Good For The Game

More research, more interdepartment dependency. 

## Changelog
:cl:
add: Techfab circuits now researchable.
del: Removed techfab circuit from all heads except RD.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Elaborate on how is this good for the game? Sci has already access to about the strongest things in the game, and now they will have access to about any item they want to print? Techfab circuits being in heads' lockers are a good thing because A. traitors can steal them steathily, perhaps sabotage both the lathe and techfab of one department (RnD is usually busy) B. A head can lend the circuit to someone who they deem trustworthy. C. Lathes and techfabs being in a limited quantity is good because they're very powerful
It's not more interdepartmental dependancy, it's just putting more stuff into sci, where it already has too much on it hands. 

Bad change imo

**Comment by Afya212** [comment]
Eh that's fair about the lockers. Though I was mainly interested in this since someone was complaining how if the head one and the main one get stolen you're just completed screwed. I'm not used to how fabs work here fully, it's weird how they all share resources so maybe it is. 
Also seems Travis decided to shoot itself mid-test, nice.

**Comment by Azarak** [comment]
Yeah if the two get stolen you are screwed, it's called sabotage and it should have consequences and not just "lol RND printer go brrrr"

**Comment by Afya212** [comment]
Fair fair, was just based off a suggestion, not overly attached to it.

**Comment by ShadeAware** [comment]
Haha very gamer, time to print Security/Engie lathes every round **:^)**

**Comment by Afya212** [comment]
I'll take that as general against, fair enough.

**Pull request closed without merging**
