### PR TITLE
Adds a craftable double stunbaton (makeshift electrostaff that sucks)

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

See https://github.com/quotefox/Hyper-Station-13/pull/137

## Why It's Good For The Game

It's silly, it's useless, but it should be a thing. Plus it looks cool (or tool, depending on how you view it).

## Changelog
:cl:
add: Double stun batons
add: Double stun baton crafting recipe
imageadd: Double stun baton sprites
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
it compiles

**Comment by Azarak** [comment]
We already have riot electrostaves and they're balanced fairly well, this could be a needless headache to balance

**Comment by BobJoga** [comment]
> We already have riot electrostaves and they're balanced fairly well, this could be a needless headache to balance

They're absolute shit though

**Comment by BobJoga** [comment]
they're now absolute dogshit

**Pull request merged**
