### PR TITLE
Lets antag banned people be converted into some antags

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
..into vassals, sintouched and also survivalists. They will be warned to be at their best behaviour and admins will be notified.

## Why It's Good For The Game
Booting people out of their character in an RP server is bad

## Changelog
:cl:
tweak: Lets antag-banned people become vassals, sintouched and survivalists
/:cl:

### CODE REVIEW

**Comment by CinderWC** [comment]
I feel that this could be abused by metagangs/metafriends to get their antag-banned buddies into an antag role.
However i do agree that booting people out of their character in conversion rounds when we are supposed to be MRP-HRP is fucking dogshit

**Comment by LimblessLayabout** [comment]
I'm on board with this so long as we're notified.
If we have a button to quickly check the watchlist or notes so we can deantag specific persons, so much the better, but I would really rather be on a server where the banned _CAN_ be converted and keep playing, than one where events and dice can systematically ghost a well-behaved user with a certain type of ban.

**Comment by LimblessLayabout** [comment]
Making a note to ensure special antags such as through events get covered (no more HIGHLANDER mass-ghostings, russianmobs, etc)

**Comment by Akrilla** [comment]
tgstation.dme, line 3541, column 1:
warning: duplicate #include "modular_skyrat/code/modules/antagonists/revenant/revenant.dm"
- 3538:1: previously included here
tgstation.dme, line 3542, column 1:
warning: duplicate #include "modular_skyrat/code/modules/antagonists/revenant/revenant_abilities.dm"
- 3539:1: previously included here

linter job fail

**Pull request merged**
