### PR TITLE
[Semi-Modular] The Long Awaited ZOMBIES REWORK!

### PR DESCRIPTION
**Pull request by ShadeAware**
**LARGE AMOUNT OF CREDIT TO JAKE PARK FOR HELPING ME WITH A LOT OF THE CODE.**
## About The Pull Request
Reworks zombies (almost) entirely to finally fit the nanite horror theme I half-assed a while ago but have only now actually taken the time to finish.

**MAJOR CHANGES:**

- Infection now only has a 30% chance of taking hold per hit when cut by a horror. Nanite Horrors are now alerted by a bold text message when their claws have penetrated deep enough to infect an individual.

- Nanite Horrors have lost their thermal vision, but with it have gained great power. They are now partially immune to stuns and taser bolts, have been sped up to be on-par with normal humans, and can run without any stamina cost.

- Nanite Horrors, as the name suggests, are supposed to be made mostly from nanites. With this in mind, Nanite Horrors are now vulnerable to EMPS! EMPing a nanite zombie will cause a temporary lapse in their body, knocking them down and dealing a minor amount of burn. The power of the knockdown and burn damage scales with the power of the EMP!

- Nanite Horrors now have garbled speech, to help dissuade would-be friendly zombies. You're a feral creature, NOT a circus act! **Act like it!!!**

- Nanite Horrors now show as "alive" on health monitors n' such, since the nanites piloting them are in reality keeping the body alive as long as possible to facilitate their spread!

- Nanite Horrors now have their own custom scream, a loud roar to instill fear into the hearts of their victims!

## Why It's Good For The Game
Zombies have now finally completed their transition from "simple sprite edit" to "complete overhaul" into something far more worthy of our HRP setting. Nanite Horrors are now finally here.

## Changelog
:cl:
balance: Nanite Horrors are now partially stun and taser immune, and have infinite run buffer.
balance: Nanite Horrors have lost their inherent thermal vision.
balance: Nanite Horror speech is now garbled to dissuade would-be friendly zombies.
balance: Nanite Horror infection now only has a 30% chance of actually taking hold per-hit.
balance: Nanite Horrors are now weak to EMPs, suffering from burn damage and knockdown.
tweak: Nanite Horrors now show as alive on health/crew monitors, as per their lore; the nanites are keeping the host alive to facilitate their spread.
add: Nanite Horrors now have their own scream sound, a loud roar. Use it for that extra scare factor!
add: Nanite Horrors are now informed when their hits infect an individual.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
Finally... murder miners zombies...

**Comment by ShadeAware** [comment]
Making this a draft because theres some things I need to polish before im comfortable with it.

**Comment by Yawet330** [comment]
`/obj/item/organ/zombie_infection/emp_act(severity)
	. = ..()
	if(. & EMP_PROTECT_SELF)
		return
	else
		owner.adjustFireLoss(40 * severity)`

My only gripe with the PR is this (as discussed with the person who did it), which allows you to shoot somebody with 1u of da nanites and then spam EMP you, considering it works off of your organs rather than your race. Mostly just a balance consideration but code is good.

**Comment by LimblessLayabout** [comment]
Q: It's noted that zombies have garbled speech, can they communicate with -each other- clearly?
Purely a concern for organizing hordes and whatnot.

Secondly; are they marked as antagonists, or a species change? I noted that nanite horrors were not trivial to track from an admin perspective.

**Comment by ShadeAware** [comment]
Zombie speech is garbled to everyone, period. Making them able to converse with one another and not the crew would require language fuckery that I'm not confident would entirely work with the way Zombies are.

Also to answer your second question, Zombies are handled as a species change.

**Pull request merged**
