### PR TITLE
Removes botany dispensers, And adds unstable mutagen as a biogenerator thing

### PR DESCRIPTION
**Pull request by improvedname**
Botany dispensers were over due and this is a good middleground.

## Changelog
:cl: Improvedname
balance: Removes botany dispensers.
Add: Biogenerators can now make unstable mutagen.
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
nope.

**Comment by improvedname** [comment]
hahhaa pr close go brr

**Comment by Owai-Seek** [comment]
So, now botany can just, not leave botany the entire round, forever, and not need to ask for their first batch of mutagen -or- get science upgrades for the dispenser?

This is silly.

**Comment by Azarak** [comment]
For a botanist that manages to grow a bit more than nessecary this makes so that he doesn't have to do anything to get his mutagen.

A change to remove the dispenser and perhaps supply botanists with a few bottles roundstart would be much better in my opinion

**Comment by improvedname** [comment]
Ill do it in another pr
Saltpetre can be made by the biogenerator as well so admins technically can consider the chem dispenser powergaming now

**Comment by improvedname** [comment]
Life is hopeless yknow

**Comment by Useroth** [comment]
closing in favour of #1628

**Pull request closed without merging**
