### PR TITLE
The Bridge Officer, a job intended for roleplay.

### PR DESCRIPTION
**Pull request by thestubborn**
And easing into command roles

Oh I bet ya'll thought I'd stop coding after people slander me? WRONG.

tired, sleep, sleep good, shout at me in the morning

[Nothing stops this train, nothing.](https://www.youtube.com/watch?v=OyabiLNfjQw)

### CODE REVIEW

**Comment by KathrinBailey** [comment]
Why though

**Comment by thestubborn** [comment]
It's a job focused on roleplay, with the command team mostly, although they could, in emergancies be used as a coordination of evacuation/rescue efforts, manning cams or sensors.

Also the outfits are cool.

**Comment by KathrinBailey** [comment]
Why do they have cargo access? We have cargo techs. HoP also has cargo access.
Why do they have botany access?
Why do they have kitchen and bar as additional access?
Why look at cams when the AI job is almost always open?
Why look at sensors when we have medical doctors at the medbay reception and handheld crew monitors?
Why is sitting on the bridge all shift looking at consoles you mostly have no access to use nor aren't responsible for using **fun**? I could sit in the manager's office in a fast food place and call myself "bridge officer", but it doesn't mean I'd be contributing jack all or doing anything remotely productive (or fun).
As a head of staff main, why do I need this person? All the help I need comes within my department, I need engineers as the CE to help me, or MDs as the CMO, not an assistant that just twiddles their thumbs on the bridge.

This is why you need to follow the PR format instead of just removing it, it's there for a reason.

**Comment by thestubborn** [comment]
cargo, botany, kitchen and bar is for lowpop
why do we have a brig doctor when we could just shout over a med doctor?
and the hop/cap dont really *have* a department, or better yet, say you wanna go do fun shit, off load paperwork to someone, or better yet, say you want to roleplay with underlings who have nothing to do, unlike heads of staff who often have things to do

also i remove that shit because its overtly long

**Comment by thestubborn** [comment]
and its also so you can learn command shit without taking up a valuable slot, like a head of staff, and i said the sensor stuff IN EMERGENCIES, because if a med doc is sitting looking at sensors/cams during a blob attack then they're a shitty medical doctor

**Comment by KathrinBailey** [comment]
I... literally just said.
Handheld crew monitors. You put it at the top right of your screen.
You don't learn command by AFKing on the bridge. If you want to learn Command, we have the Head of Personnel and Quartermaster, both are much more valuable for learning command. Quartermaster has nothing expected of them and is great for learning how to lead your department. HoP rarely has to manage service, so they can learn command outside their department.

**Comment by thestubborn** [comment]
i mean if you wanna go afk on the bridge go wild, a BO shouldnt do that, just like a sec officer shouldnt afk in the brig, or a cap in their officer

the HOP manages access, which is pretty fucking important, if you think some new person to command wont fuck that up somehow then...oh boy, and the QM is meant to both manage the miners, not let them run around with gamer gear, ensure the techs are doing shit and not letting bad orders through, as well as stamp manifests and bounties

**Comment by thestubborn** [comment]
and thats not even counting the fact the hop is the *second in command* and most times the *acting captain*
i'd rather relax on the bridge, roleplay, and ease into a command job instead of being thrust into it
unless all the cit gamers moved here or something this is meant to be roleplay first, correct?

**Comment by davidchan13** [comment]
Sounds a lot like Paradise's NT Rep. Neutral, not sure its the job we should be stealing.

**Comment by thestubborn** [comment]
i dont play no paradise
i only steal jobs from quality servers, like /vg/

**Comment by ForrestWick** [comment]
BO tends to just be the job people take when they wanna powertrip but not have any real responsibility. Considering the bloat of extra jobs we have already, I don't think one that's sole reason for existing is "RP" would really fit

**Comment by Strazyplus** [comment]
I have played as the BlueShield, their purpose is to protect the captain/heads. it is a good role but many would protest and say it's unneeded. but BlueShield makes certain things happen if they are good. 

When I play BlueShield I prepare myself for rescue ops. I carry a medkit and an emergency extinguisher at all times. and depending on the situation I carry spare supplies if the captain needs oxygen. during the downtime, I am basically being a bridge officer and I found it enjoyable in small doses. I look at the crew monitor and report the dying crew, I check on other heads via cameras. and I follow the captain EVERYWHEREEEE.

**Comment by Akrilla** [comment]
Closing this for now, but you can talk to a maintainer about if this is something we're looking for.

**Pull request closed without merging**
