### PR TITLE
"The herpes of arts and crafts."

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Gives glitter an expiry date of about 5 minutes. Once the expiry date passes, it qdels itself.

## Why It's Good For The Game

One guy fucking hates glitters for some reason
glitterhater

## Changelog
:cl:
balance: Nerfed glitter. See PR #1073 for more info.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
thanks mapbot

**Comment by frontline03** [comment]
Im sorry but glitter is meant to be a pain in the ass to remove

**Comment by BobJoga** [comment]
> Im sorry but glitter is meant to be a pain in the ass to remove

i mean i thought so too but people really **hate** glitter or something

**Comment by frontline03** [comment]
> > Im sorry but glitter is meant to be a pain in the ass to remove
> 
> i mean i thought so too but people really **hate** glitter or something

Isn't that the point?

**Comment by ShadeAware** [comment]
Yeah I see no point to this. Glitter is supposed to be annoying, therefore its doing its job. 

If it ain't broke don't fix it.

**Comment by CinderWC** [comment]
Glitter is supposed to be annoying. Clean that shit yourself

**Comment by BobJoga** [comment]
**PR's closed due to mutes caused by Kathrin Bailey. For any grievances or complaints, contact Floof Ball#0798 on discord. The PR owner will also not listen to any of your complaints unless you provide screenshots that prove you have contacted Floof Ball#0798 on discord first.**
pool

**Pull request closed without merging**
