### PR TITLE
puts a pipebomb in owai-seek's mailbox

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

@winter-flare dont go outside on 01/11/2020

## Why It's Good For The Game

image

## Changelog
:cl:
add: there is a pipebomb in your mailbox
/:cl:

### CODE REVIEW

**Comment by Oshibkka** [comment]
Very good PR! I think this would be a very good addition to the game. 👍

**Comment by BobJoga** [comment]
**edit:** looking at pipe bomb code is hard

**Comment by FargothUr** [comment]
as a very prominent and well known icon of Skyrat (as I have erped over a thousand times) I can very much say that this PR will help make ERP great again, I have busted over twenty nuts in a span of a minute over the idea that this will get merged, 10/10, would merge again.

**Comment by IronEleven** [comment]
Ow the edge.

**Comment by KathrinBailey** [comment]
Yeah fuck off

**Comment by BobJoga** [comment]
> Yeah fuck off

crynigga

**Comment by glarfle** [comment]
I got muted for a week because I thought this was funny

10/10 please speedmerge👍

**Comment by FargothUr** [comment]
vote should be recounted because a "femoid" (guy irl LOL) closed the PR, and women aren't allowed to vote in based countries

**Comment by FargothUr** [comment]
wow skyrat bot UNBASED suck my BALLS

**Pull request closed without merging**
