### PR TITLE
[Modular] Plushie Back

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Adds back some plushies, adds another.
Also changes Reeces coat, per his request.

## Why It's Good For The Game

Plushies are cute. Give some recognition to those who deserve it.

## Changelog
:cl:
add: Added more plushies
add: Added better sprite to Reece's Great coat
/:cl:

### CODE REVIEW

**Comment by Commandersand** [comment]
i dunno if being able to sprite and copy pasting code means you deserve your OC in the game code

**Comment by KathrinBailey** [comment]
Smh look at all these losers who don't already have their character in the code.
Enjoy your random chance spawn of your plushie that's already in a very diluted pool, nerds.
I'm on the freakin' walls.

**Comment by BobJogaIsForkinBanned** [comment]
> Smh look at all these losers who don't already have their character in the code.
> Enjoy your random chance spawn of your plushie that's already in a very diluted pool, nerds.
> I'm on the freakin' walls.

no one likes you

**Comment by BobJogaIsForkinBanned** [comment]
> i dunno if being able to sprite and copy pasting code means you deserve your OC in the game code

Don't know who you're throwing shade at but that is kinda rude

**Comment by KathrinBailey** [comment]
> i dunno if being able to sprite and copy pasting code means you deserve your OC in the game code

Agreed, unfortunately we don't really have much when it comes to quality assurance for PRs. It's been getting better but we still get low-quality shit that causes issues that Cinder inevitably has to spend ages fixing.

**Pull request merged**
