### PR TITLE
[READY] MetaStation (Perma)Brig Nitpicks

### PR DESCRIPTION
**Pull request by CinderWC**
## About The Pull Request
This PR resolves some nitpicks i have come accustomed to since Meta's new Permabrig.
If there is anything that needs to be adjusted with this PR please DM or @ me on Discord @KathrinBailey 

## Why It's Good For The Game
Its honestly nitpicks, no real game changing changes so it really is personal preference

## Changelog
:cl:
tweak: Tweaked a lot of decals and floors in the brig to fit my preferences a lot more. I believe it looks better this way
tweak: Replaced the holding cell's red bedsheet with a black one
tweak: Adjusted brig areas
tweak: Swapped positions of both crates in the brig infirmary
fix: The Cafeteria Jukebox is now placed in the middle of the room and not one too far to the right. Symmetry is key. Enlarged the cafeteria to achieve this.
del: Removed Fore Maint Area tag from the permabrig as it made no real sense
del: Removed purple scrubs from the brig physician's locker
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
I like the current map better then the proposed changes tbh

**Comment by CinderWC** [comment]
> You didn't contact me at all about any of this, so this PR doesn't actually fix any existing bugs that I have on the _to do_ list at all. All it does is unnecessarily change things and make it kinda just... uglier.
I did contact you, i mentioned your name on this Pull Request.
On top of that, i would not be required to contact you, as the moment one of your PR's is fullmerged you consent to whatever you worked on being Open Source and being modifiable by anybody and everybody, you are not entitled to sole ownership of this Prison and i am allowed to edit it, so are others.
The PR was never made to resolve bugs. It was merely to "fix" some nitpicks i had with how decals and floors were placed according to my personal preferences

> The colour palette, for some reason, has been hammered out. Colour contrast has also been reduced and I'm clueless to why, since it just looks uglier. The only change of any substance seems to be no grass in prison hydro, which is an okay change, not sure why you decided to remove the colour contrast in the room as well?
I brought the colour palette in line with the rest of the station as it looked grossly out of place.
You place those yellow-black warning stripes in places where they really should not be in. Those should be used for areas that are seen as restricited areas, or dangerous areas. Putting those stripes around a bunch of botany equipment is nonsensical to me.
 
> edit: Also probably don't use the fix tag for non-fixes. You moved the jukebox on a 10 tile wide room, so instead of being a bit too far to the right, it is now a bit too far to the left. Beforehand it was in the middle of the three tables above it, now it looks really out of place.


That is a fix. The cafeteria is 10 tiles from east to west and i placed it perfectly in the middle, while before it was 1 tile to the right which would mean "6 tiles, jukebox, 4 tiles"

**Comment by KathrinBailey** [comment]
No need to be condescending. I'm perfectly aware that once I've done a PR, anyone and everyone is allowed to mess with it for better or worse. I just take issue with this since it falls under the latter category.

Once I got tagged, I assumed this was going to fix bugs or change the balance in some way. It's just changing decals.  I'm just sitting looking at mapdiffbot thinking _**why?**_

So, if you want nitpicks.
image
What's with leaving these low-alpha corners on plasteel? It's inconsistent with even the room directly next to it. Why change it from orange to red in the first place? Why use low-alpha red decals on plasteel when literally all of security except **for a single tile directly above it** exclusively uses those corners on dark turfs to avoid the incredibly washed-out salmon colour?
 
How is this
image
an improvement upon this in any way?
image

Why is this fine
image
But a hazard warning to stand clear of the literal giant painful people-crushing blast doors not okay? It's inconsistent. Especially this is directly outside the doors, ya'know, where a lot of people tend to stand.
image

I can understand removing the grass from this.
image
But why would you remove the separate colours under the trays?
image
Kinda baffled at why you decided that it needed to be green all of sudden. Three parts of this room. The large open area that you walk into. The botany trays on the left, the most important bit. The top and middle rows of tiles with the vendors and biogenerator/seed extractor. The room had three colours to match this.

I'm well aware that people aren't too much of a fan of the hyper-colourful flashy arcade area.
image
Sure, it's a bit too flashy for a prison, but...
image
I really don't think this is an improvement. The circuit turfs look incredibly out of place, and I'm not sure where's there's green corners to the left of the sleepers. The room was divided into three segments of 3x2 with a dividing walkway between the segments, now it's just a janky generic square room with nothing remotely interesting about it. Probably not even a point keeping the blue/green decals at all.

Why did you remove the corners on the right?
image
image
Purple has their own shower room with purple decals right outside.
Orange has their own shower room with orange decals right outside.

Every doorway has either a dark turf with exception of the cafeteria, since its entire floor is already dark.
image
Why is this suddenly exempt?
Same for purple's shower room too.

Sure, I sometimes get carried away with my hazard stripes. Wasn't exactly what I was referring to with colour contrast/palette though.
image
So why did this
image
Turn into this? It's janky, the stripes are on the outside of the showroom turfs in its original position, now there are more stripes that are suddenly on the inside of the showroom turfs.
> You place those yellow-black warning stripes in places where they really should not be in. Those should be used for areas that are seen as restricited areas, or dangerous areas. Putting those stripes around a bunch of botany equipment is nonsensical to me.

> That is a fix. The cafeteria is 10 tiles from east to west and i placed it perfectly in the middle, while before it was 1 tile to the right which would mean "6 tiles, jukebox, 4 tiles"

This is untrue. Check mapdiffbot. It's also 10 tiles wide. That means the middle of the room is 5 tiles from the left and 5 tiles from the right. Where does that put the jukebox? In between the 5th and 6th tile, that's the middle of the room. The jukebox is 32x32 (1 tile). The jukebox cannot exist in the middle of the room, it's impossible.
(1) (2) (3) (4) (5) TWO DIMENSIONAL JUKEBOX (6) (7) (8) (9) (10)
(1) (2) (3) (4) 64x32 UNSPRITED CHUNGUSBOX (7) (8) (9) (10)

**Comment by CinderWC** [comment]
>What's with leaving these low-alpha corners on plasteel? It's inconsistent with even the room directly next to it.Why change it from orange to red in the first place? 

It was changed from orange to red to keep with the red visual style and not add too many colours.

>Why use low-alpha red decals on plasteel when literally all of security except for a single tile directly above it exclusively uses those corners on dark turfs to avoid the incredibly washed-out salmon colour?

The entire sec front hallway has it like that (The one that is infront of the entrance.

>How is this an improvement upon this in any way?

Why the fuck is heavy machinery such as license plate stampers on wooden floor? It would make sense to keep the room more boring looking and industrial rather than make it look as fancy as it is.

>But why would you remove the separate colours under the trays?

Keeping consistent with the rest of the placed things. Removing some of the colorfulness form the room.

>I really don't think this is an improvement. The circuit turfs look incredibly out of place, and I'm not sure where's there's green corners to the left of the sleepers. The room was divided into three segments of 3x2 with a dividing walkway between the segments, now it's just a janky generic square room with nothing remotely interesting about it. Probably not even a point keeping the blue/green decals at all.

So the haphazardly placed carpets in the middle of the sleepers was not "out of place" to you?
The way it is now it looks more calculated and unified and removes the flashiness that (personally) hurts the eyes

>Why is this suddenly exempt?
Same for purple's shower room too.

Fixing.

>So why did this Turn into this? It's janky, the stripes are on the outside of the showroom turfs in its original position, now there are more stripes that are suddenly on the inside of the showroom turfs.

Fixing.

>This is untrue. Check mapdiffbot. It's also 10 tiles wide. That means the middle of the room is 5 tiles from the left and 5 tiles from the right. Where does that put the jukebox? In between the 5th and 6th tile, that's the middle of the room. The jukebox is 32x32 (1 tile). The jukebox cannot exist in the middle of the room, it's impossible.

Pepega Moment, hold my beer

**Comment by CinderWC** [comment]
@jjpark-kb Review and merge/close as you see fit.

**Comment by jjpark-kb** [comment]
Closing.

**Pull request closed without merging**
