### PR TITLE
Medibots don't like apples.

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

**Informative video:** https://www.youtube.com/watch?v=q-798rM5New

Medibots are afraid of apples. When in patrol mode, at the sight of an apple related atom, they will try to run away. Medibots are also afraid to step on turfs which have been appled, and will avoid them at all costs. Therefore, you can trap medibots with apples.

Also medibots will scream if trapped by apples.

## Why It's Good For The Game

"An apple a day keeps me away"
-Medibot, 2560

## Changelog
:cl:
tweak: Medibots are now afraid of apples.
/:cl:

### CODE REVIEW

**Comment by Strazyplus** [comment]
Feature request: hitting a medbot with an apple makes it scream.

**Comment by BobJoga** [comment]
> Feature request: hitting a medbot with an apple makes it scream.

Good request. Will do.

**Comment by Owai-Seek** [comment]
While amusing I don't really see how it's good for the game. I dislike medbots in general because they just squat in medbay taking work from proper medics.

**Comment by BobJoga** [comment]
> While amusing I don't really see how it's good for the game. I dislike medbots in general because they just squat in medbay taking work from proper medics.

I mean this serves no purpose for the game beside amusing crewmembers with a gimmick. Mostly shouldn't be a problem either way.

**Comment by LimblessLayabout** [comment]
100% silly but I do love this. Bots can use the attention.

**Pull request merged**
