### PR TITLE
No (Removes cum command from Voice of God)

### PR DESCRIPTION
**Pull request by CameronWoof**
No

## About The Pull Request

No

## Why It's Good For The Game

No

## Changelog
:cl: 
del: Voice of God can no longer make people climax.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Good PR, but make a proper changelog please.

**Comment by KasparoVy** [comment]
no

**Comment by Investigator77** [comment]
No (Yes)

**Comment by Useroth** [comment]
tbh, it checks for the HYPNO pref
also, I think it should stay, but with the area effect of it disabled, only activable with "X, cum"

**Comment by CameronWoof** [comment]
Liking hypno =/= liking being made to cum by some rando with VoG
this ability's grief potential far eclipses any niche good it might do for a scene. People can simply roleplay out the encounter instead. It's not worth keeping around.

**Comment by Owai-Seek** [comment]
I honestly don't care either way honestly. It checked to see if someone was a nympho, or possibly if had the hypno tag, but, it isn't that big of a loss. It was enough to raise an eyebrow on occasion, but otherwise, wasn't very prevalent. More of a "Huh, that happened." kind of thing.

Honestly, the entire pref system as a whole is a mess, but that kind of conversation doesn't really fit on this PR.

Also, bring back Buns of Steel.

**Comment by Commandersand** [comment]
i mean you're gonna ignore it when it does happen right?

just do that

**Comment by Akrilla** [comment]
already removed pog

**Pull request closed without merging**
