### PR TITLE
The Hugbot

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

The hugbot is the newest and cuddliest addition to the array of bots you can build. To build a hug bot, all you need is a borg arm, attach it to a box of hugs, then add a proximity sensor and voila! A hugbot!

The hugbot, as its name implies, goes about hugging crew members. It will not hug crew members which have already got the hugged moodlet.

The hugbot also has adjustable operating modes, allowing it to hug, pat and boop the crew!

The hugbot will provide helpful and friendly moral support to the crew, in the form of friendly reminders that they are an important member of the crew, and that they are loved.

Just be sure it isn't emagged. Emagged hugbots will hug too hard, knocking down crew members! They will also spurt out some less-friendly statements to boot.

## Why It's Good For The Game

Gives a use for the box of hugs, and also is a fun and gimmicky bot for robos to make. Primarily it's just a dumb and fun addition.

## Changelog
:cl:
add: Adds the hugbot
imageadd: Adds icons for the hugbot
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
This is a war crime against anyone with a set of luminescent eyes installed. Other than that, cute.

**Comment by IrkallaEpsilon** [comment]
Oh god.. it will make people tailwag

**Comment by jbox144** [comment]
> 
> 
> This is a war crime against anyone with a set of luminescent eyes installed. Other than that, cute.

How come?

**Comment by IrkallaEpsilon** [comment]
Toggling tailwag somehow turns off luminescent eyes.

Theres a worse crime:

Antag capture you and antag cuff you to chair, antag make you sad by placing a dead corgi infront of you or steal your trinket. Antag place hugbot infront of you and that one makes your tail wag permanently. Antag tells you you wont get out unless you say on tape how much you love headpats and wagging.

I really love this bot and how much evil you can do with it.

**Comment by Owai-Seek** [comment]
I don't believe it's toggling tail wag, as doing any help intent action (Actually, I haven't tried shaking hands, but Patting, Hugging, or Nose Booping) all turn of luminescent eyes.

**Comment by Gandalf2k15** [comment]
Petition to call this the companion cube

**Comment by davidchan13** [comment]
Emagged hugbot should hold hands instead, causing stamina damage from the shock at how much of a degenerate it is.

**Pull request closed without merging**
