### PR TITLE
[Code Bounty]Non-combat combat mechas

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Makes mechs and mech weapons produced by the exofab have, by default, security level restrictions. What this means is: Some mecha actions can only be used depending on the security level (phasing, at the moment) and the same applies for the weapons. This lock can be bypassed by either emagging the mecha or equipment, or unlocking it with an access card with armory access.

**Update:** You can also hack mechas to unlock them now.

**But why?**
To avoid banning roboticist players for bulding combat mechas. This essentially lets roboticists create mechas just for fun or armory storage, while still providing antags with an opportunity to get a functioning combat mecha.

## Why It's Good For The Game

We end up punishing players less with a very simple fix, without wacking things up in the game. Nukie or CC mechas will still be operated as normal.

## Changelog
:cl:
balance: Exofab produced mechas and mecha equipment now have security level based restrictions.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Yikes! I really really really do not like this.
This seems kind of a hand-fisted approach to the issue; Directors (and to a lesser extent Sec) should be keeping an eye on Robotics anyhow. This just seems kind of... well, lazy on Command/Secs part that this even needs to be a thing in the first place. The Ion Gun exists for a reason.

Additionally, this is going to bring up issues where antags are just going to keep the alert level down by any means required so Security can't even use any exosuits they happen to have.

Alert locking anything is a mistake, and this is will be no different I feel.
Thats just my 2¢.

**Comment by ShadeAware** [comment]
Additionally, you're also going to have issues where **everything is going to shit** and incompetent command won't be able to raise the alert level due to being unwilling or flat out unable. So, with this, it'll essentially be a case of "Tough shit lol hope you enjoy dying to the purple box that got on station and sitting out for the next two hours".

**Comment by RatFromTheJungle** [comment]
i see no reason robotics should be able to build combat mechs on a greenshift since all i've really seen come of it, is RDs playing sec against to many antags, and robotics building durands/gygaxs for giggles.
image

**Comment by jjpark-kb** [comment]
PR turning stale with some conflicts. Issues could arise with Roboticists making durands and other combat mechs during a green(?) shift, and then swap to combat when an issue comes. Closing for now.

**Pull request closed without merging**
