### PR TITLE
Revert "[MIRROR] removes dildo"

### PR DESCRIPTION
**Pull request by KathrinBailey**
Reverts Skyrat-SS13/Skyrat13#3257

Apparently this is purely cosmetic and a
image
type of change.

Please I'm so tired I just want my naptime I didn't even mean to wake up again.

### CODE REVIEW

**Comment by ForrestWick** [comment]
tbh I say just remove them. They're purely cosmetic and just kinda bloaty. They were being removed on Cit because they just kinda don't fit for the most part, and considering we're shooting for a more grounded environment there's really no reason to keep them

**Comment by CameronWoof** [comment]
What do we need these for?

**Comment by Owai-Seek** [comment]
This is the circuit assemblies, not dildos themselves, afaik.

**Comment by ThatGuyFromThatPlace** [comment]
This was removing the dildo circuits, not the dildo items
The dildo circuits that went down the hall and fucked anyone and everyone they passed... Which is, unhealthy to the server's RP atmosphere as well as just, something people don't want

**Comment by linuxbunter213** [comment]
Trust Kathryn Bailey to want to remove them anal bitch

**Pull request closed without merging**
