### PR TITLE
Adds high heels

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

title
sprites taken from baystation
heels can be found at clothing vendors in their polychromic form

## Why It's Good For The Game

fluff

## Changelog
:cl: Bob Joga, ported from Baystation
add: High heels.
imageadd: High heels icons.
/:cl:

### CODE REVIEW

**Comment by Akrilla** [comment]
add interactions with being stepped on 😳

**Comment by BobJoga** [comment]
> add interactions with being stepped on 😳

already a thing kind of

**Comment by ShadeAware** [comment]
bro pog

**Comment by ShadeAware** [comment]
@Akrilla Make attacking someone while they're down step on them instead 😳

**Comment by Akrilla** [comment]
image
accidental icon deletes

**Comment by BobJoga** [comment]
> image
> accidental icon deletes

fixed

**Pull request merged**
