### PR TITLE
[READY]Adds a flashing combat mode button and a flashing sprint mode button

### PR DESCRIPTION
**Pull request by improvedname**
Because frankly the light outline wasn't clear enough.
The button now flashes!~

## Changelog
:cl: Improvedname
tweak: The combat and sprint mode button now briefly flashes when activated.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
Kind of useless but since it doesn't really affect anything, meh
+0

**Comment by improvedname** [comment]
@BobJoga Thank you for your constructive feedback, check the diffbot before judging.

**Comment by jjpark-kb** [comment]
I do enjoy the flashing. I think it would be nice if they flashed in their original color as well? Like for the slime core theme.

**Comment by BobJoga** [comment]
> @BobJoga Thank you for your constructive feedback, check the diffbot before judging.

I'll be honest that comment was just kind of bad, just forget i said anything really. Apologies.
But still, after checking out the diffs, i don't think i like it that much because it just flashes too fast for me - Maybe you could make each frame in the animation last a bit longer?

**Comment by improvedname** [comment]
@jjpark-kb @BobJoga 
I'd leave that to a vote honestly but then again its personal preference,

**Comment by improvedname** [comment]
WOOPS

**Comment by improvedname** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11617

**Pull request closed without merging**
