### PR TITLE
Warns players that EORG is no longer allowed...

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
... unless they enable it in preferences.

## Why It's Good For The Game
This can be testmerged as a temporary measure or fullmerged. It reduces strain on admins and prevents people and makes people more aware of a new rule changed.

## Changelog
:cl:
tweak: Round end message now warns you that EORG isn't allowed.
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
Tested, it's functional:
image

**Comment by BobJoga** [comment]
Are our players this awful? I literally made a bold message warning them in chat already, this is redundant.

**Comment by BobJoga** [comment]
>to_chat(L, "<span class='notice'>The round has ended and you have chosen to <b>not participate</b> in end of round grief. Please behave as you have made your decision.</span>")

this is redundant

**Comment by BobJoga** [comment]
If people ignored two chat messages, adding another one won't solve it. It's not an issue of ignorance, it's an issue of straight up malice.

**Comment by KasparoVy** [comment]
Yeah bans em

**Comment by Echopsychotic** [comment]
Would it not be simpler to expand the safe zone out from the second you get off the shuttle?

**Comment by KathrinBailey** [comment]
closed by #3061

**Pull request closed without merging**
