### PR TITLE
Puts Nanite replication protocolls back in as a normal node. Removes BEPIS technode unlock for that.

### PR DESCRIPTION
**Pull request by IrkallaEpsilon**
Previously available relatively late (or if some guy reasearched nanites first and survived the lynching) now locked behind literal gambling and a waste of time.

## About The Pull Request

Removes one nanite technode from BEPIS. Moves the nanite technode back to regular RND. Considered raising the point cost a little.  Will do if asked.

## Why It's Good For The Game

BEPIS is a massive mistake. RNG paywalls that might give you nothing or 'amazing' stuff like gloves that cause 40 damage if you miss a grapple. How fun.

## Changelog
:cl:
tweak: BEPIS RNG fest now doesnt have nanite stuff in it anymore. Its dilluted enough as it is.
balance: Nanite replication protocoll research cost upped to 12500.
/:cl:

### CODE REVIEW

**Comment by IrkallaEpsilon** [comment]
One moment gonna have to check on some crap.

**Comment by ShadeAware** [comment]
Stole my mf idea 😭

**Comment by IronEleven** [comment]
Protocols were always intended to be BEPIS locked because they're so damn powerful (mostly Factory and Synergy), but Cit ported them in the wrong order.  Those two protocols specifically shit all over nanite balance if they're just straight up available for points every single round.

**Comment by Azarak** [comment]
What IronEleven said. I also don't like how powerful nanites are, like threats become trivial level

**Comment by Moostard** [comment]
As a person who learned and does the nanites nearly every round i must add that the whole nanite tree costs A LOT of research points. Not only that but it takes about 15-20 minutes to fully program them and few more minutes to build the pods around the station.
Nanites are balanced, just the other protocols dont have much sense.
One EMP can make you defenceless or even slowly kill you. Shocks damage them easily.
BEPIS is one big RNG machine and it is nearly impossible to get the protocols out of it, unless you rob the vault or something.
Virus is better than nanites in pretty much everything without the protocols.
Only like 1/4 people actually take the nanites even that they know they are good.
What makes nanites unique is the fact that they help you in combat and give some utility AND they are able to "ressurect" you if your body is still in tact.
But without the protocols their ressurection capabilities gets hit hard as they wont be able to heal the body quickly enough before the heart is rotten and not able to be defibbed.
Normal growth rate is 0.5, which can be 0.6 with one program but the BASIC healing program drains 0.5 nanites per cycle completly stopping them to even reach the more powerful healing program and other crutial programs like brain fixing and blood regeneration.
ALSO they are available to everyone, but not synths. Its not like only an antag or sec can have them.
BEPIS should be a nice addition but it shouldnt just be a necesity for some technology.

**Comment by IrkallaEpsilon** [comment]
Nanites can be powerful, but they have severe drawbacks:

Tempering is very easy, anyone can go to the nanite cloud and just add or remove programs. If you are off cloud and get EMPed malicious programs stay and you will die from them. If you are on cloud and get EMPed your nanites do not work properly. In either case an EMP means visit RnD for the manual chamber to remove nanites and reinject. 

An EMP is as easy as going to your nearest department lathe, getting a few sheets of uranium, deconning a chair nobody ever uses for iron, make a grenade casing, one beaker iron, other uranium done.

Protocolls:
Kickstart: Useless.
Tinkerer: Useless. nobody carries a beaker of iron with them
Sleep: Extremely gimmicky, perhaps in some kind of regenerative coma kind of deal probs pretty useful, could see some uses, sleep protocoll with induced sleep and feign death. Still very gimmicky.
Factory: Decent, takes time to build up but not blatantly overpowered. You cant run the somewhat decent programs with this 24/7. So no permanent bio reconstruction or permanent armor boost. One emp and the regen boost is gone.
Synergy: The only one thats pretty busted. Who would have thought that increasing regen with more volume was a good idea. If protocolls need to be nerfed to get them off of Bepis it would be synergy. Synergy is pretty much the go to. No drawbacks, no counters, no gimmick, just straight up "More regen if you have more volume.".

Lets see what other shit bepis offers: Stunnerangs/Stun Boomerangs, Hypno Chair, literal chair with wheels on it. LED light helmets, rocket gloves which hurt you ALOT if you miss. Nothing of that particularly useful bar the Hypno chair.

**Comment by IrkallaEpsilon** [comment]
Upped nanite replication protocoll research point cost to 12500. 2.5 times more costly in terms of research points that previously. That should delay them till really most things have been researched.

**Comment by ShadeAware** [comment]
Synergy should be locked behind BEPIS if anything

**Comment by IrkallaEpsilon** [comment]
Synergy should be nerfed, thats legit the only one that is completely out of balance.

**Comment by Moostard** [comment]
Yeah so, BEPIS is a pain to use. I just felt it. It should be an addition to gain weird not really useful technology.
But it has one technode which are protocols that are a must for nanites to work properly and not just be a weak virus wannabe with serious disadvantages.
Adding protocols to BEPIS is the worst idea you can come up with.
Especially that science doesnt have many ways of getting money.
I literally dont feel like the 15 minutes of sitting and programming them is even worth the time.
If you learn how nanites work you will see the LOST potential nanites bring.
We REALLY need those protocols back in RnD, no joke.
Also nanites are seen very rarely anyway and saying "too powerful" is either a joke or you hate nanites for some reason.
Everyone can get them, but not synths. If thats the problem then just let them have those but i dont know how logical that will be.

**Comment by IrkallaEpsilon** [comment]
I dunno if this is all too necessary with the budget cards being now in place.

**Comment by jjpark-kb** [comment]
certain technology is too strong for being able to just be research-able. The BEPIS is a great way of incorporating economy and research. 

If anything, more things need to be locked behind the BEPIS.

**Pull request closed without merging**
