### PR TITLE
[Ready] Player ticket manager

### PR DESCRIPTION
**Pull request by Akrilla**
## About The Pull Request

Players can now have more than one ahelp ticket at once, and it's nicely contained in an admin like player ticket manager. You can see your active tickets by using the "View Tickets" verb in the admin tab.

## Why It's Good For The Game

Baseline for further admin ticket changes, and makes it much easier for players to see their full conversation with an admin for logging and ease of use.

## Changelog
:cl:
add: Adds the player ticket manager, allowing players to have more than one active ticket (ahelp) at once. You can see your active tickets using the "View Tickets verb in the admin tab.
/:cl:

### CODE REVIEW

**Comment by Akrilla** [comment]
Not quite merge ready, need to test slightly more.

**Comment by ShadeAware** [comment]
Looking good, but I still wish we could see our past notes 😔

**Comment by Akrilla** [comment]
I'll bring it up with staff since I think it's something we should do tbh

**Comment by Azarak** [comment]
Looks good, I hope this doesn't break ahelps and cause anarchy to reign down

**Pull request merged**
