### PR TITLE
Bob weapons

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

This PR was made to address some balance changes Kat made (which, in my honest opinion, were awful) as well as the new parts they implemented.
Here's a condensed list of misc changes:
- Typepaths of many crafting items and weapons have changed to be more consistent
- Many recipes have been changed to accomodate the new parts
- Redundant recipes and parts were either removed, adapted or deleted
- Brought back the modular receiver, to be used as a generic receiver
- Changed name and desc of some items to be more consistent

New weapons and recipes have been added as well:
- New .22 magnum ammo type (casing and box can be made in the hacked autolathe). 22 magnum projectiles do 35 brute damage each (no armor penetration, takes bullet armor into account).
- Replaced the bolt action improvised rifle with 3 rifles: Lever action rifle (7.62mm, 1 chambered + 1 internal magazine), zip rifle (7.62mm, 1 chambered) and OU rifle (.22 Magnum, 2 chambered). The OU rifle can shoot a fast burst of two 22 magnum cartridges or shoot one at a time, depending on the toggle.
- ~~Pocket shotgun (essentially an extremely sawn-off improvised shotgun, but cannot be dual wielded, has a 0.4x damage and 0..5x armor penetration, has a tiny size and can be stored in pockets)~~ **Removed for the moment.**

Balance changes:
- The improvised shotgun can no longer be dual wielded, all versions of it will blow up in your face if you try to do so.
- The improvised shotgun no longer has an 0.8x damage multiplier - only the sawn version does.
- The lever action and zip rifle can be sawn off - at the cost of having an 0.8x damage multiplier. Rifles can only be dual wielded when sawn off. OU rifle cannot be sawn off.

**There are other changes which i may have forgotten, so i encourage taking a look at the code to see if something is goofy.**

## Why It's Good For The Game

Code consistency and good balance.

## Changelog
:cl: Bob Joga and JungleRat
add: Bolt action rifle has been replaced with 3 other types of rifle.
balance: Improvised rifle and improvised shotgun changes. See PR #2390 for more details.
balance: Changes in many crafting recipes to be consistent with weaponcrafting updates.
code: More consistency all around with gun crafting.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
oh these are **good.**

**Comment by RatFromTheJungle** [comment]
This, this is epic

**Comment by Owai-Seek** [comment]
Why would people literally ever need pocket shotguns?

**Comment by BobJoga** [comment]
> Why would people literally ever need pocket shotguns?

It has little use and it's quite shit. I'd say it's really for the entertainment value, and if you're desperate, a not really reliable but at least usable self defense firearm

**Comment by RatFromTheJungle** [comment]
> 
> 
> > Why would people literally ever need pocket shotguns?
> 
> It has little use and it's quite shit. I'd say it's really for the entertainment value, and if you're desperate, a not really reliable but at least usable self defense firearm

it's closer to being fluff, something not practical, not exactly useful in any context, but slapped in there so people have the option should they seek it

**Comment by Azarak** [comment]
Remove the pocket shotgun

**Comment by KathrinBailey** [comment]
4/6 maintainers are against this, 2/6 maintainers haven't expressed any opinions or mentioned it at all.

**Pull request closed without merging**
