### PR TITLE
Adds a can of whoopass

### PR DESCRIPTION
**Pull request by DeezNyas**
A can of whoopass that costs 7 TC to use, throwable weapon, not useful in much else

## About The Pull Request

Adds a 7 TC Can of whoopass item that you can throw at people to bonk them. Serves no other purpose other than funie reference to dudes of hazmat

## Why It's Good For The Game

It's funny and I coded it ergo speedmerge you fucks

## Changelog
:cl:
add: Can of whoopass
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
Good PR.

**Comment by IrkallaEpsilon** [comment]
Would suggest making that unacquireable from surplus crate. Surplus crate is dilluted enough as it is.

**Comment by DeezNyas** [comment]
> Would suggest making that unacquireable from surplus crate. Surplus crate is dilluted enough as it is.

Getting something that can instantly shatter a person's leg by throwing it isn't exactly 'clutter'

**Comment by DeezNyas** [comment]
> Good PR.

😳

**Pull request closed without merging**
