### PR TITLE
huge blob buff, please be careful

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
there are a lot of value changes. Check the changelog and the code itself for all the changes

## Why It's Good For The Game
blobs are so very weak and have been weak for too long.

## Changelog
:cl:
tweak: Blob cost to spread is reduced from 4 > 3
tweak: Blob cost to attack is reduced from 3 > 0
tweak: Blob shield cost reduced from 15 > 5
tweak: Blob clouds increased from 1 > 2 (0 > 1)
tweak: Blob is announced at 3 > 5 minutes after spawning
tweak: Blob core will have a 5% > 10% chance of upgrading the blob around it
tweak: Blob factories spawn 3 > 5 blobs now instead every 8 seconds
tweak: Blob nodes will have a 0% > 5% chance of upgrading the blob around it
tweak: Blob resources will now increase by 1 > 2
tweak: Power cost for Resource decreased 40 > 20
tweak: Power cost for Node decreased 50 > 30
tweak: Power cost for Factor decreased 60 > 40
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
Whyyyyyy are we buffing blob? What positive experience do we stand to gain?

**Comment by calibraptor** [comment]
Increase the rarity immensely to compensate please.

**Comment by H0gberg** [comment]
blob buff is good, it makes it the intimating antag it's meant to be, good change Jake!

**Comment by ThatGuyFromThatPlace** [comment]
Blob is an antag, that can outright end the round instantly, and it already has done so previously, with nothing but annoyed players as a result. 
Blobs have on multiple occasions, ended the round for ~80 people, all for the satisfaction of 1-3 players at most...
I firmly believe that dumping all these buffs onto the blob will easily make it blatantly overpowered, and, do not think they are weak or underpowered, but, rather require skill, and planning. After all, it should, require skill and planning to literally bring the round to a screeching halt in your favor, fucking over every other player on the server

**Comment by Owai-Seek** [comment]
There are only a few blob buffs that I feel are "necessary" (after talking with someone while they were digging through the code. Don't slap me too much if I'm mistaken.)

-Making it so reflective tiles actually reflect emitters, because from what I was told, they don't.  Apparently, the chance for reflecting lasers is also very low. When discussed, `Ricochet` was brought up.
-Blobbernauts being able to see their health, and the cores health, in a Health-HUD fashion. (I imagine blobbernaut strength is determined by blob type, and from what I've seen, many have pulled back after receiving one or two hits, when they could probably take 10-12 depending on type.)
-General blob spore changes. Most smokes only seem to react in-body, and 9/10 times, some idiot bombs the blob and vents the area, meaning everyone is wearing internals. This is especially bad with EMP spores, as they do nothing to mechs.

**Comment by jjpark-kb** [comment]
got approved, shamelessly merging.

**Comment by N0B0DY-1MP0R7AN7** [comment]
Please.... please do remove this.
I've seen half of OOC complain about blobs being OP BEFORE this went online.

**Comment by KasparoVy** [comment]
The solution is to stop playing when blob happens and come back later

If no-one's gonna listen then c'est la vie

**Comment by ThatGuyFromThatPlace** [comment]
Oh look, my prediction was correct. Now blob is almost guaranteed to end the round, there's always 2 blobbernauts minimum, and, nobody has fun. Great job forcing this overbuff through despite nobody wanting it.

**Comment by chefferz** [comment]
This has made the last two days of dealing with the blob unpleasant and impossible to fight.

**Comment by ThatGuyFromThatPlace** [comment]
> This has made the last two days of dealing with the blob unpleasant and impossible to fight at the sake of ghost role enjoyment and one person, particularly with the fact blobbernaughts can disable you in three hits,
> 
> Increase the rarity of this at an absolute minimum. Increase the attack cost back to 3. Why it was dropped to zero is ???.

Agreed. The biggest offenders to this buff was the attacks costing nothing (Blob is now impossible to melee) and the resource nodes being quite literally doubled in efficiency.

**Pull request merged**
