### PR TITLE
Adds a lot of shit to the new inventory slots

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Title

- Sausages can now go on the ear slot
- Injectors can now go on the ear slot
- Candles can now go on the ear slot
- ID cards can now go on the ear slot
- The skeleton key can now go on the wrist and ear slots
- Crayons can now go on the ear slot
- Pugilist gloves and subtypes can now go on the wrist slot
- Bone bracers can now go on the wrist slot
- Rings can now go on the wrist slot
- Cigarettes can now go on the ear slot
- Pills and patches can now go on the ear slot
- Keys and subtypes can now go on the wrist slot (janitor and segway keys mostly)

## Why It's Good For The Game

ear candle means i can make bad jokes about ear wax

## Changelog
:cl:
tweak: Sausages can now go on the ear slot
tweak: Injectors can now go on the ear slot
tweak: Candles can now go on the ear slot
tweak: ID cards can now go on the ear slot
tweak: The skeleton key can now go on the wrist and ear slots
tweak: Crayons can now go on the ear slot
tweak: Pugilist gloves and subtypes can now go on the wrist slot
tweak: Bone bracers can now go on the wrist slot
tweak: Rings can now go on the wrist slot
tweak: Cigarettes can now go on the ear slot
tweak: Pills and patches can now go on the ear slot
tweak: Keys and subtypes can now go on the wrist slot (janitor and segway keys mostly)
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
image
?? I don't get it
how
why

**Comment by Zenitheevee** [comment]
yeah, my only odd thought is id cards in the ear... 

Then again, i always thought pens were more resting _On_ the ear and not jammed in there like some tween trying to dislodge their eardrum

**Comment by BobJoga** [comment]
> image
> ?? I don't get it
> how
> why

someone asked for it, it's a thing in eris, also the thought makes me laugh

**Comment by YakumoChen** [comment]
It just works.

**Comment by Investigator77** [comment]
The ear slot can be interpreted as both "sticking in your ear" and "behind your ear" depending on the item

**Comment by Gandalf2k15** [comment]
donuts on wrist slot and speed merge.

**Comment by xXPawnStarrXx** [comment]
Carrots should go in the ear slot, makeshift ear plugs in prison.

**Comment by Yawet330** [comment]
stale bot is not poggers.

**Pull request closed without merging**
