### PR TITLE
More Posters.

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Adds more posters...

## Why It's Good For The Game

We don't have a whole lot of posters for variety... this is a solution for that.

## Changelog
:cl:
add: Added 50+ new contraband posters.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
finally
valve guy poster

**Comment by KathrinBailey** [comment]
Have you tested that all the ones not called poster123 or poster123_legit both spawn correctly in game and make the correct poster when using wirecutters on the posters?

The naming scheme might be there for a reason, not sure.

**Comment by jjpark-kb** [comment]
> Have you tested that all the ones not called poster123 or poster123_legit both spawn correctly in game and make the correct poster when using wirecutters on the posters?
> 
> The naming scheme might be there for a reason, not sure.

hmm, it should work, ill try.

**Comment by jjpark-kb** [comment]
So yea, it works. Naming scheme is fine.

**Pull request merged**
