### PR TITLE
Advanced markings

### PR DESCRIPTION
**Pull request by BobJoga**
##  About The Pull Request

Adds advanced markings to the character setup. These are simply put, limb-based, stackable markings that can also have fluff text attached to them. They work in a similar vein to the cosmetic scars in #2578, with the added benefit of completely supporting sprite accessories.

image

~~**Note:** While the code is pretty much complete, i still have yet to add all sprite accessories relating to body markings, as well as properly renaming icons, so only spriteless examine fluff markings are an option at the moment.~~

It's 100% done.

**Edit:** This PR also stops descriptors from saying "for a [species]" when examined, by default

## Why It's Good For The Game

epic character customization

## Changelog
:cl: Bob Joga, VOREstation for sprites
add: Added advanced, limb-based markings on the character setup.
tweak: Descriptors by default no longer mention species, and are therefore generalized.
/:cl:

### CODE REVIEW

**Comment by H0gberg** [comment]
Now this... is epic

**Comment by ShadeAware** [comment]
Based Bob at it again proving again how this codebase needs him.

**Comment by JGlitch** [comment]
yes, please, NOW

**Comment by DarkWolfInsanity** [comment]
What if my character is made entirely of markings? Would there be a setting to disable marking examining?
image

**Comment by BobJoga** [comment]
> What if my character is made entirely of markings? Would there be a setting to disable marking examining?
> image

Yes. Just don't have any description/examine text for it!

**Comment by Azarak** [comment]
Im worried about the extra need of networking 10 or so extra images per a player mob to every client. I dont know if maybe taking all the markings and blending them together when the character joins the round would be better, but that could cause lag spikes due to the server processing that Blend does

**Comment by KasparoVy** [comment]
Images are pretty efficient afaik, would be good to testmerge and profile the difference

**Comment by BobJoga** [comment]
> Im worried about the extra need of networking 10 or so extra images per a player mob to every client. I dont know if maybe taking all the markings and blending them together when the character joins the round would be better, but that could cause lag spikes due to the server processing that Blend does

I think this warrants at least a testmerge.

**Comment by ShadeAware** [comment]
bruh

**Comment by BobJoga** [comment]
this is shitcode

**Pull request closed without merging**
