### PR TITLE
Fixes an ancient botany bug

### LINKED ISSUE #2041: Grass growth is not working
## Round ID: N/A

 (Numerous rounds spanning the last several months)

## Date and Time of Issue:

 N/A (Numerous rounds spanning the last several months)

## What Map did this Issue occur on: 

All (Box, Meta, Puby, Delta)

## Testmerges (If Applicable):

N/A no consistent test merge has been present for this bug.

## Reproduction:

 Grass growth is entirely RNG and unreliable. 

Grass has a maturation of 2, and a default production of 5. This is supposed to mean that after 7 cycles, it will be ready for it's first harvest.

This is not the case. Vanilla grass, gene edited and chemical enhanced grass alike, there is no rhyme or reason to when grass ready to harvest. Typical wait can be 50+ growth cycles with cases of age 100 grass still not having a single harvest. 

This also applies to mutate strains of grass (Carpet and Fairygrass)

This is troublesome as grass has it's uses to botany and public garden users who might want to make grass floor tiles and/or harvest grass to produce sand to create sandstone and dirt piles to grow more plants with.

TL;DR:
Plant grass seeds.
Use data analyzer to check stats (2 maturation + 5 production = harvest after 7 cycles)
Wait 10 times that number while tending plant and watching it meticulously.
Still not recieve any harvest.

### LINKED ISSUE #2560: Modded fairygrass can't be harvested
## Reproduction: I've noticed that fairygrass, when having a maturation time of 2 and a production time of 1, doesn't seem to ever grow to the point where you can harvest it. The fairygrass in my case was planted in a self-sufficient tray.
1. Mutate grass to fairygrass
2. Replace production time to 1
3. Plant in self-sufficient tray

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

It fixes a rounding error that breaks certain plants growthstages and iconstates.

## Why It's Good For The Game

It fixes the growth bug when you get growth speeds on a plant way too low.

Closes #2041
Closes #2560

## Changelog
:cl:
fix: fixed botany rounding error that caused grass and other plants to misbehave
/:cl:

### CODE REVIEW

**Comment by xXPawnStarrXx** [comment]
Is this what causes grass to go to negative growth speeds and not even grow at all even though the stats seem fine?

**Comment by yorii** [comment]
> Is this what causes grass to go to negative growth speeds and not even grow at all even though the stats seem fine?

I think so yes, been a while I don't remember what actually fixes it, I just remember it was something obscure like this edit.

**Comment by yorii** [comment]
I think I made travis do the thing now

**Comment by yorii** [comment]
I may be stupid

**Comment by Azarak** [comment]
This only touches up on the icon state of the overlay. I don't think it fixes that grass bug. I havent seen icon states bug out anyway. Also what's up with that comment

**Comment by yorii** [comment]
I had some issues with Travis so I kept editing a comment to get it to actually compile and now I'm too scared to remove it

**Comment by yorii** [comment]
also the iconstates are in fact not working correctly on a few plants

**Comment by yorii** [comment]
Tested it and yeah it fixes the grass bug too @Azarak

**Comment by Azarak** [comment]
it is a bizarre bug, if you say so I trust you

**Review by Azarak — APPROVED** [review]

**Pull request merged**
