### PR TITLE
[Modular] [Ready] Changes the Positronic Brain welcome message.

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Changes a small bit of text on the Positronic welcome from "Above all else, do no harm" to "Above all else, follow your laws".

## Why It's Good For The Game
Was discussed a bit in Player-Staff-Chat, the DNH clause could cause some confusion and conflict with specific laws. Exosuit positronic brains are already precluded from going on rampages by the threat of being beaned.

## Changelog
:cl:
tweak: Changes Positronic Brain welcome message to be more neutral in regards to which laws it should follow.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I'm actually not sure if this makes sense. Being cyborgified overrides previous posibrain flavortext, and posibrains can be made to do other things (notably be put in mechs) for which the flavor text becomes relevant, both from a hardcode perspective (they shouldn't be able to use weapons) and from a gameplay perspective (posibrains don't GET laws to follow, thus making the flavor text moot)

**Comment by Akrilla** [comment]
Above is true, not sure what best way to fix that

**Comment by YakumoChen** [comment]
I wouldn't actually think a change is needed? Only the posibrain, by itself, is tasked to SERVE and DO NO HARM as its core directive. Unless you'd like posimechs to be able to use weapons (why?), you are better off doing nothing, or otherwise removing the "DO NO HARM" directive altogether and removing the posimech limitations.

**Comment by Azarak** [comment]
What above people said

**Pull request closed without merging**
