### PR TITLE
Biogenerator Tweaks

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Tweaks the recipes of biogenerators.
Removes all liquid creation from biogenerators and just makes them into bottles.
Biomeat is now actually biomeat.

## Why It's Good For The Game

Biogenerator is apparently bad.

## Changelog
:cl: BurgerBB
balance: Rebalances Biogenerators.
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
Please also do this for the Prisoner variant.

**Comment by BurgerLUA** [comment]
sure

**Comment by Owai-Seek** [comment]
Still don't know how modular code works but if this is just a replacement list for the biogen I have the following concerns:

- Nerfs Cheese Production
- Replaces Synthmeat in biogen with a meat that nobody but flies can eat.
- Makes obtaining meat tedious and encourages monkey murder. (Synthmeat was already omega expensive compared to monkey cubes, cmon, wtf)
- Makes getting flour tedious again.
- Doesn't add soymilk :(
- Adds Diethylamine, which is just a flat out better Ammonia for the same cost.

Also, as a note, I'm fairly certain all of the bottles dispensed by the biogen give 50 units, not 30

**Comment by davidchan13** [comment]
Biomeat is generally worthless. If we are going this route we might we well add mutagen bottles at t4 parts so the biogen isn't just a textiles producer and some value to hydro

**Comment by Akrilla** [comment]
Will likely be closed in a couple days if no updates.

**Comment by BurgerLUA** [comment]
Will make another PR next week.

**Pull request closed without merging**
