### PR TITLE
Shamelessly steals nanite updates from a downstream

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

pretty much this https://github.com/DeltaKris/Another-Era/pull/18

tldr nanites now respect rules proper, signaller nanites

## Why It's Good For The Game

i hate nanites but this is cool

## Changelog
:cl: Trigg
add: Nanite Signaler program
add: Stamina Damage is now an option to be detected by the damage sensor program
fix: On the nanite programmer, you can now use 0 as a number without making the field reset to its default.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
what the fuck for some reason this is using shit from https://github.com/Skyrat-SS13/Skyrat13/pull/2922

**Comment by BobJoga** [comment]
holy shit i am actually retarded i committed everything from my master

**Comment by TriggeredBoi** [comment]
the madlad actually did it

now do infiltrators too like you also said you would.
and probably remove my _new era_ comments.

**Comment by BobJoga** [comment]
> the madlad actually did it
> 
> now do infiltrators too like you also said you would.
> and probably remove my _new era_ comments.

i'll remove those and replace them with "thanks trigg"
image

**Comment by TriggeredBoi** [comment]
even better

**Pull request merged**
