### PR TITLE
Rewords Vampire Conversion

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Rewords a vast majority of the Bloodsucker conversion ritual to be much more neutral in terms of the thoughts and feelings of the participants.

## Why It's Good For The Game
The Vampire conversion ritual is filled with extremely creepy and downright disturbing messages that border on preference-breaking with just how much they allude to mindbreak and BDSM. A vast majority of people, myself included, found this to be incredibly creepy and not fitting the server whatsoever.
Originally, I wanted to change how conversion was done entirely, but that was canned by the administration (despite a vote), so this is a compromise.
image

## Changelog
:cl:
tweak: Made Vampire thralling a lot less creepy and less BDSM/Mindbreak fetish bullshit.
/:cl:

### CODE REVIEW

**Comment by hugmeorelse** [comment]
This PR is pref-breaking me. 

Halp.

**Comment by hugmeorelse** [comment]
This PR is pref-breaking me. 

Halp. ;-;

Anyways, I'll take a look over it to make sure it has the changes we discussed. However, I suggest you stop making it about a fetish when this game mode comes from a non-ERP server. If it was that case purely, I would reject this PR because sensationalism of this kind won't be tolerated. Maiming and bone-breaking isn't necessarily fetish, especially considering its origins.

The issue with the original flavor text and mechanics is that it was very railroaded into a very specific form of conversion. We only want to make the text more neutral to allow for more creativity on part of the players. I'll be reviewing the code to see if it does that. If it does, I will most likely accept it on that account.

**Comment by hugmeorelse** [comment]
This PR is pref-breaking me. 

Halp. ;-;

Anyways, I'll take a look over it to make sure it has the changes we discussed. However, I suggest you stop making it about a fetish when this game mode comes from a non-ERP server. If it was that case purely, I would reject this PR because sensationalism of this kind won't be tolerated. Maiming and bone-breaking isn't necessarily fetish, especially considering its origins.

The issue with the original flavor text and mechanics is that it was very railroaded into a very specific form of conversion. We only want to make the text more neutral to allow for more creativity on part of the players so as to allow for more roleplay as it is a roleplaying server. I'll be reviewing the code to see if it does that. If it does, I will most likely accept it on that account.

**Comment by hugmeorelse** [comment]
This PR is pref-breaking me. 

Halp. ;-;

Anyways, I'll take a look over it to make sure it has the changes we discussed. However, I suggest you stop making it about a fetish when this game mode comes from a non-ERP server. If it was that case purely, I would reject this PR out of principle, because sensationalism of this kind won't be tolerated. Maiming and bone-breaking isn't necessarily fetish, especially considering its origins.

The issue with the original flavor text and mechanics is that it was very railroaded into a very specific form of conversion. We only want to make the text more neutral to allow for more creativity on part of the players so as to allow for more roleplay as it is a roleplaying server. I'll be reviewing the code to see if it does that. If it does, I will most likely accept it on that account.

**Comment by hugmeorelse** [comment]
This PR is pref-breaking me.

Halp. ;-;

Anyways, I'll take a look over it to make sure it has the changes we discussed. However, I suggest you stop making it about a fetish when this game mode comes from a non-ERP server. If it was that case purely, I would reject this PR out of principle, because sensationalism of this kind won't be tolerated. Maiming and bone-breaking isn't necessarily fetish, especially considering its origins.

The issue with the original flavor text and mechanics is that it was very railroaded into a very specific form of conversion. We only want to make the text more neutral to allow for more creativity on part of the players so as to allow for more roleplay as it is a roleplaying server. I'll be reviewing the code to see if it does that. If it does, I will most likely accept it on that account. Based on what I see, the re-wording seems fine. Only minor edits are needed like removing the parentheses in "This is the vassal rack, which allows you to thrall crewmembers into (likely reluctant) servants".

**Comment by Arturlang** [comment]
A big reason why i wanted to redo the whole thing

**Pull request merged**
