### PR TITLE
[FEEDBACK WANTED!!!] Changes ahelp language to be more forgiving and kind + Extra transparency

### PR DESCRIPTION
**Pull request by CinderWC**
## About The Pull Request
Modified Version of https://github.com/Citadel-Station-13/Citadel-Station-13/pull/8946
Big thanks for @BurgerLUA for setting the blueprint for me to work off of

Recently that PR has made their way into our dev channel and i was apalled at how badly Burger was ridiculed for making some very valid changes. This PR is about porting that over and possibly elaborates or modifies it a bit more to fit our environment

**Changes are to the following situations:**

When an admin starts to handle your ticket:
`Your ticket is now being handled by (X ADMIN). Please wait while they type their response and/or gather relevant information.`

When an Admin rejects your Ticket:
`Your adminhelp was rejected.
The adminhelp verb has been returned to you so that you may submit another ticket.
Please try to be calm, clear, and descriptive in adminhelps. Assume that the admin has not seen any related events, and clearly state the character names or byond keys of anybody you are reporting.`

When a ticket is marked as IC issue:
`An admin has looked at the submitted issue and has determined that the reported incident is valid.
Some actions by users, while appearing malicious, can be legitimate due to their status or given situation.
Please do not be discouraged from reporting similar instances in the future.`
## Why It's Good For The Game
Burger summed it up best in the original PR:
> The current language is really weak and doesn't really give anything for the person to chew on when it comes to learning the game. For the IC issue response, it assumes too much about why you're ahelping by stating "Losing is a part of the game.", which can cause the undesired effect of the admin not really knowing about the situation as not everyone who ahelps does it because they die or get caught. It also doesn't really explain that much for a button that is so commonly used, so that is also fixed.
It also re-words some of the responses to seem less direct and more friendly. For example, It doesn't say "do not assume that the admin knows everything" but says "assume the admin knows nothing". Language has a huge impact on mood and mannerisms which is why you never have tech support companies say "Calm and be patient before you speak to our operators." but rather "Please speak in a calm, clear manner when describing the problem."

## Changelog
:cl:
add: Handle Ticket Verb now states WHO is handling the ticket
tweak: Tweaks ahelp preset responses to be more friendly.
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
I think changing the text is an all-around improvement for admin to player interactions, but I'm always a bit finicky about wording on things. It's still a large step forward from slapping a player in the face with "Losing is part of the game!"

**Comment by KathrinBailey** [comment]
Yeah this seems nice.
Ahelps handling/rejection/IC etc verbs shouldn't be "Fuck you, Baltimore! If you're dumb enough to ahelp new shitter this weekend, you're a big enough schmuck to come to Big Bill Hell's Ahelp verb!". 

**POLITENESS GANG**

**Comment by BobJogaIsForkinBanned** [comment]
I very much like this, yeah.

**Comment by Strazyplus** [comment]
why was he ridiculed? this looks like a good improvement however I think the messages can be a little bit less but I spent a small bit of time trying to shorten them and failed.

Those are good messages to send now... the only thing I can suggest shorting is:

When an admin starts to handle your ticket:
Your ticket is now being handled by (X ADMIN). Please wait while they gather relevant information.
or
Your ticket is now being investigated by (X ADMIN). Please wait for a response.

**Comment by CinderWC** [comment]
>the only thing I can suggest shorting is When an admin starts to handle your ticket

I know that this may look very long in the file itself, but it wont be that long looking ingame and will look a lot more neater than what it looks like right now. However i may actually go through with the shortening after i give it some more thought

**Comment by ShadeAware** [comment]
poggers

**Comment by LimblessLayabout** [comment]
On this subject, can we get 'MAN UP' subbed out for a 'CHILL OUT' verb?

**Comment by CinderWC** [comment]
> On this subject, can we get 'MAN UP' subbed out for a 'CHILL OUT' verb?

Nah I want that to stay the same.
We gotta keep some level of assertiveness

**Pull request merged**
