### PR TITLE
Removes "my ass is heavy" line from HECU masks

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

title

## Why It's Good For The Game

it's lrp

## Changelog
don't really feel it's necessary

### CODE REVIEW

**Comment by Moostard** [comment]
This game has a lot of memey stuff.
It adds some fun to the game.
Remove Beepsky's lines too as he has pretty LRP insults then.

**Comment by NopemanMcHalt** [comment]
This is so sad.
Station Bot, play Astronomia.

~~let me guess someone complained about that and staff supported it?~~

**Comment by BobJoga** [comment]
> This game has a lot of memey stuff.
> It adds some fun to the game.
> Remove Beepsky's lines too as he has pretty LRP insults then.
> (don't)

In a perfect world, PRs like these would not exist. But this is not a perfect world.

**Comment by BobJoga** [comment]
I really don't care about ""LRP"" content, this PR is only a thing because staff complained. I can't do shit about it. If i was pulling the strings the server would be a memey hellhole.

**Pull request merged**
