### PR TITLE
Added TTS device for loadouts

### PR DESCRIPTION
**Pull request by Jamini**
Adds a handheld TTS device in loadouts that costs 7 (of 10) loadout points.

The Device can be clicked to send a message to local say. (Bounce radios and intercomms can overhear this, headsets cannot)
All inputs should be sanitized. I was unable to crash my local server with a few commands I know that used to do so with papercode years ago.
It can be renamed (and given a new description) with a pen, like food/drink items.
Alt-clicking on the device gives the user an option to make the TTS Beep, Buzz, or Ping.

--------

Why is this good for the game:

This is a nice fluff item, and a possible utility for mute characters who want an alternative to spamming PDAs. The high price is there to help justify how much it will offset the quirk. (Putting it in-line with the advanced tablet in price/availability) as well as the relative difficulty of building a similar item with circuits. (Which is not hard, but does require cargo or science assistance)

It also doesn't remove the negative quirk, as well as requiring a free hand and inventory space to utilize.

Plus, honestly, it's a very real item irl. I've seen a lot of people new to the server who are confused that they don't exist outside of building one every shift with a circuit.

---------

Other thoughts:

It would be cool to consider giving one to the Curator, since they are supposed to be a polyglot. However that is outside of the scope of this particular PR.

Everything should be modularized for skyrat.

### CODE REVIEW

**Comment by Akrilla** [comment]
Items like this tend to mess with languages, I wouldn't want this being too overly accessible if it could just be used to bypass language barriers.

**Comment by Jamini** [comment]
That is a fair point, however I wouldn't call it more accessible than a
modular circuit TTS. 7 loadout points is quite a lot, which gives up a
large chunk of potential utility items (I.e. you can spawn with a cheap
tablet, crowbar, and a stack of paper for that value).

Doubly so when a scientist or CT could make an equivalent item for free in
3/6 minutes or less in current code.

It might be possible to have the tts pull the default language of the user
if you feel it would be a serious issue. Though that could get messy.

**Comment by Azarak** [comment]
Im wondering if there's a better way to do this.. Like talking through an item like you can do with bounced radios or the ventriloquist dummies. Plus this would require you to indicate whose the device is, perhaps by its name. Not sure how well it works with runechat too.

**Comment by Jamini** [comment]
Talking through an item wouldn't work for the intended function of the
item.

The device can be renamed with a pen, as stated.

Runechat posts to the location where the device is. If it is in a pocket it
will show it over the inventory slot (which is weird, but that's how
runechat works.)

**Comment by Akrilla** [comment]
Allow the item renaming through an obvious alt-click interaction, and an examine text note that tells the user they can rename the device by doing so. That and conflicts and I'm okay with this, but will be weary about it possibly being abused in the example I gave above.

**Comment by Jamini** [comment]
Talked with Akrilla on discord.

- Alt-click remains functionality. The description of the device has been updated to make that more apparant
- Renaming is still possible with a pen. The flag that performs this appears to automatcially add text to the item stating it can be renamed.
-Updated my own repo to clear out some merge conflicts.

**Pull request merged**
