### PR TITLE
[april fools testmerge] Introducing: The N word counter subsystem

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds an N word counting subsystem, that notifies admins whenever a player says a variation of the N word, and shows the total count of N words as well as all N word including messages in the round end report.
Future features may include:
Adding n word counts for each individual, and warning them if they exceed their n word pass treshold.
Adding the most n-word saying person to the round end report.
Counting Barack Obama (and variations) as 10 n words.
N word passes assigned to each player. Exceeding your assigned use of the n word pass results in smiting.

## Why It's Good For The Game

It makes our server even more gamery than hippie.

## Changelog
:cl:
add: N word counter subsystem
tweak: Round end reports now show n word statistics 
/:cl:

### CODE REVIEW

**Comment by CinderWC** [comment]
maxresdefault

**Comment by IronEleven** [comment]
I've only heard it secondhand but Cit's maintainers have claimed that having the n-word anywhere in the code, even as part of a word filter, is enough to get repos shut down.

**Comment by BobJoga** [comment]
> I've only heard it secondhand but Cit's maintainers have claimed that having the n-word anywhere in the code, even as part of a word filter, is enough to get repos shut down.

Some people have told me this and i am quite... confused by it to be honest. I couldn't find any proper information on the subject.

**Comment by PersianXerxes** [comment]
GitHub, as a company, does shut down projects that use the n-bomb or the name of a certain 30's era German political party.

This isn't funny, please don't make meme PRs like this just to endanger our repo. :/

**Comment by BobJoga** [comment]
> GitHub, as a company, does shut down projects that use the n-bomb or the name of a certain 30's era German political party.
> 
> This isn't funny, please don't make meme PRs like this just to endanger our repo. :/

Well then god damn, i'll have to shut down this joke PR.

**Comment by BobJoga** [comment]
> GitHub, as a company, does shut down projects that use the n-bomb or the name of a certain 30's era German political party.
> 
> This isn't funny, please don't make meme PRs like this just to endanger our repo. :/

I just looked into it and we have one instance of the n word on our code, and so far nothing has happened. I'll still do some precaution changes (sneakier n word vars) to the PR as i did in hippie.

**Comment by jjpark-kb** [comment]
I really hope this doesnt fuck us.

**Comment by CinderWC** [comment]
Just close the entire thing please.

We shouldn't put our repo on the line just because we have to have le funny n word meme PRs

**Comment by BobJoga** [comment]
> Just close the entire thing please.
> 
> We shouldn't put our repo on the line just because we have to have le funny n word meme PRs

fine
i shall officially close the best pr to ever get denied on any ss13 server

**Comment by BobJoga** [comment]
IT SHALL BE REVIVED, FOR A BRIEF MOMENT. FOR A BRIEF DAY.

**Comment by CinderWC** [comment]
Bob. No.

**Pull request closed without merging**
