### PR TITLE
Credits

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
Makes credits roll at the end of a round.
Credit:
https://github.com/BeeStation/BeeStation-Hornet/pull/318
https://github.com/BeeStation/BeeStation-Hornet/pull/320
https://github.com/BeeStation/BeeStation-Hornet/pull/321
https://github.com/BeeStation/BeeStation-Hornet/pull/327
https://github.com/BeeStation/BeeStation-Hornet/pull/400
https://github.com/BeeStation/BeeStation-Hornet/pull/407

## Why It's Good For The Game
Credits look cool

## Changelog
:cl:
add: Added credits from Bee, from Oracle.
/:cl:

### CODE REVIEW

**Comment by Afya212** [comment]
Eh, they can also get in the way if you're in the middle of doing something when the round ends.

**Comment by jjpark-kb** [comment]
> Eh, they can also get in the way if you're in the middle of doing something when the round ends.

it has a pref

**Comment by Akrilla** [comment]
basedtainer

**Comment by ShadeAware** [comment]
based

**Pull request merged**
