### PR TITLE
[Testmerge] Ports Bobbahbrown & Burger's Rune-like chat popups (PR from TG)

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
original PR: https://github.com/tgstation/tgstation/pull/50608

I made some small changes so it so you don't get double text for yourself while using comms and I also put the layer above all lighting mumbo jumbo

## Why It's Good For The Game
Check the original PR

## Changelog
:cl:
add: Adds rune scape-like chat popups, toggleable in game settings
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
### poggers

**Comment by RatFromTheJungle** [comment]
doesn't respect whispering nearly as much as the chatbox, you can essentially read the entire message with no issue 
tested at 4 tiles

**Comment by Azarak** [comment]
> 
> 
> make it so that the text shows up above blindness

Will do

**Comment by Akrilla** [comment]
What's the state of this rn now then?

**Pull request closed without merging**
