### PR TITLE
[Semimodular] Stasis Beds

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
adds stasis beds:
pauses bodily functions while buckled. Chemicals, organs, bleeding, etc.
can be used for surgery

Operating computers now work on diagonals.

## Why It's Good For The Game
stasis beds are extremely helpful for medical. Death should be feared, but it really shouldn't pull you out of the game for 20+ minutes with doctors failing to deal with you. Stasis beds can help this.

## Referenced PRs
https://github.com/tgstation/tgstation/pull/43075
https://github.com/tgstation/tgstation/pull/50443
https://github.com/tgstation/tgstation/pull/46223
## Changelog
:cl:
add: Added stasis beds
tweak: tweaked operating (surgery) computers to work on diagonal
/:cl:

### CODE REVIEW

**Comment by Weblure** [comment]
Is there a way to unbuckle yourself from these beds without external help? I don't remember if these lock you into a state of unconsciousness or not. All I remember from my short time on TG is that being abandoned on one of these things was worth than death.

**Comment by TheSpaghetti** [comment]
Let us have both sleepers AND stasis beds, please.

**Comment by jjpark-kb** [comment]
> Is there a way to unbuckle yourself from these beds without external help? I don't remember if these lock you into a state of unconsciousness or not. All I remember from my short time on TG is that being abandoned on one of these things while in crit was worth than death.

you can unbuckle yourself from these stasis beds.

> Let us have both sleepers AND stasis beds, please.

I didnt remove the sleepers.

**Comment by TheSpaghetti** [comment]
> > Is there a way to unbuckle yourself from these beds without external help? I don't remember if these lock you into a state of unconsciousness or not. All I remember from my short time on TG is that being abandoned on one of these things while in crit was worth than death.
> 
> you can unbuckle yourself from these stasis beds.
> 
> > Let us have both sleepers AND stasis beds, please.
> 
> I didnt remove the sleepers.

The code looks like you did.

**Comment by Weblure** [comment]
> > > Is there a way to unbuckle yourself from these beds without external help? I don't remember if these lock you into a state of unconsciousness or not. All I remember from my short time on TG is that being abandoned on one of these things while in crit was worth than death.
> > 
> > 
> > you can unbuckle yourself from these stasis beds.
> > > Let us have both sleepers AND stasis beds, please.
> > 
> > 
> > I didnt remove the sleepers.
> 
> The code looks like you did.

Looks like he replaced 1 sleeper with a stasis bed in each station:
image

**Comment by Dr-0range** [comment]
Is it possible this update disabled pixelshifting and turning while buckled?

**Comment by Yawet330** [comment]
Issues: Stasis beds stop reagent processing, and do not allow for painless surgery.

-do you see the issue-

**Comment by jjpark-kb** [comment]
> Issues: Stasis beds stop reagent processing, and do not allow for painless surgery.
> 
> -do you see the issue-

Dont use that tone on a github PR.
Its intentional that they dont process reagents.
Ill think of something.

**Comment by werewolfboyfriend** [comment]
can we get the stasis beds placed on maps in _addition_ to stuff instead of removing a sleeper and a surgery table? it's kind of a small nerf alongside this, otherwise

**Comment by jjpark-kb** [comment]
conflicting files. Upstream is starting to do stuff.

**Pull request closed without merging**
