### PR TITLE
I was promised $20 for this PR: Removes Contamination from Uranium

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Removes the contamination from uranium. All uranium products no longer have contamination.

## Why It's Good For The Game

It is actually a very common myth that Uranium, even in its enriched or refined form, is radioactive to the point where it would cause these sort of **immediate** issues, and with such intensity. The immediate dangers from Uranium is actually caused by inhaling, ingesting, or injecting the substance into people, and of course nuclear fission. These are handled by other mechanics, so this addition is not needed.

## Changelog
:cl: BurgerBB
del: Removes contamination from Uranium. The reality is that even 50 sheets of uranium is not strong enough to cause contamination like this.
/:cl:

### CODE REVIEW

**Comment by Useroth** [comment]
I think the problem is rooted a bit deeper and this is more focused on symptoms than the cause.

**Comment by BurgerLUA** [comment]
> I think the problem is rooted a bit deeper and this is more focused on symptoms than the cause.

No, this is actually fixing the cause. The cause is that materials made with uranium are radioactive regardless of their structure. The proc is making it apply the radioactivity to anything made with uranium.

Again, uranium emits an extremely very small amount of radiation but it can add up over time. It's not worth calculating.

**Comment by Useroth** [comment]
This is not limited to uranium. One of the recently merged changes has introduced a lot of weird stuff, like mech parts containing plasma exploding upon the welding step of mech construction.

**Comment by BurgerLUA** [comment]
> This is not limited to uranium. One of the recently merged changes has introduced a lot of weird stuff, like mech parts containing plasma exploding upon the welding step of mech construction.

That's the same cause here. It's because traits are being applied to objects made with plasma.

**Comment by Putnam3145** [comment]
TG already dealt with most of this; check how they did it. I don't really know of any specific PRs, though...

**Comment by Ghommie** [comment]
Yea, give me a moment to fix this upstream in a better way, I know what's up.

**Comment by BurgerLUA** [comment]
I'm going to scream.

**This PR is 100% seperate from whatever bug occurs** with components being crafted with uranium. The reality is that uranium barely emits any radiation at all and the only effects you will see, other than inhaling or ingesting it, will be long term.

This isn't a bugfix. This is a removal.

**Comment by Ghommie** [comment]
Honestly I wouldn't have minded if you came clean about the uranium material being too much of a trouble without that ambigous realism excuse, it's fine.

**Comment by BurgerLUA** [comment]
> Honestly I wouldn't have minded if you came clean about the uranium material being too much of a trouble without that ambigous realism excuse, it's fine.

It's not an excuse, it's a reason. I was fully transparent in the PR description and there was a discussion on this in the skyrat discord. If this was a bugfix, I would've labeled it as a bugfix, but it's not.

**Pull request merged**
