### PR TITLE
Drunkenness changes

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds alerts for being drunk.
Changes around some alcohol related traits. Alcohol tolerance will make you take less damage and other penalties from being too drunk, lightweight does the opposite. Drunken healing trait now heals based on how shitfaced you are, instead of using static values.

## Why It's Good For The Game

https://www.youtube.com/watch?v=qGyPuey-1Jw

## Changelog
:cl:
add: Being drunk now throws screen alerts.
balance: Alcohol related quirks are now a bit more severe - alcohol healing heals based on how shitfaced you are, alcohol tolerance makes you take less ill effects from being shitfaced, and alcoholic lightweight makes you less suffer more from the effects of being drunk.
tweak: Being drunk no longer makes you burp.
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
I'd have to see how it actually works in practice before I draw any conclusions, but I've always wanted a HUD element to tell how drunk I am, because you can't really feel it through a screen.

I don't like this description however.
"All that alcohol you've been drinking is impairing your speech, motor skills, and mental cognition. Make sure to act like it."

Your speech already gets messed up, but personally, I'd prefer to get tagged with a status effect based on how drunk I am, not told to act that way.

**Comment by BobJoga** [comment]
> I'd have to see how it actually works in practice before I draw any conclusions, but I've always wanted a HUD element to tell how drunk I am, because you can't really feel it through a screen.
> 
> I don't like this description however.
> "All that alcohol you've been drinking is impairing your speech, motor skills, and mental cognition. Make sure to act like it."
> 
> Your speech already gets messed up, but personally, I'd prefer to get tagged with a status effect based on how drunk I am, not told to act that way.

it was like that, this PR is restoration of unused content. but i'll change it.

**Comment by Azarak** [comment]
I dont see a need for the changing in the damage formulas. The status effect seems kind of neat and for the burp you could remove just the asterisk

**Comment by Azarak** [comment]
wrong button lol

**Comment by KasparoVy** [comment]
> 
> 
> I dont see a need for the changing in the damage formulas. The status effect seems kind of neat and for the burp you could remove just the asterisk

Or turn it into an actual emote haha

**Comment by BobJoga** [comment]
> I dont see a need for the changing in the damage formulas. The status effect seems kind of neat and for the burp you could remove just the asterisk

ok then

**Pull request merged**
