### PR TITLE
Adds a wield button

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

the title is a joke lol, this only adds a wield button to the UI that's it really
image
image
*(i fixed the two pixel off buton lol)*

image
final version

you can wield anything now, the default is a 1.2x damage multiplier for wielded items
i plan to make wielding a necessity for big firearms

## Why It's Good For The Game

wield man good

## Changelog
:cl:
add: Added a wield button to the UI, as well as an appropriate keybind. Wield anything! Pierce the heavens!
/:cl:

### CODE REVIEW

**Comment by NopemanMcHalt** [comment]
>Wield anything!

Finally, two-handing soap.

**Comment by Ziiro** [comment]
`you can wield anything now, the default is a 1.2x damage multiplier for wielded items`

My titanium toolbox thanks blesses this

**Comment by ThatGuyFromThatPlace** [comment]
As much as I enjoy wielding (Though, I'm only familiar with Eris' wielding, not Interbay's)
I feel this, combined with the fact that TG has the least available armour out of any codebase, is going to end with melee combat becoming highly lethal, and, surprise attacks being ridiculous combining combat mode 50% + wielding 20%

Adding a raw, 20% damage multiplier is kinda a basic way of implementing it (Don't know if that's how Interbay does it, but, Eris has a specific 'force' and 'wielded_force' for every weapon), and, I kinda have to wonder how this works with weapons that already can be wielded

**Comment by ForrestWick** [comment]
Ok is this literally any item or are there exceptions? Cause power fist, armblade, and similar shit should not be allowed to be wielded. On that note, this should be a hotkey, not a UI button.

**Comment by BobJoga** [comment]
> Ok is this literally any item or are there exceptions? Cause power fist, armblade, and similar shit should not be allowed to be wielded. On that note, this should be a hotkey, not a UI button.

It's both. I added a hotkey.

**Comment by BobJoga** [comment]
> As much as I enjoy wielding (Though, I'm only familiar with Eris' wielding, not Interbay's)
> I feel this, combined with the fact that TG has the least available armour out of any codebase, is going to end with melee combat becoming highly lethal, and, surprise attacks being ridiculous combining combat mode 50% + wielding 20%
> 
> Adding a raw, 20% damage multiplier is kinda a basic way of implementing it (Don't know if that's how Interbay does it, but, Eris has a specific 'force' and 'wielded_force' for every weapon), and, I kinda have to wonder how this works with weapons that already can be wielded

Combat mode is broken and there is already a PR nerfing it. I have already informed maintainers of this. Values can be changed very easily, this is just the default.

**Comment by Owai-Seek** [comment]
Can we actually have the title remain relevant to what the PR actually does so people know what's happening at a glance. This is just a flat buff to combat across the board.

**Comment by BobJoga** [comment]
> Can we actually have the title remain relevant to what the PR actually does so people know what's happening at a glance. This is just a flat buff to combat across the board.

Read my other comments.

**Comment by CameronWoof** [comment]
I don't feel that this is necessary. We already _have_ a "hit this button to do more damage" button and I don't even like that one. With this merged, getting into a fight will involve _yet another_ pointless button press. Combat mode, wield, sprint, possibly even harm intent depending. All this work just to do reasonable damage. 

I question the need for yet more needless complication in the name of making the already robust even stronger. This isn't the way.

**Comment by BobJoga** [comment]
> I don't feel that this is necessary. We already _have_ a "hit this button to do more damage" button and I don't even like that one. With this merged, getting into a fight will involve _yet another_ pointless button press. Combat mode, wield, sprint, possibly even harm intent depending. All this work just to do reasonable damage.
> 
> I question the need for yet more needless complication in the name of making the already robust even stronger. This isn't the way.

This is. Combat mode needs to be nerfed and i have been pushing for it for a long, long time. This gives depth to combat, which a lot of people feel is just "click until horizontal" - anything to make combat better is welcome, because it's lacking. Also, you are ignoring the drawbacks of using what would be an empty hand, as well as the requirement of both hands. This isn't a "damage buff button", it's something greatly needed for combat balance, especially ranged weapons.

**Comment by Yawet330** [comment]
ignore democracy, maintainers, speedmerge. Ate' combat mode, luv' wielding items.

**Comment by Investigator77** [comment]
This is necessary if we want to balance long guns in the near future.

**Comment by mattroks101** [comment]
The wield system for InterBay and Eris are practically identical, I'd know I wrote both implementations. The system was originally created to give more options for combat, and also because bay wielding was broken at the time. 

The idea was, you could block better and do slightly more damage, but you had to sacrifice your other hand to do it.  Some weapons on InterBay were nerfed to only deal good damage when they were wielded as well. Over time it became used to better balance out long guns, and add more combat options for using guns, something that was incredibly overlooked when the system was created originally in InterBay. 

I cannot stress enough how broken wielding was on bay back then, however I don't think your base wielding system is broken, so if you're adding this purely for combat purposes you're going to need to keep weapon damage balance in mind. Anyway that's just the two cents from the guy who originally wrote the systems.

**Comment by CameronWoof** [comment]
> This is necessary if we want to balance long guns in the near future.

Why would this be the case when we already have a two-handed component?

**Comment by BobJoga** [comment]
> > This is necessary if we want to balance long guns in the near future.
> 
> Why would this be the case when we already have a two-handed component?

Because this makes use of the two handed component and let's us easily make firearms capable of firing both one handed and two handed, with appropriate accuracy for each.

**Pull request closed without merging**
