### PR TITLE
Ports natural wigs from /tg/

### PR DESCRIPTION
**Pull request by AtlasRules**
## About The Pull Request

Ports the natural wigs from /tg/ which allow you to change the hair colour and style

## Why It's Good For The Game

Standard wigs aren't great, and this allows races that can't have hair to have hair.

## Changelog
:cl:
add: Natural wigs from /tg/
/:cl:

### CODE REVIEW

**Comment by AtlasRules** [comment]
wdym modularize

**Comment by Useroth** [comment]
Make new files for the additions in modular_skyrat folder, and try to do the least possible amount of changes in the "base" files of the codebase, because we're a Cit downstream and it makes automatic mirrors a LOT less of a headache for us.

For decent examples of modularization, you should look at BobJoga's, Azarak's and Coolgat3's PRs.
You can hit me up if you need a hand still as well.

**Comment by AtlasRules** [comment]
this is a shitshow of code so im just gonna

**Comment by AtlasRules** [comment]
adding hair to shadowlings is gonna be easier so i'll just do that

**Pull request closed without merging**
