### PR TITLE
Increases price of detomatrix and syndibombs

### PR DESCRIPTION
**Pull request by ForrestWick**
## Why It's Good For The Game
haha bomb machine go **BRAAAAAAAAAAAAAAAAAAAAAAAAAAP**

## Changelog
:cl:
tweak: Commented out syndibombs
balance: Repriced detomax

/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
wack

**Comment by ShadeAware** [comment]
What is wrong with you.

**Comment by ShadeAware** [comment]
Also 
>Commenting out bombs
>Leaves the now useless detonation button
### **Bruh.**

**Comment by jjpark-kb** [comment]
Just increase the price of syndibombs as well. Commenting out the bombs is making travis fail you.

**Comment by ForrestWick** [comment]
> Also
> 
> > Commenting out bombs
> > Leaves the now useless detonation button
> 
> ### **Bruh.**

Fixed

**Comment by Ghommie** [comment]
Absolute state of Skyrat, even longer roleplaying sessions.

**Comment by ShadeAware** [comment]
Yeah I see no reason for this. This is salt PR in its truest form and a pretty quick revert imo.

**Comment by Ghommie** [comment]
>April fools

>Done one day earlier

Nice.

**Comment by ForrestWick** [comment]
> > April fools
> 
> > Done one day earlier
> 
> Nice.

Fool, the April fools was that this wasn't an April fools joke at all (it was semi a joke tho)

**Comment by Ghommie** [comment]
Guess my foolproof anti-fooling cloak of the fool didn't work, I have been fooled.

**Pull request closed without merging**
