### PR TITLE
[Map Edit: Lavaland] MultiZ Lavaland

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

MultiZ lavaland.
Adds a lower level, so you can mine to your hearts content without dealing with megafauna... no guarantee against normal fauna though! 
With a lower z level on lavaland, chasms dont remove your body now! instead, your body gets buried inside some walls, which can still very much kill you fast.

## Why It's Good For The Game

Lets cater to the mining miners... Perhaps there can be additions for ghost roles on a bare level such as this...

## Changelog
:cl:
add: Added another zlevel to lavaland.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
I wouldn't like to see this added into the game without any extra content related to it. Empty space feels unfinished, unfinished feels disappointing. It isn't hard to avoid fauna at all, and you can use your GPS to see where mega's are.

An extra Z-level for lavaland would be an amazing opportunity to introduce xenoarcheology into the server touch. Perhaps bundle it with a prettier biome underground, like a jungle with bioluminescent plants

**Comment by jjpark-kb** [comment]
okay aza

**Comment by jjpark-kb** [comment]
Okay, so I will work on Xenoarch. But I want it to be in a separate PR.

**Comment by ShadeAware** [comment]
A good basis for something down the line. I'm looking forward to where we take this!

**Pull request merged**
