### PR TITLE
[Map Edit: Box, Pubby, Delta] GenPop for Security

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Adds the genpop lockers and turnstiles to perma and security.
Removes the holding cells.

## Why It's Good For The Game

Put the normal prisoners in with the perma prisoners. More interactions with possible better RP situations.

## Changelog
:cl:
add: Added turnstiles and genpop lockers to box, delta, and pubby.
del: Removes the holding cells.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
I really dislike this. There isn't any real point to it; you're not going to get any RP of value done during a 2 to 5 minute sentence. Even 10 minutes is stretching it.

**Comment by jjpark-kb** [comment]
> I really dislike this. There isn't any real point to it; you're not going to get any RP of value done during a 2 to 5 minute sentence. Even 10 minutes is stretching it.

The length of being imprisoned is going to be lengthened, so there is a point. There might be more RP than you realize.

**Comment by jjpark-kb** [comment]
Probably going to work on this later.

**Comment by KathrinBailey** [comment]
image
It's a fair point for when you work on this again.

**Pull request closed without merging**
