### PR TITLE
Update(revert) to PA(particle accelerator) sprite

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Good old memories

## About The Pull Request

It brings back the PA sprite from 2015 because it looks way better and conforms to the art style! And I'm an old timer. Nostaliga.

Here's what it looks like!
image

## Why It's Good For The Game

Gives just a little bit more continuity to the art style.

## Changelog
:cl:
add: Updated particle accelerator sprite to 2015 version.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
This one actually looks worse...

**Comment by Gandalf2k15** [comment]
it doesn't really look worse, it's just less steampunk, which I hate about the current one.

**Comment by werewolfboyfriend** [comment]
ew no, it looks way worse _and_ it's got an outdated console that no longer matches the art style.. idk, seems to me like maybe it could be salvageable but it would need adding an up to date console and heavy touchups on the rest

**Comment by Gandalf2k15** [comment]
Well, look at the radiation collectors and what not, those are the same style. The new sprite came about in 2016 which looks awful and was very edgy at the time. Plus the computer for that one is also out of date. This was made for the art style and is classic. The computer can be updated in a few seconds.

**Comment by BobJoga** [comment]
This is fantastic, good old nostalgia. Only problem is yeah, the computer, which will really look out of place - maybe you could quick fix one that matches current computers?

**Comment by Gandalf2k15** [comment]
I'll redo this PR at some point. I want muh nostalgia.

**Pull request closed without merging**
