### PR TITLE
Added some new sympthoms

### PR DESCRIPTION
**Pull request by Microvolnovka19**
## About The Pull Request

Meh. Cringe

## Changelog

add: Added new things

### CODE REVIEW

**Comment by ForrestWick** [comment]
No

**Comment by Useroth** [comment]
_ICly it's horrible. OOCly it breaks preferences. Personally, I like it._
But on a more serious note, this one has a lot of griefing and/or "unforseen results" potential and will likely have to be heavily discussed whether we want this or not.

**Comment by Microvolnovka19** [comment]
It checks preferences (!(M.client?.prefs.cit_toggles & PENIS_ENLARGEMENT)  and BREAST_ENLARGMENT

**Comment by Microvolnovka19** [comment]
If person has their Breast_enlargment off, it would do nothing.

**Comment by CinderWC** [comment]
No. this is just a griefy Virus and just leads to LRP.

**Comment by BobJoga** [comment]
I don't know how i feel about this mate

**Comment by Microvolnovka19** [comment]
Actually, i dont know about it too. I made it just for fun to test some things. Do, as your heart leads

**Comment by Useroth** [comment]
I don't hate the idea, but in the end, I believe it can end up in too many unpleasant situations.

**Pull request closed without merging**
