### PR TITLE
New traitor item: Morph cube

### PR DESCRIPTION
**Pull request by BobJogaIsForkinBanned**
## About The Pull Request

Adds a new traitor item costing 18tc: The morph cube. It basically let's you turn into any simple mob stored type stored on it, provided you are within cube 7 tiles of the cube and that the mob type stored isn't on the blacklist(any carbon, megafauna or elite fauna). Starts out with a rat stored, and can only have a single creature scanned at a time.

## Why It's Good For The Game

Another gimmicky traitor item. Yuupee!

## Changelog
:cl:
add: 18tc morph cube traitor item. See #1332
/:cl:

### CODE REVIEW

**Comment by CinderWC** [comment]
I like the idea of this, however. Can you turn back into a human once you turn into a simplemob, or will you be stuck as it?

**Comment by BobJogaIsForkinBanned** [comment]
> I like the idea of this, however. Can you turn back into a human once you turn into a simplemob, or will you be stuck as it?

Yes, you can. And to better explain: Only human to mob transformations are limited to cube range, mob back to human is not, just to be sure you don't get stuck in that form.

**Comment by CinderWC** [comment]
Yeah i like it you got my vote chief

**Comment by BobJogaIsForkinBanned** [comment]
> Consider a global list for this, instead of doing it every time a new cube is made.
> 
> ```
> /obj/item/morphcube/Initialize()
> 	. = ..()
> 	for(var/NO in typesof(/mob/living/simple_animal/hostile/megafauna))
> 		blacklistedmobs += NO
> 	for(var/NO in typesof(/mob/living/carbon))
> 		blacklistedmobs += NO
> 	for(var/NO in typesof(/mob/living/simple_animal/hostile/asteroid/elite))
> 		blacklistedmobs += NO
> 	for(var/NO in typesof(/mob/living/simple_animal/hostile/boss))
> 		blacklistedmobs += NO
> ```
> 
> Not to mention the fact, that this list will grow every single time a new cube is spawned.

Alright will do. Honestly not doing a global list in the first place was kind of dumb.

**Pull request merged**
