### PR TITLE
Nerfs Synthflesh to /tg/'s current synthflesh, but not as bad.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Synthflesh now heals 1.25 brute and 1.25 burn for every 1u of synthflesh applied, but deals 25% of the health healed as toxins damage if and only if the patient is alive. 40u patches would heal a total of 50u burn and 50u brute, while dealing 25u toxins damage assuming they had greater or equal to 50u burn and 50u brute damage and the patient was alive.

Synthflesh now de-husks corpses that became husks from burn damage only at 40u instead of 100u.

## Why It's Good For The Game

Synthflesh is honestly an incredibly powerful chemical that is incredibly easy to make. Instead of messing with the recipe and outdating all the other wikis for it, I decided to just softport /tg/station's synthflesh changes instead and put them at reasonable values.

The reduces synthflesh requirement for de-husking those from burn damage should also encourage medical doctors to use non-cloning based revival methods instead.

## Changelog
:cl: BurgerBB
balance: Synthflesh now heals 1.25 brute and 1.25 burn for every 1u of synthflesh applied, but deals 25% of the health healed as toxins damage if the patient is still alive. Synthflesh now de-husks corpses that became husks from burn damage only at 40u instead of 100u.
/:cl:

### CODE REVIEW

**Comment by BobJogaIsFuckingBanned** [comment]
I hate this so god damn much that i dead ass created another account just to downvote this. This change serves no purpose except making synthflesh outdated and useless, people will just use styptic powder and silver sulf instead. And if by that line of logic you say that we need to port TG's changes to those too, i say: No, just no, fucking hell absolutely no. The way TG is trying to make medicine better is the laziest, scummiest and least fun for the players way to do it. I'd rather work for 2 weeks straight, non-stop, on an entire medbay rework so it is more similar to what paradise has going on.

**Comment by Commandersand** [comment]
bad nerf
but the 40u to dehusk is really good, i suggest making it 60

**Comment by CinderWC** [comment]
I like the idea of being able to dehusk corpses so that people stop going to the Cloner as a first everytime.
But what you did to the Synthflesh overall is just a massive butchering and i genuinely do **NOT** want to see this merged, whatsoever.

**Comment by BurgerLUA** [comment]
Changes:
Synthflesh only deals toxins damage on living patients.
Synthflesh only applies mood debuffs on living patients.
Reduced toxin damage from 50% to 25% of amount healed.

**Comment by ShadeAware** [comment]
Good PR after the changes; Synthflesh was, in hindsight, a bit of a catchall.

**Comment by BurgerLUA** [comment]
when the other PR is merged then I will modularize this one since they both affect the same file

**Comment by BurgerLUA** [comment]
Now modularized.

**Pull request merged**
