### PR TITLE
Chad Geneticists

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

(inspired by https://github.com/tgstation/tgstation/pull/50149)

Changes two genetic powers and adds two new ones.
- Strong now makes you not have any penalties while dragging
- Stimmed makes your system (slowly) heal from toxin damage and remove toxic reagents from your body
- New V.A.T.S mutation: Makes you more accurate with firearms, plays the annoying vats sound effect whenever you pick up a firearm.
- New thick skin mutation: Makes you more resilient to brute damage, same for burn but really diminished.
- Anti-glow is now actual unlockable through genetics. Great for shadowpeople!

## Why It's Good For The Game

Genetics is barely worth the chore as-is and is not fun enough. This doesn't completely solve the problem, but it soothes some of the wounds.

## Changelog
:cl:
add: Added new VATS genetic mutation. Useful for SCHÜT.
add: Added new thick skinned mutation. SKIN IS ARMOR BABY.
tweak: Strong makes you suffer no penalties from dragging. Useful for paramedics and rescuing people.
tweak: Stimmed makes you heal from toxin damage (slowly) and cleanses toxic reagents from your body. Now geneticists can flex to their chemist coworkers about how they can't do shit against them.
tweak: Anti-glow mutation is now accessible via normal means.
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
...but why would a gene give you wrestling abilities...

**Comment by BobJoga** [comment]
> ...but why would a gene give you wrestling abilities...

Some people are just born with HULKAMANIA, brother.

**Comment by Seris02** [comment]
this is literally just a powergaming genetics pr, ngl, it's real shit

**Comment by BobJoga** [comment]
> this is literally just a powergaming genetics pr, ngl, it's real shit (not the good real shit, the real shit as in, really bad)

aight bro i'm gonna add another very RP friendly genetic mutation that does absolutely nothing, is a waste of time and serves no purpose at all

**Comment by trollbreeder** [comment]
nice of you to port my PR over

**Comment by BobJoga** [comment]
> nice of you to port my PR over

good pr thank

**Comment by BobJoga** [comment]
Got told there is an issue with a genetic mutation. I'll use this as an opportunity to fix that issue. For now, DNM.

**Comment by Seris02** [comment]
why not just add something that isn't purely powergaming
like
the strength and stimmed buffs I understand 
but the wrestling gene is like
# what the fuck even is this why you don't inherit wrestling from genes it doesn't even make sense

**Comment by BobJoga** [comment]
> why not just add something that isn't purely powergaming
> like
> the strength and stimmed buffs I understand
> but the wrestling gene is like
> 
> # what the fuck even is this why you don't inherit wrestling from genes it doesn't even make sense

Give me a better idea and i may do it. Otherwise, hulk hogan geneticists will be a thing.

**Comment by BobJoga** [comment]
@Seris02 I've replaced it with another mutation that just makes you resilient to damage. I'm not making any more changes.

**Comment by Seris02** [comment]
that makes a lot more sense
_pats_

**Comment by BobJoga** [comment]
just fucking merge this already fufjgushgntjntfg

**Comment by BobJoga** [comment]
this is gonna be just like https://github.com/Skyrat-SS13/Skyrat13/pull/753 isn't it

**Comment by Useroth** [comment]
Not entirely sure I like stuff like that with no real drawbacks.

**Comment by BobJoga** [comment]
> Not entirely sure I like stuff like that with no real drawbacks.

Genetics already has instability as the system in place serving for drawbacks. That's the drawback for these - you're wasting precious instability. In fact a considerable amount for each.

**Comment by BobJoga** [comment]
**PR's closed due to mutes caused by Kathrin Bailey. For any grievances or complaints, contact Floof Ball#0798 on discord. The PR owner will also not listen to any of your complaints unless you provide screenshots that prove you have contacted Floof Ball#0798 on discord first.**
pool

**Pull request closed without merging**
