### PR TITLE
Malf APCs are EMP-Proofed

### PR DESCRIPTION
**Pull request by YakumoChen**
Clone of https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13371 because I would have mirrored it regardless.

## About The Pull Request

When an Antag AI hacks an APC, it becomes immune to EMPs.
Machines in the same room as the APC are still affected

## Why It's Good For The Game

Getting killed as a malf AI because some funny man floated outside your core and threw a single grenade is honestly the dumbest thing to experience. EMP'd APCs are disabled for a ridiculously long time and it often only takes one or two to kill you, without even needing to ever go inside the satellite. You're made a sitting duck for several minutes and it's not a fun way to die.

With this change, an overridden APC is no longer affected by an EMP. While this doesn't stop all your turrets, borgs, and Pingsky from being disabled for half a minute, it at least ensures whoever is trying to wipe your code has to actually look you in the face to do it, and gives you a fighting chance.

This doesn't address plenty of other cheese strats to kill the AI (and doesn't affect non-malf AIs) but I consider this one to be the most cripplingly shitty way to die for a fairly high-power antag.

## Changelog
:cl: YakumoChen
balance: APCs hacked by an antag AI are EMP-Proof
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Yay for more cyborg/AI powercreep and slowly removing any and all counters to them that have been left in the game for a reason.

**Comment by YakumoChen** [comment]
I never agreed with the borg change but this should have been a long time coming. EMPing the APC removes any need to deal with anything the AI does, it's just a delayed death the moment the APC shorts out.

**Comment by MLGTASTICa** [comment]
Honeslty a  much better solution would be adding EMP proofing as a 200 CPU cost upgrade , APC's should get it off right the bat.

**Comment by YakumoChen** [comment]
200 CPU is absurd. That's 20 entire APCs to strike out an delayed, unavoidable death instead of an inconvenience that disables your defenses for a short period. Although EMPs still do direct damage to AIs, so it's not like you can't just spam them, but it still gives the AI more of a chance to deal with it.

**Comment by MLGTASTICa** [comment]
Yeah and ? giving them a cheap ability to EMP proof is absurd. When they can just re-do the sattelite zoning to EMP proof either way.

**Comment by YakumoChen** [comment]
It's EMP proofing just the APC, almost exclusively just to prevent the AI being powerless for 5 minutes at a time, which is more or less just a delayed AI death with zero risk on anyone else's part.

**Comment by MLGTASTICa** [comment]
Even if i play AI a lot , this is just a massive buff over a issue that can be easily countered by a smart player. Instead of total emp-proofness you could just add EMP-resistance or do a exception of the forced EMP countdown if the AI tries to turn it on so it actually works.

**Comment by YakumoChen** [comment]
There isn't an "EMP resistance" in the code. There's also no easy way to hook into the EMP proc without a whole refactor, and I'm not that skilled of a coder. If you want to try, go ahead.

**Comment by SpookyTheFox** [comment]
EMP proofing hacked APCs seems perfectly reasonable. It's a multi-minute lockup, which is massively lame. A more elegant solution though, might be to cap EMP radius, or redo the math so it follows cubic reduction like real RF pulses.  It currently has no cap, and you can cheese anything from across the map given enough uranium to grind up.

**Pull request closed without merging**
