### PR TITLE
Clothing modification kit no longer required for reskins, more reskin fixes

### PR DESCRIPTION
**Pull request by BobJogaIsForkinBanned**
## About The Pull Request

Title.

## Why It's Good For The Game

fuck reskin kits, they're an annoyance

## Changelog
:cl:
fix: Fixes a bunch of reskins for clothing.
del: Reskin kits are still in the game, but most of it's purpose is gone as now reskinning is just performed by alt clicking.
/:cl:

### CODE REVIEW

**Comment by Akrilla** [comment]
Be sure to test a reasonable number of these, pretty large sweeping changing

**Comment by BobJogaIsForkinBanned** [comment]
> Be sure to test a reasonable number of these, pretty large sweeping changing

Will test.

**Comment by BobJogaIsForkinBanned** [comment]
> Be sure to test a reasonable number of these, pretty large sweeping changing

it's good

**Comment by improvedname** [comment]
Just make them o b j e c t s

**Pull request merged**
