### PR TITLE
Removes cook access to the morgue.

### PR DESCRIPTION
**Pull request by Owai-Seek**
## About The Pull Request

Removes chef access to morgue.

## Why It's Good For The Game

Being able to yoink people out of morgue trays, and shove them into the grinder, brains and all, is not a good thing. Unless someone wants to fix the grinder so it doesn't just delete brains, this is the simplest fix for things like this at the moment.

## Changelog
:cl:
tweak: Cook no longer has Morgue access.
/:cl:

### CODE REVIEW

**Comment by calibraptor** [comment]
Another nudge towards better quality RP.

**Comment by ShadeAware** [comment]
This was an artifact from TG, let it die imo 👍

**Comment by necromanceranne** [comment]
While I can get behind a change aimed at cutting down on a more ridiculous element of the chef, making gibbers weaker, as you suggest, has some gameplay consequences you do need to be careful about.

(Lings, as the primary example of an antagonist only defeatable with full body destruction)

**Comment by Owai-Seek** [comment]
Ejecting brains from the gibber wouldn't have an effect on ling removal at all, as their brains are worthless.

**Pull request merged**
