### PR TITLE
Edits Overthrow Commenting to Multi-Line Commenting [PR Title Changed]

### PR DESCRIPTION
**Pull request by Ludox235**
Why did this get merged maintainers where are you??

### CODE REVIEW

**Comment by Yawet330** [comment]
this shitcode was done by a maintainer sorry!

**Comment by Gandalf2k15** [comment]
Ah yes the One where I specifically stated to fix it before merging. Nice.

**Comment by Ludox235** [comment]
> 
> 
> Ah yes the One where I specifically stated to fix it before merging. Nice.

Bro I literally told them shouldn't you use /* */ and they just went "nah i used comment command in vsc" like bro....

**Comment by hugmeorelse** [comment]
Cease all shittery. If you can't keep conversations civil, don't make them at all here.

**Comment by hugmeorelse** [comment]
> Why did this get merged maintainers where are you??

The title is rude and excessive, considering your main issue is the fact that they commented out code differently. The only difference between // and /* and */ is readability and QoL for the coder. It's good to make this change, but trying to stir drama over this is ridiculous.

**Comment by Ludox235** [comment]
> 
> 
> > Why did this get merged maintainers where are you??
> 
> The title ("Cease your shitcode") is rude and excessive, considering your main issue is the fact that they commented out code differently.
> 
> The only difference between // and /* and */ is readability and QoL for the coder. **It's good to make this change just so it's just very slightly less pain to uncomment later on, but trying to stir drama over this is ridiculous.**
> 
> If your entire point was for maintainability, then you should have a chosen a more efficacious title that makes it easier to identify for coders later on.

don't care didn't ask
either merge it or don't

**Comment by Akrilla** [comment]
lol

**Pull request merged**
