### PR TITLE
You now can play the circle game.

### LINKED ISSUE #2196: *Circle does not auto gottem
## Date and Time of Issue:

12am EST, 5/27/2020

## Testmerges (If Applicable):

Issue may be caused from merging new health system, and the combination of leg and foot targeting?

## Reproduction:

the *circle emote puts an item in your hand that when somebody examines your legs or feet, they'll get got, however. that functionally seems to be broken.

do *circle emote, get somebody else to target legs, and examine. Tried it on TG station, worked fine.

### PR DESCRIPTION
**Pull request by Rug-Dealer**
## About The Pull Request
Examining somebody with the *circle emote equipped ends up with you getting bopped, as it should.
Closes #2196 

## Why It's Good For The Game
image
gottem boys

## Changelog
:cl:
fix: The circle game now works! Whip out a circled hand with *circle and try to get someone to look at it (by examining you) to bop them.
/:cl:

### CODE REVIEW

**Comment by Weblure** [comment]
Can someone explain what this is? What is 'the circle game' and why does it deal 15 stamina damage (and 50 as hulk)?

**Comment by Rug-Dealer** [comment]
The circle game is a game (more akin to an amusing jape, if anything) where you hold a circled hand below your waist, and if someone looks at it you get to bop them.
I just ported the code from tg, since what happened was that the circle game was merged downstream to Citadel, but not the change that makes it actually functional since that was added in a later PR.
Mechanically, what it does is automatically bop someone for 15 stamina damage when you:
a) have the circled hand out (you do this by using the *circle emote)
b) stand next to someone
c) get examined by them
This, understandably, has very limited offensive use, and serves mostly as a harmless prank among your peers.

**Comment by Weblure** [comment]
> The circle game is a game (more akin to an amusing jape, if anything) where you hold a circled hand below your waist, and if someone looks at it you get to bop them.
> I just ported the code from tg, since what happened was that the circle game was merged downstream to Citadel, but not the change that makes it actually functional since that was added in a later PR.
> Mechanically, what it does is automatically bop someone for 15 stamina damage when you:
> a) have the circled hand out (you do this by using the *circle emote)
> b) stand next to someone
> c) get examined by them
> This, understandably, has very limited offensive use, and serves mostly as a harmless prank among your peers.

That makes sense, thank you for clarifying.

**Comment by Akrilla** [comment]
I'm really confused by this code - why is it an item, and where is any reference to the *circle emote? Also the timer usage seems like it would be incredibly buggy.

**Comment by Akrilla** [comment]
Oh no I see, *circle already exists, just for some reason the code didn't exist.

**Pull request merged**
