### PR TITLE
HoP Change

### PR DESCRIPTION
**Pull request by Afya212**
## About The Pull Request

Removes HoS

## Why It's Good For The Game

Because remove pain

## Changelog
Unnecessary

### CODE REVIEW

**Comment by Seris02** [comment]
vice captain is basically the same thing, remove that too if you don't want more pain
HoP isn't vice captain

**Comment by Akrilla** [comment]
You might need to explain a bit more why these titles are being removed.

**Comment by SarmentiCampbell** [comment]
Yeah, I don't see why they are being removed, If there was any problems with them, Bunny would have told me to remove 'em when i've did that PR.

**Comment by Afya212** [comment]
Vice-Captain isn't an accurate title for the HoP, and having two peoples different jobs be the HoS has being a bit of pain when it happens in my experience.

**Comment by SarmentiCampbell** [comment]
Yeah but that isn't a reason though? The Vice-Captain is accurate, HoP is supposed to be the Captain's Right Hand and HoP is responsible for staffing, aren't they?

**Comment by Azarak** [comment]
a HoS abbreviation for the Head of Personnel is bad, as it mistakes him with the actual Head of Security. I see how vice-captain is not accurate either.

**Comment by Strazyplus** [comment]
Vice-Captain - absolutely not, remove it
 Head of Staff - is bad and should be removed yes...

**Pull request merged**
