### PR TITLE
Deactivates Character Hijack Brain Trauma

### PR DESCRIPTION
**Pull request by EldritchSigma**
About The Pull Request
Hopefully comments out the argueably worst Brain Trauma.
Yes. It has some RP value in it if you are into that sort of thing. But frankly.. I havent seen a single good "split personality" that doesnt make me look like a massive shitter on every bloody server. It wrangles control from the person about their character. It shouldnt be a thing here. I dont think I need to explain why hijacking somebodies character is really bad.

Why It's Good For The Game
No LRP ahahaha epic schizophrenia meme. Should comment out this godawful brain trauma. Other options that could be considered: Make it opt in only, but thats beyond my scope of abilities.

Changelog
🆑
del: Split personality.
/🆑

### CODE REVIEW

**Comment by Strazyplus** [comment]
I disagree with removal - I suggest making it so that both sides can communicate via mind. Also make it whoever gets to be the split personality gets a role message telling them the correct way of playing in big red text. Split personality ghost role should not be abused to grief the host player.

However, all this is pointless, I was someone's split personality for 10 seconds before the doctor removed me. I did not even get to speak. 7 minutes later there was another person who formed an imaginary friend, I looked like a lawyer so I was gonna act as their lawyer and be their best friend and have some fun roleplaying when they wake- oh I got removed. welp RIP.

**Comment by Commandersand** [comment]
that's a bit oof, shouldn't it be a deep rooted trauma to prevent lol neurine?

**Comment by Useroth** [comment]
I like Strazyplus' idea regarding it.

**Comment by Akrilla** [comment]
+1 on above, against removal, but would support that change.

**Comment by EldritchSigma** [comment]
I forgot that this existed.. fuck. I have a better idea how to handle this that makes it dead clear to the split personality to not character hijack and cooperate with the dude they are put into making it more into a neutral trait and not a full on negative one.

**Pull request closed without merging**
