### PR TITLE
Boxstation Security - New Prison & Aesthetic Overhaul

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
• Reworks Boxstation prison and completely revamps it into a modern genpop prison.
• Slightly modifies the rest of security. Mostly aesthetic changes.
• Populates the armoury with more items.
• Brig Physician gets an operating bed so they are better equipped to deal with TG wounds.
• Fixes a ton of horrible mapping errors littering security, mostly tons of wires just leading into nowhere.

## Media
image
_The new brig._

image
_The new armoury._

image
_Brig physicians rejoice! It's nicer._

image
_Slightly updated interrogation room._

image
_Get ready to enter the priissssooon!_

image
_The previous isolation cells were godawful and the idea behind them was so horrific I'm mind-blown. Stick people in a 1x1 behind a blast door. Seriously? It's now a padded cell with a timer. You can slap them in for five minutes._

image
_Orange wing. It's nice and snug_

image
_Hydroponics! With a view! Grow things in a nice cozy peaceful spot._

image
A small pool.

image
_Purple wing. Yeah this is familiar for some of you folks. It's really girly._

image
_Green wing. It's the most bland of them all, but if you really need the space..._

image
_The library. It's small, no one really uses it. You have a nice private space._

image
_The kitchen and cafeteria!_

image
_All of the wings have shutters in them. You can lock prisoners into any of the three wings. The rest of the prison is accessible no matter which wings you close off._

## Why It's Good For The Game
In a break from my usual format, I've put the pretty pictures further up. They should be convincing for why this PR is good for the game.
**So, what specific improvements have been made from the original prison?**
1. It's more compact. It's actually smaller. Space has been much better utilised.
2. The horrific blast-door GBJ cells have been replaced by a padded cell that uses a door timer. You now can't lock antags in a 1x1 with a blast door roundstart for the rest of the round with no hopes of them escaping. You can communicate with people whilst in the cell, which means less chances of people just ghosting because they've been placed in ghetto admin jail.
3. Hidden rooms are in, with loot! It's unlikely that you'll get enough loot to actually stage a break-out.
4. It looks considerably better. The old prison doesn't look very good at all
5. This is actually a genpop prison; it actually has genpop lockers.
6. You can close individual wings off. If you're terrified that someone might slap another prisoner, you can lock them in their own wing. All of the prison's features are not directly connected to the wings. All three wings can be closed and the rest of the prison is still perfectly accessible.
7. No space carps that spawn directly outside of the prison which made engineering have to fix the window more rounds than not. Now you can do prisoner stuff without having to sit inside a room whilst engineering fixes the breach and a bad atmos tech leaves the air alarms on refill mode and makes the entire prison 303 kilopascals.

Also, a security records console is now in the brig. Have you brought someone in? Do you want to add a crime to their records? Now you can do it from the brig. You can sit down there and look through the cameras if you want.

The Brig Physician area is now much nicer and because a lot of TG wounds require surgery, they have a surgery table. Without one, the Brig Physician is woefully under-equipped to do anything but fix minor boo-boos. 

## Changelog
:cl:
add: A completely new prison for Boxstation!
tweak: Boxstation Security has received an aesthetic overhaul.
fix: Huge heaps of mapping errors in Boxstation Security have been fixed.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
I like the new brig.

The prison isolation cell is way too easy for someone to break into or out of. The old 1-tile with blast doors is far better.

The prison itself is _**WAAAAAYYY**_ too extravagant. Its a prison, not a four-star hotel.

**Comment by PersianXerxes** [comment]
The prison we deserve. Great work all around, Kat.

Seeing glass tables in the prison proper, however, gives me pause. Would strongly advise replacing them with some other style of table.

**Comment by Tename** [comment]
Few things I noticed, those emergency shield generators seem like they would be a bit difficult to get out, maybe move what I guess is the contraband closet near that table with the toolboxes and shorten it by one.

I would also recommend making that pool in the prison short so you can walk around it, or move the heating/cooling machine to the other side if thats possible, haven't worked with pools before.

**Comment by SpaceVampire** [comment]
This has bothered me for a while, but why is the prison much nicer then the rest of the station? It really does feel like some crazy luxury space hotel. How about you take this moment to move the lathe to somewhere locked behind warden access as well? Its silly to put more stuff in the armory, where due to our long rounds for most of the time you are just going to print better gamer gear from there anyway.

**Comment by KathrinBailey** [comment]
image

Extra lasers have been yeeted for space to move the protolathe.
Autolate placed where the protolathe was.

**Comment by Owai-Seek** [comment]
I don't play prisoner or security, so take it with a grain of salt, but I feel the new prison looks extremely claustrophobic.

**Comment by YakumoChen** [comment]
I once again question why a prison stay feels like more of a vacation than an actual punishment, but eh, I do like the brig changes.

**Comment by YakumoChen** [comment]
I feel like the lathe should be in the warden's office but I don't see room for it.

Could you also add a copying machine somewhere? Bit of a pet peeve of mine to not have one around when I feel like doing paperwork.

**Review by Azarak — APPROVED** [review]

**Comment by Azarak** [comment]
Looks nice! Would like a second opinion as I'm not an expert in this

**Comment by Gandalf2k15** [comment]
As far as I can see, i am happy with these changes as well.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Arctaisia** [comment]
This makes me *want* to be a prisoner on box now :eyes:

**Pull request merged**
