### PR TITLE
[WIP]Meet the Surgeon

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

yeah it's a medbay and combat rework

## Why It's Good For The Game

Doctors are currently useless. This aims to fix that without getting to baymed levels of frustration, or altering the base medicine mechanics too much.

## Changelog
:cl:
add: bone
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
Don't forget to make it modular :)

**Comment by BobJoga** [comment]
> Don't forget to make it modular :)
I'd rather not make this "rework" at all if it has to be modular.

**Comment by ShadeAware** [comment]
This feels like something that really shouldn't be modular, yeah

**Comment by BobJoga** [comment]
i will now piss cum

**Comment by BobJoga** [comment]
closing for now. may come back to it later.

**Pull request closed without merging**
