### PR TITLE
removing cryptominers

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
people abuse shit, so we remove shit, final.
removing cryptominers

## Why It's Good For The Game
balance

## Changelog
:cl:
del: Removed cryptominers
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
Can you explain how these were abused?

**Comment by werewolfboyfriend** [comment]
why not nerf instead? these have encouraged so many people to actually start learning how atmos works

**Comment by hugmeorelse** [comment]
These will be placed back in once we rebalance it.

**Comment by Somememeguy** [comment]
I feel like the issue with cryptominers currently is that they give too many credits. But you also still have to babysit them during the round. Why not make them take more bluespace crystals and give less credits, but offer a constant, steady stream of credits? Maybe remove syndie cryptominers too. Then make it so you can use upgraded parts on the normal ones to increase the credits gained to maybe a maximum of 25 or something.

**Comment by hugmeorelse** [comment]
> I feel like the issue with cryptominers currently is that they give too many credits. But you also still have to babysit them during the round. Why not make them take more bluespace crystals and give less credits, but offer a constant, steady stream of credits? Maybe remove syndie cryptominers too. Then make it so you can use upgraded parts on the normal ones to increase the credits gained to maybe a maximum of 25 or something.

Interesting suggestion. I'll bring it up to Jake.

**Comment by hugmeorelse** [comment]
> I feel like the issue with cryptominers currently is that they give too many credits. But you also still have to babysit them during the round. Why not make them take more bluespace crystals and give less credits, but offer a constant, steady stream of credits? Maybe remove syndie cryptominers too. Then make it so you can use upgraded parts on the normal ones to increase the credits gained to maybe a maximum of 25 or something.

He agreed. We'll try something along those lines.

**Comment by jjpark-kb** [comment]
closing in favor of changing them a little. expect another PR soon

**Pull request closed without merging**
