### PR TITLE
Adds logging to combat indication

### PR DESCRIPTION
**Pull request by Azarak**
## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Commandersand** [comment]
your admin logs are gonna be spammed with combat mode waving/spinning

**Comment by Azarak** [comment]
@Commandersand This only is logged when the combat flick popup happens

**Comment by Commandersand** [comment]
that's still a lot of times people toggle combat mode for non combat stuff

**Comment by Azarak** [comment]
Well it's simple logging and not admin notice

**Pull request merged**
