### PR TITLE
Brings the shrink module to how it was before

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
from 0.8  to 0.75. This was unintended change that came from the fix

## Changelog
:cl:
add: Shrunk borgs are now tiny bit smaller. Bjork!
/:cl:

### CODE REVIEW

**Comment by Akrilla** [comment]
conflict

**Comment by jjpark-kb** [comment]
fucking, I think I did the wrong change. I hate ree

**Comment by jjpark-kb** [comment]
there.

**Comment by ThatGuyFromThatPlace** [comment]
It was intentionally made that they didn't shrink as much, for balance reasons. Smaller sprites are harder to click

**Pull request merged**
