### PR TITLE
[READY]The Skeleton Key

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds the Skeleton Key to the uplink, essentially an infinite (and overall better working) emag.

## Why It's Good For The Game

Why is it not?

## Changelog
:cl:
add: Syndicate members specialized in the art of thievery have managed to ~~steal~~ find yet another unique artifact, the skeleton key. It's now available in the uplink.
imageadd: Skeleton key icon
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
This doesn't affect anything but doors, correct? Otherwise, hard no.

**Comment by BobJoga** [comment]
> This doesn't affect anything but doors, correct? Otherwise, hard no.

It opens absolutely anything. Vaults included.

**Comment by ShadeAware** [comment]
Does it EMAG things or just OPEN them?

**Comment by BobJoga** [comment]
> Does it EMAG things or just OPEN them?

It only opens doors and vaults. Emags other things.

**Comment by ShadeAware** [comment]
Then no. Its a direct upgrade with no downside except cost, which isn't exactly a downside to most.

**Comment by BobJoga** [comment]
> Then no. Its a direct upgrade with no downside except cost, which isn't exactly a downside to most.

Wasting almost all your tc is pretty bad ngl bro

**Pull request merged**
