### PR TITLE
Nerfs Praetor Suit

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
bob closed his PR so here's a new one.

Nerfs the Praetor Suit from lavaland. Keep note that this is a child of _Deathsquad Armor_ 
**old stats**
armor = list("melee" = 75, "bullet" = 55, "laser" = 55, "energy" = 45, "bomb" = 100, "bio" = 100, "rad" = 100, "fire" = 100, "acid" = 100)
slowdown = 0 (no slowdown)
**new armor values:**
armor = list("melee" = 70, "bullet" = 40, "laser" = 40, "energy" = 25, "bomb" = 50, "bio" = 100, "rad" = 50, "fire" = 100, "acid" = 100)
slowdown = default (deathsquad suit slowdown, iirc normal hardsuit slow)

**comparisons**
**captain hardsuit:** armor = list("melee" = 40, "bullet" = 50, "laser" = 50, "energy" = 25, "bomb" = 50, "bio" = 100, "rad" = 50, "fire" = 100, "acid" = 100)
**actual deathsquad armor:** armor = list("melee" = 80, "bullet" = 80, "laser" = 50, "energy" = 50, "bomb" = 100, "bio" = 100, "rad" = 100, "fire" = 100, "acid" = 100)
**ERT armor (you can get these fully powered, randomly, from Big Legion):** armor = list("melee" = 65, "bullet" = 50, "laser" = 50, "energy" = 50, "bomb" = 50, "bio" = 100, "rad" = 100, "fire" = 80, "acid" = 80) _slowdown = 0_
**Nerfed ERT suits from tendrils:** armor = list("melee" = 65, "bullet" = 25, "laser" = 20, "energy" = 10, "bomb" = 50, "bio" = 100, "rad" = 50, "fire" = 100, "acid" = 40) _Default slowdown. Not EVA suitable_
## Why It's Good For The Game

Deathsquad Lite has no slowdown which makes it arguably better than literal deathsquad armor, and is better than standard ERT armor, the best already achievably acquirable armor in the game
Overpowered hardsuits have been on lavaland already, and have already been nerfed, so there's no reason why we should be just adding a new one to replace them.

## Changelog
:cl:
balance: nerfed Praetor suit
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
I made another PR. This is unecessary. #3311

**Comment by YakumoChen** [comment]
Name your PRs something sensible then.

**Comment by BobJoga** [comment]
> Name your PRs something sensible then.

No.

**Comment by YakumoChen** [comment]
well then a maintainer to consider this for merging instead, because I do.

**Comment by BobJoga** [comment]
> well then a maintainer can consider this for merging instead, because I do. This fits a better niche than other megafauna loot instead of just being a straight upgrade of HECK.

Slowdown makes this objectively worse than the HECK suit and just not worth getting if you are a miner.

**Comment by YakumoChen** [comment]
have you considered maybe loot should have niche uses..... outside lavaland??

**Comment by BobJoga** [comment]
> have you considered maybe loot should have niche uses..... outside lavaland??
> 
> or that alternatives should exist instead of having all loot be the same rehash of the same item with slightly different armor values?

As a miner, if loot is niche i just throw it away. If it has no use on lavaland, why should i care about it? Slowdown suits serve no purpose. There is no niche for "powerful but slow" on the station or anywhere else because speed is key.

**Comment by YakumoChen** [comment]
suits no purpose for _you_, maybe you forget that ss13 and mining doesn't revolve around your powergame, bob

**Comment by Yawet330** [comment]
agree with bobjoga here, if the suit is just as slow on lavaland as it is on station, its junk. Mobility is king for every fight.

**Comment by Echopsychotic** [comment]
I like this PR. Miners dont need normal speed with a hardsuit that is better than ERT and is captain tier. Make it balanced.

**Comment by BobJoga** [comment]
> I like this PR. Miners dont need normal speed with a hardsuit that is better than ERT and is captain tier. Make it balanced.

This is not balanced. It's useless.

**Comment by Ludox235** [comment]
> 
> 
> > I like this PR. Miners dont need normal speed with a hardsuit that is better than ERT and is captain tier. Make it balanced.
> 
> This is not balanced. It's useless.

Damn bro sorry for not letting you get literally deathsquad tier armor.

**Comment by BobJoga** [comment]
> > > I like this PR. Miners dont need normal speed with a hardsuit that is better than ERT and is captain tier. Make it balanced.
> > 
> > 
> > This is not balanced. It's useless.
> 
> Damn bro sorry for not letting you get literally deathsquad tier armor.

Doesn't need to be DS tier. Just needs to have 0 slowdown.

**Comment by Investigator77** [comment]
My face when I add slowdown to the suit that wasn't supposed to have slowdown

**Comment by Zenitheevee** [comment]
yeah not gonna lie, When it comes to a situation where you kinda have a life/death situation, Slowdown is **_REALLY_** Bad. 
Take in consideration:
>The fight you have to do to get this _Should_ be incredibly difficult (Whether it is seems to just come down to who's doing it. I've seen people do it EASILY, And some people really struggle with it)
>When it comes to _**ACTUAL STATION SIDE DEFENSES**_ Bob's version (Which he linked earlier) Is actually _WEAKER_
>Bob's changes also have a good few other changes making it worth more to carry out with, including the nerfing of HECK and Dragonbone armour
>If this is going to be "Powerful but slow", Then why did you nerf _ANY_ of its values?

**Comment by YakumoChen** [comment]
Consider:
This doesnt slow you down in space
In tight spaces speed does not really matter (speed is more valuable in open spaces or running)
Not every lavaland item is made exclusive for lavaland (miner hardsuit is a good example)
The other version of this does not have a reason to be anything other than "HECK with better stats"
No I am not keeping the stats the same and letting miners obtain armor that is _absolutely_ better than the captain hardsuit

**Comment by BobJoga** [comment]
> Consider:
> This doesnt slow you down in space
> In tight spaces speed does not really matter (speed is more valuable in open spaces or running)
> Not every lavaland item is made exclusive for lavaland (miner hardsuit is a good example)
> The other version of this does not have a reason to be anything other than "HECK with better stats"
> No I am not keeping the stats the same and letting miners obtain armor that is _absolutely_ better than the captain hardsuit

1. It does - slowdown is still applied in space, you just don't really notice it
2. I would rather take the running
3. Miner hardsuit was never a lavaland item, it is a leftover from the asteroid days, one which i barely see getting used
4. Yes, that is precisely the point
5. I made a better nerf then

**Pull request closed without merging**
