### PR TITLE
Revert "huge blob buff, please be careful"

### PR DESCRIPTION
**Pull request by CameronWoof**
Reverts Skyrat-SS13/Skyrat13#3228

Huge, unnecessary buff merged much too quickly. Blobs don't need to be this effective at ending rounds. In the future, sweeping changes like this (over 50% increase in effectiveness!) should be testmerged before being added.

### CODE REVIEW

**Comment by ShadeAware** [comment]
The Blob Buffs were absolutely necessary. This is a salt PR in the most blatant method imaginable; all of the station destructions thus far after the death of the blob have been the result of incompetent station crew abandoning the station or outright ignoring the threat instead of actively doing something, **anything** to attempt to help. Reverting these changes are just going to put Blobs back to the slot they were in, where they would spread for about a minute and then die instantly.

**Comment by chefferz** [comment]
> 
> 
> The Blob Buffs were absolutely necessary. This is a salt PR in the most blatant method imaginable; all of the station destructions thus far after the death of the blob have been the result of incompetent station crew abandoning the station or outright ignoring the threat instead of actively doing something, **anything** to attempt to help. Reverting these changes are just going to put Blobs back to the slot they were in, where they would spread for about a minute and then die instantly.

Calling this a SALT PR when the last two days have been blobs easily and quickly taking over the station, particularly when paired with bobmed and other antagonists, is a easy copout response. 

Literally every time the blob has spawned after this it has won, and please tell me what there is to gain from having a literal zero RP mass round ending antag buffed to this extent instead of just saying "salt PR"

**Comment by ShadeAware** [comment]
> 
> 
> > The Blob Buffs were absolutely necessary. This is a salt PR in the most blatant method imaginable; all of the station destructions thus far after the death of the blob have been the result of incompetent station crew abandoning the station or outright ignoring the threat instead of actively doing something, **anything** to attempt to help. Reverting these changes are just going to put Blobs back to the slot they were in, where they would spread for about a minute and then die instantly.
> 
> Calling this a SALT PR when the last two days have been blobs easily and quickly taking over the station, particularly when paired with bobmed and other antagonists, is a easy copout response.
> 
> Literally every time the blob has spawned after this it has won, and please tell me what there is to gain from having a literal zero RP mass round ending antag buffed to this extent instead of just saying "salt PR"

Perhaps if people could actually adapt to the curveballs that a VIDEO GAME is supposed to throw at them, they wouldn't constantly be losing. We shouldn't hugbox every little thing and deny any sort of power to Antagonists because people cannot be bothered to tear themselves away from piddling about to **play the game.**

Threats like Blob are not supposed to be roleplayed _with_. Rather, the roleplay comes from how you and your fellow crew interact when dealing with the threat. If you're incapable of roleplaying with your fellow crew against a common enemy, then that is **entirely your problem and your problem alone.** Attempting to project this problem onto other people like everyone shares your defect is quite honestly insulting to the crew at large.

**Comment by ThatGuyFromThatPlace** [comment]
> The Blob Buffs were absolutely necessary. This is a salt PR in the most blatant method imaginable; all of the station destructions thus far after the death of the blob have been the result of incompetent station crew abandoning the station or outright ignoring the threat instead of actively doing something, **anything** to attempt to help. Reverting these changes are just going to put Blobs back to the slot they were in, where they would spread for about a minute and then die instantly.

No, this is a PR that needs to happen, and, to call it a salt PR is ridiculous
The buff was overkill to an extreme degree, and, it was buffing an NRP antag that ends the entire round
The blob's winrate - as a round ending antagonist that fucks over all other antagonists and non-antagonists alike with zero RP involved - is, easily above 75% as of the buff. The blob needed bugfixes, and, minor, minor buffs, not that.
And, quite honestly, the blob buffs should've been test merged, not full merged instantly, so, that's yet another reason this PR is necessary

**Comment by CameronWoof** [comment]
I see no reason an antagonist incapable of roleplay should have a significant chance of torpedoing an entire round. Blobs being weak ultimately serves the aim of the server, which is to provide roleplaying opportunities. A blob that causes significant damage but is ultimately destroyed allows room for roleplay, as characters can breathe and react in the aftermath. A blob that balloons out of control in an unending mechanical contest and then ends the round does not.

**Comment by ShadeAware** [comment]
> 
> 
> > The Blob Buffs were absolutely necessary. This is a salt PR in the most blatant method imaginable; all of the station destructions thus far after the death of the blob have been the result of incompetent station crew abandoning the station or outright ignoring the threat instead of actively doing something, **anything** to attempt to help. Reverting these changes are just going to put Blobs back to the slot they were in, where they would spread for about a minute and then die instantly.
> 
> No, this is a PR that needs to happen, and, to call it a salt PR is ridiculous
> The buff was overkill to an extreme degree, and, it was buffing an NRP antag that ends the entire round
> The blob's winrate - as a round ending antagonist that fucks over all other antagonists and non-antagonists alike with zero RP involved - is, easily above 75% as of the buff. The blob needed bugfixes, and, minor, minor buffs, not that.
> And, quite honestly, the blob buffs should've been test merged, not full merged instantly, so, that's yet another reason this PR is necessary

The thing is, you are not even **attempting** to deal reasonably with the situation. Instead of doing what any sane person would do and attempt to study the changes and reel back as needed, adjusting them, instead this PR has been opened with a kneejerk "REVERT NOW BAD CHANGE BAD BAD BAD" mentality that plagues this repo to no end. 

There is a difference between "This needs to be changed" and "SCREE CHANGE BAD REVERT NOW". This is the latter. Salt PR and Kneejerk change are perfectly apt descriptors of what this most obviously is.

**Comment by chefferz** [comment]
> 
> 
> > > The Blob Buffs were absolutely necessary. This is a salt PR in the most blatant method imaginable; all of the station destructions thus far after the death of the blob have been the result of incompetent station crew abandoning the station or outright ignoring the threat instead of actively doing something, **anything** to attempt to help. Reverting these changes are just going to put Blobs back to the slot they were in, where they would spread for about a minute and then die instantly.
> > 
> > 
> > No, this is a PR that needs to happen, and, to call it a salt PR is ridiculous
> > The buff was overkill to an extreme degree, and, it was buffing an NRP antag that ends the entire round
> > The blob's winrate - as a round ending antagonist that fucks over all other antagonists and non-antagonists alike with zero RP involved - is, easily above 75% as of the buff. The blob needed bugfixes, and, minor, minor buffs, not that.
> > And, quite honestly, the blob buffs should've been test merged, not full merged instantly, so, that's yet another reason this PR is necessary
> 
> The thing is, you are not even **attempting** to deal reasonably with the situation. Instead of doing what any sane person would do and attempt to study the changes and reel back as needed, adjusting them, instead this PR has been opened with a kneejerk "REVERT NOW BAD CHANGE BAD BAD BAD" mentality that plagues this repo to no end.
> 
> There is a difference between "This needs to be changed" and "SCREE CHANGE BAD REVERT NOW". This is the latter. Salt PR and Kneejerk change are perfectly apt descriptors of what this most obviously is.

You do realize this can be reverted and another, more balanced PR made, right?

**Comment by ThatGuyFromThatPlace** [comment]
> You do realize this can be reverted and another, more balanced PR made, right?

This

> The thing is, you are not even **attempting** to deal reasonably with the situation. Instead of doing what any sane person would do and attempt to study the changes and reel back as needed, adjusting them, instead this PR has been opened with a kneejerk "REVERT NOW BAD CHANGE BAD BAD BAD" mentality that plagues this repo to no end.
> 
> There is a difference between "This needs to be changed" and "SCREE CHANGE BAD REVERT NOW". This is the latter. Salt PR and Kneejerk change are perfectly apt descriptors of what this most obviously is.

No, I consider the fact that the blob buffs were immediately and "Shamelessly" full merged without test merging to be "Not even **attempting** to deal reasonably with the situation" and "A kneejerk change"

The reason this is good, is, it's better to have the buffs not in, in the meanwhile, before a proper, balanced buff is merged, rather than letting blob end rounds constantly and run amok rampaging through the server.

**Comment by Owai-Seek** [comment]
Blobs, as they are now, serve no other purpose other than to spawn, wreck shit, and end the round. Before these changes were put into place, I watched three blob rounds. Two of said rounds were in engineering, one was in chapel. Both engineering based blobs took several mechs firing into it for a sustained period of time to keep it contained, and the crew barely won. Anyone outside of a mech got their shit kicked in. The one in chapel put its core too close to space, and got magdumped by someone in a mech hardsuit with microfusion cells.

The thing about blobs, is that, not everyone can feasibly combat them. A large portion of the server, would, in a roleplay setting (and actually don't) have any experience with combat whatsoever. Most of the players don't have hardsuits to attack from space, especially when a bunch of assistants yeet off into space with all the EVA suits.

There is no time to roleplay with a blob. It's a round ending threat, the only thing that exists are mechanics, and action. It completely takes the spotlight away from anything else happening in the round. You can't roleplay with 6-10 rotting miasma corpses in medbay. You can't roleplay with a blobbernaut fisting your face. What you can roleplay is the aftermath, which isn't even a thing if the blob wins.

**The thing about antagonists is that they're not not SUPPOSED to win**. Your goals ARE NOT TO WIN on skyrat, and it's getting really, really draining dealing with people who are playing to win, instead of playing to create a story.

**Comment by Sir-Lagsalot** [comment]
> 
> 
> all of the station destructions thus far after the death of the blob have been the result of incompetent station crew abandoning the station or outright ignoring the threat instead of actively doing something, **anything** to attempt to help.

That's... the point, yeah.
Blobs aren't supposed to win if the crew cooperates. If blobs could consistently win against an organized crew, it'd... kinda suck, yknow? Blobs would just be ending rounds left and right.

**Comment by davidchan13** [comment]
If blobs kicking the crap out of the crew consistently is what it takes to shift the playerbase meta to working together rather than just doing their own little autismo forts and hiding in their departments to never come out till the shuttle comes out, I say it's worth a few rounds ending early.

Command can always call ERTs and if ERTs aren't strong enough then coders can look into bringing them up to spec.

**Comment by SpookyTheFox** [comment]
I'm here in support of rolling back the blob buff. This is ridiculous. Blobs were already a chore that were becoming less and less fun to combat, and spawning far too often. If the players were aware ahead of time that it would be a blob round, I am confident in saying most would simply skip playing that round at this point. Previously, the crew was winning by only small margins, and often had enough station damage that the shuttle was called soon after defeating the blob anyway. The slightest setback, such as xenobio not having yellow cores, allowed the blob to win. Now, it's pointless to fight the blob, and I can't fathom why the changes were made in the first place. This is not the only instance of a recent change that has made an antag type substantially over perform. These changes do not make the game more fun for anyone, they simply punish the playerbase.

**Comment by calibraptor** [comment]
I initially requested that the rarity of blobs be increased immensely to account for the massive increase in strength, if not made an admin button because typically the only person having fun is the person who's controlling the blob.

For the crew it's a station ending threat that forces them to drop everything they are doing to try and contain it in a drawn out battle of attrition.

**Comment by necromanceranne** [comment]
If this antag doesn't serve to further the agenda of the server, why have it in the first place?

**Comment by CameronWoof** [comment]
> If this antag doesn't serve to further the agenda of the server, why have it in the first place?

It's my opinion that it can still serve in a weaker state, but you might be right. I only know that this current incarnation is _definitely_ wrong, hence the PR. If further action needs to be taken later, we can figure that out.

**Comment by Commandersand** [comment]
idk the only time i ever saw blob win before the buffs was when security and the entire crew were completely incompetent and the AI had a law about lying and the crew had no idea where it was, like EVERYTHING that could go wrong went wrong, even cargo because they ordered a bunch of non lethals for the blob lol

i'd say just keep some of the buffs 
>If this antag doesn't serve to further the agenda of the server, why have it in the first place?

this is action/RP
blob adds good panic RP(if you even want to RP a blob existing or just ignore it for your scene) and a lot of action

**Comment by YakumoChen** [comment]
Only time I've seen blob win pre nerf was when the entire crew ignored it and let it get to 400 tiles (400 is the wincon on typical servers so a blob that size is usually too big to kill regardless), so they could board the escape shuttle and bug out.
(Spoiler: the shuttle didn't leave)

**Comment by Strazyplus** [comment]
I think **instead of** just reverting full sail, should nerf it slightly. 

IMO the blob does not always win, but pre-buff the blob always lost no matter how much cheese you do. and only chance is if the crew completely ignored.

I believe blob, xenos and vines and /majority of lavaland/ ect provides a buffer to the roleplay. I feel these threats provide variety to the server.

Do not revert, tweak instead.

**Comment by Sir-Lagsalot** [comment]
Blob turnout is actually pretty decent here, especially compared to other servers I've played on. I've been seeing it decline recently, though. People can't really be fucked to fight blobs anymore it seems.

**Comment by Gandalf2k15** [comment]
This is no longer relevant as there are new PR's to fix it.

**Pull request closed without merging**
