### PR TITLE
[READY] Removes the Combat Shotgun from the Warden's Locker

### PR DESCRIPTION
**Pull request by CinderWC**
## About The Pull Request
Hello it me.
After we had a bit of a discussion about the utility that the Warden and HOS has, a few of us really agreed on the point of removing the combat shotgun

## Why It's Good For The Game
There is almost no reason for the Warden to have a Combat Shotgun, as they aren't supposed to go around validhunting and lethaling antags anyway, and there should never be a situation where the Warden has to lethal their prisoners, ever.

## Changelog
:cl:
del: Removed the Combat Shotgun from the Warden's Locker
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
Honestly there is no reason for the warden to have two shotguns, at all, period.
+1

**Comment by RatFromTheJungle** [comment]
image

**Comment by ForrestWick** [comment]
Wardens aren't supposed to be going lethal on antags via validhunting or lethaling prisoners, that's fair.

However, they're tasked with defending the brig and armory. They need something to bust out if shit is going extremely south, something that doesn't need to be jammed into a recharger.

**Comment by Rayfod** [comment]
The combat shotgun can also be filled with beanbags, and all the none lethal shotgun shots.
So I don't see a reason to remove it, based around that they have a lethal option for the shotgun itself, how about changing the ammo that it starts with instead of removing it?

**Comment by BobJoga** [comment]
> Wardens aren't supposed to be going lethal on antags via validhunting or lethaling prisoners, that's fair.
> 
> However, they're tasked with defending the brig and armory. They need something to bust out if shit is going extremely south, something that doesn't need to be jammed into a recharger.

They have the particle defender.

> The combat shotgun can also be filled with beanbags, and all the none lethal shotgun shots.
> So I don't see a reason to remove it, based around that they have a lethal option for the shotgun itself, how about changing the ammo that it starts with instead of removing it?

They have a particle defender.


The warden does not need two shotguns. And if he does, the HoS also needs two weapons.

**Comment by CinderWC** [comment]
> If a warden truly needs a ballistic shotgun, he has access to the armory.

Exactly. People in here are acting like there suddenly are no shotguns in the armory anymore that the Warden can grab

**Comment by CinderWC** [comment]
They need something to bust out if shit is going extremely south, something that doesn't need to be jammed into a recharger.

So go into the armory and grab a Riot Shotgun from in there?

> The combat shotgun can also be filled with beanbags, and all the none lethal shotgun shots. So I don't see a reason to remove it

Riot Shotguns can do the same.

> If a warden truly needs a ballistic shotgun, he has access to the armory.

This. People acting like the Warden suddenly has no more options for lethals when every map has 2 Riot Shotguns + Beanbag and Buckshot spawns.

**Comment by ShadeAware** [comment]
Warden has access to an entire fucking **armory**, they can afford to loose an extra combat shotgun lmao. They already get their own personal weapon, which is essentially just a laser carbine shotgun. 👍

**Comment by Rayfod** [comment]
Well, removing something without making a replacement is always bad IMO, it could very easily just have the combat shotgun replaced with a pistol shotgun [That fires two shots, and would fit in your pocket], or something else, but removing items /even if they already have a special weapon/ is a bad mentality from my view. 
And the idea that you need to take out a riot shotgun, that they have a very limited amount of, would basically be the same as me saying, that another riot shotgun need to be added to the armory since the warden needs an extra since he no longer has the combat shotgun.
Not saying that the combat shotgun did not need a nerf, but I generally just don't like the "let's just remove the item, since it's really good"

**Comment by CinderWC** [comment]
> Well, removing something without making a replacement is always bad IMO

No it isn't. Sometimes things plain don't work well or things are adjusted for balance, this is one such change.

>it could very easily just have the combat shotgun replaced with a pistol shotgun [That fires two shots, and would fit in your pocket], or something else, but removing items /even if they already have a special weapon/ is a bad mentality from my view.

So you want me to add a pistol shotgun when the Warden can just grab a Riot Shotgun from the armory that is going to powercreep that pistol? lol

> And the idea that you need to take out a riot shotgun, that they have a very limited amount of, would basically be the same as me saying, that another riot shotgun need to be added to the armory since the warden needs an extra since he no longer has the combat shotgun.

You can order Riot/Combat Shotguns from Cargo, don't act like there suddenly is no more shotguns obtainable than those 2 in the armory.

> Not saying that the combat shotgun did not need a nerf, but I generally just don't like the "let's just remove the item, since it's really good"

Like above, the item still exists in the fucking game, just order it bruh

**Pull request merged**
