### PR TITLE
Skyrat Boxstation Maint Loot Improvements

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Implements the blockers that I added earlier to boxstation and also re-places maint loot to areas that are fitting.

## Why It's Good For The Game

Makes my two changes earlier actually good by placing both additions in a better way.

## Changelog
:cl: BurgerBB
add: Obstructions in Skyray Boxstation maint are now more random and the loot is placed differently. Also adds trash piles to Skyrat Boxstation.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
>Conflicting files:
>Boxstation

I'm going to cry.

**Comment by Akrilla** [comment]
is this ready?

**Comment by BurgerLUA** [comment]
> is this ready?

yes

**Comment by BurgerLUA** [comment]
Wait, Useroth wants me to add maint piles to maint.

**Comment by Akrilla** [comment]
will review when done

**Comment by BurgerLUA** [comment]
Done. @Akrilla

**Pull request merged**
