### PR TITLE
Nooses

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

i want to die

## Why It's Good For The Game

because byond makes me want to kill myself
https://www.youtube.com/watch?v=XVON0vP8k4s

mmfhksh

## Changelog
:cl: Bob Joga and the cool people at Hippiestation
add: Nooses
add: Crafting recipe for nooses
/:cl:

### CODE REVIEW

**Comment by NopemanMcHalt** [comment]
😔

**Comment by Owai-Seek** [comment]
I don't like the concept of nooses for several reasons. It makes people uncomfortable, it's unnecessary, and I can almost guarantee that it'll only be used for LRP shenanigans or memes, just like the Femur Breaker.

The suicide command was removed for a reason. One of the servers rules is to to not push mental health issues on others. Sure, you could say that a traitor could use this in a roleplay to hang someone, but I feel like the bad, by far, outweighs any good this PR will have.

**Comment by BobJoga** [comment]
> I don't like the concept of nooses for several reasons. It makes people uncomfortable, it's unnecessary, and I can almost guarantee that it'll only be used for LRP shenanigans or memes, just like the Femur Breaker.
> 
> The suicide command was removed for a reason. One of the servers rules is to to not push mental health issues on others. Sure, you could say that a traitor could use this in a roleplay to hang someone, but I feel like the bad, by far, outweighs any good this PR will have.

I don't mean to be offensive but so far you seem to be the only one really uncomfortable with it. I have yet to receive anyone else who feels wary of this PR in this way.
Also how is this pushing a mental health issue onto others?Firstly, it's just a game item - this isn't related to anyone's OOC mental issues, it's a tool for character development and RP. Secondly, it's just a noose. An instrument of homicide and suicide used since the dawn of mankind. You're not forced to use it and this isn't directed at anyone personally.

**Comment by Owai-Seek** [comment]
You had comments on it the -last- time you made it. Just because I'm the only person speaking out about it right now doesn't mean I'm the only person it makes uncomfortable. A lot of people don't speak out about things specifically because they feel like they'll be brushed off or targeted for it.

**Comment by BobJoga** [comment]
> You had comments on it the -last- time you made it. Just because I'm the only person speaking out about it right now doesn't mean I'm the only person it makes uncomfortable. A lot of people don't speak out about things specifically because they feel like they'll be brushed off or targeted for it.
> 
> Most players don't even look at the github.

The game can't be tailored to a small minority of people. SS13 already has, by it's very nature, a lot of gore, violence and dark themes - even if it's coated with some sillyness. We can't remove guns from the game because we have pacifist players that get wary by it. We can't remove ERP because we have asexuals. I won't target anyone because they don't like nooses, if a majority of people say no to this idea i'm fine with closing it - but i really don't think not adding features because of a minority is wise.

**Comment by BobJoga** [comment]
honestly i'll just replace this with an entire gallows pole (way cooler)

**Pull request closed without merging**
