### PR TITLE
massive kudzu/spacevines buff

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
on the event spawn, 3 ghost playable venus plants spawn
added a slipping mutation
increased the growth chance
on spread to a turf with a door, has a 50% chance to open the door
space vines can spread on space now

## Why It's Good For The Game
vines are so tame and boring...

## Changelog
:cl:
add: Added slipping mutation to kudzu
add: Added 3 ghost playable venus plants on kudzu event
add: Spacevines can now grow on space
add: Kudzu has a chance to open doors
tweak: increased growth chance on kudzu
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
I don't feel much excitement at the idea of further emphasizing dangerous, roleplay-free antagonists. Vines are now at least somewhat contained by airlocks, having them sprawl indefinitely out through doors alongside the other buffs and the addition of *three* hostile ghost roles all seems really over the top for what's supposed to be a fairly minor event.

**Comment by MimicFaux** [comment]
I like the idea of a kudzu spawning to gaurd it, I think three is too many

**Comment by ThatGuyFromThatPlace** [comment]
What with the human traps being player controlled now, we've already had a Kudzu be the equivalent of a mildly weaker blob, taking out many players, and, taking some out for the rest of the round. Although Kudzu is very weak if caught early, the Kudzu is as of the plants being player controlled, can be extremely troublesome if left unchecked. A single trap and a slight increased **initial** growth rate/burst might be fine, however, three spawning instantly and having it spread to space and slam through doors seems... Excessive. This feels like it'll put it on level with an AI controlled with weaker blobbernauts.

**Comment by YakumoChen** [comment]
Not every mildly dangerous event has to be potentially round ending in a way that murders a bunch of crew for no good reason

**Comment by Echopsychotic** [comment]
Love how I bring up clown vines and now you get the slip vines. My wildest nightmares realized.

**Comment by davidchan13** [comment]
+1 to everything BUT the space vines.

Space vines were on tg a long time ago and they were utter cancer if they ever spread into space as there was reliable way to deal with them. This was lag inducing crap no one wanted with all the processing each tile of vines needed with near unlimited growth into the void. 

If you wanted to make it so vines could extend 1 tile into space, and required some actual grounding adjacent, that would be fine, allowing the vines to cross small gaps. But being able to grow endlessly into space? Fuck no please.

**Comment by Owai-Seek** [comment]
I think three traps is also too many, but it might be something to work out after some testing.

As for the space tiles, what if the vines had an area it's not allowed to spread into? In addition, possibly only spreading on space in the station Z-Level?

All of space (as far as I know) uses  `/turf/open/space/basic` but there's a spawn area surrounding the station for asteroids called `/area/space/station_ruins/` that you could possibly blacklist vines from spreading to? This would (hopefully) contain them to an area around the station.

**Comment by jjpark-kb** [comment]
> I think three traps is also too many, but it might be something to work out after some testing.
> 
> As for the space tiles, what if the vines had an area it's not allowed to spread into? In addition, possibly only spreading on space in the station Z-Level?
> 
> All of space (as far as I know) uses `/turf/open/space/basic` but there's a spawn area surrounding the station for asteroids called `/area/space/station_ruins/` that you could possibly blacklist vines from spreading to? This would (hopefully) contain them to an area around the station.

Ill probably try to do what davidchan said and allow the vines to spread in space one tile away from a wall.

**Comment by jjpark-kb** [comment]
> +1 to everything BUT the space vines.
> 
> Space vines were on tg a long time ago and they were utter cancer if they ever spread into space as there was reliable way to deal with them. This was lag inducing crap no one wanted with all the processing each tile of vines needed with near unlimited growth into the void.
> 
> If you wanted to make it so vines could extend 1 tile into space, and required some actual grounding adjacent, that would be fine, allowing the vines to cross small gaps. But being able to grow endlessly into space? Fuck no please.

so instead of the 1 tile into space, I just made it to where they cant spread into the space_ruin space area, like Owai suggested.

**Comment by davidchan13** [comment]
I'm not familiar with how space ruins are mapped but I hope that's enough to stop pockets of vines from growing free floating in space.

**Comment by chefferz** [comment]
https://i.imgur.com/sLEUCpm.png

This is the result of vines spreading in a very short period, for a natural event. Breaching windows and spawning ELEVEN different kinds of Kudzu, on top of player controlled man traps, along with being able to survive in space in the first place (they're plants, they require oxygen to function) is making this incredibly silly.

**Pull request merged**
