### PR TITLE
[MIRROR] species customization now allows 16 million colors instead of 4 thousand 

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12848
--------------------

## Why It's Good For The Game

customization

## Changelog
:cl: silicons
tweak: sanitization now doesn't cut off 15.7 or something million possible colors from character preferences (instead of only allowing 16 values for R G and B, it now allows 256 each)
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Thank fuck. I always hated shortcolour, amazing work to all involved for figuring this out

**Comment by Gandalf2k15** [comment]
Do not merge until further notice.

**Comment by silicons** [comment]
don't merge without https://github.com/Skyrat-SS13/Skyrat13/pull/3084 unless you want everyone's saveslots breaking 
hexcolor sanitization didn't convert both ways.

**Comment by hugmeorelse** [comment]
> don't merge without #3084 unless you want everyone's saveslots breaking
> hexcolor sanitization didn't convert both ways.

Thanks for the heads up.

**Pull request closed without merging**
