### PR TITLE
Gives a select few species selectable blood color and reagent

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Title.

Custom color applies to: All types of synthetics, insectoids (including moffs), vox, slime and jelly people.
Alternative reagents apply to: All types of synthetics.

## Why It's Good For The Game

snowflakey character setup good :)

## Changelog
:cl:
add: Some species now have blood color and reagent options
/:cl:

### CODE REVIEW

**Comment by TheSpaghetti** [comment]
yes

**Comment by BobJoga** [comment]
I fucked this up hard. I'll make another PR later.

**Comment by BobJoga** [comment]
fixed everything

**Comment by BobJoga** [comment]
can't be bothered to deal with the conflicts now tbh

**Comment by BobJoga** [comment]
i fixed this but fuck i'm just gonna create nanother pr

**Pull request closed without merging**
