### PR TITLE
Revert "A literal shitposter PR"

### PR DESCRIPTION
**Pull request by hugmeorelse**
**Why was this approved?**

### CODE REVIEW

**Comment by Yawet330** [comment]
because it was funny.

**Comment by Weblure** [comment]
Actually, being able to copy posters is a nice feature for security. Having to copy/paste + retype a bunch of the same shit over and over for each wanted poster is agony. The shitposts don't really have a good place here, though.

**Comment by hugmeorelse** [comment]
> Actually, being able to copy posters is a nice feature for security. Having to copy/paste + retype a bunch of the same shit over and over for each wanted poster is agony. The shitposts don't really have a good place here, though.
> 
> Also, why was this speed-merged ahead of fix PRs during a freeze?

That will be brought back, just not the shitposts.

**Comment by Weblure** [comment]
> That will be brought back, just not the shitposts.

Why remove it in the first place, though? You removed a feature during a feature freeze, so we can't exactly restore that feature any time soon... Wouldn't it make more sense to just remove the shitposts and leave in the feature?

**Comment by hugmeorelse** [comment]
> > That will be brought back, just not the shitposts.
> 
> Why remove it in the first place, though? You removed a feature during a feature freeze, so we can't exactly restore that feature any time soon... Wouldn't it make more sense to just remove the shitposts and leave in the feature?

It's almost like it's my server.

**Comment by Weblure** [comment]
> > > That will be brought back, just not the shitposts.
> > 
> > 
> > Why remove it in the first place, though? You removed a feature during a feature freeze, so we can't exactly restore that feature any time soon... Wouldn't it make more sense to just remove the shitposts and leave in the feature?
> 
> It's almost like it's my server. Feature freezes means new features being added in. This isn't a new feature. I'm just having Bob gut the meme out and push a new PR.

Fair enough, I wasn't sure what your intentions were. It'd just be nice to keep this feature in without it getting stuck behind the freeze, despite being in long before it.

**Pull request merged**
