### PR TITLE
[Pls review!] Fixes n stuff for Oldstation (and QoL for Lavaland syndies)

### PR DESCRIPTION
**Pull request by werewolfboyfriend**
## About The Pull Request
I haven't had much time to play in the last week or two, but I wanted to finish this up anyhow. Oldstation is one of my fave ghost roles. The ruin for it is a little quirky though, particularly with the naming of APCs and airlocks. There's also a few other things that were bugging me which I wanted to address.
I added a few more area defines, renamed some, and fixed the naming on airlocks and APCs. I changed the wording "artificial program" in the note items to "artificial intelligence". I've also fixed the invisible IDs and APC card. IDs are special ones with a stripe down the middle to reference the actual old ID sprites and the APC card is a flipped engie budget card. The IDs are not modular, but brig phys and blueshield IDs aren't either. I gave the skyrat begin/end sprites actual images though.
More notably, I guess, I added and changed some rooms and items around to make some more sense and add a little more flavor to the place.
- Small chapel, to go with the chaplain role. Seats eight worshippers.
- Small, spaced morgue with eight morgue trays.
- Forbidden crate added to the spaced medbay.
- Engineering reorganized, and it now has a high capacity welding fuel tank.
- Security partially reorganized, and the upper half has two destroyed holding cells.
- Dorms/living area expanded. Rooms are now 3x3 and can be bolted. Cryopod now available as well as a ClothesMate, and there's a KinkMate hidden behind a wall.
- Ship remodeled.
- The upper half of R&D room has been reorganized slightly.  Machines are now flush with the wall and there's a couple of extra tables.
- The xeno hive area is now called the secure research wing. I've added some table frames and broken computers to try and make it so you can guess what the areas actually were, but I didn't want to get too overt about it or add anything valuable without good cause. The spot right next to the vault is now intended to have been an RD's office, for example.
- **The AI core/Empress room has loot, now: A shotgun and an implant beacon.** I felt like one of the big things that bugged me about the gameplay for Oldstation was getting nothing for killing the Empress. I think these aren't terribly unreasonable items, but had some trouble coming up with ideas, so..
- I think I added another couple xenos in some places! Not actually sure how many, but it wasn't a lot.
- Lastly, I added a fair amount of random spawn loot to the place. There's some trash piles, maint loot, garbage, one safe + one very safe toolbox, one gloves, an internals mask and tank set, a random cigar box, and two low-tier toilet loot spawns.

oldstation

As for the Lavaland Syndies, the changes are nearly all QoL for xenobio there:
- The big pen no longer has windows to lava, so things you put in there will no longer get shot by the turret. It now has windows to the inside. I scooted the door down so it doesn't eat into the room. The pen is three tiles bigger, as a result. Also went ahead and opened chemistry up a couple more tiles in the same area.
- Monkey recycler, sci goggles, fire extinguisher added. 
- There's now scrubbers in the pens. Moved the freezer up right next to the kill chamber to keep the piping simple, and also it looks better.
- Kill chamber has plastitanium windows like everywhere else in the base now,
- Botany and the circuit lab have interior windows now. 

## Why It's Good For The Game
Oldstation's been in need of refining. I think what I've done benefits both roleplay and gameplay.
As for the Syndie base, the pen window's been a pain for ages and nobody really wants to take the time to set up scrubbers for dealing with miasma. The rest is little things I think can offer small benefits to players.

## Changelog
:cl: Werebear
add: Oldstation has had some rooms added, some edited, and has more random loot spawns. 
tweak: Lavaland syndies no longer have a xenobio pen vulnerable to their own turret, and now have scrubbers in place for miasma. Other small edits, as well.
fix: Oldstation fixes: Areas, APCs, and airlocks now have consistent names and the crew spawn with visible IDs.
/:cl:

### CODE REVIEW

**Comment by SarmentiCampbell** [comment]
Oh man, you made me remember that syndie base should have a roboticist/science lab with that pr

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
From now on we need all icon files to be modular regardless, as they will eventually be overwritten.

**Comment by Gandalf2k15** [comment]
As a side quest, do you think you could make the spawner use your loaded character?

**Comment by werewolfboyfriend** [comment]
Okay. I had the ID icons modular, but it was having some odd behavior. I'll see if I can get that right.

For the spawner using a loaded character  -- is that a thing in place for any other ghost roles?

**Comment by Gandalf2k15** [comment]
I am not entirely sure, if you can't do it then maybe add a magic mirror for spawnees.

**Comment by Funce** [comment]
I could look at the that spawner using a saved character. I've brushed up on it with my most recent PR

**Comment by werewolfboyfriend** [comment]
OK, I modularized the oldstation IDs and added a magic mirror as per @Gandalf2k15. I wanted to keep it out of the actual bathroom, so I took the time to redo the spawn area... and then redid the bathrooms also.
Capture
Capture
(those are both low toilet loot)
I didn't touch the non-modular blueshield and brig phys IDs, so they're still non-modular. Really.. not a fan of ID code so I didn't wanna delve into it for that.
Andd.. if you'd be interested in looking into the saved character spawner thing, @Funce, it's something beyond my time/skill level right now.

~~also apparently I'm logged in on locally the account I thought I lost access to, that's super weird and that's why my commits are on a different account~~

**Pull request closed without merging**
