### PR TITLE
shovel_dogborg.mp4

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

attacking dogborgs with a shovel deals double the damage

## Why It's Good For The Game

bad bad dog

## Changelog
:cl:
balance: Dogborgs receive x2 the damage when attacked by shovels.
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
image

**Comment by nik707** [comment]
god we need your talents upstream

**Comment by ShadeAware** [comment]
@KathrinBailey have you ever been hit in the head with a shovel? That shits disorienting as fuck if it doesnt just knock you the fuck out.

**Comment by ShadeAware** [comment]
Although, maybe the double damage should only apply if aiming for the head.

**Comment by KathrinBailey** [comment]
> @KathrinBailey have you ever been hit in the head with a shovel? That shits disorienting as fuck if it doesnt just knock you the fuck out.


> Although, maybe the double damage should only apply if aiming for the head.

**It's a fucking borg. They're robots that can't feel pain.**

**Comment by BobJoga** [comment]
> image
> meme pr no thanks

It's not a meme i genuinely hate dogborgs and wish to cave their heads in with a shovel.

**Comment by BobJoga** [comment]
> > image
> > meme pr no thanks
> 
> It's not a meme i genuinely hate dogborgs and wish to cave their heads in with a shovel.

In fact the only reason i don't do a PR completely removing them is because the dogborg players will send a hired assassin to murder me if i do it.

**Comment by BobJoga** [comment]
> > @KathrinBailey have you ever been hit in the head with a shovel? That shits disorienting as fuck if it doesnt just knock you the fuck out.
> 
> > Although, maybe the double damage should only apply if aiming for the head.
> 
> **It's a fucking borg. They're robots that can't feel pain.**

then why do they erp, they probably can't feel sexual stimulus either

**Comment by Azarak** [comment]
Bad implementation and meme PR

**Pull request closed without merging**
