### PR TITLE
[MIRROR] Reverses Random Mining Base Placement 

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11582
--------------------

## About The Pull Request

This reverts #11225

## Why It's Good For The Game

The random mining base has been awful for most miners:

1 - Mobs and Megafauna have been spawning right next to it or in shuttle areas

2 - It spawns too close to the edge of the map sometimes

3 - Lava placement is still a bit weird.

## Changelog
:cl:
tweak: Reverts Mining Base RNG Placement
/:cl:

### CODE REVIEW

**Comment by Useroth** [comment]
Not sure about this one.

**Comment by jjpark-kb** [comment]
We probably shouldnt. We can always just add onto the ruin if they add stuff to their base.

**Comment by jjpark-kb** [comment]
Actually, now that I have thought about it. It would be nice to have the miners back to their original spot. The way it generates makes it seem too... shitty? map-generated? 
I actually think this should be merged.

**Comment by Azarak** [comment]
The flagging for random generation is designed specifically with lavaland base in that certain spawn place, so i dunno

**Pull request merged**
