### PR TITLE
DRAGONMECH!

### PR DESCRIPTION
**Pull request by Strazyplus**
## About The Pull Request

Adds all new borg to the game Drakeborg! or DERGBORG!! they come in medical, security, mining, engineering, peacekeeping, and janitor module variants! including two plushie variants!

medic
mining
peace
security
engineering
janitor

**AND PLUSHIE!**

plush-medic

## Why It's Good For The Game

ca2rd

**BECAUSE DRAGONS AND MECHS AND SHIT**

## Changelog
:cl:
add: Added drakeborgs
add: Added drakeborg plushies
imageadd: added many drakeborg images and thier plushies
server: added plushies to the creator's account so they start with drakeborg plushies always.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
add cheemsborg so i can finally accept that dogborgs exist

**Comment by Strazyplus** [comment]
> add cheemsborg so i can finally accept that dogborgs exist

These are not dogborgs we are okay with your non-acceptance of dogborg existence. some of them are horrible.

**Comment by Strazyplus** [comment]
Github is doing a idiot thing, now I am fighting for control while trying to fix a problem reeeeeee

**Comment by Owai-Seek** [comment]
Something about their walking animation feels really off for me. Other than that, I have no real qualms about more borg reskins being added.

**Pull request closed without merging**
