### PR TITLE
Eris Style 2: Maxcap Boogaloo

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Revives #3555 which revived #3062 
(Almost) total overhaul of our style to something that isn't fuck-off outdated and old, and actually pleasing to the eye to look at and gives a sense of depth.
Credits to Bob Joga for code help and the original PR
Credits to Hyperstation, Eris, Yogstation, and JungleRat for various sprites.
image
image
image
image

## Why It's Good For The Game
Our old walls and style is a mishmash of shitty codersprites that have been around for many years and have not aged well whatsoever. Its time we finally ditch these old sprites in favor of something thats actually worth keeping around on a basis that isn't just "FETCH ME THEIR SOULS".

## Changelog
:cl:
sprites: Almost total overhaul of the game's artstyle to something actually good. See #3571 for more information.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
### **ITS ALIVE**

**Comment by ThatGuyFromThatPlace** [comment]
Looks like, yet another improvement upon the last version of the PR. Again.
It only gets better with time
And, glass is now transparent, and has a full-tile sprite. Not, that the transparency matters much with the low walls there

**Comment by ShadeAware** [comment]
> 
> 
> Looks like, yet another improvement upon the last version of the PR. Again.
> It only gets better with time
> And, glass is now transparent, and has a full-tile sprite. Not, that the transparency matters much with the low walls there, but, hey, Eris has it transparent last I checked so, might as well.

All of the glass is transparent, its just blocked by the low walls

**Comment by Tename** [comment]
I mean its a bit better, still dislike the general style, but I liked the transparency added to the windows even if I kind of think they are too blue. I think the doors still sort of look, odd. plating, I really hate still and think the current plates should remain they just don't look right in my opinion.

Bugs: I noticed firelocks appear above shutters, this looks really weird, especially in the mech bay.

**Comment by ShadeAware** [comment]
Fuck it, I give up. This was a fools errand. Keep your shitty 12 year old codersprite boxes.

**Comment by Evan423** [comment]
Honestly, I think they're not bad, they're nice and quite well made. Despite all of the criticism which most of it isn't constructive, or tells anyone what could be changed on it, I'll say what I believe could be changed with them to make them better. I've seen quite a few people say they just don't like it straight up, and just recently saw a large amount of people in the OOC text in the testmerge saying they straight up don't like it, this can be taken as criticism but I would say to listen to the people who don't want it too, and put up legitimate criticism. 

I will now state what I believe can be improved on. Some sprites don't go with this at all, and this can change if you, or others are willing to change up some sprites to make them fit the style more. Maybe some changes with lighting too, along with it needing to be tampered on more. They are well made, and will match, for example, Eris's walls, which look good in their own environment because of the lighting, sprites, and lore, along with the general atmosphere Eris pulls off. I believe they're nice, and I would like them merged myself, but that is my opinion, and what I want. I want it because it looks new, fresh, and clean, this is my opinion, and I don't give a shit what people think.

These sprites look good, but the atmosphere, lighting, and just sprites and the community aren't ready for it yet. Keep tinkering, making sprites, editting things, and It'll look golden.

**Comment by Tename** [comment]
Hey man, sorry you feel that way but, I was starting to feel it a little bit with the transparent windows, you do you though, but I think with a little bit of tweaking people would feel it eventually.

**Pull request closed without merging**
