### PR TITLE
[april fools testmerge] BUTT BOTS BUTT BOTS

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Replaces all bots in the station with buttbots.

ButtBot

Also, see https://soundcloud.com/stephanosrex/honk-honk-butt

## Why It's Good For The Game

butt
council

## Changelog
:cl:
add: Buttbots have taken over the station
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
it compiles

**Comment by hugmeorelse** [comment]
This seems too meme-y.

**Comment by hugmeorelse** [comment]
This seems too meme-y. However, xeno butts. 

@Useroth Please review and give your thoughts. I don't mind lewd items and content being added in. We don't pretend not to be degenerates, but this seems too meme-y.

**Comment by BobJoga** [comment]
i haven't coded it all yet but it'll be amazing guys i swear

**Pull request closed without merging**
