### PR TITLE
Adds emergency welding tool to loadout

### PR DESCRIPTION
**Pull request by Strazyplus**
## About The Pull Request

adds the Emergency Welding tool to the loadout, it is the mini-welder tool it is small and capacity of fuel is very small. 

image
NICE
image

## Why It's Good For The Game

The tool is not too commonly seen or used, For those Synthliz and IPCs who gotta have something in case something bad happens.

## Changelog
:cl:
add: Added Emergency welding tool to loadout
tweak: made it blacklisted for assistants and prisoners (why? prisoners for good reason but assistants do not have a job or a task to perform they can just get their own or find a better welder.
/:cl:

### CODE REVIEW

**Comment by Strazyplus** [comment]
I am gonna make it modular hold on

**Comment by Commandersand** [comment]
mmm powergmae

**Comment by KathrinBailey** [comment]
Can you blacklist from prisoners? Otherwise now prisoners start the game with a crowbar and welder and... yeah. That 10u of welder fuel will last a while.

**Comment by Strazyplus** [comment]
> Can you blacklist from prisoners? Otherwise now prisoners start the game with a crowbar and welder and... yeah. That 10u of welder fuel will last a while.

I did not think of prisoners oh lorda

**Comment by Strazyplus** [comment]
There I made it so only "Head of Security", "Captain", "Head of Personnel", "Chief Engineer", "Research Director", "Chief Medical Officer", "Quartermaster", "Medical Doctor", "Chemist", "Virologist", "Geneticist", "Scientist", "Roboticist", "Atmospheric Technician", "Station Engineer", "Warden", "Detective", "Security Officer", "Cargo Technician", and "Shaft Miners" to get the emergency welder tool 

AND its modularized

**Comment by NopemanMcHalt** [comment]
> There I made it so only...

Paramedics and Blueshield: ***Am I joke to you?***

**Comment by KathrinBailey** [comment]
@Strazyplus You might find it useful to contact some of the folks on Citadel and ask them if you can blacklist instead of whitelist every job but one. Try contacting Azarak too, her might be able to help since I know he is doing character creation stuff and this is along those lines.

**Comment by Strazyplus** [comment]
> @Strazyplus You might find it useful to contact some of the folks on Citadel and ask them if you can blacklist instead of whitelist every job but one. Try contacting Azarak too, her might be able to help since I know he is doing character creation stuff and this is along those lines.

Paramedic and BlueShield can get the tool now.

**Comment by Strazyplus** [comment]
Removed trace of my editing from the non-modular hands.dm

**Comment by Strazyplus** [comment]
no change just made it tidy looking, unless people want me to add service to whitelist I think I am done.

**Pull request closed without merging**
