### PR TITLE
Kinetic Accelerators of the Rainbow

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

This adds 6 new KAs, Stats and features WILL be given in comparison to Base, Premium and Blood Drunk versions
Base KA: 40 Damage, 16 Cooldown, 3 Range, 100 Modability (Thanks for pointing that out, Yakumo)
Prem KA: 50 Damage, 16 Cooldown, 4 Range, 100 Modability
Bloody KA: 50 Damage, 14.5 Cooldown, 4 Range, 125 Modability
New ones:
Precise KA: 45 Damage, 18 Cooldown, 6 Range, 80 Modability 
Rapid KA: 25 Damage, 12 Cooldown, 4 Range, 80 Modability (Cannot Bayonet or Flashlight)
Heavy KA: 65 Damage, 22 Cooldown, 3 Range, 80 Modability (Has a new special AoE mod that is unremovable.. or should be)
Modular KA: 25 Damage, 30 Cooldown, 4 Range, 180 Modability
BYO(Custom) KA: 0 Damage, 27 Cooldown, 1 Range, 300 Modability (Can Bayonet and Flashlight, But _WILL_ be ugly)
Ashen KA: 60 Damage, 13.5 Cooldown, 5 Range, 100 Modability (Cannot Bayonet or Flashlight, Tendril Exclusive)

The Precise, Rapid, and Heavy KA's can be bought for 10K mining points, Modular at 15K, and BYOKA at 30K

HEADS UP! I will probably try to change some of these Later in favor of making them more unique and not just large stat-mongering variants, Probably a bit better to fit with some other design changes.

https://i.imgur.com/cDyCFme.png

## Why It's Good For The Game

Adds more KA Specialized for certain tasks and playstyles

## Changelog
:cl:
add: 4 new purchasable Kinetic Accelerators with different balance bases and unique sprites
add: 1 Build Your Own KA, That is more of a joke with some niche usability (Also uniquely sprited)
add: 1 Necro-tendril drop exclusive KA with a unique sprite
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I thought the base KA has 3 range?

**Comment by Zenitheevee** [comment]
> 
> 
> I thought the base KA has 3 range?

Ah, it.. evidently seems to have 3 range..

**Comment by YakumoChen** [comment]
How does that new knowledge factor into your new KAs?

**Comment by Zenitheevee** [comment]
> 
> 
> How does that new knowledge factor into your new KAs?

I feel it _Could_ give me a bit more play with the Heavy KA, Mainly trading one range for a bit of extra damage, Or giving the Modular KA back its planned 200 modability

However, I feel When it comes to being massively mobile (Where the KA excels at) Range is, Quite honestly, An under-utilized and over-powered stat. And taking in further things like the cost of some mods, its a much-debatable balancing act of specialization.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
Final checks complete, 1-day allowance for changes granted.

**Comment by Zenitheevee** [comment]
alright, stats have been looked at again to make sure i'm happy with them and Changelog section has been cleaned up to fit with a merge.

**Comment by ForrestWick** [comment]
I'm really not sure about this tbh. Given we don't have anything like nukies, the crew at large doesn't benefit and it's exclusively a miner buff. The BYOKA is a cool idea, but stuff like the heavy one just gimmie bad vibes.

**Comment by Zenitheevee** [comment]
> 
> 
> I'm really not sure about this tbh. Given we don't have anything like nukies, the crew at large doesn't benefit and it's exclusively a miner buff. The BYOKA is a cool idea, but stuff like the heavy one just gimmie bad vibes.

I feel like claiming its a _Buff_ is a bit misleading, But i do understand a good amount of concern shared with the Heavy. I am more than willing to drop the Heavy a good handful of changes in stats to rebalance it, given its rather robust damage stats, But a few things to keep in mind with it is that its innate AoE prevents other AoE modkits from applying, Including those that would increase the AoE damage, And i could expand its Modkit blacklist to a good amount of modkits if **given a good list of problematic, non-stat mongering mods.**

**Comment by ForrestWick** [comment]
> > I'm really not sure about this tbh. Given we don't have anything like nukies, the crew at large doesn't benefit and it's exclusively a miner buff. The BYOKA is a cool idea, but stuff like the heavy one just gimmie bad vibes.
> 
> I feel like claiming its a _Buff_ is a bit misleading, But i do understand a good amount of concern shared with the Heavy. I am more than willing to drop the Heavy a good handful of changes in stats to rebalance it, given its rather robust damage stats, But a few things to keep in mind with it is that its innate AoE prevents other AoE modkits from applying, Including those that would increase the AoE damage, And i could expand its Modkit blacklist to a good amount of modkits if **given a good list of problematic, non-stat mongering mods.**

The main issue I'm seeing with heavy is the damage is pretty insane, and could lead to just making megafauna even easier to kill. KAs are already as a good place. I feel like just having the BYOKA alone would be fine, but the rest seem either unnecessary or just too powerful

**Comment by Zenitheevee** [comment]
> The main issue I'm seeing with heavy is the damage is pretty insane, and could lead to just making megafauna even easier to kill. KAs are already as a good place. I feel like just having the BYOKA alone would be fine, but the rest seem either unnecessary or just too powerful

Well, They _are_ unnecessary, This is _Mining_ we're talking about, where most players who go for megafauna will either rush a Crusher, but thats strawmanning the issue here.

To as much reassurance as i can offer, I have done atleast _Some_ testing to help figure out that, While the Heavy KA fires a 65 damage round, The CD is a real kick in its teeth. 

(Note: These tests are done with a _BASIC_ set up. No Config changes, so whatever the configs are upon download are what they are)

In an unmoddified setting, I was able to get 6 shots out of both the Premium and Normal KA's in 10 seconds, Where as the Heavy kinda barely made 4 scootching onto the 11th second 
For a normal KA thats about ~240 damage, And you can slap on 3 damage modifiers to bring that up to about.. 420 or so?
For a normal Premium KA, You're doing 10 more damage per shot, at around 300 unmodified, 480 damage focused.
For the Heavy, thats.. barely comparable to the __Normal_ KA at around 260 unmoddified? And with the lesser modification, you can only get 80 more total damage to a damage of 340, Decidingly __Less__ than the normal, damage focused KA.

And, Before the question of "Cooldown based" is brought up, The heavy __BARELY__ gets an improvement, At being able to make 5 shots before 10 seconds, and barely scooching one at the 11th (Since the Heavy can only get 2 CD mods, bringing it down from 22 to 17, Barely above the KA's BASE), releasing a grand total of.. 325 damage?
Both the Premium and Normal KAs however, can easily out damage it at **12** shots in 10 seconds with 3 CD decrease mods.
For the normal KA, Thats topping at about 480, While the premium gets a flat 600. 
Both the Normal and Premium KA's out damage the heavy in both cases (and this honestly came to a surprise to me), With Heavy's only significant upside is that its reliability comes in its ability make normal legions not much of a problem, or dealing with Tendril groups or bunched up enemies.

**Comment by Zenitheevee** [comment]
I some how failed a map diff render check....

With.. files that shouldn't... touch map files...

Map files i... dont even know the location of...

**_i am confusion_**

**Comment by Zenitheevee** [comment]
ok, seems there's not much i can do on my end, atleast not with my level of experience or ability, to fix... whatever's going on.

**Comment by Zenitheevee** [comment]
sprite conflict fixed... yay.....

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
