### PR TITLE
[WIP]Brings back telescience, but this time you're fucked by RNG

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

It's fucking telescience jutsgrhfmhdrjmrhrsfmkhngk it's telescience it's good it's fun,, everyone loved it /tg/ fucking killed it, i bring it back

## Why It's Good For The Game

Orange man bad

## Changelog
:cl:
add: Telescience fucking RETURNS
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
DHBFJDNINJIRINESINJJESONOJMESDIBMJ FUCK

**Comment by ForrestWick** [comment]
I don't like the idea of sci having everything again. It'd be better if everyone had their protolathes and shit still, but science had to manually transfer their research, along with RND consoles needing to be linked to servers.

**Comment by BobJoga** [comment]
> I don't like the idea of sci having everything again. It'd be better if everyone had their protolathes and shit still, but science had to manually transfer their research, along with RND consoles needing to be linked to servers.

Code it yourself

**Comment by Useroth** [comment]
Come on, Travis. Fucking check this.

**Comment by Useroth** [comment]
Also imma testmerge.

**Pull request closed without merging**
