### PR TITLE
[MIRROR] Clockwork Cult rework

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12742
--------------------

## About The Pull Request
Makes Clockwork Cult less of a clusterfuck of plasma flooding and Gygax rushing (though I know the latter won't be stopped regardless)
This is finally in somewhat of a testmergable state, everything seems to be working on local.

## Why It's Good For The Game
Reebe was a garbage attempt at making clockwork cult unique from Blood Cult, but hopefully, this attempt will be able to capture what made both component-based clock cult AND Reebe clock cult fun.

## Changelog
:cl:
add: The belligerent scripture and a brass multitool, and a new marauder variant which act similar to holoparasites/guardian spirits.
del: Removed the abductor teleport consoles they get, removes abscond for the time being as I've not seen much use for it other than just spamming it and hoping you end up in the armory.
tweak: moved around scriptures to make the cult work better as being based around the station, makes the Ark scream more often and work as a summonable object, clockwork armor now has a flat 0 defense up to 10 instead of negatives against laser damage. Makes the Ark work better in a station based setting, as well as the Heralds beacon in case It works for the mode.
soundadd: added powerloaderstep.ogg for Neovgre
/:cl:

### CODE REVIEW

**Comment by KeRSedChaplain** [comment]
Just gonna say now that I humbly request you guys to take the mode in your own unique direction, but since open source is open source do whatever, thank you.

**Comment by jjpark-kb** [comment]
> Just gonna say now that I humbly request you guys to take the mode in your own unique direction, but since open source is open source do whatever, thank you.

image
Hmmmmm

**Comment by Akrilla** [comment]
thanks for your blessing

**Comment by KeRSedChaplain** [comment]
ehhh its less of a blessing but more of just "hey I'll be disappointed if this gets merged without your own unique spin but I can't stop you"

**Pull request closed without merging**
