### PR TITLE
Blueshield Weapon Beacon/Bugfixes

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request
Gives the blueshield a weapon beacon, offering the PDW-9, a self-recharging variant of the energy revolver with a lesser cell capacity.

Fixed the blueshield armour causing anthro sprites to bug out.

Fixed the snowflake glove implementation.

Also fixes the PDW-9.

Gives the blueshield combat boots.

image

## Why It's Good For The Game
More stuff.

## Changelog
:cl:
add: Gave the blueshield a weapon beacon, and access to the PDW-9.
fix: Fixed the blueshield armour for anthros.
/:cl:

### CODE REVIEW

**Comment by Investigator77** [comment]
Looking like a Mass Effect gun, I like.

**Comment by Gandalf2k15** [comment]
Test-merge approved.

**Comment by Arturlang** [comment]
@Gandalf2k15 PDWs icon doesnt update when recharging.

**Comment by Gandalf2k15** [comment]
Icons now automatically update.

**Pull request merged**
