### PR TITLE
Removes botany chem dispensers but adds botany supplies box with chems and more..

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Removes botanical chem dispensers from all the maps it was introduced to and replaced it with a box containing 4 bottles of mutagen and 3 bottles of saltpetre(the chemicals they cant get from a hacked vendor) each into a botanist locker. So in total 240 mutagen in most maps.

Box botany had its DNA manipulator moved into the main room for convinience, and got a backroom tray. 

Touched on some inconsistent decals on the botany areas in some maps.

Also brought back DNA manipulator into Pubby main room because god why was it moved to backroom.

## Why It's Good For The Game
Chem dispenser was very silly as you could induce it indefinetly and get infinite mutagen with just 1 click, not even doing the recipe. This supplies the botanists with enough mutagen for smart botanists to make their own mutagen plant, but for more reliable and convinient mutagen they still need to bother science for an extra dispenser(or break into tech storage).

## Changelog
:cl:
add: Moved botany stuff around in some maps
add: Added box of botanical chems to each botany locker
del: Removed botanical chem dispensers from maps
/:cl:

### CODE REVIEW

**Comment by CinderWC** [comment]
I honestly really think that this is a way better change than me and Jake did with Botany as it does give Botanists a way to mutate their plants. But not overly annoyingly so with that dedicated Chem Dispenser.

I really enjoy this change

**Comment by jjpark-kb** [comment]
> ## Why It's Good For The Game
> Chem dispenser was very silly as you could induce it indefinitely and get infinite mutagen with just 1 click, not even doing the recipe. 

Inducers are required to be either researched, or traded with with engineering. It could also be an argument that botanists shouldn't know how to make chemicals such as mutagen in a chemical dispenser. 

> This supplies the botanists with enough mutagen for smart botanists to make their own mutagen plant, but for more reliable and convenient mutagen they still need to bother science for an extra dispenser(or break into tech storage).

Sure, this gives botanists mutagen round start now in limited quantity. However, it still doesn't give them diethyl, ammonia, etc. Back to the argument that botanists shouldn't know how to make those kinds of chemicals in the first place. Yes, they use the chemicals in their role, but that doesn't mean they know how to make them. Breaking into tech storage also does not seem very role-play-y, and seems quite powergame-y. Bothering others for chemicals isn't roleplay, as others have mentioned before, it is a hook for roleplay, but doesn't mean it will be roleplay...

I would prefer Owai's nerf of throwing Mutagen back into T4.

**Comment by Azarak** [comment]
@jjpark-kb You dont need inducers to induce the machine over and over again, you can disassemble the machine and switch the cells, there's a public cell charger in primary tool storage. Diethylamine and Ammonia are provided in the hacked botany vendor and if we see fit I may change the contents of the botany box to incldue them

**Comment by KathrinBailey** [comment]
People will still opt for chem dispensers because there is no reason to do things the boring tedious time-consuming way when you can dump saltpetre and ammonia onto plants. 
Also we're getting into a discussion on role knowledge versus character knowledge, role knowledge is anti-fun and anti-roleplay. If we had professions in the character creator that can be seen in examine text, maybe it'd have to check if the mob is wearing an ID or something, then we can maybe discuss making botany a medical thing, because botany can grow a ton of healing stuff.

**Pull request merged**
