### PR TITLE
Possums: The Revenge

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request
Adds possums into maint tunnels on all base maps (minus lambda and cog) and replaces Cargo's pet sloth with Poppy the Safety Possum, a possum wearing a hazard vest and hardhat

## Why It's Good For The Game
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

## Changelog
:cl:
add: Added a new animal: possums
add: Cargo now has a new pet: Poppy the Safety Possum
del: Removed cargo sloth pets in favor of Poppy
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
the possum pet looks amazing

**Comment by improvedname** [comment]
What has paperwork ever done to you

**Comment by ShadeAware** [comment]
You got merge conflicts with DeltaStation2. Also, wouldn't it make more sense to make Poppy an Engineering pet? She has all the right garb. Don't take away Cargo's pet sloth for an opossum they never asked for.

**Comment by ForrestWick** [comment]
> You got merge conflicts with DeltaStation2. Also, wouldn't it make more sense to make Poppy an Engineering pet? She has all the right garb. Don't take away Cargo's pet sloth for an opossum they never asked for.

I'll put sloths in maint or something as a seperate PR and cargo techs can drag them back if they want. As it stands, I can't see anyone being a Citrus/Paperwork apologist

**Comment by ForrestWick** [comment]
I gotta redo this shit from scratch cause Delta decided to be retarded

**Pull request closed without merging**
