### PR TITLE
Normalizes Ian

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Idea by https://github.com/Skyrat-SS13/Skyrat13/pull/2490

Nar's-ian is gone. Void corgis and exotic corgis are gone. Puppy making is also gone because it calls on the life proc every 40 seconds, with a 7 tile view, on top of 2corgi.

Might remove all the fluff clothing stuff too.

## Why It's Good For The Game

Improves code. Makes Ian very HRP.

## Changelog
:cl:
fix: Ian is no longer LRP.
/:cl:

### CODE REVIEW

**Comment by SarmentiCampbell** [comment]
Gee, Thanks Owai.

**Comment by Weblure** [comment]
Fine with me, literally none of these are even used. :o)

**Comment by Weblure** [comment]
> Gee, Thanks Owai.

>Blaming someone else for a knee-jerk salt PR in response to their legitimate PR

**Comment by BobJoga** [comment]
> > Gee, Thanks Owai.
> 
> >Blaming someone else for a knee-jerk salt PR in response to their legitimate PR
> 
> The puppy shit is too easy to abuse to lag the shit out of the server anyway, honestly. I have no qualms with merging both this and #2490
> 
> Also, please be sure to tag properly in the changelog. This is a removal or a tweak at the least, not a fix. Let's all do our part to keep PRs clear and consistent, and not a mess of mislabeled meme PRs. We need more people to participate in PR discussions, and the best way to do that is make it clear to the average player what all is being done, and not disguise a removal PR as a bugfix that'll be ignored by the average player.

This PR is provided as-is. It was made as protest with a very defined intent.

**Comment by Weblure** [comment]
> It was made as protest with a very defined intent.

I didn't know Github was a platform for protesting, and evidently, the maintainers didn't know that either. Looks like we're merging your protest.

**Comment by BobJoga** [comment]
> > It was made as protest with a very defined intent.
> 
> I didn't know Github was a platform for protesting, and evidently, the maintainers didn't know that either. Looks like we're merging your protest.

woops lol don't really care

**Comment by Seris02** [comment]
A few things:
1. This isn't a fix, **don't fucking label it as one**. If anything it should be labelled as salt.
2. Stop being so fucking obtuse and derisive.

And number three:
# Stop shitting on every idea you think is shit and not expect to get shat on in return. 
# Don't make shitty PRs that aren't in tune with the server if you don't expect those to get shat on either. 
# If you don't know what kind of content is in tune with the server, then just stop making fucking idiotic meme content. This isn't a server about memes.

**Comment by Seris02** [comment]
@BobJoga see above comment, gonna be honest and say that I'm not gonna look at any response you give because you probably won't actually gain any sort of common sense from the comment above.

**Comment by BobJoga** [comment]
> A few things:
> 
> 1. This isn't a fix, **don't fucking label it as one**. If anything it should be labelled as salt.
> 2. Stop being so fucking obtuse and derisive.
> 
> And number three:
> 
> # Stop shitting on every idea you think is shit and not expect to get shat on in return.
> # Don't make shitty PRs that aren't in tune with the server if you don't expect those to get shat on either.
> # If you don't know what kind of content is in tune with the server, then just stop making fucking idiotic meme content. This isn't a server about memes.

👍

**Comment by Azarak** [comment]
You very rarely see void Ian, so it's more of an easter egg, and isn't a meme in itself. I dont really see the need for any of this.

**Pull request closed without merging**
