### PR TITLE
Bobmed - TG Bamboomed port and skyrat adaptation

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

ports the following PRs from TG:
https://github.com/tgstation/tgstation/pull/48959
https://github.com/tgstation/tgstation/pull/49634
https://github.com/tgstation/tgstation/pull/50558
https://github.com/tgstation/tgstation/pull/51786

(There are probably a few more in there that i forgot to mention, but overall it's shit i've taken and modified from TGstation)

**My changes:**
- Limb separation (hands and feet)
- Synthetic wounds, treated with the repair surgery that Azarak did and i modified
- Cloning costs credits and biomass
- New chems and recipes (Corticosteroids, fibrin, biomeat)
- Rib and hip dislocation (treated pretty much the same as other dislocations)
- ~~First aid and robotics skills, that help with treating wounds~~ Deprecated. Citadel skill system is shit and i won't use it.
- Scars don't get affected by visibility, it's only a check if there is clothing covering them
- Character setup scar options
- Limb-based bleed suppression
- Dismemberment wounds (get applied on the parent body zone and are treated like critical slash wounds, very lethal in a very few seconds)
- Cryo cells do not cure wounds above moderate, moderate wounds take a very long time to be cured since it's only a 0.35% chance on each on_xadone() call

https://tgstation13.org/wiki/Guide_to_Wounds

**List of changes to do:**
- [x] Generally test and bugfix.
- [x] Making bleed suppression limb-based, like the bleeding is now.
- [x] Refactor all current clothing to have correctly set "wound" armor values.
- [x] Make the cloner also takes credits to clone.
- [x] Fix scars being shown through clothing.
- [x] Make scars more easily curable.
- [x] Making scars a set of character setup options
- [x] Adding synthetic wounds
- [x] Making dismemberment actually scary
- [x] Throw a bunch of useless features on top of all of this
- [x] Fix damage overlays
- [x] Bring back self-surgery

_The to-do list above does not reflect all of my amibitions for bobmed - this is just what is necessary for me to consider it acceptable to fullmerge._

**Additional info:**
I have posted a condensed guide on all of these changes on the **#bulletin-board** channel on discord. Since people have seemingly missed that, i will copypaste it to avoid confusion best i can.

- IPCs get wounds that are specific to them. The way they work varies a bit depending on wound type, but just use repair surgery for all of them.
- Cloning requires biomass and credits. Biomass can be gotten from throwing meat at the cloner and pressing the process button on the computer UI. You need 300 biomass to clone someone. Most types of meat give 50 biomass, but biomeat gives 100 biomass.
- Corticosteroids cure scars. They can be made with: 10 synthflesh, 5 ephedrine, 5 kelotane, 5 bicaridine. (12.5u)
- Fibrin treats pretty much all types of wounds, greatly reducing bleeding and maybe even curing wounds. Can be made with: 10 blood, 10 oxygen, 10 water, 10 bicaridine (20u)
- Biomeat is a more effective type of meat when filling the cloner with biomass. 3 slabs of it are enough to clone someone. A single slab can be made with: 8 blood, 10 cryoxadone, 20 synthflesh, 2 nutriment.
- Hip and rib dislocations. Can be treated with bonesetter like all other dislocations. Get a health analyzer on a patient for more info.
- Cryo cells cannot cure wounds above moderate, and moderate wounds only have a 0.35% chance on each tick to be cured. It is more effective to go for surgery or treatment.
- Dismemberment is HIGHLY lethal. When a limb gets dismembered, it applies a critical slash wound to the parent body zone - treating this wound is hard, and the patient is likely to bleed to death, but reattaching the limb will in fact cure it.
- The character setup has cosmetic scars optons, AND persistent (temporal) scars. Fancy!
- Limbs are separated. The chest is no longer bound to the groin, arms are no longer bound to hands, and legs are no longer bound to feet.
- Shotguns and other projectiles have a HIGH chance of embedding shrapnels. They CAN eventually fall off, but it deals brute damage over time and it is best to simply go to the medbay and get shrapnel removed surgically.
- To replace extremities, you can simply use the main limb on the surgery assuming the extremity is attached. This solves the issues with robotics.
- Alternatively, you can cut extremities from limbs that have been removed by simply using a sharp object on them.

### Videos and screenshots

https://youtu.be/mJwQuFe4mXY
showing off a bunch of smites

image
imcisions

image
liveleak moment (yes this is a dismembered groin)

https://discordapp.com/channels/@me/689080167787790341/736533056726368296
police brutality

image
image
miner brutality

image
image
disembowelment + blood gushing effects of disembowelment

image
blood gush onto da window

image
image
the phantom pain smite
(drops all your limbs without dropping any organs)

image
dismembering a limb gushes blood in the appropriate direction

## Why It's Good For The Game

fuck dumb boo boo ointment fixes all medicine

## Guide
Jglitch and a few other wikiboys have helped me set up this basic guide to help people out when this is testmerged!
https://skyrat13.tk/wiki/index.php/Guide_to_Wound_Tending

That should take care of *most* issues, though admittedly i could have gotten more in-depth with a lot of wounds and stuff.

## Changelog
:cl: Bob Joga, Ryll-Ryll, TG Station coders, Baystation and Paradise Station for some small stuffies
refactor: Medicine has been pretty much entirely overhauled. See PR #2575 on github for more info.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Oooh, don't be such a baby. Ribs grow back!




















_No they dont._

**Comment by BobJoga** [comment]
I think it's about ready for a testmerge.

**Comment by TheSpaghetti** [comment]
Nice, more excuses to do surgery so I can make completely unnecessary modifications to people right after fixing the thing that they needed surgery for in the first place.

**Comment by BobJoga** [comment]
Gonna keep this drafted cause i'll have to test it a bit. Don't want a disastrous testmerge.

**Comment by RatFromTheJungle** [comment]
gib plox

**Comment by Owai-Seek** [comment]
Issues I've heard of/taken notice of.

Cannot put hands/feet back on.
Literally nobody knows how to do anything because there's no documentation/recommended reading.
Nobody knows how to make biomass or -any- of the new chems. You literally need to code-dive to find them.
The amount of injuries people get is often ridiculous. With all the stacked wounds, broken bones, missing limbs, and collapsed chest cavities, it incentivises cloning -even more- than before. 

People legit just, avoid playing medical on bobmed rounds. Medical is already severely understaffed, and people don't -want- to do pain/injury roleplay. This medical system keeps people away/out of the things they want to do for an extended period of time, and honestly, it's just making people get incredibly frustrated. Medics end up quitting because they don't know what to do, or -can't- do anything. People get frustrated because they get permanently taken out of the round because they can't be treated or cloned.

**Comment by BobJoga** [comment]
> Issues I've heard of/taken notice of.
> 
> * Cannot put hands/feet back on.
> * Literally nobody knows how to do anything because ~there's no documentation/recommended reading.~ the documentation is all on the -discord- of all places, which people aren't going to know about/find.
> * Nobody knows how to make biomass or -any- of the new chems. ~You literally need to code-dive to find them.~
> * The amount of injuries people get is often ridiculous. With all the stacked wounds, broken bones, missing limbs, and collapsed chest cavities, it incentivises cloning -even more- than before.
> 
> People legit just, avoid playing medical on bobmed rounds. Medical is already severely understaffed, and people don't -want- to do pain/injury roleplay. This medical system keeps people away/out of the things they want to do for an extended period of time, and honestly, it's just making people get incredibly frustrated. Medics end up quitting because they don't know what to do, or -can't- do anything. People get frustrated because they get permanently taken out of the round because they can't be treated or cloned.
> 
> After making this post, and dredging through the arguments and complaints in all of the discord channels, I found out that a bunch of info is on #bulletin-board for whatever reason. Information like this really needs to be in the PR, and not in the middle of a discord chat nobody knows about..
> 
> Regarding cloning, and you comments on cloning.
> 
> image
> 
> Punishing the victim in these situations for security letting them die, and medical cloning them, does nothing to punish security -or- medical. Being taken out of the round for 10-20 minutes, then being cloned into a half-baked cripple resulting in even more of a round being wasted, doesn't sound fun at all. If you've -ever- tried to get a lawyer or command to do something about incompetency, you know full well that whining and bitching about it is just another waste of time on top of the 30 minutes you're already out.
> 
> Pain mechanics sound cool though because instead of beating someone to crit they'll actually feel pain and go down instead of just, going on like a robot.
> 
> TL:DR - I really wish this was just a straight port without adding all of this anti-cloner/additional limb nonsense so people could learn the basic systems first.

First off: You can put feet and hands in. I have consistently tested this, you just install robo limbs as normal but target the extremity instead. Cloning is not incentivized because it is costly, and wounds are honestly quite easily fixed most of the time even if it takes surgery. The information of this PR is on the #bulletin-board because it is actually the palce where people see changes the most, people barely access this github even to report serious bugs. About the last complaints: It is not punishing the victim, just like credits it is punishing doctors for being incompetent, they can avoid cloning most of the time and it should be a last ditch effort to revive people - it is fluffed to be painful and traumatic, mechanics should by all means convey that. If you are incompetent as a medical doctor, you suffer the consequences of it - cloning will take a hit to your salary and will piss people off since it is traumatic for their character and mechanically annoying. About this TLDR: I am sorry but this is nonsense, adding new limbs does not complicate the medical process at all, and it is a necessary step for any decent medical system.

**Comment by chefferz** [comment]
This has no place on this server. Medical is far too understaffed, and this server guised as a ""HRP"" server isn't even built to handle the influx of shit that occurs when the antags start to do damage. It has generated nothing positive at all.

Your discord quote is disgusting.

**WHAT YOU WANT DOES NOT MEAN THE SERVER WANTS THIS SHIT** _BOTTOM LINE_

**Comment by CameronWoof** [comment]
This PR should be broken up into multiple parts so that people can properly understand and critique the changes. This is already a massive overhaul with just the TG ports, but then Bob has lumped a big pile of changes and an IPC wound system on top of it. 

Clean TG port first, let people play with and learn that, then PR the additional changes so people can judge them once they have context for what the changes will do to the existing system.

**Comment by chefferz** [comment]
> 
> 
> This PR should be broken up into multiple parts so that people can properly understand and critique the changes. This is already a massive overhaul with just the TG ports, but then Bob has lumped a big pile of changes and an IPC wound system on top of it.
> 
> Clean TG port first, let people play with and learn that, then PR the additional changes so people can judge them once they have context for what the changes will do to the existing system.

It's almost like if this was modularized it would be much easier to acclimate to!

**Comment by Vynellin** [comment]
The MRP server isnt a good fit for this. There have been many many rounds showing why you either should have it tested on calm rounds. Or have it on the hrp server first so we dont have 20 dead who take longer than the round is to revive all of them.

**Comment by CaptainHooch** [comment]
I personally don't like it. I see its potential but the way this is put in as one big Test Merge file isn't good for the game, bobmed needs to be stripped down piecemeal and modularized so that the parts the community likes can be put in, and the parts nobody likes can be tweaked or tossed out. Right now the injury system is over the top, just about everything beyond a basic bruise or burn becomes life threatening, breaking bones and having crap embedded in you causing life threatening bleed injuries over every little thing is too over the top, and when rounds hit high chaos medbay will get overwhelmed to a level it will be impossible to manage and cause more round removal. Frankly its too much realism in a video game, I'd rather take gamey mechanics that allow the game to flow smoothly over injecting an amount of realism that slows down the game, overwhelms medical staff, and is from what I've seen in the ooc chat on testmerged rounds a highly unpopular system.

**Comment by Commandersand** [comment]
bobmed is god tier

medical just needs to up their skill TBH and we're usually filled on medical anyways

honestly just make any severe trauma like artery/broken bones/whatever to only proc when something does more than 30 brute damage on a single hit
and like at 50 accumulated brute to a limb gives any damage a chance to do that

**Comment by Vynellin** [comment]
also we should have a wiki for all the changes or somthing. AS well as having other ways thats not just going to medbay to deal with shit. (Irl you can easily pop your bone in place.)

**Comment by Vynellin** [comment]
also if a pre cloned person dies pelase set it to aleart medical if theres no biomass.

**Comment by BobJoga** [comment]
> This has no place on this server. Medical is far too understaffed, and this server guised as a ""HRP"" server isn't even built to handle the influx of shit that occurs when the antags start to do damage. It has generated nothing positive at all.
> 
> Your discord quote is disgusting.
> 
> **WHAT YOU WANT DOES NOT MEAN THE SERVER WANTS THIS SHIT** _BOTTOM LINE_
> 
> Fat reminder that 99% of the "Hostage Situations" I've seen are LRP bullshit of "EITHER I GET MY WAY OR I'M KILLING XXX" and then negotiations obviously go in a circle because the antag won't budge an inch and security has to act because they're spread so thin with all the other shit going on and other antags.
> 
> Also your quote " wounds are honestly quite easily fixed most of the time even if it takes surgery. "
> Except it's almost like the stations only have two surgical beds, and sometimes very little staffing to deal with the influx of issues. God fucking help a blob round where people are trying to take it down and _oh look 20 people come in with broken everything haha HRP right?_
> 
> I will say it a thousand times. This is outright a huge antag buff because it allows people to wreck shit (which on a HRP server it really should only be conflict initiated by antagonists) in such a one sided way that it's absurd. Someone's already going to counter "well you can do the same to the antag" except you're talking about a server that willingly feeds bloodsuckers and continues to coddle antagonists in a way that literally gives them green text on a silver platter.

I will not reply to you because your criticism is stupid and deconstructive. Go fuck yourself.

**Comment by BobJoga** [comment]
> This PR should be broken up into multiple parts so that people can properly understand and critique the changes. This is already a massive overhaul with just the TG ports, but then Bob has lumped a big pile of changes and an IPC wound system on top of it.
> 
> Clean TG port first, let people play with and learn that, then PR the additional changes so people can judge them once they have context for what the changes will do to the existing system.

This is the basis for a much larger project. None of these changes can exist separately because i need all of this to get the following work done, this is especially notable on the limb separation part. You simply want me to cut up this PR to get the other changes denied, which will not happen because they are integral for what i am trying to accomplish: a decent medical system.

**Comment by BobJoga** [comment]
> also we should have a wiki for all the changes or somthing. AS well as having other ways thats not just going to medbay to deal with shit. (Irl you can easily pop your bone in place.)

I am dealing with these problems and setting up a guide.

**Comment by BobJoga** [comment]
> also if a pre cloned person dies pelase set it to aleart medical if theres no biomass.

Sure.

**Comment by BobJoga** [comment]
> I personally don't like it. I see its potential but the way this is put in as one big Test Merge file isn't good for the game, bobmed needs to be stripped down piecemeal and modularized so that the parts the community likes can be put in, and the parts nobody likes can be tweaked or tossed out. Right now the injury system is over the top, just about everything beyond a basic bruise or burn becomes life threatening, breaking bones and having crap embedded in you causing life threatening bleed injuries over every little thing is too over the top, and when rounds hit high chaos medbay will get overwhelmed to a level it will be impossible to manage and cause more round removal. Frankly its too much realism in a video game, I'd rather take gamey mechanics that allow the game to flow smoothly over injecting an amount of realism that slows down the game, overwhelms medical staff, and is from what I've seen in the ooc chat on testmerged rounds a highly unpopular system.

I will say it again because these two comments state the same:
This is the basis for a much larger project. None of these changes can exist separately because i need all of this to get the following work done, this is especially notable on the limb separation part. You simply want me to cut up this PR to get the other changes denied, which will not happen because they are integral for what i am trying to accomplish: a decent medical system.

**Comment by CameronWoof** [comment]
What you're saying is that you want all of your changes put in at once because you think all of them are great ideas. We're saying that if that's actually true, breaking them up into multiple PRs shouldn't be seen as a threat to you. 

This is a _really, really big_ pile of changes and it's going to take weeks or months for all of them to shake out, be tested and understood by the community. You should start with a tgmed port as a baseline (as that is already documented and has been thoroughly tested for us by tg) and then add in whatever additional features you like one-by-one until we get a system that the community understands and has been vetted for use here.

**Comment by BobJoga** [comment]
> What you're saying is that you want all of your changes put in at once because you think all of them are great ideas. We're saying that if that's actually true, breaking them up into multiple PRs shouldn't be seen as a threat to you.
> 
> This is a _really, really big_ pile of changes and it's going to take weeks or months for all of them to shake out, be tested and understood by the community. You should start with a tgmed port as a baseline (as that is already documented and has been thoroughly tested for us by tg) and then add in whatever additional features you like one-by-one until we get a system that the community understands and has been vetted for use here.

I can ask maintainers which ideas are bad and take them out. So far they have veto'd none of it. I will not split this up because it is a ton of effort on my part, effort which is absolutely unnecessary.

**Comment by hugmeorelse** [comment]
Let's take a breather for now. While there have been productive conversations both on the Discord and this PR comment section, I sense a shitstorm brewing.

This will be re-opened some time before Bababooey Medicine is test-merged again. Relay all your concerns to Bob Joga or the maintainers and please do so civilly. We encourage our developers to block those who act rudely, while we, in turn, highly encourage our developers to listen to those that act politely and bring up complaints in a civil manner.

Also, we are recruiting more moderators who are in charge of solely moderating OOC behavior and conversations. Discord Moderators will now have the authority to moderate these discussions in Github as well.

**Comment by BobJoga** [comment]
I will reopen this PR and continue my work, but if the issues i've faced during all of these persist, i am not afraid to kill this project for real.

**Comment by BobJoga** [comment]
I am not solving these merge conflicts because Citadel is too fucking slow. No.

**Comment by BobJoga** [comment]
Closed until i can find a way to fix the bullshit cit did.

**Comment by BobJoga** [comment]
image

PR's closed

**Comment by BobJoga** [comment]
flowey-export3

**Comment by BobJoga** [comment]
i am so fucking tired

**Comment by Ryll-Ryll** [comment]
This is probably the single most ambitious crossover event I've ever seen, 657 changed files golly. I love a lot of the ideas you're adding into the mix and may steal some back for the /tg/ version of wounds but you might wanna stagger all those changes over a few PRs. The original 2 wounds PRs on /tg/ were around 250 and 150 files changed and even then they were a mess to review

**Comment by BobJoga** [comment]
> This is probably the single most ambitious crossover event I've ever seen, 657 changed files golly. I love a lot of the ideas you're adding into the mix and may steal some back for the /tg/ version of wounds but you might wanna stagger all those changes over a few PRs. The original 2 wounds PRs on /tg/ were around 250 and 150 files changed and even then they were a mess to review

Holy shit, the god himself has commented on my mess of his work. I would split this up into various PRs but at this point slashing the PR into various bits and pieces is too much effort, honestly not worth it - What i'll do is simply keep maintaining this and waiting for testmerges, but nothing new will be added featurewise, just bugfixing and QoL. But yeah i probably shouldn't have gone this ambitious right away...

**Comment by Owai-Seek** [comment]
We don't really need unrelated changes being put in on this already bloated PR.

Changing it so it requires an account ID to access the money has nothing to do with medical.

**Comment by BobJoga** [comment]
> We don't really need unrelated changes being put in on this already bloated PR.
> 
> Changing it so it requires an account ID to access the money has nothing to do with medical.
> 
> [9c6eddd](https://github.com/Skyrat-SS13/Skyrat13/commit/9c6eddd410b25cf4f4fd6c87f597aca19a8a61ba)

It does and people would complain about their account being drained by doctors otherwise.

**Comment by Ryll-Ryll** [comment]
I hate to be the one to say this but 678 files is like, 1/6th of the files in your entire codebase. I know that it's easy to get swept away with one feature merging into another, into another, into another (I eventually had to hard-limit myself with my original PR's when I hit around 200 files, and 150 for wounds 2), but there's a loooooot of tg structural code that you're porting on the side I saw like shrapnel and bullet embedding, as well as a lot of significant rewrites of your own, and the truth is that this PR is a basically a time bomb at this point. 

In the short term, having this many changes will make it impossible to thoroughly review, let alone test, all of the changes to make sure they're functional and mesh together smoothly (notice all of the wound fixes PRs I've already made on tg), as well as being a total pivot to your server's medical system that everyone is going to have to learn all at once. While the original wounds PR definitely had its splashes and moments of confusion where people had to relearn how to do things, it also benefited from a more gradual implementation where people could get used to the basic parts of the system, then more advanced stuff came later once there was a decent amount of general knowledge for how stuff worked. Worst came to worst, people could still codedive through the PR to see how things worked themselves, but even trying to load all of the files you've changed takes a few tries for github to not time out loading it all.

There's another bigger issue in the long run is that changing such a massive portion of your codebase will probably kill any chance of you staying a smooth downstream from citadel, because you're going to be running into merge conflicts and differing mechanics nigh constantly. I can't speak about the experience of coding for a downstream codebase, but again, this is practically 1/6th of your entire codebase, focused on many of the most high traffic files.

There's a lot of awesome and really cool ideas in here, some of which I'm very interested in stealing and backporting to tg, but at some point there's gonna be a question of how you're actually going to get this stuff merged, and there's a very real chance that your maintainer team (or whoever handles reviews and merging) is going to hem and haw at this and have serious, serious reservations about pulling that trigger. For your own sake, I seriously recommend you cut your losses now and start trying to carve this into more manageable chunks, cause otherwise you risk the entire thing rotting and going stale.

**Comment by BobJoga** [comment]
@Ryll-Ryll I get where you're coming from and this PR is a big nightmare for maintainers to work with, but if i have to cut my losses and start creating new PRs to chop this into parts, i've already lost my hard work and will have to do it like 3 times over. If i have to cut this PR up, i am simply surrendering and not doing this, because it is not worth the effort, and i'd rather work on something - anything - else. This is a big PR because i wanted to unfuck something that was for a long time disastrous, old medicine is unfun, boring and for me it's simply put unplayable. To finish this off: I don't think we benefit from staying a downstream of cit, we simply don't. If this PR means we have to cut off from the chains, at this point that is fine with me - i don't like Citadel and 90% of their changes only bring me annoyance. In short: If the maintainers are not willing to merge this version, i will not suffer through making other ones, i'd rather work on something else.

**Comment by Owai-Seek** [comment]
Can we stop adding more and more disincentives to cloning and focus on bugfixing and proper balance?

-Cloning already costs biomass.
-People take clone damage from cloning.
-People get brain damage and traumas from low-tier cloning.
-People get mutations from cloning.
-While waiting for cloning, people are stuck in ghost chat out of the round, which includes the time they were left dead.

image

Now you're stacking even more on top of things, which make the stressful job medical has -EVEN MORE UNFUN to deal with.

People complained about the money mechanic, and it got removed, now you're just adding more on top of it to make people frustrated again.

It's infinity more stressful (and gross to me) to literally stitch an entire corpse back together, than it is to save them the suffering of cloning them. We have DNR and DNC traits for a reason, those already serve the purpose of stopping people from cloning (or reviving) a body when they personally don't wish to come back that way.

**Comment by BobJoga** [comment]
> Can we stop adding more and more disincentives to cloning and focus on bugfixing and proper balance?
> 
> -Cloning already costs biomass.
> -You require a specific ID type/access to clone.
> -People take clone damage from cloning.
> -People get brain damage and traumas from low-tier cloning.
> -People get mutations from cloning.
> -While waiting for cloning, people are stuck in ghost chat out of the round, which includes the time they were left dead.
> 
> image
> 
> Now you're stacking even more on top of things, which make the stressful job medical has -EVEN MORE UNFUN- to deal with.
> 
> People complained about the money mechanic, and it got removed, now you're just adding more on top of it to make people frustrated again.
> 
> It's infinity more stressful (and gross to me) to literally stitch an entire corpse back together, than it is to save them the suffering of cloning them. We have DNR and DNC traits for a reason, those already serve the purpose of stopping people from cloning (or reviving) a body when they personally don't wish to come back that way.

The money mechanic removal was Xyel's order, otherwise i would have kept it.

**Comment by BobJoga** [comment]
> I'd suggest removing the advanced sutures and mesh from medkits. Those are currently something extra that botany and chemistry can work together to make; making them available in fairly large amounts roundstart kind of ruins that teamwork activity.

I have only added one for each specialized medkit. They are still in relatively short supply.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
