### PR TITLE
realistic transgender mechanics 

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

females (penis) have a 40% chance to kill themselves

## Why It's Good For The Game

very high roleplay feature

## Changelog
:cl:
add: trans people now kill themselves sometimes
/:cl:

### CODE REVIEW

**Comment by glarfle** [comment]
I know this is going to get immediately deleted, but for legal reasons, this is totally not funny or based, and should be removed.

**Comment by FargothUr** [comment]
this is funny as fuck what do you mean!?

**Comment by BobJoga** [comment]
why did this pr get closed this is actually very hrp

**Comment by ForrestWick** [comment]
Bruh go outside

**Comment by FargothUr** [comment]
im CRYING and SHAKING this CANNOT be happening!

WHY WOULD A HRP SERVER LIKE SKYRAT DENY SUCH A REALISTIC PR!?

**Comment by ShadeAware** [comment]
cringe

**Comment by BobJoga** [comment]
image

**Comment by FargothUr** [comment]
based PR this will make the gameplay for skyrat THAT much better, now I can actually erp without being tricked by PENUS LOLEEEE

**Comment by glarfle** [comment]
> based PR this will make the gameplay for skyrat THAT much better, now I can actually erp without being tricked by PENUS LOLEEEE

Okay yeah real talk people who unironically trap you when you try to erp are actual scum

**Comment by Tupinambis** [comment]
See a psychiatrist.

**Comment by BobJoga** [comment]
> See a psychiatrist.

hey at least i dont think im a woman

**Comment by chefferz** [comment]
Just report this to github , in detail, please. 

https://github.com/contact/report-content?content_url=https%3A%2F%2Fgithub.com%2FSkyrat-SS13%2FSkyrat13%2Fpull%2F3642&report=BobJoga+%28user%29

**Comment by BobJoga** [comment]
> Just report this to github , in detail, please.
> 
> https://github.com/contact/report-content?content_url=https%3A%2F%2Fgithub.com%2FSkyrat-SS13%2FSkyrat13%2Fpull%2F3642&report=BobJoga+%28user%29

thats so fucking petty lmao

**Comment by BobJoga** [comment]
> Just report this to github , in detail, please.
> 
> https://github.com/contact/report-content?content_url=https%3A%2F%2Fgithub.com%2FSkyrat-SS13%2FSkyrat13%2Fpull%2F3642&report=BobJoga+%28user%29

image

**Comment by ThatGuyFromThatPlace** [comment]
Okay, so, aside from this obviously being a troll PR just to piss sensitive people off:
In a future where you can literally get a small machine to **instantly** add genitals, and, can even turn into a monkey by placing yourself in a machine for under 30 seconds, I don't exactly think there would be as much of a mental toll on people if they can literally at the drop of a hat completely alter their body fully to whatever gender they feel like.

Also, this doesn't take synths/robots _like my character_ into account, who, just have the parts because people wanted them to have them, and, a robot/synth literally wouldn't ever have any possible reason to have any sort of issues like this

All-in-all, low effort and doesn't take into account the futuristic setting of SS13
This would be like making your character want to off themselves for having augmentations in Cyberpunk

**Comment by FargothUr** [comment]
>troll PR
>comments seriously on it
LMAO

**Pull request closed without merging**
