### PR TITLE
[Map Edit: Meta] HoS Announcement Console(?)

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

HoS was missing this.

## Why It's Good For The Game

HoS should be able to have this.

## Changelog
:cl:
add: Added HoS announcement console(?)
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
small map fix, wasnt merged.

**Comment by SquishyOranges** [comment]
Why would the HoS need an announcement console? They can already use the little wall thingy for announcements.

**Comment by jjpark-kb** [comment]
> Why would the HoS need an announcement console? They can already use the little wall thingy for announcements.

Thats what it is... This is a fix for it, it puts back the thing that they USED to have.

**Pull request closed without merging**
