### PR TITLE
DeathSquad name changes (pretty sure I did it right)

### PR DESCRIPTION
**Pull request by DexterDude**
## About The Pull Request

Uhhh. Adds a bunch of deathsquad names that are highly ambiguous to race and whatever. Also not meme names. All based on a photenic alphabet and random numbers. Pretty...sure I did this right.

## Why It's Good For The Game

Obviously the very serious and very rare deathsquad needs to be very serious in this very serious server, yes? Also fuck that DAMN meatball GEORGE MELONS.

## Changelog
:cl:
code: Changed it so that deathsquad names are very serious.
/:cl:

### CODE REVIEW

**Comment by BobJogaIsForkinBanned** [comment]
I still think DS should have actual names, because everyone having numbers and shit will really make it harder to communicate. But that's my two cents.

**Comment by Commandersand** [comment]
please don't remove the goofiness of ss13

**Comment by Useroth** [comment]
I'll leave it up to discussion and possible modification for now. Someone should probably leave to emojicracy or something

**Comment by DexterDude** [comment]
Honestly have no clue how I fucked it up somehow.

**Comment by Investigator77** [comment]
This really isn't that good. Nobody would ever call their ground units by (NATO Phonetic Alphabet letter).(###). It's dummy impractical and just doesn't work. You should instead change it to be actual surnames of varying nationality/ethnicity or simple nicknames like "Baker", "Firestorm" or something else. I'd rather refer to "Trooper Jones" or "Officer Stargazer" than just "Alpha.238"

**Comment by Useroth** [comment]
We'll probably have an alternative PR for it, sometime.

**Pull request closed without merging**
