### PR TITLE
Contractor reroll limit back in.

### PR DESCRIPTION
**Pull request by IrkallaEpsilon**
## About The Pull Request

Reroll in

## Why It's Good For The Game

https://cdn.discordapp.com/attachments/481643171798056960/757770996542341130/Well.jpg

^This is bad.

## Changelog
:cl:
tweak: Reroll limit at 3 which is more reasonable than infinite. Since infinite is not a number but 3 is and is a limit that can be reached.
/:cl:

### CODE REVIEW

**Comment by Yawet330** [comment]
fuck SEEK for getting this added back

**Comment by RemervKeberb** [comment]
Thing is, the infinite rerolls kinda balanced itself out because the more you rerolled the worse your contract payout became. Seek only got 6 tc for that contract after all those rolls and that's because he was lucky, usually it's around 4-2 TC at that point when you can get like 17 from one of the starting ones.

**Comment by IrkallaEpsilon** [comment]
Wait that a thing?

**Comment by IrkallaEpsilon** [comment]
Yeah Kebirb got a point here. Theres diminsihing return. 

Also nobody said it was SEEK Yawet thats just rude and I send you a sad Irsil on discord for that.

**Pull request closed without merging**
