### PR TITLE
[Testmerge] Dynamic client-side processed lighting on a component

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
This PR adds an overlay lightning component, which is a substitute for lighting. What it does is it applies a mask as close to what a real lighting would look like, the mask simulates lit behaviour by adding the right luminosity to its parent aswell as adding lumcounts to turfs caught in the luminosity. The mask is processed client-side through plane master and a filter to look nicely. With this lighting following projectiles is instant too and looks amazing! 

This will result in MASSIVE performance upgrade

## Changelog
:cl:
add: Added dynamic lightning for all things considered to be moving often
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Does this mean no more choppy lighting that doesn't follow me around properly? If so, major buff to Nyctophobes :eyes:

**Comment by Azarak** [comment]
Yes no more laggy lights

**Comment by Cyprex** [comment]
Could you post a video of this in action?

**Comment by Timberpoes** [comment]
Rohesie's port of this to /tg/ combined with my investigation into a an overlay bug that it introduced has revealed that your modular_skyrat/icons/misc/light_256.dmi has an image dimensions 352x352px instead of the expected 256x256px.

This would, naturally, cause a bit of weird behaviour when calculating offsets to center the overlays (and in the overlay size in general, which is a number of tiles too large in range)

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
