### PR TITLE
Otieborgs & Engihounds!

### PR DESCRIPTION
**Pull request by Strazyplus**
## About The Pull Request

**Partial port from Vorestation https://github.com/VOREStation/VOREStation/pull/8575
Otieborgs created by: https://github.com/Verkister**
**@Strazyplus had no involvement of the creation of the chonk Otieborgs or the engihounds** (i just ported)

(I **wanted** to port those tweaks and clutter removal but I am a bad coder.)

89124266-514c3b00-d4de-11ea-8539-1261bee86b80
wewww

Adds the chonk Otie Security and Janitor borgs as well Engihound variants, improves/adds all missing hound wreck animations

## Why It's Good For The Game

More choices of borgos to play as....  This is for you @BobJoga 

## Changelog
:cl:
add: Added Otieborgs! (made by @Verkister ) 
add: Added Engihounds!
fix: fixed hound wreck animations!
imageadd: added Otie Janitor & Otie Security
imageadd: added Engihounds
/:cl:

(go send some hearts at original pr)

### CODE REVIEW

**Comment by Echopsychotic** [comment]
Finally borgs from vore station.5

**Comment by BobJoga** [comment]
I mean i hate dogborgs in general but whatever, not like i can remove them. Good PR.

**Comment by SarmentiCampbell** [comment]
Imagine not liking this chunky fella

**Comment by hugmeorelse** [comment]
Buff dogborgs when? 🗡️

**Comment by hugmeorelse** [comment]
Manly, buff dogborgs when? 🗡️

**Pull request merged**
