### PR TITLE
Virology shuffle, atomized

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Uplifted the limit of diseases on a person from 1 to  3, but made it so you can't stack the same symptoms with different diseases. One of the symptoms just gets neutered when stacked.
Eternal Youth symptom now actually makes you become younger over time. **It doesn't make you ever go below 18 years old, nor does it affect examine.**
Added flesh melting symptom, which will melt your flesh until you turn into a variation of skeleton depending on the resistance of the disease. Highest possible tier is space resistant skeleton, lowest is having your flesh fall off constantly which causes brute damage.
Tweaked old radiation healing symptom into gamma healing symptom, which basically heals you depending on how much radiation you have in your body (does not make you immune to the effects of radiation, stacks up with the amount of radiation you have indefinitely).
Added radiation healing symptom, which heals your radiation away.
Added damage converter symptom, which slowly converts brute and burn damage into toxin damage.
Reshuffled and rebalanced some values around.

## Why It's Good For The Game

REJECT NANITES, RETURN TO VIROLOGY

## Changelog
:cl: Bob Joga, Paradise Station for the damage conversion symptom idea
tweak: Diseases are no longer capped at one per person, instead it's 3.
tweak: Eternal youth symptom now actually lowers your age over time.
balance: You cannot stack symptoms in virology anymore with different diseases that have the same symptoms.
balance: Shuffled around some stats on some virology symptoms
balance: Old radiation healing is now called gamma healing and really stacks up with the amount of rads you have
add: Added flesh melting symptom to virology
add: Added radiation healing symptom to virology (as in it heals radiation)
add: Added damage conversion symptom to virology
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Based and Bobpilled Virology semi-rework

**Comment by YakumoChen** [comment]
ah yes I would like to return to a time where viro could outheal literal changelings please readd that.

**Comment by BobJoga** [comment]
> ah yes I would like to return to a time where viro could outheal literal changelings please readd that.
> /s

image

**Comment by Yawet330** [comment]
> ah yes I would like to return to a time where viro could outheal literal changelings please readd that.
> /s

hahahahaha this is before changeling fleshmend got nerfed to barely heal over 15 damage.
(even regen coma is better than it now)

**Pull request closed without merging**
