### PR TITLE
[FUCK] Lavaland Eternal Part 2: Ultra Nightmare

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request
image

### Hell on station

This is a continuation of lavaland eternal, but now the focus is kneecapping miners to the ground to make them squeal and scream in pain. This pretty much buffs a fuckton of fauna and nerfs some very important stuff, but it does add new loot. This PR is nothing but pure evil.

### Buffs

A lot of elite loot has been stat buffed.

Added GPS to the vendor. Cost 500 points each.

Medikits in the vendor now cost 750 points instead of 800.

Sif sword now does 22 damage instead of 20.

All megafauna now drop ultra argent cells, which are as powerful as a bluespace cell, can be crushed to deal the damage resistance status effect for 2 full minutes, and selfcharge slightly faster than normal argent cells.

Argent cells now recharge slightly faster (700 to 750 charge rate).

Screeching crates (gotten from legion and strong tendrils) can now drop 100% genuine 40 damage katanas.

Rogue process has been fixed, his fight is difficult but not completely broken, and his attacks are properly telegraphed.

Adds a temporary berserk martial art to replace the mayhem in a bottle. The martial art is extremely powerful in melee but effective worthless at range. Only works for two minutes, then it is gone.

Normal bubblegum can now drop the super shotgun as loot.

Adds distilled dragon's blood. Essentially just dragon's blood without RNG, you select your reward. Can only be gained through enraged drake.

Adds amulet of kings. Essentially just a fancy memento mori, does nothing that the memento does not. Gained from enraged drake. Looks cool.

Super shotgun hook is slightly faster at transporting you to your target and stuns them for half a second.

### Kind of buffs

Added super organs as a possible outcome of both normal dragon blood and distilled dragon blood. Essentially lungs that let you breathe anywhere and a heart that ocasionally injects epinephrine in you if you're in crit. This is a "kind of" since it dilutes the rng pool for normal dragon's blood.

Colossus now drops eyes of god and memento mori as loot, and memento mori has been buffed so it won't dust you... the cost was removing them from the necropolis chest loot pool.

Hierophant now drops a tarot guardian creator... at the cost of removing it from tendril chests.

#### Equipment

Many megafauna modkits have had their costs upped.

Shotgun modkit for the PKA now has a -20 damage penalty. Still shoots 3 shots.

Legion cores now take time to apply.

Legion cores are no longer an aheal. They heal a minor amount of damage instantaneously (about 10 for brute, burn, and toxin), give 50 nutrition instantaneously, add 30 units of miner salve instantaneously, add 10u of coffee instantaneously, add 10u of nicotine instantaneously, but their full heal effect goes over the duration of 10 seconds. It should get the miner to about 40 health healed for every damage type (accounting for initial healing and overtime healing, not salve healing since that shit is slow and ineffective). They also inject 10 epinephrine but only if you're in crit. Using a legion core while the effect is ongoing simply refreshes the timer for regeneration, none of the initial effects apply.

Explorer suit now starts with 20 melee protection. Maximum is 50.
Exosuit now starts with 45 melee protection.
Seva suit starts with 10 melee and can now only attach two goliath plates, thus maximum 20 melee.

Miners no longer spawn with a suit voucher.

**Vendor bullshit:**
Marker beacon now costs 25 points.
10 marker beacons now cost 200 points.
30 marker beacons now cost 500 points.
Fulton beacon now costs 500 points.
Shelter capsule now costs 750 points.
Normal PKA, Crusher, wormhole jaunter, tracker implant, survival knife now cost 800 points.
Survival pen, explorer webbing and advanced scanner now cost 1000 points.
Stabilizing serum now costs 1250 points.
Conscript bag now costs 1500 points.
Diamond pickaxe now costs 2500 points.
Suit voucher now costs 3000 points.
Dashing boots now cost 3000 points.
Mining suit and jetpack upgrade cost 3000 points.
Luxury capsule now costs 5000 points.
Full replacement bag now costs 5000 points.
Premium KA now costs 10000 points.
Luxury bar capsule now costs 15000 points.
Premium crusher now costs 15000 points.
Mining point cards now all cost more than they're worth because inflation.

#### General mob behavior

Enraged bubblegum is now slightly faster on his movespeed, and now he always rages on blood warps (becomes red and mean and immune to many attacks). He also spawns slaughterlings now :)

Normal bubblegum now spawns slaughterlings again. Yes, along with blood smacks.

The gladiator zwei spin now stuns you.

Replaced the spellblade with the crucible completely, simply put the spellblade has no balance checks at all - it delimbs without any checks for armor, on top of being ranged and autocharging and deflecting 50% of all attacks.

Candy no longer gives pure bloodcrawl as loot. You get a nerfed version instead - this nerfed version requires large pools of blood to be cast, and will take away 10% of your maximum blood volume whenever you enter a pool of blood.

Blood drunk miner now has 1250 health, and his saw does full damage (it did diminished damage when compared to a human wielding it before).

All elites now have 1200 health.

Goliaths now try to tentacle you even in melee.

Watchers now shoot at you even in melee, although they now avoid melee and just keep giving suppressing fire.

Legions now heal health over time.

Shambling miners can now score critical hits on you (5% chance), which do 20 + 25 damage.

Shambling miner crusher drop rate is now 5% instead of 15%.

Imp projectiles now penetrate 50% of armor.

Miner priest dash can now ram into targets and deal damage. His axe slam attack is not directional anymore and allows for weird lines.

Legionnaire charge is no longer directional, allows for weird lines too.

All tendrils now have 350 integrity (compared to 250) and are thus harder to destroy, and if you're unlucky there is a 20% chance on initialization for a tendril to become a **strong** tendril, which will have double the normal integrity and have a doubled mob spawn cap. These tendrils however, do give better loot.

Attacking a tendril now alerts all nearby lavaland mobs (7 tile range) to attack you.

#### Scarring

All fauna (excluding megas) can get "scarred'. Scarred is simply when the fauna gets too damaged, and is therefore determined to fight for it's life. The threshold for scarring fauna is 0.3x their maxhealth - every one of them at that point will receive quite a big buff, how that buff works depends on the mob.

**Elites:**
Pretty much all of them get lessened attack cooldowns.

**Goliath:**
Starts running away from you, tentacles more often, does more melee damage.

**Watcher:**
More melee damage, lesser cooldown on their freezing beams.

**Legion:**
Health regeneration is doubled.

**Shambling miner:**
Higher chance to score a critical hit, higher "dodge" chance.

**Imp:**
Projectiles do more damage and fire stacking, 100% penetrates armor.

## Why It's Good For The Game

The people asked for garbage. The people receive garbage.

## Changelog
:cl:
balance: Mining is now an unfun nightmare.
/:cl:

### CODE REVIEW

**Comment by CoreFlare** [comment]
The only change that as a miner main I disapprove of is legion cores taking time to apply. Otherwise, I fully approve of this PR.

**Comment by BobJoga** [comment]
> The only change that as a miner main I disapprove of is legion cores taking time to apply. Otherwise, I fully approve of this PR.

Yeah too bad.

**Comment by CoreFlare** [comment]
How long will be the timer for legion cores, anyway? 1 - 3 seconds would seem fair to me if you're doing it at all.

**Comment by BobJoga** [comment]
> How long will be the timer for legion cores, anyway? 1 - 3 seconds would seem fair to me if you're doing it at all.

I'm gonna put it to 4 seconds on self application just to piss everyone off. On other people it's 1 second.

**Comment by KasparoVy** [comment]
Dope art.

**Comment by hugmeorelse** [comment]
> > How long will be the timer for legion cores, anyway? 1 - 3 seconds would seem fair to me if you're doing it at all.
> 
> I'm gonna put it to 4 seconds on self application just to piss everyone off. On other people it's 1 second.

Bob. Really?

**Comment by BobJoga** [comment]
Lowered application time on self to 1 second.

**Comment by CoreFlare** [comment]
Now I approve of everything in this PR. S🅱️eedomergo

**Comment by CoreFlare** [comment]
I mean I am not a holy grail of balance but I just personally think the PR is good.

**Comment by YakumoChen** [comment]
kinda disagree on giving the megafauna more loot (especially colossus as he's very easy to cheese) but eh, guess I'll just have free xray night vision and a guardian every round now.

**Comment by BobJoga** [comment]
> kinda disagree on giving the megafauna more loot (especially colossus as he's very easy to cheese) but eh, guess I'll just have free xray night vision and a guardian every round now.

It's more effort than being granted from RNGesus. But sure ignore how much i completely kneecapped  mining here.

**Comment by YakumoChen** [comment]
> 
> 
> > kinda disagree on giving the megafauna more loot (especially colossus as he's very easy to cheese) but eh, guess I'll just have free xray night vision and a guardian every round now.
> 
> It's more effort than being granted from RNGesus. But sure ignore how much i completely kneecapped mining here.

Sure, but nerfs won't stop experienced miners very much.

**Comment by BobJoga** [comment]
> > > kinda disagree on giving the megafauna more loot (especially colossus as he's very easy to cheese) but eh, guess I'll just have free xray night vision and a guardian every round now.
> > 
> > 
> > It's more effort than being granted from RNGesus. But sure ignore how much i completely kneecapped mining here.
> 
> Sure, but nerfs won't stop experienced miners very much.

Let's see then. Coming from an experienced miner, this nerf is very much hell and i was barely able to defeat BDM, but sure i guess you're right all miners are autistic speedrunners and wouldn't mind kaizo lavaland at all.

**Comment by BobJoga** [comment]
Will make a PR without stupid nerfs.

**Pull request closed without merging**
