### PR TITLE
[READY] EVA access for engineers and paramedics.

### PR DESCRIPTION
**Pull request by CoreFlare**
## About The Pull Request

This gives engineers and paramedics access to EVA storage roundstart as part of their basic access set.

## Why It's Good For The Game

The emojiocracy vote was heavily in favour of these changes. Plus, engineers really should've had this in the first place.

## Changelog
:cl:
tweak: Engineers now have EVA access.
add: Paramedics now have EVA access.
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
EVA in general should really have it's door perms changed. it's only a command area because in ye olden days of TG station, magboots and jetpacks AND RCDs were theft objective items. These were before magboots and RCDs were printable from techfabs and when jetpacks were insanely fucking rare.

**Comment by Owai-Seek** [comment]
If this gets merged it'll have to be watched to make sure people aren't abusing free EVA access. A lot of people don't put shit back, and end up hiding things in their personal lockers, ERP dens, or just throw it wherever the fuck they want because they get sick of the slowdown.

EVA is generally supposed to be used for emergencies, and while I do think engineering should have access to it, I'm not so sure for paramedics. Preferably, I think a recon hardsuit with built in tracking or GPS placed in medical would be a nice thing for paramedics to have.

Also, to note, it was heavily in favor for engineers, not so much paramedics. (83% of voters said yes to the engineering section of the vote.) ~47.3% of Disagreed with (on some level) to give EVA access for paramedics.

Paramedic EVA: 148 Votes
78 (52.7%) In Favor
57 (38.51%) Hardsuit Only
13 (8.78%) Said No

I think giving EVA to engineers is fine, but perhaps paramedics should get a second look, or have a balance decision done by maintainers.

**Comment by ShadeAware** [comment]
Engineers have their own hardsuits, whereas Paramedics get jack shit despite the fact that they're the ones who are usually going to have to go out into space because someone thought fists beat carp.

**Comment by Owai-Seek** [comment]
While I think they should get something, I don't think giving them access to the very limited emergency EVA suits is the best solution, especially when EVA suits tend to get abandoned (or stolen). I feel like giving paramedics access to them will only encourage them to grab them round start and hoard them in medical, rather than using them for their intended emergency-only purposes.

There are alternate solutions available, one of which could just be updating medical lockers to contain spaceworthy suits. This would give medical ~3 roundstart space suits. (Two in the Medical Lockers, one in the CMO office.)

As a note, paramedics do have ways to get spaceworthy gear already. There tend to be borgs, (most of the time) which a paramedic could ask for assistance, gaining entry to the CMO office and locker for the medical hardsuit contained within (Or just, asking the CMO, if they're available.) You can also order medical hardsuits from cargo directly.

**Comment by SiliconMain** [comment]
Paramedic2
there is another option

**Comment by Weblure** [comment]
It'd be much more preferable to give medbay its own hardsuits. EVA is a limited resource and paramedics aren't going to wanna run back and forth between medbay and EVA every time they have to save someone who got spaced. They're more than likely just gonna toss the suit in medbay somewhere. 

There's also no good way of tracking who took what suit when multiple departments have access to them. May as well just give them their own suit that they're in charge of keeping track of, like every other department has to do. Also, imagine having pretty, blue hardsuits.

**Comment by Azarak** [comment]
Engineering has EVA in their own department
Paramedics arent nessecarily trained in EVA operations
Corpse recovery should be delegated from doctors onto people with EVA access and training
and if a doctor deems themselves space worthy he can always as HoP for EVA access.

If you wound up dead in space chances are something went terribly wrong, your recovery shouldnt be as simple as all designated recovery mans getting all the means to get you quickly, just cause.
Making the game easier doesnt make it fun, neither does it encourage RP or interactions between people.

**Comment by CoreFlare** [comment]
Hold up.

I can understand paramedics, but engineers? They should've had this in the first place. It simply doesn't make sense to me why the people who go into space don't have base access to the space suits. You only get 2 engineering hardsuits, which, for all intents and purposes, isn't enough. There are always going to be more than 2 engineers with the pop we've been getting recently and they're going to want to be able to not die when they're trying to repair things.

I suggest either giving them EVA, or giving them more suits, because the emojiocracy vote was 10 to 2 in favour of giving engineers EVA access.

**Pull request closed without merging**
