### PR TITLE
Syndicate stole paperwork crate

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Puts the paperwork crate behind an emag, due to syndicate stealing it.
This was done because several individuals would keep spamming that crate over and over and then making 100 topic calls per minute to maximize profits on it, which was super lame and could make the other cargo techs feel like they're insignificant when it comes to bringing in profits.

## Why It's Good For The Game
Cookie clicker gameplay bad

## Changelog
:cl:
tweak: put the paperwork crate behind an emag
/:cl:

### CODE REVIEW

**Comment by Useroth** [comment]
Lmao. Should probably just reduce the profits from it or something.

**Comment by CinderWC** [comment]
Yes, i am one of the main people who was pissed over specific people spamming these crates to maxify profits for little to no effort. But i believe that we should nerf, rather than remove the paperwork crate entirely

**Comment by Ghommie** [comment]
Feel free to PR a removal on the upstream anytime, I don't like those either. :joy:

**Comment by BobJoga** [comment]
why isn't this merged already

**Comment by Useroth** [comment]
Also, they've been nerfed upstream.

**Pull request closed without merging**
