### PR TITLE
Reskinning: Renewed

### PR DESCRIPTION
**Pull request by BobJogaIsForkinBanned**
## About The Pull Request

Adds a BUNCH of reskins, makes item icons consistent all around, refactors the reskin proc to be better and to accomodate the recent changes.
And here's the real kicker of it all:
**Most reskinnable objects now need a "General Modification Kit", found at the clothesmate, to be reskinned and can only be reskinned once.**
Also, better ninja sprites courtesy of JungleRat.

## Why It's Good For The Game

1. Code consistency
2. More RP friendly reskins

## Changelog
:cl: BobJoga, Investigator77 and Junglerat
refactor: Reskin proc is now accomodated to recent changes, and much better overall.
refactor: More consistency in icons and icon_states all around.
add: New "General Modification Kit", which is required for most reskinning.
imageadd: Many, many, many new reskins.
imageadd: Spider clan members now resemble actual spiders.
del: Removed herobrine.
/:cl:

### CODE REVIEW

**Comment by Investigator77** [comment]
SolFed Contractor mercenaries for a security team. poggers.

**Comment by RatFromTheJungle** [comment]
finally, a good PR

**Comment by CinderWC** [comment]
Please test it. I'm begging you

**Comment by BobJogaIsForkinBanned** [comment]
> Please test it. I'm begging you

I'll test it. In fact, lemme mark this as draft.

**Comment by BobJogaIsForkinBanned** [comment]
Tested and working well. Ready to be merged.

**Pull request merged**
