### PR TITLE
Tile Floofing: Allows you to change what type of titanium and what type of plasteel types you place.

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
Modularises titanium turf icons and adds a shift-click function for titanium tiles, allowing you to change what type of titanium tile you place. You can also click on flooring with plasteel to change which tile is considered the "default" tile in memory. If you crowbar a white tile in medical, placing a plasteel tile in medical will always make that tile white. This function is nice, but it means you can't change the tile at all. That tile will always be white if you use plasteel. If you attack any turf that's a child of plasteel with a stack of plasteel tiles, you can change the tile. You can make medical full of dark tiles, security full of grimy tiles. Plasteel tiles act as a 'tile painter'.
Also ports TG 80s carpet.

## Why It's Good For The Game
Allows the few good engineers more freedom to make beautiful builds. A lot of very common tile types cannot be built in-game, this PR allows you to build a fair few of them.
Allows users to pick which titanium tiles they want to use. Do you want the sleek TG aesthetic? It's up to you. Want the tile aesthetic that's fun for bathrooms? Up to you. You can decide this **in-game**. Oh, you want to make a new medical? You want those white tiles in your new medical? That was impossible, outside of admin intervention , to do in-game. Now you can have your white tiles!

## Changelog
:cl:
add: New Titanium icons from https://github.com/tgstation/tgstation/pull/50454 ported.
add: New carpet from TG, 'eighties' carpet. Currently requires an admin to spawn. Ask in-game!
add: Shift-click titanium tiles to change what tile it places.
add: You can 'paint' plasteel flooring and their subtypes by clicking on them with a plasteel tile.
/:cl:

## Media
image
image

### CODE REVIEW

**Comment by ShadeAware** [comment]
Yoooooo this looks nice
Minor suggestion! What about being able to produce that circuit tile that you see around? The blue/green stuff?

**Comment by KathrinBailey** [comment]
image
**You can't make any of these floors in-game, this PR lets you. Good heck.**

**Comment by Gandalf2k15** [comment]
nice shuttle :3

**Review by Gandalf2k15 — APPROVED** [review]
If i got a dollar for every if statement I'd be slightly less poor

**Pull request merged**
