### PR TITLE
Meme name removal because we're MRP-HRP.

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
Removes Deathsquad meme names and replaces them with forty new names.
The names are:
Prefix: Agent
Great War British phonetics (Able, Easy, Dog, Yoke etc)
Cities (Ravenna, Damascus, York, Marseille etc)
Moons (Hallimede, Ceres, Tethys, Ganymede etc)

The prefix can be changed, some options for the prefix:
• Agent
• NT Officer
• Corporate Officer
• Asset Protection
• Um, just no prefix. Just "Able", "Damascus", "Gallipoli", "Hallimede" as a single name.

## Why It's Good For The Game
We're a roleplay server.
Do you really think that in a roleplay server, a Deathsquad operative should be called any of these names?
• Thick McRunfast
• THAT DAMN TRAITOR GEORGE MELONS
• Killing McKillingalot
• Stabby McGee
Yeah these sound like fucking clown names, not Deathsquad names. They sound like Beesetation clowns.
image
image
Now people who see Deathsquad officers don't have to check if they're in a MRP-HRP server or not.

## Changelog
:cl:
tweak: Deathsquad members now a new pool of 40 non-meme names based on cities, moons and World War phonetics.
del: Removes a few shit OOC memes from IC.
/:cl:

### CODE REVIEW

**Comment by Afya212** [comment]
`A whole bunch of spiders in a SWAT suit` I see nothing wrong here.
But really Plus Uno.

**Comment by YakumoChen** [comment]
keep Blast Hardcheese please, it's a reference

**Comment by YakumoChen** [comment]
Also if you want a professional sounding list of names I recommend using the NATO Alphabet and not just a bunch of random nouns and star names scraped together.

**Comment by Azarak** [comment]
What Chen said, I think it'd be much cooler if the agents werent just random names

**Comment by Moostard** [comment]
The DS names are memey as they arrive when there is total chaos and there are things to kill.
It adds a funny atmosphere. Those people are MADE for KILLING.
ERT names are normal as they are professionals sent to help the crew in crisis.
DS names are like that because they come just to kick ass.
The roleplay with DS would always end in a kill anyway(considering they will even do such roleplay, kinda hard to roleplay with someone who is running away) as they dont leave any witnesses and survivors.
We dont have to remove meme things "because its a roleplay server".

**Review by Afya212 — APPROVED** [review]

**Comment by NullDagaf** [comment]
> We dont have to remove meme things "because its a roleplay server".

...do I even need to say anything?

**Pull request merged**
