### PR TITLE
Ports hippiestation nooses... again.

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

see https://github.com/Skyrat-SS13/Skyrat13/pull/911
this time it doesn't crash the server and it works and etc

## Why It's Good For The Game

because byond makes me want to kill myself
https://www.youtube.com/watch?v=XVON0vP8k4s

mmfhksh

## Changelog
:cl:
add: Nooses
add: Crafting recipe for nooses
add: Eternal byond compiling torment
imageadd: Noose icons
soundadd: Noose sounds
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
I'm against this. Feels like it'll just be abused to high hell, even for a few weeks, and cause more problems than it's worth. We don't need nooses at all, and the femur breaker and guillotine are already bad enough.

**Comment by BobJoga** [comment]
> I'm against this. Feels like it'll just be abused to high hell, even for a few weeks, and cause more problems than it's worth. We don't need nooses at all, and the femur breaker and guillotine are already bad enough.

It gives many roleplaying opportunities, such as leaving a mangled corpse hanging as a traitor in maint. That'd be awesome and gritty to find as sec. I **know** people will abuse it, but we shouldn't remove features because a minority abuses them. I think a better alternative woul be adding logs for noose stuff, to warn/note/ban people who abuse them.

**Comment by Owai-Seek** [comment]
I still don't think stuff like this should be widely available, the entire thing makes me uncomfortable and I'm sure it does the same for many others. Sure, it's just a "spaceman game", but this hits too close to home for me.

**Comment by BobJoga** [comment]
> I still don't think stuff like this should be widely available, the entire thing makes me uncomfortable and I'm sure it does the same for many others. Sure, it's just a "spaceman game", but this hits too close to home for me.

I get that this is somewhat grim, but considering the shit you can do as traitor/changeling/any other antag, this is far from the darkest shit. I mean just the concept of changelings is pretty fucking terrifying.

**Comment by BobJoga** [comment]
**PR's closed due to mutes caused by Kathrin Bailey. For any grievances or complaints, contact Floof Ball#0798 on discord. The PR owner will also not listen to any of your complaints unless you provide screenshots that prove you have contacted Floof Ball#0798 on discord first.**
pool

**Pull request closed without merging**
