### PR TITLE
Revives BobJoga's ERIS Walls PR, with minor edits, additions, etc..

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Updates our current piss-poor codersprite artstyle into something far more passable, taking sprites from a variety of places and meshing them into one coherent package. Fully modular to boot!
image
image
image
image

## Why It's Good For The Game
The current wall sprites and such are extremely old and poor to look at, making the game as a whole downright ugly at times. This aims to rectify that issue with all new sprites for the walls.

## Changelog
:cl:
edit: Walls and such have been overhauled, see #3062 and #3555 for more info.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
based and erispilled

**Comment by ShadeAware** [comment]
Travis Error is unrelated to the actual PR itself, this is pretty much ready for live testing.

**Comment by RatFromTheJungle** [comment]
based

**Comment by BurgerLUA** [comment]
Legitimately I do not think that this is a good PR to add to Skyrat.

I don't even know where to really start when it comes to critiquing this PR. I don't want to say "remove it" but legitimately that is where my opinion lies with this PR. I haven't played Eris but their sprites looked good and I was kinda jealous that they had a consistent artstyle that actually looks decent. It has a nice aesthetic and it's honestly probably better that what /tg/ currently looks like.

HOWEVER this current implementation is absolutely not good. The old /tg/ sprites still exist. I'm seeing two artstyles conflict with eachother and it looks like trash. It would be like trying to adding the artstyle of Factorio to Minecraft without removing all of Minecraft's existing textures. Everything looks so off and ugly, and I literally do not mean to be a dick but I absolutely cannot play more than 5 minutes looking at these textures.

**Comment by ThatGuyFromThatPlace** [comment]
> Legitimately I do not think that this is a good PR to add to Skyrat.
> 
> I don't even know where to really start when it comes to critiquing this PR. I don't want to say "remove it" but legitimately that is where my opinion lies with this PR. I haven't played Eris but their sprites looked good and I was kinda jealous that they had a consistent artstyle that actually looks decent. It has a nice aesthetic and it's honestly probably better that what /tg/ currently looks like.
> 
> HOWEVER this current implementation is absolutely not good. The old /tg/ sprites still exist. I'm seeing two artstyles conflict with eachother and it looks like trash. It would be like trying to adding the artstyle of Factorio to Minecraft without removing all of Minecraft's existing textures. Everything looks so off and ugly, and I literally do not mean to be a dick but I absolutely cannot play more than 5 minutes looking at these textures.

The issue of artstyle whiplash has already been dealt with compared to the original PR
See: https://github.com/Skyrat-SS13/Skyrat13/pull/3062
Compare it to this PR where the sprites have been changed, the walls darkened, and, overall, artstyles brought to a medium between TG and Eris

**Comment by ShadeAware** [comment]
More sprites will be updated in a new style as time goes on, likely straying away from direct rips and instead focusing on original content in an Eris-like style

**Comment by Owai-Seek** [comment]
I'm still very much not a fan of replacing the under plating of the floor tiles. The old ones look fine and match the floor tiles above them. It just makes maintenance look -weird-.

image

image


I'm not a particular fan of tossing Eris tilesets over the current TG one as a whole, but these are just bad and inconsistant.

**Comment by ThatGuyFromThatPlace** [comment]
> I'm still very much not a fan of replacing the under plating of the floor tiles. The old ones look fine and match the floor tiles above them. It just makes maintenance look -weird-.
> 
> image
> 
> image
> 
> I'm not a particular fan of tossing Eris tilesets in over the current TG ones as a whole, but these ones in particular are just bad and inconsistent.

To be fair, that's not even what maint in Eris looks like. That sprite is used exclusively for pried up floor tiles in Eris. 
And, Eris has three layers instead of TG's two. 
Floor tiles > Plating (What we see now in Skyrat) > Underplating (The dark tiles in the screenshot below)
Eris maint

**Comment by Tename** [comment]
I personally really dislike the art style of Eris, specifically the windows not being transparent, over detailing of some walls. I would rather have them be simplistic. And I dont think it matches with the look of everything else.

**Comment by DoomsdayOrange** [comment]
My guy the doors stick out like a sore thumb really badly. This doesn't look good.

**Comment by RatFromTheJungle** [comment]
the only two things I personally dislike, are the new lockers/closets, (they clash too hard with other furniture), and the under-plating for floors, which if less harsh alternative isn't around, I could easily have one done in like 20m tops.

**Review by Azarak — CHANGES_REQUESTED** [review]
Revert the lockers as they're too much out of place and are too eye catching. 
The plating could really use a proper sprite, and not the out of place external hull one, how does one put tiles on that?
Revert the catwalks back to the old ones, one - their metal coloration clashes with all the other ones, two - they lack see-through, three - warning decals are orange instead of yellow.
Revert the grilles back to the old ones, or look at bay ones for inspiration, they have pretty damn good ones.

**Comment by ThatGuyFromThatPlace** [comment]
> the only two things I personally dislike, are the new lockers/closets, (they clash too hard with other furniture), and the under-plating for floors, which if the less harsh alternative isn't around, I could easily have one done in like 20m tops.
> 
> (and to note, the only thing I dislike about the maint floors is that they are kinda nasty looking with pipes/anything else really ontop of them)

Those sprites were never intended to have pipes on top of them. 
Like I said in another comment, Eris has: Floor > Plating > Pipes > Underplating
TG has: Floor > Pipes > Underplating

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
1. On top of Azarak's stuff, revert changes to the default plasteel floor ("floor"). Bright colours are useful for drawings your eyes, if most of the screen is really bright and the same colour as the top of the walls, you make the scene as well defined and visually distinct as a blank sheet of paper. The sprites are fine to be preserved elsewhere, but not as the new default.

2. Fix your repathing of stuff like sand and asteroid stand to the eris icon file and put it back to good ol' floors.dmi so the black void is less unnerving.

3. Investigate Eris's codebase and any other codebase using 3/4 perspective walls for mineral wall sprites for wooden walls and such if you haven't already. If not everything is 3/4, then it's going to get really shoddy-looking.

4. Once you near the end of your changes, change the indestructible walls/windows to the new ones too. As of now, you get this.
image
And no, this isn't for my benefit. CC uses indestructible walls/windows all over. It's also going to be needed for ball maps etcetera.

5. Preserve the old wooden floor and optionally the new plasteel floor as subtypes of their replacements.

6. Undo your revert to TG's new titanium floors. There's no need to change these. I already made old titanium floors available to place in-game and in map editors.

7. Investigate servers, such as Hestia, for their 3/4 directional doors.

8. Randomised icons for basalt floors needs fixing.
image
They make such a huge difference.

**Comment by KathrinBailey** [comment]
Due to toxic behaviour and refusal to address requested changes this PR will be closed.
You had the option to speak about the requested changes with civility but chose to act toxic and refuse to do the changes.
Some of these changes were up for discussion.
image
This wasn't up for discussion, neither was 3/4 directional doors.

**Comment by ThatGuyFromThatPlace** [comment]
> Due to toxic behaviour and refusal to address requested changes this PR will be closed.
> You had the option to speak about the requested changes with civility but chose to act toxic and refuse to do the changes.
> Some of these changes were up for discussion.
> image
> This wasn't up for discussion, neither was 3/4 directional doors.

Ah, okay, so, everyone who wants this gets punished because, you don't like what he said

Also, some of the changes are asking things that wouldn't work
Eris doesn't have 3/4th doors
I believe they are planning to get 3/4th doors in the future, but, until then, they have the door sprites you see in this PR. Bay 3/4th doors would look absolutely terrible as, Bay artstyle is just as distinct as Eris's, unlike TG which doesn't have an art style
And, Bay 3/4th doors have a completely different angle. Eris walls are much less steep than Bay walls

And, the TG grilles aren't better than Eris grilles. Eris grilles are too small and thin, but, TG grilles look like a cell shaded MS paint mess

**Comment by DoomsdayOrange** [comment]
> > Due to toxic behaviour and refusal to address requested changes this PR will be closed.
> > You had the option to speak about the requested changes with civility but chose to act toxic and refuse to do the changes.
> > Some of these changes were up for discussion.
> > image
> > This wasn't up for discussion, neither was 3/4 directional doors.
> 
> Okay, so, everyone who wants this gets punished because, you don't like what he said? No context provided either?
> 
> Also, some of the changes are asking things that wouldn't work
> Eris doesn't have 3/4th doors
> I believe they are planning to get 3/4th doors in the future, but, until then, they have the door sprites you see in this PR. Bay 3/4th doors would look absolutely terrible as, Bay artstyle is just as distinct as Eris's, unlike TG which doesn't have an art style
> And, Bay 3/4th doors have a completely different angle. Eris walls are much less steep than Bay walls
> 
> And, the TG grilles aren't better than Eris grilles. Eris grilles are too small and thin, but, TG grilles look like a cell shaded MS paint mess, and, Bay grilles are 3/4ths last I checked, which, doesn't look good at all

Its a lesson in "don't be a twat"

**Pull request closed without merging**
