### PR TITLE
Nerfs sonic jackhammer

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request
~~Removes the sonic jackhammer's ability to delete r-walls.~~
Sonic jackhammer now takes 5 seconds to smash through a regular wall, instead of an instant click destroy. This time is multiplied by 5 for r-walls, bringing it to 25 seconds.
~~Also unlocks some citadel snowflake donator stuff to the general public.~~

## Why It's Good For The Game
Because destroying r-walls in 5 seconds flat using a mass printable tool from a relatively unsecured lathe isn't.

## Changelog
:cl:
tweak: Sonic jackhammer now takes 25 seconds to destroy a reinforced wall. Added a 5 second timer to destroying regular walls.
add: Adminspawn supersonic jackhammer.
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
Instead of flat out removing its ability to destroy r-walls, I could give it a longer timer, or have it apply damage to the wall (thus taking multiple attempts to smack it down). Feel free to discuss.

**Comment by IrkallaEpsilon** [comment]
Might be worth changing the wall destruction time to 15 seconds (and probs need two hits to get through maybe? Kinda like Guys the thermal drill go get it). Is it possible to add this item to the RCD destruction pulse?

**Comment by MLGTASTICa** [comment]
honestly i say keep its ability to delete r-walls removed , compared to C4 and Thermite , it puts those items in the shadow , ontop if being very easy to print and being faster to use and obtain than the others.

**Comment by IrkallaEpsilon** [comment]
Thermite is storeable in any bag, and with 2 beakers you can just smear 10 units on a wall and erase it that way, thermite is at the very least a sidegrade, if not a straight upgrade due to how it outright erases walls. Its also pretty fast acting. Thermite is just mixing Iron, Aluminum and oxygen in a chem dispenser. It can even be done without a chem dispenser (grind a chair, grind a can of soda and grind a can of air).

**Comment by MLGTASTICa** [comment]
thermite requires 30U to melt R-walls . with a bluespace beaker you'd only be able to melt 10 walls, so i believe its much more balanced then 5 delay unlimited r-wall removed.

**Comment by IrkallaEpsilon** [comment]
Weird I did it with 10 already on a very consistent basis

**Comment by SpaceVampire** [comment]
I wouldn't do the donator stuff, or at least make that its own PR so we can talk about it there.
You shouldn't do two things that aren't linked in the same thing.

**Comment by KathrinBailey** [comment]
I'd consider upping the timer of the normal jackhammer to destroy rwalls and adding a small time for normal walls.
Create a subtype of the jackhammer that has the same stats as normal, before this nerf, and leave it as admin-spawn only because it's useful for events.

**Comment by Gandalf2k15** [comment]
I suggest you separate the nerf from the item unlocking.

**Comment by Zenitheevee** [comment]
Maybe change R-wall deletion to... ehhhh 15 seconds instead of outright removing it, or see if you can give it the mech-drill repeating damage code. 

While it _Is_ in the handily least secure protolathe, removing it takes a large portion of potential scenarios and a really handy tool outside of non-lethal antags trying to just do their job, and lethal antags reaching targets hiding in rooms that would leave them having nearly half a minute of escape time once they realize shits being broken.

**Comment by Oscari-pog** [comment]
The only people this will upset will either be loud antags, or people that cant handle not being able to defeat a malf AI with a single tool available from the cargo lathe

**Comment by NotRanged** [comment]
Removed the item unlocking (idk why this /needs/ a seperate pr but ok).

Jackhammers now take 25s to destroy r-walls.

**Comment by SpaceVampire** [comment]
I think it should be 15s like what everyone else above me already said.
Its also just good form not to stick unrelated stuff in the same PR?
Its like trying to sneak stuff past on the end of some bill. Its not hard to make two PRs.

**Comment by Yawet330** [comment]
pffft, 15s is still far too far, 25 is good. You should not be able to greytide caps office in 30s, nor anywhere else (15s per wall remember)

**Review by Azarak — APPROVED** [review]

**Comment by ForrestWick** [comment]
Jackhammers deleting rwalls is a bad meme and it's best to remove the ability now because people are gonna be in for shell shock when the rebase happens. The only reason it didn't happen on citadel is because clock cult existed, and after that was removed there was no real need to remove it from a balance perspective. 

Despite that, however, the fact they can bust down rwalls is ridiculous. Trying to say thermite exists isn't a good argument and just reinforces the sentiment everyone has already of chem warfare being shit.

Nothing is lost if the jackhammer gets smacked. Deleting walls in 5 seconds is good enough

**Pull request merged**
