### PR TITLE
Refurbished Centcom Docking Area - The Squeakquel

### PR DESCRIPTION
**Pull request by calibraptor**
## About The Pull Request
The Centcom docking area has been remapped for both function and flavor. 

**ALSO I MOVED LESS SHIT AROUND THIS TIME.**

The safe zone and EORG Area have been separated by a neutral hallway, so players no longer need to walk through the warzone in order to reach safety.

QoL changes from the current safezone:
-Dedicated spectator gallery for the EORG area. Allowing the players to watch the carnage from relative safety.
-Fully upgraded sleepers and cloning pod in the medbay area, as well as better equipment in general. Medical mains rejoice!
-Fully upgraded cyborg rechargers as well as infinity cells. Silicon mains rejoice!
-Table with fully topped up plasma and N2 belt tanks, on the off-chance a Vox/Plasmaman runs dry. Vox/Plasmaman mains rejoice?
-Safezone is immensely larger than our current one, the cafe area alone seats 60+ people.

Screenshots
Safezone: https://i.imgur.com/aYfXvaP.png
Griefzone/Neutralzone: https://i.imgur.com/b8lzw3f.png

## Why It's Good For The Game

Makes it easier for admins to deal with the end of round shitstorm, and players get nice new area to chill in that's large enough to accommodate the server at peak hours.

## Changelog
:cl: Calibraptor
add: The emergency docking area at Centcom has been refurbished in line with new safety regulations.
/:cl:

### CODE REVIEW

**Comment by calibraptor** [comment]
Mapping alternative to #3190

**Comment by Owai-Seek** [comment]
Someone mentioned lasers going through the observation windows. I'm personally unsure of how thunderdome windows work, but if lasers -do- go through it, I'd advise removing the "stairs" going down to the bar. With the stairs/opening there, someone could theoretically fire lasers into the safezone.

Some extra cleaning supplies would be a nice QoL addition, and maybe Prescription Health HUDS for the observation room, but that's unnecessary.

I really don't like there being an airhorn in observation, people suck, and they're gonna be assholes with it.

I'm unsure of what the orange hammer does.

**Comment by calibraptor** [comment]
> 
> 
> Someone mentioned lasers going through the observation windows. I'm personally unsure of how thunderdome windows work, but if lasers -do- go through it, I'd advise removing the "stairs" going down to the bar. With the stairs/opening there, someone could theoretically fire lasers into the safezone.
> 
> Some extra cleaning supplies would be a nice QoL addition, and maybe Prescription Health HUDS for the observation room, but that's unnecessary.
> 
> I really don't like there being an airhorn in observation, people suck, and they're gonna be assholes with it.
> 
> I'm unsure of what the orange hammer does.


- The windows cannot be shot through. They're literally indestructible walls that you can see through.

https://imgur.com/NsFWxJu

- The medbay has some space cleaner in it.

- I can replace the airhorn with something else.

- The orange hammer is a toy that makes a bwoink sound when you hit people with it.

**Comment by Arctaisia** [comment]
Really hoping this gets merged, it's well done and nice looking!

**Comment by calibraptor** [comment]
Slapped down an invisible light in the middle of the killzone. (It shows up in the mapmaker, but won't be visible to players.) 

Got rid of the airhorn.

Decided against the salt shakers and toys (too meta) sitting on the two tables inbetween the safezone entrances and replaced them with delicious donuts.

Also replaced the bluespace bodybags in the medical area with advanced health scanners, since it occurred to me folks might use them to grief.

Screenshots will be updated accordingly in a minute.

**Comment by Strazyplus** [comment]
remove airhorn and add drakeplush and it'd be done.

joke aside I like the changes, speedmerge?

**Comment by DarkWolfInsanity** [comment]
> 
> 
> remove airhorn and add drakeplush and it'd be done.
> 
> joke aside I like the changes, speedmerge?

He said he removed the airhorn 3 days ago and that they decided against toys. Just bring a drakeplush from the station. there's tons of the things on a normal round

**Comment by Strazyplus** [comment]
image

**Pull request merged**
