### PR TITLE
Minor Oldstation Fixes/Tweaks

### PR DESCRIPTION
**Pull request by werewolfboyfriend**
## About The Pull Request
- "Beta Station North Corridor" is now divided into "Beta Station Fore Corridor" and "Beta Station Port Corridor".
- "Beta Station Medical Bay", "Charlie Station Cargo", "Charlie Station Living Quarters", "Charlie Station Solar Access Hallway", "Delta Station Secure Research Wing", and "Salvage Shuttle" are new areas.
- Various APCs and doors renamed to accurately reflect their location, fix typos, or be more consistent.
- Threw in a few posters for a little extra flavor, a deck of cards on the gambling table, and a couple of extra trash items.

## Why It's Good For The Game
Oldstation is one of the best ghost roles and it's been bugging me for a little bit on how some areas are inconsistent and APCs/doors aren't named properly or have typos. I've seen it cause some confusion, most especially the fact that the atmos APC in the Beta Station part was referred to as Charlie xenobio. 
Also, I think the area could use just a touch more flavor. As it is, some parts of it don't necessarily feel like they may have been inhabited before. I thought this was worst in the living area, and I think the tiny bit of clutter helps.
As a side note, I'm not sure why the note and a door on oldstation referred to an AI as an  'artificial program' but I'm assuming that's intentional and I've kept it.

## Changelog
:cl:
tweak: Minor oldstation fixes/tweaks.
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
I feel this PR is too large what it is meaning to do.
Did you use mapmerge?

**Comment by werewolfboyfriend** [comment]
It;'s been a loooong while since I've touched SS13 stuff, I definitely forgot mapmerge. I'll get to it.

**Comment by jjpark-kb** [comment]
If possible, please mapmerge and do the changes.

**Comment by jjpark-kb** [comment]
failed to meet requirements in a timely manner, closing.

**Pull request closed without merging**
