### PR TITLE
Removed Dog Borg Size modules

### PR DESCRIPTION
**Pull request by WTFIsmyname**
They're broken as fuck and no one wants to fix them.

## About The Pull Request

Removed Dog Borg size modules and removed the fabricator code referencing them. No one wants to fix them so just get rid of them

## Why It's Good For The Game

They're ugly as sin, and every time they get fixed they get broken just as fast from the upstream. Just fuck them off tbh

## Changelog
:cl:
Removed borg Size Modules from Fabricator
Removed borg Size Modules
Basically fuck borgs
/:cl:

### CODE REVIEW

**Comment by Yawet330** [comment]
this changelog will not work.

**Comment by Yawet330** [comment]
image

**Comment by WTFIsmyname** [comment]
> Fix the Travis error Yawet mentioned and properly mark your edits.
> Also afaik the borg expand actually works and doesn't have any issues, so removing that is a no unless there is an actual issue with it.
No they don't actually work.
They were scaled to a more managable size once before but the CIT upstream put it in a situation where it is back to a 2* scaling, which is fucking insane.
Also the bug with using multiple is still around
Also it fucks with hitboxes
Also it looks like garbage
There is no reason to keep these around.

**Comment by WTFIsmyname** [comment]
Fixed. Moved the comment to where it should have ended.

**Comment by namjay1170** [comment]
I for one use it 100% of my borg rounds and its a big part of why I enjoy the role, I would really appreciate it if you would instead fix it instead of shadow realm it

**Comment by ShadeAware** [comment]
Yeah, this doesn't seem to be actually done in good faith. It just looks to me like you were looking for any reason to remove them instead of fix them. If you have the know-how to comment them out, you know how to fix it. 

This entire PR is just salt against Dogborgs, its pretty easy to see that.

**Comment by WTFIsmyname** [comment]
> Yeah, this doesn't seem to be actually done in good faith. It just looks to me like you were looking for any reason to remove them instead of fix them. If you have the know-how to comment them out, you know how to fix it.
> 
> This entire PR is just salt against Dogborgs, its pretty easy to see that.

If I knew how to fix it I would. I have asked for literally months for these to be fixed but no one wants to. At this point it's dead content and just a pain in the ass to deal with as an admin.

**Comment by Strazyplus** [comment]
misread this, thought it was an attempt to remove dogborgs. lol
honestly, I dislike the size modifiers, it makes the borgs look ugly as sin.
but that's just opinion not worthy of removal. and I begrudgingly would not even if I could.

I have not seen the size modifier actually break anything as of late.

**Comment by Azarak** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/2887 Fixes this

**Pull request closed without merging**
