### PR TITLE
[READY]Adds argent energy cells to lavaland

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds argent energy cells to lavaland, that can function as a selfcharging (slightly better than) basic power cell, or be deconstructed for many research points in RnD (10000), or be used (aka crushed) as a 90% damage reduction for 10 seconds powerup once. You get them from destroying tendrils.

## Why It's Good For The Game

More ways to get research points, and of course miners needed another powerful and somewhat easy to access item.

## Changelog
:cl:
add: Added argent cells to lavaland
imageadd: Added status effect icon for argent cell, argent cell icon itself
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Self charging power cells will make the yellow core reaction from xenobiology obsolete. Also,
### DOES MINING REALLY NEED MORE GAMER GEAR?

**Comment by BobJoga** [comment]
> Self charging power cells will make the yellow core reaction from xenobiology obsolete. Also,
> 
> ### DOES MINING REALLY NEED MORE GAMER GEAR?
It selfcharges but to compensate, it doesn't have a very ridiculously high capacity.
I can change it to be even worse if need.
To top it off: **miners always need gamer gear**

**Comment by Hatterhat** [comment]
i've seen a lot of awful mining related PRs in my day, and this is really up there

**Comment by BobJoga** [comment]
> i've seen a lot of awful mining related PRs in my day, and this is really up there

this pr bad however i will not provide any reasoning or ways to improve
i'm out now haha

**Pull request merged**
