### PR TITLE
[MIRROR] Field of Vision component.

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12075
--------------------
## About The Pull Request
Title. Somewhat inspired by Interbay's (which was taken from lfwb), though the code is fairly different, making use of planes and 513 alpha filters.
Extensively tested, it does the job visually, but there is still stuff to do, such as:
- [x] Adding a config to enable/disable FoV.
- [x] Code to toggle the FoV off when dead, being a dullahan (for obvious reasons), or using a camera console, entering closets etc.
- [x] Move some of the code clustering (mostly plane related bug fixes from tg) this WIP in different PRs.
- [x] Make the shadow cone also mask open space (pretty easy but there is a port to do first, see above).
- [x] Make mobs face whicher thing they are pulling regardless of density when moving (unless they have combat mode on). I don't want to add another janky fov plane blocker image for pulled objects.
- [x] Using `visible_atoms`/`get_actual_viewers` instead of `view`/`viewers` where appropriate.
- [ ] Get someone to make a better 180° icon, the current one is basically "blind right eye" state rotated 45° clockwise.
- [x] Documentation.
- [ ] Doing byond forum bug reports for some byond issues I found while working on this that had me backtrack quite a bit.
- [x] Possibly other improvements and tweaks.
- [x] dim the environment (again) to fit the shadow cone visuals.

## Why It's Good For The Game
Mostly flexing on the lag older PRs such as tgstation/tgstation#24304 and tgstation/tgstation#24537 would cause, aided by 513 filters.
Otherwise it's a fairly interesting feature, though tgstation & co have pretty much developed around full 360° vision the whole time (except combat mode, which was ported from interbay), so expect some potential salty tf2 spy gameplay whenever this is enabled.

## Changelog
:cl:
add: FoV component, probably a component.
/:cl:

### CODE REVIEW

**Comment by Afya212** [comment]
Dew it

**Comment by CinderWC** [comment]
**No**

**Comment by LimblessLayabout** [comment]
Can somebody post a preview of what we're actually looking at?

**Comment by ShadeAware** [comment]
Why does it keep getting worse

**Comment by Arturlang** [comment]
Fuck yea

**Comment by CinderWC** [comment]
travis kill

**Pull request merged**
