### PR TITLE
Kneecaps fusion temperature limit

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

After a round where an antag atmos tech decided the station is now a star, people called for a fusion nerf.

## Why It's Good For The Game

Clamps max temp to 5e9, which is more than enough for fusion's few legitimate uses (stimulum, noblium), but no more:
Broken powernets with -NaN TEGs
Stationwide instakill radiation pulses with the supermatter
Heatfloods cooking every room which has its door opened for 0.1 seconds
Heating up space tiles and delaminating the supermatter through its own heatsink
Burning through reinforced floors with black fire

## Changelog
:cl:
balance: Fusion max temperature clamped to 5e9 K.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
You need to clamp both positive AND negative, as fusion can be endothermic, and make it a logarythmic scale so its exponentially harder to get higher temps instead of just making a HARD limit

**Comment by NotRanged** [comment]
do you know how clamp works, read the code again

**Comment by Arturlang** [comment]
Oh right, TCMB is 2.7, sorry, but i know that it only hard limits to those two numbers, which can feel pretty stupid and prevents trying to find better mixes trying to get to the highest temperature, why stop that drive? The method i proposed should still allow it while making it harder to make game breaking fusions.

**Comment by NotRanged** [comment]
I'm not going to change it, and frankly, I don't care if this PR gets merged or not; I did it on request of many angry players after a fusion canister leak wiped the entire station out with no counterplay.

**Review by Azarak — APPROVED** [review]

**Pull request merged**
