### PR TITLE
[Modular] "New" Healing Chemicals

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Adds sixteen new chemicals, which are tiered.

_**Tier 2:**_
1. **Bicaridine+:** _Plasma, Bicaridine (1:1) Yields 2_
Bicaridine has been lowered in half the amount that it heals. This is the chemical that heals the same amount as Bicairdine did. It has a 20u overdose.
2. **Kelotane+:** _Plasma, Kelotane (1:1) Yields 2_
Kelotane has been lowered in half the amount that it heals. This is the chemical that heals the same amount as Kelotane did. It has a 20u overdose.
3. **Antitoxin+:** _Plasma, Antitoxin (1:1) Yields 2_
Antitoxin has been lowered in half the amount that it heals. This is the chemical that heals the same amount as Antitoxin did. It has a 20u overdose.
4. **Tricordrazine+:** _Bicaridine+, Kelotane+, Antitoxin+ (1:1:1) Yields 3_
Tricordrazine has been lowered in half the amount that it heals. This is the chemical that heals the same amount as Tricordizone did. It has a 20u overdose. Tricordrazine also has been changed from prob(80) of healing to prob(70). This medicine has the original prob(80) of Tricordrazine.

_**Transitioning:**_
1. **T-Brute:** _Bicaridine+, Bicaridine (1:1) Yields 2_
T-Brute is a "medicine" that is used to transition the tier 2 chemical into its tier 3 version. However, when taken by itself, it slowly deals brute damage and removes other chemicals from your system.
2. **T-Burn:** _Kelotane+, Kelotane (1:1) Yields 2_
T-Burn is a "medicine" that is used to transition the tier 2 chemical into its tier 3 version. However, when taken by itself, it slowly deals burn damage and removes other chemicals from your system.
3. **T-Toxic:** _Antitoxin+, Antitoxin (1:1) Yields 2_
T-Toxic is a "medicine" that is used to transition the tier 2 chemical into its tier 3 version. However, when taken by itself, it slowly deals toxic damage and removes other chemicals from your system.
4. **T-Basic:** _T-Brute, T-Burn, T-Toxic (1:1:1) Yields 3_
T-Basic is a "medicine" that is used to transform the tier 2 chemical to its tier 3 version. However, when taken by itself, it is a **_lethal_** poison that could be compared to a more tame version of an anti-tricordrazine.

_**Tier 3:**_
1. **Bicaridine++:** _T-Basic, T-Brute (1:1) Yields 2_
Bicaridine has been lowered in half the amount that it heals. This is the chemical that heals double the amount as the original Bicaridine did. It has a 10u overdose.
2. **Kelotane++:** _T-Basic, T-Burn (1:1) Yields 2_
Kelotane has been lowered in half the amount that it heals. This is the chemical that heals double the amount as the original Kelotane did. It has a 10u overdose.
3. **Anti-Toxin++:** _T-Basic, T-Toxic (1:1) Yields 2_
Antitoxin has been lowered in half the amount that it heals. This is the chemical that heals double the amount as the original Antitoxin did. It has a 10u overdose.
4. **Tricordrazine++:** _Bicaridine++, Kelotane++, Anti-Toxin++ (1:1:1) Yields 3_
Tricordrazine has been lowered in half the amount that it heals. This is the chemical that heals double the amount as the original Tricordizone did. It has a 10u overdose. Tricordrazine also has been changed from prob(80) of healing to prob(70). This medicine has a prob(90).

**_"Nullifying Medicine"_**
Some may get the idea to mix the chemicals together in order to create some kind of powerful healing chem so that one can avoid advanced chemicals all together. Well, these medicines remove the possibility of putting the tier 2 and tier 3 in the same mixture.
1. **Brutex:** _Bicaridine++, Bicaridine+(1:1) Yields 2_
Brutex is medicine that will very slowly heal brute damage. It metabolizes very slowly. It has a 10u overdose.
2. **Burnex:** _Kelotane++, Kelotane+ (1:1) Yields 2_
Burnex is medicine that will very slowly heal burn damage. It metabolizes very slowly. It has a 10u overdose.
3. **Toxicex:** _Anti-Toxin++, Antitoxin+ (1:1) Yields 2_
Toxicex is medicine that will very slowly heal toxic damage. It metabolizes very slowly. It has a 10u overdose.
4. **Allex:** _Tricordrazine++, Tricordrazine+, Tricordrazine (1:1:1) Yields 3_
Allex is medicine that will very slowly heal all damage at a medium percentage of prob(50). It metabolizes very slowly. It has a 10u overdose.

## Why It's Good For The Game

Adding more chemicals can allow for future chemical creations based off these new ones. It would also be nice to have more chemicals so the chemists can not only have more to do, but doctors have tiers of medicine to choose from in the basic chems, rather than having to wait for advanced medicines to be pumped out.

## Changelog
:cl: Jake Park
add: Added sixteen new chemicals.
balance: balanced the four basic chems in order to incorporate the sixteen new ones. See: https://github.com/Skyrat-SS13/Skyrat13/pull/1211
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
I honestly doubt anybody, and I mean **anybody** who actually plays the game wants these in the slightest. Have you even held a vote before doing these massive changes? If not, its safe to say these will be merged to the sound of crickets and reverted with fanfare.

**Comment by jjpark-kb** [comment]
> I honestly doubt anybody, and I mean **anybody** who actually plays the game wants these in the slightest. Have you even held a vote before doing these massive changes? If not, its safe to say these will be merged to the sound of crickets and reverted with fanfare.
Its important to understand that Github is here for that very reason. For people to voice their concerns and vote whether or not a PR should be merged/TM, etc. Im still working on balancing and talking to others about possible changes.

**Comment by KathrinBailey** [comment]
Concerned at the balance.
What stops me from having Bic, Brutaline and Obligerine in the same pill? Now I have an absurd amount of brute healing, much more than I could have before. I can also stack three tiers of tricord.
Also, the names are iffy. I'm not sure if they're based on something but it'd be nice if they all follow some sort of convention. "Bicaridine, Brutaline, Brutadine"; "Kelotane, Kelamine, Kelotose". Just makes it easy to remember. Also  hard to spell long word man is bad.

What is the intention behind the PR anyway? To give chemistry something to do? To buff chemistry? To nerf botany chem?

**Comment by LimblessLayabout** [comment]
This will have serious ramifications for sleeper usage, which may or may not be the intent.
I personally agree that the chem names should be kept as a more consistent family and simplified - these current names are honestly difficult for me, particularly the antitox group, and I cannot imagine trying to fit them in the span of the chem recorder slots.

I am not averse to this entire concept, having different stocks of meds would be nice - as it is, I keep a mountain of synthflesh, eye and ear meds, and tricord around, and spend the rest of my time making special purpose meds that rarely get used. And those few common-purpose chems get applied to every situation, that mountain of meds frequently runs out faster than I can replace them in a crisis.

**Comment by jjpark-kb** [comment]
> Concerned at the balance.
> What stops me from having Bic, Brutaline and Obligerine in the same pill? Now I have an absurd amount of brute healing, much more than I could have before. I can also stack three tiers of tricord.

So im going to be working on that. Im going to add more chemical reactions that will make these chemicals react with others so that if you try to stack them, they turn either into some kind of poison or some kind of just... inert chemical.
> Also, the names are iffy. I'm not sure if they're based on something but it'd be nice if they all follow some sort of convention. "Bicaridine, Brutaline, Brutadine"; "Kelotane, Kelamine, Kelotose". Just makes it easy to remember. Also hard to spell long word man is bad.

There actually is reason behind the naming. T2 are all german if you remove the -ine, -ane, and -one. The T3 are all french names. Do that same thing and you get the words. The only ones that do not have this of course is the antitoxin tiers, which are straight up their language. The transitioning chemical is "Language medium", which is because it is the chemical to transition the german T2 to the french T3.

> What is the intention behind the PR anyway? To give chemistry something to do? To buff chemistry? To nerf botany chem?

This can be seen as some steps for me. I plan to add more chemicals that can be expanded upon. I want there to be more tiers between chemicals. I also just want more content, allowing chemists to have options to either stay in the basic t1-3, or go straight to advanced chemicals.

**Comment by KathrinBailey** [comment]
Stopping the tiered chems stacking would be awesome. They don't have to start killing you, maybe just be less effective. What's the reason for blood and water for making T2 chems also?
If you're making new chems, some stuff that'd be cool:
• Healings chems that take a long time to metabolise but have a long heal-rate, so they heal slowly over a long period of time.
• Ghetto epipen.
• Chem that heals all organs so person can be defibbed, potentially a mixture of high tier healing chems and other organ heal chems.

**Comment by CinderWC** [comment]
Yeah no i absolutely hate this. This is an all-around nerf to medbay that nobody is going to want whatsoever.

Even if, there should be a vote for a PR this big in democracy-by-emoji

**Comment by jjpark-kb** [comment]
> Stopping the tiered chems stacking would be awesome. They don't have to start killing you, maybe just be less effective. What's the reason for blood and water for making T2 chems also?

The reason for blood and water is because it makes sense to me when speaking of biological medicine. It is a little too easy, but I think its fine since it only makes the T2 chems, which are similar in power to the current medicine. Basically requires an extra step to get it. With the addition of the new chems, if you dont mix it right, you will get less T2 chems and actually make some of the transitioning medicines instead.
I also stopped the tiered chems stacking by introducing more chems that react based on which chems. Please read the new PR to get an idea as my comment may get too long.
> If you're making new chems, some stuff that'd be cool:
> • Healings chems that take a long time to metabolise but have a long heal-rate, so they heal slowly over a long period of time.

I just added this with the -ex medicine, which is supposed to remove the ability to cheese and create insane healing mixes.
> • Ghetto epipen.

I would love to add this, but it might need to be a little later, or if I find it important to add it to this PR.
> • Chem that heals all organs so person can be defibbed, potentially a mixture of high tier healing chems and other organ heal chems.

Also would love to add this, but same reason as above, may want to add this later, or now depending on the merge-ability of this PR.

**Comment by BurgerLUA** [comment]
I like the general idea of the PR but I don't like the names or the recipes for them.

I think the tiers of healing chems should require materials such as plasma sheets or bluespace crystals in order to mix as things like water and blood just doesn't make any sense.

**Comment by BurgerLUA** [comment]
Oh also you might want to be very careful with additional medications as if you combine all the brute medication together, you'll get a super fast metabolising chemical as chemicals don't metabolize based on how much of it is in your system, but rather based on whether or not it exists.

**Comment by jjpark-kb** [comment]
> I like the general idea of the PR but I don't like the names or the recipes for them.

I have just resolved this by naming each of the tiers their basic form with a + or a ++, denoting its either a tier above, or two tiers above.
 
> I think the tiers of healing chems should require materials such as plasma sheets or bluespace crystals in order to mix as things like water and blood just doesn't make any sense.

I changed the blood/water for just plasma this time.
Thank you for the feedback!

> Oh also you might want to be very careful with additional medications as if you combine all the brute medication together, you'll get a super fast metabolising chemical as chemicals don't metabolize based on how much of it is in your system, but rather based on whether or not it exists.

Also, the nullifying medicine should reduce peoples abilities to do stacking of the same kind of medicine. Putting tier 1 and tier 2 get you a transition medicine. Putting tier 2 and tier 3 get you a nullifying medicine. Putting all three together, youll get some kind of combination, depending on the order of mixing.

**Comment by Commandersand** [comment]
>nerfing standard chems by HALF
>regular healing rate now has a worse overdose limit
>tier 3 chems still heal ~2/3 at a time because they're a third of the overdose limit
>can't stack chemicals
also
>plasma as not a catalyst
AAAAAAAAAAAAAAAAAAAAA
horribly changes as a very frequent medbay player, you should have just added a double healing chem that takes the standard chem+plasma to make

**Comment by jjpark-kb** [comment]
> > nerfing standard chems by HALF

Nerfing by half allows for the other two tiers to actual be decent, and allow for a better step-up from basic to advanced chemicals.

> > regular healing rate now has a worse overdose limit
> > tier 3 chems still heal ~2/3 at a time because they're a third of the overdose limit

When I was creating the tier 3 chemicals with their overdose limit, I had in mind that the player would be in medbay being taken care of by doctors and that they would occasionally put back in some more medicine within the patient.

> > can't stack chemicals

I especially did not want stacking chemicals because that would have allowed for massive powercreep, which is not an intended feature. Departments already have enough powercreep, medbay does not need more. 

> > also
> > plasma as not a catalyst

Plasma is an abundant resource. It appears frequently on mining and when technology exists, bluespace miners can make plentiful amounts of plasma. Plasma is not an issue when being consumed in the process to create the chemicals.

> > AAAAAAAAAAAAAAAAAAAAA
> > horribly changes as a very frequent medbay player, you should have just added a double healing chem that takes the standard chem+plasma to make

So this goes back to me not wanting to make basic chems stronger than advanced chems. I want a more linear path, and an overall better feel for going from basic chemicals to advanced chemicals. Also, its more chemicals, which means that chemists may feel they are being more productive with more chemicals to produce. Just know that you have to mix the chemicals right or you might get the wrong ratio chemical of something.

**Comment by Commandersand** [comment]
i dunno nerfing something that already exists to make the new thing better is pretty bad balance.
also 10u is a REALLY low OD limit, it's just not worth it if you can't even stack it and it's only twice as much healing
Plasma is abundant but
1.sometimes miners are absent
2. having to use plasma for something you could make before without it is lame

**Comment by jjpark-kb** [comment]
> i dunno nerfing something that already exists to make the new thing better is pretty bad balance.

Thats how it works when you add content that wants to be more linear. 

> also 10u is a REALLY low OD limit, it's just not worth it if you can't even stack it and it's only twice as much healing

I agree that 10u is pretty low, so I may look into changing it. I just dont want it to be stronger than advanced chemicals.
> Plasma is abundant but
> 1.sometimes miners are absent

Public mining is still a thing here. Even though we are downstream of Citadel, we have public mining.

> 2. having to use plasma for something you could make before without it is lame

You can get used to having to use plasma in order to make stuff. It isnt hard to go to the lathe, remove some plasma from the silo, grind it up, and put it in.

**Comment by CinderWC** [comment]
>>    i dunno nerfing something that already exists to make the new thing better is pretty bad balance.

>Thats how it works when you add content that wants to be more linear.

VYl1TkE

**Comment by jjpark-kb** [comment]
> > > i dunno nerfing something that already exists to make the new thing better is pretty bad balance.
> 
> > Thats how it works when you add content that wants to be more linear.
> 
> VYl1TkE

Not only is this comment not helpful, it isnt true.
I nerfed the default chems, made t2 what the default chems used to be, and made the t3 slightly better. If you want to make comments, perhaps make them helpful?

**Comment by CinderWC** [comment]
>If you want to make comments, perhaps make them helpful?

I am very helpful, i have told you that what this is, is powercreep as you are making an older chemical less useful in favor of your new added ones. You then proceeded to insult me over this in Discord DMs and then blocked me

**Comment by CinderWC** [comment]
So i guess me defending myself and telling you that what i said is helpful is off-topic. That is very great so let me elaborate on this:

The act of adding something that is more powerful than what was already there is considered powercreep.
Now you have criticized me in the past for adding powercreep myself so i went ahead and pointed out the same thing with your PR. which was then met with insults in DMs.

Please keep your personal bias out of this thread as i did mean what i said

**Comment by jjpark-kb** [comment]
> So i guess me defending myself and telling you that what i said is helpful is off-topic. That is very great so let me elaborate on this:

It is not contributing to the actual development of the PR, so yes, it is offtopic. Drop it.
> 
> The act of adding something that is more powerful than what was already there is considered powercreep.

Plenty of departments have powercreep, this is barely anything. Rather than give me problems, give solutions to it.
> Now you have criticized me in the past for adding powercreep myself so i went ahead and pointed out the same thing with your PR. which was then met with insults in DMs.

Posting a picture of a website in a manner that you did is pretty rude. Again, give answers/solutions that can help solve stuff, rather than complain and only list out the errors. Plenty of others have voiced their opinion and have given constructive feedback.
> 
> Please keep your personal bias out of this thread as i did mean what i said

I guess it can be said back to you?

**Comment by CinderWC** [comment]
> Plenty of departments have powercreep, this is barely anything. Rather than give me problems, give solutions to it.

Only point i will talk about before i leave: Powercreep in other departments does not justify adding more powercreep. What you could have done is keep the default chems at their standard values and make the new chems have better stats than those standard values

**Comment by Commandersand** [comment]
>hiding comments calling out discord insults and blocking

that's a big yikes right there

also "linear progression" and "just get used to grinding plasma all the time" isn't a good reason to nerf already existing chems. 
If you want to nerf bicard just make a new chemical that uses the original recipe and that heals less and getting regular bicard require heating it up

the chem dispensers have limited charge and you're doubling the amount of reagents needed to have the same amount of healing

**Comment by CinderWC** [comment]
@Commandersand This PR is testmerged now

**Comment by BurgerLUA** [comment]
I don't like how you can't make pills or patches out of it as it is forbidden from being interacted with in the dispenser.

**Comment by IronEleven** [comment]
I have two primary issues with this PR.  The first is that this feels like it's going to seriously bloat the amount of recipes a chemist is going to have to remember and look up, and that leads into my second issue: documentation.  We don't have a wiki, and I know it's being worked on, but I'm not optimistic about it coming up quickly after how Citadel's wiki went.  And until we have that wiki, major divergences from upstream need to be intuitive, or it's going to create problems for newer players.  Look at Fermichem, it was pretty easy to find information when it was new, but now that information's gotten more and more buried and difficult to find, and you had to basically get links from people who were around for that stage of Citadel's development.  Now add to that you have chems with very low OD thresholds (most healing chems are somewhere in the 20s), and ones that are outright poison, both of which have a very real possibility of mixing inside someone.  This isn't intuitive, and if this change goes live before a wiki, it's going to lead to a lot of accidental poisonings on a server where people ALREADY don't trust med players.

Sorry to ramble, but TL-DR, we need a wiki first or it's going to wind up like organs and synthtissue.

**Comment by KathrinBailey** [comment]
> I have two primary issues with this PR. The first is that this feels like it's going to seriously bloat the amount of recipes a chemist is going to have to remember and look up, and that leads into my second issue: documentation. We don't have a wiki, and I know it's being worked on, but I'm not optimistic about it coming up quickly after how Citadel's wiki went.
> 
> Sorry to ramble, but TL-DR, we need a wiki first or it's going to wind up like organs and synthtissue.

I can add this to the Skyrat wiki in about 30 minutes. I can promise you that if this gets merged and Jake approached me afterwards, I will ensure that it is properly documented on the wiki. We have a chemistry page up there at the moment.

**Comment by Commandersand** [comment]
since stacking will be allowed i really just ask for:
removing t-chems and leaving T-basic because a different tchem for every one is ehhh
i'd say t-basic+t2+heating

**Comment by SquishyOranges** [comment]
The problem with adding these chemicals are that It adds to much unnecessary bloat to the recipe list and will certainly confuse someone. The "Transition Chems" don't really help since the only thing they do is make the chemist just grind out chems . And that usually is a dull experience. 

If you really wanted to add more chems, I suggest you add more simpler, and less confusing chems.

**Comment by jjpark-kb** [comment]
image
The people have spoken. :(

**Pull request closed without merging**
