### PR TITLE
Right, so What if we do add some things

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request

Mayhem bottles have be replaced with a fancy freezer miner beam!
New upgraded vests that are better at rad shielding 
TG's locker mech thing for admins to do or such
Tray shield, shiv and makeshift hatches
Makeshift laser guns but are rather costly 
Admin only guns and general debug stuff

## Why It's Good For The Game

Idk

## Changelog
:cl:
add: Mayhem bottles have be replaced with a fancy freezer miner beam!
add: New upgraded vests that are better at rad shielding 
add: TG's locker mech thing for admins to do or such
add: Tray shield, shiv and makeshift hatches
add: Makeshift laser guns but are rather costly 
add: Admin only guns and general debug stuff
tweak: Rubber 9mm deal 1 brute harm!
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Most of these weapons are copies from https://github.com/Skyrat-SS13/Skyrat13/pull/1360

**Comment by BobJogaIsForkinBanned** [comment]
I mean... why not just... use the second amendment PR, which i can currently working to balance?

**Comment by BobJogaIsForkinBanned** [comment]
Also... replacing the mayhem in a bottle with what is essentially a temperature gun? I just... no dude

**Comment by Commandersand** [comment]
>getting rid of cool miner loot

i remember when you tried to nerf miner points a few months ago...

**Comment by Akrilla** [comment]
Leaving until we settle with #1360 first

**Comment by Trilbyspaceclone** [comment]
*shrug
okie

**Pull request closed without merging**
