### PR TITLE
Prisoners are spawn with tracker implants

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Prisoners on spawn now have implants to track their movements

## Why It's Good For The Game

Why would these horrable criminals not have implants injected into them to track their movments?
Helps when ever theirs a prison brake, to track them down as well as can lead to more RP were they have to bribe/do getto surgery themselves to remove the implant well hiding

## Changelog
:cl:
add: CC has forced more regulations on prisoners fitting them now with an implant to track their movments
/:cl:

### CODE REVIEW

**Comment by Useroth** [comment]
Sounds good to me. I'll leave the decision to Jake.

**Comment by Useroth** [comment]
Gonna put this on hold, since we have plans to add objectives to break prisoners out of there.

**Comment by improvedname** [comment]
Because said implants allow instant teleportation to them

**Comment by LimblessLayabout** [comment]
I'd be fully in favor of an at-spawn Pax chem implant for riot control reasons - a tracker implant would introduce issues as suggested above, and while it makes sense in the setting, I have my doubts it would produce interesting conflict, as much as it would make prisoner life hellish.

**Comment by Trilbyspaceclone** [comment]
@Useroth Im fine with changing the type to be a different pax-injection or something like that.

**Pull request closed without merging**
