### PR TITLE
Makes IPC and synthlizards actually robots

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
So I basically mashed IPC's from oracle with some things from Paradise and some of my own ideas too and got this

IPC and synthetic lizards now have all robotic limbs and organs.. they:
-Their brain is located in the chest, they can run around headless with no hearing, sight, speech
-Dont breathe
-Dont take toxin damage
-Take slightly higher brute and burn, aswell as cold and burn and shock
-Cannot be healed by conventional medicine, need to use welder/cable(unless too damaged) or a new surgery, or a new chemical "Nanite Slurry" made with foaming agent, metal and gold.
-Their limbs are easily re-attachable
-They will get mild damage, stun, confusion and all that mumbo jumbo from an EMP
-Cannot be cloned, but will reboot if repaired above threshold. There's a new long surgery that repairs all damage of a synthetic person, ideal for "cloning"
-They dont need to wear a jumpsuit to hold things on their belt, ID slot, or pockets
-They dont process food and they recharge their battery (nutrition) by drinking welding fuel, plasma or using their arm implant on an APC

You can attach any robot limbs to synths and also do a simple surgery to restore their original look:
-Welder
-Spray can

There's also equivalents of tend wounds and brain surgery.

Added flags to process reagents for synths or organics

Added equivalents of Mannitol and Charcoal for synths.
Liquid Solder - ethanol, copper, silver, temperature >370 kelvin
System Cleaner - ethanol, chlorine, phenol, potassium

Added synthanol (synth alcohol) and all sorts of drinks made out of it. Credits to Paradise
Syntanol: welding fuel, plasma, space lube

IPC get chassis customization.. credits to Oracle? I think?

oh and IPC's also can have slightly transluscent hair now for enhanced toaster GF experience :flooshed:

This PR also nerfs EMP on limbs. It's much less insane now

## Changelog
:cl:
add: Reworked IPC and synthlizards to be actually robotic! Check https://github.com/Skyrat-SS13/Skyrat13/pull/1727 for more info
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
Very good and epic update

**Comment by CinderWC** [comment]
Absolutely love it.

**Comment by ShadeAware** [comment]
Chad

**Comment by Strazyplus** [comment]
YEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

**Pull request merged**
