### PR TITLE
[WIP] Meet the Blueshield 2.0

### PR DESCRIPTION
**Pull request by CinderWC**
**ORIGINAL PR:** #862

## About The Pull Request
Me, Jake and Bob have gone over the entirety of this Blueshield thing again and tested it.
I am almost 100% convinced that this entire project is cursed to hell because we continuously ran into problems with this thing at almost every turn and i just want to die now.

## Why It's Good For The Game
Blueshield's will be a role that is entirely independent from the Security department, with their entire job consisting of protecting the Heads of Staff. They are **NOT** a Security Officer and the roundstart text makes this abundantly clear.

## Changelog
:cl:
add: Added Blueshield Job
add: Added Blueshield Items
add: Added Blueshield Sprites
tweak: changed access.dm to modular_skyrat
imageadd: Added Blueshield Icons
code: Changed a good amount of code to accomodate this new job
/:cl:

### CODE REVIEW

**Comment by CinderWC** [comment]
Looking into this more later im tired

**Comment by CinderWC** [comment]
This doesn't meet the quality standards that i met for myself and i will therefore work on this just a tiny bit more to fix some of the more glaring issues that were pointed out to me (before and after i went to sleep).

**Comment by jjpark-kb** [comment]
still not ready

**Comment by jjpark-kb** [comment]
only resolved one map... The rest are failing.

**Comment by CinderWC** [comment]
very epic

**Comment by CinderWC** [comment]
i changed a single line. and it fails travis

**Comment by BobJoga** [comment]
c cum

**Comment by CinderWC** [comment]
Thanks @Useroth for fixing shit while i was asleep <3

**Comment by CinderWC** [comment]
FINALLY

**Pull request merged**
