### PR TITLE
[READY] Holding people at gunpoint (Bay-style AIMING)

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Using shift + MMB while holding a weapon in your hand will aim onto your target. After a short delay you will lock onto them, provided they didnt escape your LOS.
There will be an aiming reticle and a clear sound that you did lock onto them. Only you see the reticle

After being locked on your victim will get a period of 1.5s of grace period and warnings that he can't use radio, cant use items or can't move. 
If they will do the above you will shoot them, and keep shooting them if they continue.
You can allow/forbid them to do things, they will be notified of this.
Currently the UI for this is a radial menu around the victim, but I could move it onto the main HUD if that proves to be problematic

While locking onto a person you'll be slowed down to walk speed.

Reticle sprites and locking sounds from Outcasts13, rest by me

## Why It's Good For The Game
It's good for roleplay

## Changelog
:cl:
add: You can now aim and hold people at gunpoint (SHIFT + MMB while holding a gun)
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
░░░░░▒░░▄██▄░▒░░░░░░ 
░░░▄██████████▄▒▒░░░ 
░▒▄████████████▓▓▒░░ 
▓███▓▓█████▀▀████▒░░ 
▄███████▀▀▒░░░░▀█▒░░ 
████████▄░░░░░░░▀▄░░ 
▀██████▀░░▄▀▀▄░░▄█▒░ 
░█████▀░░░░▄▄░░▒▄▀░░ 
░█▒▒██░░░░▀▄█░░▒▄█░░ 
░█░▓▒█▄░░░░░░░░░▒▓░░ 
░▀▄░░▀▀░▒░░░░░▄▄░▒░░ 
░░█▒▒▒▒▒▒▒▒▒░░░░▒░░░ 
░░░▓▒▒▒▒▒░▒▒▄██▀░░░░ 
░░░░▓▒▒▒░▒▒░▓▀▀▒░░░░ 
░░░░░▓▓▒▒░▒░░▓▓░░░░░ 
░░░░░░░▒▒▒▒▒▒▒░░░░░░

**Comment by coldud13** [comment]
yooo

**Comment by Yawet330** [comment]
Suggestions taken from ooc
---------------------------------
1) Make it combat mode only (stops people from aiming at you from outside of it, then switching into), while also preventing accidental discharges
2) Make it expire after a certain period - you should not be able to aim at somebody forever
3) Make it unable to track/much more inaccurate past 5 tiles - no more saw sniper memes.

**Comment by Azarak** [comment]
@Yawet330 I dont want to make it expire after a time as this is useful for holding a long RP scene at gunpoint. The other two points are valid though and I've applied the combat mode restrictions now

**Comment by Yawet330** [comment]
> @Yawet330 I dont want to make it expire after a time as this is useful for holding a long RP scene at gunpoint. The other two points are valid though and I've applied the combat mode restrictions now

Thanks, my main concern with a timelimit is just a seccie standing outside of a cell, gun constantly aimed at a prisoner to keep them down, and unable to resist, rather than any real RP-wise, it was just a mechanical thing and I get where your coming from, although there should probably be a new policy drafted up for aiming too, to counteract situations like this.

**Comment by ShadeAware** [comment]
You should really only be able to aim with a type of gun in hand, otherwise you see people aiming at others... with kitchen knives? Switchblades? Etc. Etc.

**Comment by Azarak** [comment]
That was a bug, it's not longer the case and that wasn't the intended behaviour @ShadeAware

**Pull request merged**
