### PR TITLE
[TESTMERGE PLEASE I BEG YOU] Speech setup

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds a speech setup in the character setup. It lets you choose verbs and have a custom speech impediment.
image

**Features:**
- Choosable speech spans
- Robust custom speech replacers
- Choosable custom speech verbs (for say, ask, exclaim, whisper, yell, sing)
- Choosable custom message of gaining the speech modification
- Language restriction
- Datum for easy creation of speech replacers, i don't know what else it can be used for but it's a thing

## Why It's Good For The Game

Character creation fluff - but the best part really is just *not clogging the quirk options with fucking speech impediments*

## Changelog
:cl:
del: Speech impediment quirks are gone - use the speech setup instead.
add: Added a speech setup. Because why not.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Replacers could potentially be a big strain to performance as it's gonna try and parse every single sentence for every single replacers etc.

**Comment by KasparoVy** [comment]
That's fucking hysterical hahaha. Nice.

Chuck LeFuque tax evades, "WIHTOUT OXIGEN BLOB DONT' EVOLUATE?"

**Comment by BobJoga** [comment]
> Replacers could potentially be a big strain to performance as it's gonna try and parse every single sentence for every single replacers etc.

ok what do i do with them

**Comment by BobJoga** [comment]
making a simplified version of this

**Pull request closed without merging**
