### PR TITLE
Box Medical Revert/Revamp

### PR DESCRIPTION
**Pull request by Owai-Seek**
## About The Pull Request

Psych Office has been shrunk, and has been placed closer to Virology.
Virology has been adjusted, taking a little bit of the maint space to fit the psych office in.
Geneticist Office has replaced the psych office.

**This is a draft because, for one, it says it can't automatically merge, and for two, I definitely need my work checked.**

## Why It's Good For The Game

A lot of the new medbay changes make certain areas feel too big, and others much too small. Some have also complained that it's too square, and hard to navigate, as the CMO office is placed dead-center.

## Changelog
:cl:
tweak: Modified Boxstation medbay to be closer to it's original form. With space for both the geneticist room, and psych office.
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
I can already see one thing I goofed up, the double holopad in viro. I'll probably get to it when I wake up.

**Comment by CameronWoof** [comment]
Despite the changes made to Kobe's initial draft, I still feel like the original design of medbay is the superior one. The only thing I really miss here is the hallway access to the psych office, but that is a small price to pay for an otherwise much better layout.

**Comment by ThatGuyFromThatPlace** [comment]
This is, basically the **original** Box medbay at this point, but, with a new virology
We've gone full circle

**Comment by YakumoChen** [comment]
it's almost like a map that that has been a favorite for over a decade was well designed enough to deserve being a map that has been a favorite for over a decade.

Not that box can't use improvements (the pipenet is a major issue), but Box medbay was incredibly well-designed from inception.

**Comment by Owai-Seek** [comment]
This is probably ready to be tested but I don't know how to convert it from a draft.

**Comment by chefferz** [comment]
Much better than the current "revert" that has cloning beside maint and behind a single reinforced wall.

**Comment by YakumoChen** [comment]
Cloning being poorly protected from the maint is a actually a flaw I would like to see to encourage antagonism but I prefer the old medbay regardless

**Review by KathrinBailey — APPROVED** [review]
Alright, so.
Although the new Box had advantages, it also had some not so great parts. It was discussed internally and the decision to go through with this revert was one based on how easy it is to improve.
Was it easier to improve old Box medbay or new Box medbay?
The decision was old Box medbay.

**Pull request merged**
