### PR TITLE
[WIP, Do Not Merge] Ports Lumos Station

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request

Ports over Lumos Station's unique map for admin memery purposes and for the foundation of the forest colony map as well. THe current iteration of Lumos will spawn a planetary map with a large, open, woodland environment full of different beasts. Miners don't have to leave the z-level, giving paramedics a more perilous job too. This will likely only be used for events.

## Why It's Good For The Game
Map man good

## Changelog
:cl:
add: Adds Lumos map, a woodland environment full of hostile wildlife and peril.
code: added more turf options for future woodland map stuff, namely baseturf dirt with RNG flora generation, baseturf snow, sand, and basalt, and foundations for future woodland maps/planet stations
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
https://i.imgur.com/YrI6j1V.png

**Comment by ForrestWick** [comment]
https://i.imgur.com/66j90v9.png

**Comment by Akrilla** [comment]
Any further updates?

**Comment by CinderWC** [comment]
No updates given. Closing.

**Pull request closed without merging**
