### PR TITLE
This PR saves me from being banned

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

takes away '@' from blackbox death message

## Why It's Good For The Game

:)

## Changelog
:cl:
balance: Skyrat Bot has been nerfed, can't ping everyone on discord anymore
/:cl:

### CODE REVIEW

**Comment by hugmeorelse** [comment]
_Quietly taps banhammer against their palm_

**Comment by hugmeorelse** [comment]
Aw, no banning today...

Unless... Perhaps...? 👀@Useroth It doesn't work...?

**Comment by NotRanged** [comment]
Well, there's only one way to find out after this gets merged, right? ;)
Do you volunteer?

**Comment by KathrinBailey** [comment]
image
You've made the history books, buddy.

**Comment by YakumoChen** [comment]
this actually fixes itself if you just remove @everyone privledge from the bot

**Comment by hugmeorelse** [comment]
> this actually fixes itself if you just remove @everyone privledge from the bot

Doesn't work like that. If you do that, it can't ping the role that lets people know a new round has started. The only other way to make it work is to make that role be pingable by everyone else, and that's not really a good option. The only way to fix this is to strip out @ from the death quotes.

**Comment by YakumoChen** [comment]
Make it ping individual users who request a round end notif, not a role

**Comment by NotRanged** [comment]
or just don't merge it yeah see if I care lmao

**Pull request closed without merging**
