### PR TITLE
curator claymore custom icosn

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

title

## Why It's Good For The Game

a guy asked on discord

## Changelog
:cl: Bob Joga and Junglerat
imageadd: New curator claymore icons.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
> Could you give it a bit shading instead of making it a solid color

i'll talk to JungleRat about it, i didn't even do the sprite and i'm honestly just making this PR because hay is bothering me about it on discord

**Comment by BobJoga** [comment]
@Azarak The sprite has been improved and darkened a bit.

**Comment by Azarak** [comment]
@BobJoga What about the belt icon?

**Comment by BobJoga** [comment]
> @BobJoga What about the belt icon?

I'll make it darker later. Rat didn't send me updates for that.

**Pull request closed without merging**
