### PR TITLE
Second^2 Amendment Rights

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

A very, very, extensive list of additions to the makeshift arsenal of the server.
- Contender: A new weapon for traitors that can literally load any type of ammo. Costs 20tc and comes packed with 4 .762 casings.
- Box gun: A shitty makeshift contender. Can fire anything too - with a 50% chance of blowing up and making your arm get chopped off.
- Makeshift laser rifle: A shitty but upgradable makeshift laser rifle. It's not nearly as good as a normal laser gun even when upgraded though, aside from the fact you can hotswap cells.
- Makeshift laser musket: Also shitty, can't hotswap cells, can't be upgraded, and has to be pumped/cranked before each shot.
- Makeshift crossbow: Works as you'd expect, Fires metal rods.
- Makeshift hazard vest armor: Slows you down but gives you decent protection (25 melee)
- Shanks: Made with glass and cable coil. it's what you'd expect.
- Makeshift hatchet: A wrench... wired with a glass blade. It's not amazing.
- VG gun smithing components.
- Rail gun: It shoots metal rods, but relies on a power cell - 5 shots before fully discharged.
- Blunderbuss: Works like a pneumatic cannon, firing any item - but relies of welding fuel to fire.
- Cannon: A more powerful, bulky and semi-stationary blunderbuss.
- Swords: Makeshift swords! There are three types of them: The sword, your standard run of the mill fighter. Shortsword, which trades off damage for agility. Executioner sword... which trades damage and speed for the ability of maybe delimbing your target if you're really lucky.
- Locker mech: It's a bad makeshift mech.
- Holorifle: An aberration of a mix between shotgun and energy gun. Unlocked via RnD, deals a lot of damage with clone damage stacked on top.
- Durathread buff, to be better than the makeshift armor - which it obviously should be.
- Deluxe switchblade: It's a switchblade. But hella expensive and causes burn damage of top of the brute.
- Cane gun: A shotgun. But it's a pimping cane. Traitor item.

## Why It's Good For The Game

It's decent protection against threats - without being too good and overwhelming  when compared to actual factory made guns.

## Changelog
:cl: Bob Joga, Hippie and VG
add: The contender, a traitor gun that can shoot any kind of ammo.
add: Box gun. A very bad contender, which has a 50% chance to delimb you with each shot.
add: New guncrafting components.
add: Makeshift blunderbuss.
add: Makeshift cannon.
add: Makeshift rail gun and crossbow, both firing metal rods.
add: Makeshift hatchet.
add: Three types of makeshift swords.
add: Makeshift armor vest.
add: Shanks.
add: Makeshift laser rifle.
add: Makeshift laser musket.
add: Locker mech - a makeshift mech. Made out of a locker. That kind of sucks.
add: Deluxe switchblade. A switchblade, but it burns.
add: Traitor cane gun. It's a shotgun... in a cane.
balance: Buffed durathread stuff overall.
imageadd: Icons for all this new stuff + icons for the hardsuit armblade.
/:cl:

### CODE REVIEW

**Comment by Feasel** [comment]
Contender is such an awful gun if whoever knows how to switch through ammo types or just rolls a job that has access to some "unique" tools. 

Not gonna say too /too/ much due to I wanna abuse the shit out of it since why not.

But I'll say that instant 60+ hits or 75'ers ain't gonna be fun for security to deal with.

**Comment by Feasel** [comment]
Ehh... fuck it. I'll bring it out.

>Be engineering or science.
>Print tech shells
>Load tech shells into Contender.
>75+ damage buckshots

Or just be said jobs and print an autolathe and do like a billion bullets ala https://cdn.discordapp.com/attachments/646038899486883860/652838633115615232/dreamseeker_2019-12-07_05-47-29.png

**Comment by Feasel** [comment]
Or you can be the same said jobs and pull out the oneshot chem slugs due to it being able to accept such bullets.

**Comment by Feasel** [comment]
Makeshift crossbow sounds pretty fun to be honest. I gotta see if the damage or mechanics will make it OP or not.

**Comment by BobJoga** [comment]
> Contender is such an awful gun if whoever knows how to switch through ammo types or just rolls a job that has access to some "unique" tools.
> 
> Not gonna say too /too/ much due to I wanna abuse the shit out of it since why not.
> 
> But I'll say that instant 60+ hits or 75'ers ain't gonna be fun for security to deal with.

Not a contender exclusive problem. Revolvers and shotguns can do the same (shotgun slugs and .357 both deal 60 damage). A makeshift shotgun is arguably 75% of what a contender is in the right hands.

**Comment by BobJoga** [comment]
i am probably going to chop this up in a thousand smaller PRs

**Comment by BobJoga** [comment]
I will put this PR on hold. The draft will be here just so i can use this as reference when i eventually chop up everything into different PRs.

**Comment by ShadeAware** [comment]
Firestacks for the Deluxe Switchblade, while interesting and possibly useful, tend to have a runoff effect of also setting _you_ on fire, kind of negating the positive aspects of the weapon and decreasing the overall need for it when compared to its material cost. I think just a straight burn damage boost would suffice better.

**Pull request merged**
