### PR TITLE
[Modular][DNM][WIP] Rapid Decal Device

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Adds the Rapid Decal Device. 

## Why It's Good For The Game

The station goes to shit and tiles pop off the floor, no longer is it colored how it once was. This tool aims to fix it. 

I am trying to be like Dr. Frankenstein over here and combine both the crayon/spraycan with the RPD. The problem with crayons and spraycans is that they have a graf_rot which is according to the user.dir. I need to make the direction choose-able, similar to the RPD. You will also see some... pipe stuff which is from the RPD. I need to make those its own thing, but I think it should suffice.
If ANYONE could help with this, I would really appreciate it. I think rather than doing the whole preview_row thing, I could just make four buttons that are assigned to the four directions separately and that they get the icon from the chosen button at the time. Still need work.

The error I get when compiling is:
**modular_skyrat\code\game\objects\items\new_rdd.dm:110:error: recipe.get_preview: undefined var**

Currently, I have an icon (which is shit) and I /attempted/ to make the tgui-next for it. I still need tons of work on it and I may want a ton of help as well.

I believe /vg/ has a decal device thing that is similar, but it is on a different code base, and it looks sort of shitty.

## Changelog
:cl:
add: Added the RDD
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
update, I did this > _** I could just make four buttons that are assigned to the four directions separately and that they get the icon from the chosen button at the time**_
I no longer get compile errors, however, I still need to test it locally.

**Comment by jjpark-kb** [comment]
I got rid of the compiling error, now I get this while trying to rebuild tgui-next

\JJPark-KB\Skyrat13\tgui-next\packages\tgui\interfaces\Rdd.js
  134:5  error  Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?

  132 |                                 </Button>
  133 |                         </div>
> 134 |                   </Box>
      |                   ^
  135 |                 </div>
  136 |       </Section>
  137 |     </Fragment>

✖ 1 problem (1 error, 0 warnings)

**Comment by BobJoga** [comment]
Nice idea. Hope you get it done and don't just abandon it like i do with most of my somewhat complex projects.

**Comment by Useroth** [comment]
aaaaaaa
I need to pick this up like I promised to Jake

**Pull request closed without merging**
