### PR TITLE
Removes 741 commits to cleanse furfaggotry

### PR DESCRIPTION
**Pull request by frontline03**
Imma bout to end this whole mans career

Xyel likes forcing people to erp.

### CODE REVIEW

**Comment by AsaiasWolffe** [comment]
this is all well and good but wheres my cere station?

**Comment by KathrinBailey** [comment]
Okay but have you learned to map yet or can you still contribute nothing of value?
I doubt you've improved from your days of trying to guilt two people for money because all of those many hours you wasted producing something so awful it made me cringe every time you showed it off, it was like you were proud of it.
I was nice and didn't laugh at you for it at the time, so I'll be nice and give you something you need.
image

**Comment by frontline03** [comment]
Have you learnt to tell people you're working on a map?

**Comment by MrFagetti** [comment]
hell

**Comment by basedcringe** [comment]
A failed reckoning

**Pull request closed without merging**
