### PR TITLE
Ghost Cafe Cyborgs!

### PR DESCRIPTION
**Pull request by Funce**
## About The Pull Request

GHOST ROBITS FOR THE GHOST CAFE!!

#### Interference methods covered

- [x] Binary Chat
- [x] Robotics Control Console
- [x] Cyborg Upload Console
- [x] Camera Console
- [x] Module Change to Escape above

## Why It's Good For The Game
Finally... Ghost Borg ERP...

## Changelog
:cl: Sarmenti and Funce
add: Ghost Cafe Robots are now a thing!
fix: Dogborgs no longer 'bork' the chameleon projector
fix: Some other assorted Borg Chameleon projector fixes
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
This is a bad idea, as its almost certainly going to have issues with them being able to interact with the rest of the round in some way, due to how they are coded. You can get pAIs in there now, and dogborgs via that.

**Comment by Funce** [comment]
Borgs off z-level can impact round through the following

- Binary Chat
- Robotics Control Console
- Camera Console

All of these are accounted for. Please explain.

**Comment by Commandersand** [comment]
Law upload console

honestly just add new mobs that just use the cyborg sprites, all they need is to emote and have a flavor text

**Comment by Echopsychotic** [comment]
Personally I like this, and its something I have waited for. And the law upload console means little and the only thing is if they could be linked to the AI. Otherwise if you can cut off binary and their means of linking to the AI. That would be perfect.

**Comment by Funce** [comment]
I'll check that law upload thing out.

**Comment by Echopsychotic** [comment]
Do they have the ability to be blown by the cyborg control console or being seen by it?

**Comment by Funce** [comment]
I'll edit that into the original post

**Comment by Ludox235** [comment]
Once this is done I'm gonna shamelessly steal this PR.

**Comment by Funce** [comment]
Perhaps I should've upstreamed it. Ah well. By all means! Steal away!

**Pull request merged**
