### PR TITLE
start of scp era

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
adds 173.
he only moves when you cant see him.
every 15 seconds, everyone around him will blink, allowing him to move and snap your neck.
adds 049.
he kills and turns people to zombies.
adds 106.
he can walk through walls and send you to his pocket dimension

## Why It's Good For The Game
adds something that can be used for Horror/SCP events

## Changelog
:cl:
add: Added SCP 173
add: Added SCP 106
add: Added SCP 049
soundadd: added neck snaps
/:cl:

### CODE REVIEW

**Comment by Echopsychotic** [comment]
@jjpark-kb Can I just say, we had this? its called the statue that busted you up for existing and couldn't move when being observed. It also did force blind you and cut power to lights. Why not just revamp the statue mob as it is now for this purpose?

**Comment by YakumoChen** [comment]
looks bad and we already have a mob that does pretty much exactly this

**Comment by Owai-Seek** [comment]
To be constructive, there are a few things this needs to be effective, and it should be ADMIN EVENT ONLY. These are just suggestions on how to improve it, and I'd rather list them out here, instead of just forgetting to post them anywhere.

- It probably needs a lunge ability, it's too easy for them to get stuck/locked. in one spot, and unable to attack anyone before the blink runs out. It would also make it easier for them to single out the person attacking them.
- I think I also saw it walking through people, so, it might need a way to cycle harm intent, or be locked to it.
- Blinking probably shouldn't toggle if someone can't actually see it. People can use that to hunt it down / know it's nearby.
- Hitting it with a melee weapon should disarm that person, It's made out of like, concrete.

_Some relatively minor things._
- It's sprite is like, double the size of normal sprites, it's kinda out of place.
- Being that it's made of concrete, it probably shouldn't bleed.
- It would be nice if its health wasn't visible on health HUDs. Honestly, a variable that hides health huds would be really nice to have in general, if there isn't one already.

**Comment by Somememeguy** [comment]
Why not make it a variant of the statue?

**Comment by Echopsychotic** [comment]
I agree with Owai, though I do believe it needs to be buffed in some ways. 
1. Blink needs to last longer, and more frequently
2. there needs to be a prompt saying 'you blinked'
3. make blinking just normal mechanics in the game so people don't know if the SCP is nearby or not anyways.
4. Make physical damage, such as fists, KA (in pressure), and normal on hand weapons that are not rifles do not damage. (vamps included)
5. As owai said, health should not be visible for medical huds.
6. give it the shunt ability if it is stuck. (However, make sure it doesn't work from within lockers) 
Things to look into for future reference:
Synth damage indicators, does it damage synthetics at all? if not then give it a minor damage thing so synths don't just insta revive.

**Comment by ThatGuyFromThatPlace** [comment]
Now... I have a suggestion that's a bit of a stretch... But... What if, 173 could, queue up an action to take during the next blink?
Like, he locks onto a specific tile or person, and, during the next blink, he'll automatically lunge as fast as he can at that target, attacking it if it's a person he reaches

Also, the sprite is kinda... Not the greatest, and, would look a bit better if smaller. Should also live up to his "Peanut" nickname

Also, I definitely think he should deal some damage to the person, (not 200 as that's begging to insta-gib the person's head) and either through damage, or, hard-coding it to do so, guarantee a broken bone wound to the head and, then past that make them die as they do now

Don't know if he can attack borgs, as, I saw a borg absolutely meme on him while he seemingly desperately tried to do something to the borg. Do borgs blink? On that topic, also heard someone mention not blinking while in a mech

And, he definitely should be "Too large" to fit in a locker (Like Otherwordly visitors are, as a quick reference), and, be immune to grabbing/pulling (Like Otherwordly visitors are, once again, as a quick reference)

If made more deadly, and, less meme-able (Meme-able meaning, can't choke slam him into a locker), people would much more properly fear him, instead of gathering around and beating him.

**Comment by YakumoChen** [comment]
VG station has this implimented, both with better code, and a MUCH nicer sprite. Consider porting that instead.

**Comment by MemedHams** [comment]
blink needs to apply only to people with LOS, or be just a general thing that happens(this would be annoying), otherwise it'll be used to meta-track 173 down. Additionally sprite is kinda gross. I haven't taken a look at the other SCP's, but the already-existing statue mob is a fair bit more functional and tasteful of an iteration of this exact concept.

**Comment by jjpark-kb** [comment]
honestly, there has been drama, and I am no longer welcome here.
It was nice to talk to you all and I enjoyed my time here.
We may not have had the best interactions, but I want you to know I wanted the best for the community.
But drama has occurred, so I am leaving.

I will be leaving this message over my current open PRs as I close them.
Adios,
Jake.

**Pull request closed without merging**
