### PR TITLE
[Map Edit: Box] Maint Bar Change

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Changes location and maint bar itself.
okaythen

## Why It's Good For The Game

Make maint bar look nice... also requested.

## Changelog
:cl:
add: Added new maint bar
del: Removed old maint bar
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
I _maaaaay_ have also fixed a missing wire at the pool.

**Comment by CinderWC** [comment]
I was amazed at first at what was done to improve the maint bar, however after Heretic on Discord made their points. I must say i fully agree with them.
pRRjAgR
The whole fun of maint bar/normal bar was to renovate them and make them into your own. With this new maint bar there has to be very little that has to be done, just a bit of de-dusting and overall cleaning to make this a way more superior bar than the standard one and i must say that i actually do not like this whatsoever. It will just lead to an empty bar next to medbay with everyone swarming that new one every round

**Comment by ShadeAware** [comment]
I say you can keep the general layout, but take out most of the nice things such as the carpets and dancefloor etc..

**Comment by jjpark-kb** [comment]
> I was amazed at first at what was done to improve the maint bar, however after Heretic on Discord made their points. I must say i fully agree with them.
> pRRjAgR
> The whole fun of maint bar/normal bar was to renovate them and make them into your own. With this new maint bar there has to be very little that has to be done, just a bit of de-dusting and overall cleaning to make this a way more superior bar than the standard one and i must say that i actually do not like this whatsoever. It will just lead to an empty bar next to medbay with everyone swarming that new one every round

I think thats wrong. This bar does not inhibit the whole renovating. It only has carpets and the like. It may appeal to others and it may not to the rest.

**Comment by Jamini** [comment]
This change also would remove one of the nicer "date, hangout, snog" areas. That being the observatory room aft of the maint bar. Which makes me incredibly sad because I love that particular area for dates/hanging out/lewd things.

**Comment by DexterDude** [comment]
Also why does it spawn with plasma glass stuff. That's a balance issue. 

Also yes it may look nice now and the bartender can change it. But why should they? The bar already looks nice, so no reason to change it. This completely negates inspiration from people, and again, people will go to this bar more because it's actually more fancy than the basic bar if you take the miniscule effort to harm intent spiderwebs and use a tiny bit of cleaner until it's fixed.

Also for your argument about the bartender can come to that bar, that just removes the use of an entire place in the station that is absurdly huge.

     - Heretic

**Comment by Owai-Seek** [comment]
I didn't know this PR coming and I dislike it for a lot of reasons.

- Spiderwebs and glitter, and boarded doors are a pain to deal with. The old bar only had some oil stains on the floor.
- Old bar had two ways to run if you could still reach the entrance. Left through the small atmos room, and right, out to primary hall or down another hallway.
- The bare tiles are incredibly unwelcoming. The old bar was at least semi-serviceable if you didn't bring an entire kit to build with down with you.
- You can't see most of the dance floor or seating area in this setup as a bartender or barfly, and the bar itself is only three seats wide.
- Being in maintenance, (I think) the doors can randomly bolt, or be replaced by walls as well.
- There's also an incredibly cramped secret sex room... when there's two -actual dorms- nearby.
- As someone else said, the observatory is kinda, attached to this now. It's not a secret getaway when you're three steps away from pounding music and a dancefloor.
- The old bar had a rustic charm to it, this is just... not nice.

**Pull request merged**
