### PR TITLE
[READY]Lizard has Brim now

### PR DESCRIPTION
**Pull request by Funce**
## About The Pull Request
LIZARDS ARE BACK WITH THEIR BRIMS

## Why It's Good For The Game
Bugfix

## Changelog
:cl: Seris02
fix: Lizard markings and their tails are now respect what you choose again.
/:cl:

### CODE REVIEW

**Comment by Funce** [comment]
Just gotta double check that this works with BobMed

**Comment by Funce** [comment]
I'll re-open this when I get it working with bobmed

**Comment by Funce** [comment]
Bobmed has to have the other change, so other than that this is good to go.

**Comment by Arctaisia** [comment]
Lizzer with brim? :flooshed:

**Review by KathrinBailey — APPROVED** [review]

**Pull request merged**
