### PR TITLE
[MIRROR] Adds more LGBTQIA+ related holidays

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12505
--------------------
This PR does exactly as it says on the tin, it adds more LGBTQIA+ holidays to cover more than just pride month! List of holidays added are in the changelog. The majority of holidays included in this PR are awareness periods, meaning that even though they fall under the holiday classification in the code, they aren't really celebrated, but rather, used for awareness. As such, the greet text for each one is overridden to convey a slightly more serious tone in contrast with other holidays. None of these holidays have any effects beyond showing roundstart text (No station prefixes, etc). This is fairly minor representation overall, but with the vast majority of our server's playerbase falling under the general LGBTQIA+ label (i mean cmon, it's the furry community, straight folks are extremely rare around these parts), it makes sense to have some level of direct representation of the more marginalized members of the LGBTQIA+ community in the code to go alongside pride month, even if it's something as small as this!

Also, the way holidays are sorted is an absolute mess. Grmbl grmbl.

## Changelog
:cl: Bhijn
add: Added Lesbian Visibility Day (April 26th)
add: Added Bisexual Visibility Day (September 23rd)
add: Added Coming Out Day! (October 11th)
add: Added Intersex Awareness Day (October 26th)
add: Added Transgender Awareness Week (November 13th - 19th)
add: Added the Transgender Day of Remembrance (November 20th)
add: Added Asexual Awareness Week (Last full week of October, this year it'll be Oct. 25-31)
add: Added the Stonewall Riot Anniversary (June 28)
fix: Moth week is now *actually* the last full week of July, instead of the 4th of every weekday + the 5th Sunday.
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
### **_No._**

**Comment by NotRanged** [comment]
> ### **No.**

Because?

**Comment by TheSpaghetti** [comment]
They fucking **merged** this garbage PR? Really?

**Comment by BobJoga** [comment]
> > ### **No.**
> 
> Because?

Isn't an entire month dedicated to pride enough?

**Comment by Investigator77** [comment]
Sexuality shouldn't be celebrated.

As an actual OOC fag, I don't like this PR.

**Comment by TheSpaghetti** [comment]
> Sexuality shouldn't be celebrated.
> 
> As an actual OOC fag, I don't like this PR.

As an asexual, I agree completely, this PR is trash.

I do not want to celebrate my existence.

**Comment by Linzolle** [comment]
stay mad :^)

**Comment by Investigator77** [comment]
Yeah don't merge this here.

**Comment by ShadeAware** [comment]
> stay mad :^)

We aren't mad, this just doesn't need to be here. Pride Month is enough, as its all-encompassing. Adding more and more mini-holidays does nothing but bloat the code and cause confusion.

**Comment by NopemanMcHalt** [comment]
wtfdyjbutcl

**Pull request merged**
