### PR TITLE
Increase overall projectile speed by 50%

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request

Increases overall projectile speed by 50%
## Why It's Good For The Game

Makes gunplay more straight , makes dodging bullets at 30%+ Dilation harder ,projectiles will tend to hit more at long-ranges.

## Changelog
:cl:
balance: Projectiles are now 50% faster
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
image

**Comment by MLGTASTICa** [comment]
Preety sure that comment is meant for var/pixel_increment_amount , not var/pixels_per_second

**Comment by KasparoVy** [comment]
Fight the colossus now, muahahaha!

**Comment by Azarak** [comment]
Projectile speed is handled in config

**Comment by MLGTASTICa** [comment]
I've changed it to modify the projectile speed in config.

**Comment by BobJoga** [comment]
i feel colossus is gonna be iffy because of this, might need to lower death bolt speed

**Comment by Akrilla** [comment]
This was a config thing I added, but changing it here does not change the config on the live server. If you'd like this changed please ping maintainers.

**Pull request closed without merging**
