### PR TITLE
Removes the constant alien noises from xenohybrids

### PR DESCRIPTION
**Pull request by CameronWoof**
Incredibly irritating. No other race does this, and we should be damn thankful for it. 

## Changelog
:cl:
tweak: Xenomorph crewmembers now have a unique, quieter tongue.
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
They need the tongue for the beno language

**Comment by CameronWoof** [comment]
What about the language necessitates the tongue?

**Comment by Azarak** [comment]
It's got my approval after it's actually a subtype of the alien tongue :p

**Comment by KittenCatnip** [comment]
Delet this

**Pull request merged**
