### PR TITLE
Hey look it's another mining PR from Bob

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Nerfs Sif because he wasn't made with our move speeds in mind
Buffs Sif's sword because it's trash tier currently
Buff's the drake's ghost sword because it's also trash tier currently
Adds more loot to necropolis chests (lava walking and fire resistance medals, premium KA, staff of lockers with 1 maxcharge)
Replaces the enchanted mosin in the necropolis chest with a normal mosin
Modularizes the current drake armor stats because of that one Citadel PR
Nerfs Inquisitor and Champion hardsuits (necropolis chests versions only so ERTs dont get fucked), the only way to get the real suits now is by getting it as a legion chest drop

## Why It's Good For The Game

this section always feels like i'm bluffing to a police officer that has stopped my car because i was driving recklessly because i drank a copious amount of alcohol and maybe accidentally ran over pedestrians

## Changelog
:cl:
add: Lava walking and fire resistance medals to necropolis tendrils.
add: Locker staff as a necropolis tendril drop (1 max charge).
balance: Only legion chest drops have a chance to spawn the real inquisitor and champion hardsuits.
balance: Replaced the enchanted mosin necropolis chest drop with a normal mosin.
balance: Nerfed Sif a ton to be actually reasonable on our movespeeds.
balance: Nerfed inquisitor and champion hardsuits on the necropolis chests.
balance: Buffed Sif's sword drop.
balance: Buffed the drake's ghost sword.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
The premiumka is just unneeded bloat, on par with the diamond pickaxe. You don't always get that many tendrils, so when you do and its just trash you don't want, it really sucks. You are already nerfing the hardsuits by making it more unlikely they will drop, and I really don't think the nerf is needed in the first place. Same with the whole mosin nerf.

**Comment by BobJoga** [comment]
> The premiumka is just unneeded bloat, on par with the diamond pickaxe. You don't always get that many tendrils, so when you do and its just trash you don't want, it really sucks. You are already nerfing the hardsuits by making it more unlikely they will drop, and I really don't think the nerf is needed in the first place. Same with the whole mosin nerf.

The mosin thing isn't a nerf. The enchanted mosins cannot be reloaded at all.
The premium KA is actually good. Maybe not terribly good, but i'd be fine with receiving it after killing a tendril. I honestly didn't think the nerf was necessary myself but someone else would make a salt PR about it anyways, considering i see constant complaints on the discord about it.

**Comment by improvedname** [comment]
PKA is a mining reward not loot drops you already have the BPKA for that case bob

**Comment by Rayfod** [comment]
If people want to complain and code in an actual suit, then shoot. Let them do that, but taking away some of the best loot there is, for little to no reason. It is just going to throw salt to people that have done mining, and play mining daily. 
And let's not forget that you have to fight a Pulsating Tumor, to get one of these chests, or a legion skull.
Sure, the luck of yours would be pretty gigantic for getting the suits, but taking away the effect that makes it special, just leaves you with loot that nobody wants, and ruins the unique feel of getting it since everyone is "jealous" at the person with it, which makes them want to go for more.

**Comment by Akrilla** [comment]
Make your titles informative about what it's changing :knife:

**Comment by BobJoga** [comment]
> Make your titles informative about what it's changing 🔪

I touched a lot of stuff so i don't even know what i'd name this

**Comment by BobJoga** [comment]
> If people want to complain and code in an actual suit, then shoot. Let them do that, but taking away some of the best loot there is, for little to no reason. It is just going to throw salt to people that have done mining, and play mining daily.
> And let's not forget that you have to fight a Pulsating Tumor, to get one of these chests, or a legion skull.
> Sure, the luck of yours would be pretty gigantic for getting the suits, but taking away the effect that makes it special, just leaves you with loot that nobody wants, and ruins the unique feel of getting it since everyone is "jealous" at the person with it, which makes them want to go for more.

65 melee is still better than all the other mining suits, + it is fireproof
there is no way you could say this isn't unique

**Comment by SpaceVampire** [comment]
I just feel like the hardsuits nerf really isn't needed. It makes a cool item that you won't be lucky enough to get all that often seem less cool.  I'll admit that I wasn't sure about the whole mosin thing, given that I tend to just leave it on the ground once I find it, and again don't add the PKA, you can buy it, and already get a better one by killing the blood drunk miner, its just going to add more clutter to the loot tables. I would like it if it was refactored so all the PKA mods were just one thing, and then it rolled between them, because as someone who uses the crusher, its on the same tier as getting the diamond pickaxe or the other joke options.

**Comment by BobJoga** [comment]
this probably isn't going to be merged either lol

**Comment by BobJoga** [comment]
closing the PR tomorrow if no review or merge pops up

**Comment by BobJoga** [comment]
this isn't going to be merged or discussed ever

**Pull request closed without merging**
