### PR TITLE
Normalizes Cheems

### PR DESCRIPTION
**Pull request by Owai-Seek**
Let's see if I still know how to make PRs.

## About The Pull Request

Updates to Cheems:

Fixes death state.
Changes description.
Changes speech lines to boofs and borks.
Changes butcher results to 1 burger, 2 meat, and a syndie-cakes wrapper.

## Why It's Good For The Game

Normalizes Cheems with other pets while still leaving them somewhat unique. Also, death state fix.

## Changelog
:cl:
tweak: Cheems now makes dog noises. Description updated.
fix: Cheems now shows up when dead.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
Brb making a PR to normalize ian.

**Comment by Investigator77** [comment]
Cheems saying stuff like "Shomtgun crate!" "Burbger.." etc. is part of what the pet represents. It's pretty much the only special thing about him as a pet.

**Comment by ShadeAware** [comment]
Bad PR. Stop trying to ruin our fun, Owai.

**Comment by Weblure** [comment]
> Cheems saying stuff like "Shomtgun crate!" "Burbger.." etc. is part of what the pet represents. It's pretty much the only special thing about him as a pet.

Maybe he shouldn't be a pet on an HRP server, then...

**Comment by Investigator77** [comment]
Fuck off already. It's MRP-HRP, this is not BayStation either. Let people have fun. If you want 100% serious job simulator just pop in at one of the /fully serious HRP servers/

**Comment by XyvMeph** [comment]
Cheems was a shit PR to begin with, and having him talk takes away from Poly. Cargo doesn't need two pets, and if a PR request "Ruins our fun" then that implies you're a group doing stupid shit, so stop, thanks.

**Comment by BobJoga** [comment]
> Cheems was a shit PR to begin with, and having him talk takes away from Poly. Cargo doesn't need two pets, and if a PR request "Ruins our fun" then that implies you're a group doing stupid shit, so stop, thanks.
> 
> He's literally an ancient meme. You may as well have given them kermit the frog.

I only kept the sloth because Jake asked.

**Comment by BobJoga** [comment]
> > Cheems saying stuff like "Shomtgun crate!" "Burbger.." etc. is part of what the pet represents. It's pretty much the only special thing about him as a pet.
> 
> Maybe he shouldn't be a pet on an HRP server, then...

Content that the supposeddly HRP server has:

here's the list of content to get yeeted so far
- Crab 17
- Chaplain LRP meme bibles
- Every meme poster
- Chef CQC
- Cumming into reagent containers such as glasses
- Revolver plant that can be gotten via xenobio
- Baseball antag kit
- Lord singulo antag kit
- His grace
- Skeleton rattle me bones
- A bunch of clown traitor items
- Moth traitor lamp
- Research director rod suplex

You cannot justify it with being grandfather in because Baystation is actually consistent, and removed old meme content including clowns.

**Comment by xXPawnStarrXx** [comment]
The only pet that should talk, should be poly, a damn Macaw, a creature that can talk.

**Comment by BobJoga** [comment]
> The only pet that should talk, should be poly, a damn Macaw, a creature that can talk.

So what is the logic here? We're gonna remove unrealistic content?

**Comment by xXPawnStarrXx** [comment]
Not remove it, just not add MORE that's unneeded.

**Comment by BobJoga** [comment]
> Not remove it, just not add MORE that's unneeded.

I've stated in the discord why this doesn't work, and generally isn't a good justification

**Comment by Weblure** [comment]
> > Not remove it, just not add MORE that's unneeded.
> 
> I've stated in the discord why this doesn't work, and generally isn't a good justification

I don't see how it isn't. Just because some LRP-ish things were added in years ago, that doesn't mean that people should go out of their way to add in more LRP content. This, respectively, means we also shouldn't also go out of our way to comb through a decade's worth of content to purge anything that may be considered LRP, no matter how minor.

If you want to start a campaign to begin removing LRP content from Skyrat, that's fine with me. But such a large undertaking should be done bit-by-bit with feedback for each item, not randomly selected off the top of your head and purged all at once in a knee-jerk reaction.

I worded my opinions in an unprofessional and hostile manner, and I apologize for that. Regardless, I still stand behind those opinions and my reasoning. No matter how you try to put it, the existence of some old, subtle, and/or rarely-seen humor content does not justify the addition of an internet meme dog that spams the chat with internet meme text, especially if you plan to give it comms and add the ability to weaponize it without reason.

Just to be clear, I have nothing against you personally. I just strongly detest the fact that you'd go this far to defend a shitpost PR and attempt invalidate every shred of feedback given. A lot of us left Citadel to escape this type of shitposting and LRP nonsense, and while it doesn't justify our negativity -- especially not mine -- it shouldn't be surprising that you'd get this kind of reaction here.

**Comment by Erokusan** [comment]
With all of the things you've mentioned that are memes and LRP in ss13, besides the cumming into a container (I consider that some people probably have that fetish _shudder_) and Chef CQC (I'm not even sure why this is considered a meme, it actually means the chef is in their kitchen when people can easily greytide over the counter, just like the bartender and his shotgun) are things that don't often happen, if at all actually.
The research director being able to stop (suplexing) an immovable rod (which is an anomaly) is LITERALLY A MECHANIC; the meme comes from its origin, but stopping a rod is pretty damn important regardless of how its described being done.
On the other hand, the plans some have for Cheems is SO much more for a pet then it should be, sure it can talk meme phrases, sure you can butcher it and get a fucking burger and syndi-cakes out of it. But what I don't like is the fact that some would also want the **PET** to also effect the singularity, to also effect immovable rods, and weaponize the fuck out of those two things, which is definitely not something you should even start wanting to happen, because I guarantee people will abuse those.
Honestly making Cheems semi-normal I feel would be almost a reality check more then anything, have your meme pet sure, hell keep it in cargo for all I would care, but there has to be a line at some point, before it becomes less of a meme and more so an abusable mob that many will likely complain about

**Comment by BobJoga** [comment]
> With all of the things you've mentioned that are memes and LRP in ss13, besides the cumming into a container (I consider that some people probably have that fetish _shudder_) and Chef CQC (I'm not even sure why this is considered a meme, it actually means the chef is in their kitchen when people can easily greytide over the counter, just like the bartender and his shotgun) are things that don't often happen, if at all actually.
> The research director being able to stop (suplexing) an immovable rod (which is an anomaly) is LITERALLY A MECHANIC; the meme comes from its origin, but stopping a rod is pretty damn important regardless of how its described being done.
> On the other hand, the plans some have for Cheems is SO much more for a pet then it should be, sure it can talk meme phrases, sure you can butcher it and get a fucking burger and syndi-cakes out of it. But what I don't like is the fact that some would also want the **PET** to also effect the singularity, to also effect immovable rods, and weaponize the fuck out of those two things, which is definitely not something you should even start wanting to happen, because I guarantee people will abuse those.
> Honestly making Cheems semi-normal I feel would be almost a reality check more then anything, have your meme pet sure, hell keep it in cargo for all I would care, but there has to be a line at some point, before it becomes less of a meme and more so an abusable mob that many will likely complain about

Justifying those things as being mechanics doesn't work - because i can say the same about Cheems eating immovable rods. It would actually be a useful strategy. That and the chef CQC is literally "haha what if CQC... but it stands for Close Quarters Cooking!". And if it's fine to have meme mechanics as long as they're not internet memes, it means i can safely put a monty python holy grenade, a monty python rabbit, or even making casseroles explode in the microwave.

**Comment by BobJoga** [comment]
> > > Not remove it, just not add MORE that's unneeded.
> > 
> > 
> > I've stated in the discord why this doesn't work, and generally isn't a good justification
> 
> I don't see how it isn't. Just because some LRP-ish things were added in years ago, that doesn't mean that people should go out of their way to add in more LRP content. This, respectively, means we also shouldn't also go out of our way to comb through a decade's worth of content to purge anything that may be considered LRP, especially if it's something minor.
> 
> If you want to start a campaign to begin removing LRP content from Skyrat, that's fine with me. But such a large undertaking should be done bit-by-bit with feedback for each item, not randomly selected off the top of your head and purged all at once in a knee-jerk reaction.
> 
> I worded my opinions in an unprofessional and hostile manner, and I apologize for that. Regardless, I still stand behind those opinions and my reasoning. No matter how you try to put it, the existence of some old, subtle, and/or rarely-seen humor content does not justify the addition of an internet meme dog that spams the chat with internet meme text, especially if you plan to give it comms and add the ability to weaponize it without reason.
> 
> Just to be clear, I have nothing against you personally. I just strongly detest the fact that you'd go this far to defend a shitpost PR and attempt invalidate every shred of feedback given. A lot of us left Citadel to escape this type of shitposting and LRP nonsense, and while it doesn't justify our negativity -- especially not mine -- it shouldn't be surprising that you'd get this kind of reaction here.

I feel like most players here don't want a deadpan serious server. Removing LRP content is only going to anger people about things that always were there, suddenly vaporized. If you want to go the route of removing *new* LRP content, you cannot justify the old ones - It's not fair to me or anyone as a dev to have their content removed because we didn't code something for citadel a year ago. If old meme content doesn't justify the addition of new meme content, it should be removed. Period.

I have no intention of removing LRP content because it would harm the server, and would turn us into a boring ass server like Baystation ever since they removed clowns. But as i said, at least Bay is consistent - they removed meme/joke content no matter the age, they didn't try justifying it because it's old, they were fair in their judgement. If the server is going to take such an approach, there **must** be commitment to it, otherwise it's just not fair at all to devs and will always result in whiplash when one part of the code is memery and the other is ever so serious.

That said, it is very possible to be HRP with meme/joke content. CEV Eris has the wide putin meme coded in, out of all things. Though it is fair to say that a roundstart funny dog doesn't compare to an admin only wide putin, which is why i can understand complaining about the shotgun and immovable rod features.

**Comment by Owai-Seek** [comment]
There's a very clear difference between Cheems, and other pets. He speaks nonsensical meme voicelines, while every other pet just kind-of -exists-. It's clear he's an outlier, and while some of the stuff Ian can do is silly, it is not at all on part with this:

("Burbger...", "McDomnald...", "Whompper...", "Bimg Mac...", "Whemre are the miners?", "Revolutiom!",\
				"Pizza cramte.", "Collemctable hats...", "Research mining tech stupid sciemtists!", "Where's my rimpley?",\
				"Shomtgun crate.", "Free cargo!", "No horny.")

As for contributing more memes, vs removing old ones, -that stuff was already there.- From years of TG/Citadel existing. If someone dislikes it, they make a PR, and an argument, to try and remove it. Some stuff is silly, but it's not blatant. This is extremely on the nose.

"I feel like most players here don't want a deadpan serious server."

This isn't deadpan serious stuff, it's removing over-the-top voicelines for a pet because no other pet is as ridiculous as this.

**Pull request merged**
