### PR TITLE
[april fools testmerge] NanoTrasen implements a more secure cargo supply console

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Supply consoles will now only show supply packs the person has access in their ID for.

## Why It's Good For The Game

cargo gets fucked lol
negojohson

## Changelog
:cl:
balance: Nerfs cargonia
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
I don't like this. There are thimh s that would have access restrictions that hurt nobody by being ordered, and this should be a thing admins bwoink over, not something everyone should be punished for

**Comment by CinderWC** [comment]
Hello! I have to echo Forrest in his opinion. There is many opportunities where Cargo has benefited from having access to Crates outside of their actual Restriction Range.

For instance: On Cult rounds it is custom for Cargo to order mindshields and possibly Shotguns and Armor to combat the Cult, this would be impossible.
If this was merged, a Sec Officer would then have to come and order these things on the supply console which would waste time a lot of time.

I feel that it is more important for Admins to /enforce/ anti-powergaming rules rather than restrict players in what they can and can't do mechanically in the game.

**Comment by ShadeAware** [comment]
This seems like a ham-fisted way of curbing a problem that's much wider than this could really hope to solve. Plus, it will become a detriment to the station at large should supplies be desperately needed but never arrive due to a lack of access.

**Comment by BobJoga** [comment]
I'm discussing the issue with staff. We're gonna get a more sensible solution. However - i will not close the PR, i'll leave it hanging for a while just in case.

**Pull request closed without merging**
