### PR TITLE
[MIRROR] ports several tg events including fugitives

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12548
--------------------
## About The Pull Request
this ports the following tg round events:

brain trauma: someone gets a random brain trauma on the station, values were changed so no magic resilience on the trauma is possible

fake virus: people get fake virus symptoms but no actual virus

wisdom cow: a cow that speaks wisdom appears, due to lack of tg skills, instead of awarding skill xp it is milkable for liquid wisdom, which is basically mannitol but slightly better (also this means you can vv cows/goats now to set what they produce honk)

stray cargo pod: random cargo supply pod falls to the station with its location announced, rare variant drops a syndicate supply pod instead containing uplink stuff

fugitives: several fugitives appear on station, after ten minutes a hunter ship appears, with ghost roles able to be taken to become a hunter and catch the fugitives!

## Why It's Good For The Game
more roundevents is good

## Changelog
:cl:
add: ~~Adds the brain trauma event, where one player gets a random brain trauma!~~ It's commented out.
add: Adds the wisdom cow!
add: Adds the fake virus event, where people get fake virus symptoms.
add: Adds the stray cargo pod event, where a cargo pod crashes into the station.
add: Adds the fugitives event, where fugitives are loose on the station, and it's the hunters jobs to capture them.
/:cl:

### CODE REVIEW

**Comment by IrkallaEpsilon** [comment]
Random Brain Trauma event.. yikes. Yet another scene ruiner just like Appendicitis and Heart attack. Argueably worse because split personality roll chance.

Wisdom cow feels pretty LRP.

Fugtive: Can be pretty good. Though Waldo is ech.

Fake virus sounds good.

Stray Cargo pod: Gives engineering something to do I guess? There are too many engineering events though.

**Comment by Rayfod** [comment]
I do believe that we can add the dorms areas here, to make sure that the cargo event, does not effect them
```
///Picks an area that wouldn't risk critical damage if hit by a pod explosion
/datum/round_event/stray_cargo/proc/find_event_area()
	var/static/list/allowed_areas
	if(!allowed_areas)
		///Places that shouldn't explode
		var/list/safe_area_types = typecacheof(list(
		/area/ai_monitored/turret_protected/ai,
		/area/ai_monitored/turret_protected/ai_upload,
		/area/engine,
		/area/shuttle)
		)
```

**Comment by Owai-Seek** [comment]
Fake Virus, Fugitives, and Cargo Pod seem somewhat fine (from a gameplay standpoint.) Don't like the chance of a random trauma or wisdom cow. (I do like simplemob spawns, but more like, carp migration type stuff.)

**Comment by BobJoga** [comment]
> I do believe that we can add the dorms areas here, to make sure that the cargo event, does not affect them
> 
> ```
> ///Picks an area that wouldn't risk critical damage if hit by a pod explosion
> /datum/round_event/stray_cargo/proc/find_event_area()
> 	var/static/list/allowed_areas
> 	if(!allowed_areas)
> 		///Places that shouldn't explode
> 		var/list/safe_area_types = typecacheof(list(
> 		/area/ai_monitored/turret_protected/ai,
> 		/area/ai_monitored/turret_protected/ai_upload,
> 		/area/engine,
> 		/area/shuttle)
> 		)
> ```

No. Fuck having all these ERP protections.

**Comment by KathrinBailey** [comment]
> I do believe that we can add the dorms areas here, to make sure that the cargo event, does not affect them
> 
> ```
> ///Picks an area that wouldn't risk critical damage if hit by a pod explosion
> /datum/round_event/stray_cargo/proc/find_event_area()
> 	var/static/list/allowed_areas
> 	if(!allowed_areas)
> 		///Places that shouldn't explode
> 		var/list/safe_area_types = typecacheof(list(
> 		/area/ai_monitored/turret_protected/ai,
> 		/area/ai_monitored/turret_protected/ai_upload,
> 		/area/engine,
> 		/area/shuttle)
> 		)
> ```

Added dorms to the list. 👍 
Will probably come back to this PR at another time.

**Comment by KathrinBailey** [comment]
> Random Brain Trauma event.. yikes. Yet another scene ruiner just like Appendicitis and Heart attack. Argueably worse because split personality roll chance.

Brain traumas have been commented out. 👍

**Pull request merged**
