### PR TITLE
Adds an HEV suit for the Research Director

### PR DESCRIPTION
**Pull request by BobJogaIsForkinBanned**
## About The Pull Request

Title. The HEV suit does what you'd expect: Annoy you with a robotic female voice depending on occasion, inject you with medicine if you're in a critical situation, and protect your from hazards.

**A lot of the assets, such as the sprites, were taken from PR 12726 on the hippiestation repo.**

## Why It's Good For The Game

Pop culture references are fun. Not only that, but this makes the RD have a hardsuit that is actually unique and useful, and not a throw away item that is just an expensive bombsuit.

## Changelog
:cl: Bob Joga and the guys who did it on hippie
add: The RD now has an HEV suit, which has decent armoring overall against all types of damage, but lacks against bombs.
imageadd: HEV suit and helmet icons.
/:cl:

### CODE REVIEW

**Comment by Strazyplus** [comment]
but I like the RD suit, memes are okay but I'd rather have the RD suit

**Comment by BobJogaIsForkinBanned** [comment]
> add the HEV suit in another means, RD suit looks great specially with the naga taur body. please do not replace it. I suggest using the variant mod kit for this.

The standard RD suit look kind of silly (just looks like a high tech bomb suit), i barely see anyone use it and it generally serves little purpose. The HEV is a good replacement.

**Comment by Commandersand** [comment]
yeah pretty sure the suit was designed as a bomb suit visually, i think some servers have it at toxins.
It does look good though, maybe at the current one to a special bombsuit crate and give it bomb protection?

**Comment by BobJogaIsForkinBanned** [comment]
> add the HEV suit in another means, RD suit looks great specially with the naga taur body. please do not replace it. I suggest using the variant mod kit for this.



> yeah pretty sure the suit was designed as a bomb suit visually, i think some servers have it at toxins.
> It does look good though, maybe at the current one to a special bombsuit crate and give it bomb protection?

Ok so, yeah, let's reach a compromise - i'll add the old RD suit to a cargo crate.

**Comment by BobJogaIsForkinBanned** [comment]
> > add the HEV suit in another means, RD suit looks great specially with the naga taur body. please do not replace it. I suggest using the variant mod kit for this.
> 
> > yeah pretty sure the suit was designed as a bomb suit visually, i think some servers have it at toxins.
> > It does look good though, maybe at the current one to a special bombsuit crate and give it bomb protection?
> 
> Ok so, yeah, let's reach a compromise - i'll add the old RD suit to a cargo crate.

I just let the RD have the old suit by default and added the HEV to his locker.

**Comment by Azarak** [comment]
As it was already mentioned in other discussions. Please do not copy paste assets. It'd be much better if the thing had a ss13 spin on it, something our own.

And also why is there like a 100 unused assets added?

**Comment by BobJogaIsForkinBanned** [comment]
fuck this copyirght compliance shit, i'm not making a value brand version

**Pull request closed without merging**
