### PR TITLE
Change Central Command Safe/War Zones

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
Changes how the safe/war zone tiles work. Once crossed, you cannot cross back.
Added a heal tile.
Changes how centcom looks.

## Why It's Good For The Game
better choice for EORG

## Changelog
:cl:
add: Changed Centcom's safe/war zone layout
add: Added a heal tile
tweak: tweaked how safe/war zone tiles work
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
Just putting this here for clarity, this is supposed to be an alternative to this PR, which afaik, has some things requested to be changed. https://github.com/Skyrat-SS13/Skyrat13/pull/3158

As for suggestions on this one, the zone transfer lines are much too close to the shuttle, people could easily lag across or get pushed into them and get stuck inside. There's also no door to the gambling room at the bottom.

I'm not sure why you'd want to restrict people from coming back across, there might be a problem that I don't know about? Borgs/medics will often enter the death zone (at their own peril) to grab people and save them. Is there a reason for that change?

**Comment by Echopsychotic** [comment]
I will be frank, I don't like how big it seems. I know the size is basically similar it just seems far too spacious.

**Comment by jjpark-kb** [comment]
> Just putting this here for clarity, this is supposed to be an alternative to this PR, which afaik, has some things requested to be changed. #3158

Was told to remove something because "sneaking" stuff in is not good. They complied and removed it.
But then they added another thing to try and "sneak" in. Not good to do something like that that jeopardizes your PR.

> As for suggestions on this one, the zone transfer lines are much too close to the shuttle, people could easily lag across or get pushed into them and get stuck inside. There's also no door to the gambling room at the bottom.

Multiple questions/things on in this. So I feel it isn't that close, especially since a person would have to unbuckle and then walk through the door. I also don't know about developing maps with people who lag badly in mind.

The gambling den has a way into it. One of the walls you are able to walk through. 

> I'm not sure why you'd want to restrict people from coming back across, there might be a problem that I don't know about? Borgs/medics will often enter the death zone (at their own peril) to grab people and save them. Is there a reason for that change?

It was actually the original intent to the safezone and stuff. Once you choose to be safe, you gotta stay there.

**Comment by calibraptor** [comment]
> Was told to remove something because "sneaking" stuff in is not good. They complied and removed it.
> But then they added another thing to try and "sneak" in. Not good to do something like that that jeopardizes your PR.

No I didn't.

**Comment by Owai-Seek** [comment]
It's not individual players that lag, it's the server as a whole when the shuttle docks.

As for choosing one, or the other, what if the round is extended and people want to go have a duel, or go in to rescue people after things have happened? I don't understand the reasoning behind why you -have- to stay in a zone.

**Comment by ShadeAware** [comment]
This is a far more hackjob version of the far better map edit PR, which you closed for... an easteregg. 🤔

**Comment by jjpark-kb** [comment]
> This is a far more hackjob version of the far better map edit PR, which you closed for... an easteregg. 🤔

perhaps people shouldn't try to sneak stuff in.

**Comment by calibraptor** [comment]
> 
> 
> > This is a far more hackjob version of the far better map edit PR, which you closed for... an easteregg. 🤔
> 
> perhaps people shouldn't try to sneak stuff in.
> Better? That is quite subjective.

Again, the thing you claim I tried to 'sneak in' afterwards was already in the PR to begin with and prominently featured in the original screenshots.

I've made a new PR without any easter eggs. If you see something you don't like in it, actually talk to me instead of closing it. Thanks.

**Pull request closed without merging**
