### PR TITLE
Removes spacevine space spreading, removes spacevine door opening, adds spacevine player scalling

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Title - also changes the fulltile growth % from 50 to 35 to not grow as fast. (used to be 20 originally). 
Added scalling that can be easily changed with the defined values. Currently its balanced around 70 people, more people  can make the vines be up to 130% effective, less people can make them be as effective as 40%. Also moved the event start cap to atleast 20 people, because chances are that its a colossal pain/nuisance for a 10 man crew.

## Why It's Good For The Game
More balanced spacevines, also player scalling which should be very helpful for downstreams. The doors can be opened by venus traps so its not that much of an issue

## Changelog
:cl:
balance: rebalanced spacevines, they cant open doors or spread to space, their effectiveness is player number scalled, they also fully grow slower, and the event itself can only start from a minimum of 20 people
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
And now spacevines are right back where they started, never becoming an actual threat.

**Comment by Azarak** [comment]
> 
> 
> And now spacevines are right back where they started, never becoming an actual threat.

Most often than not we'll be more than at 100% effectiveness, which means they'll spread faster. Space spreading was kind of ridiculous and hurt the CPU at times. And previously the kudzu didnt spawn with three venus boys either. I think you're overexaggerating.

**Comment by Oscari-pog** [comment]
The only good part of this is removing the space spreading

**Comment by Tename** [comment]
Limiting it to twenty people seems good to me IMO, thats mostly it though.

**Comment by Gandalf2k15** [comment]
Suggest only removing the space spreading part. Otherwise code is good.

**Comment by davidchan13** [comment]
> > And now spacevines are right back where they started, never becoming an actual threat.
> 
> Space spreading was kind of ridiculous and hurt the CPU at times. 

If only someone had pointed out this very thing in the original PR. Oh wait!

**Comment by YakumoChen** [comment]
Vines aren't supposed to be an absurdly dangerous event in the first place, more a nuisance than anything that only gets bad if you don't deal with it quickly.

**Comment by Gandalf2k15** [comment]
As far as I can see this is actually a decent refactor, as it's buffed in some areas.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
