### PR TITLE
[Map Edit: Box] Science and Geneticist Change

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Does many things:

1.  Changes layout of Xenobiology
2.  Changes maintenance below Xenobiology
3.  Adds a dorm room for Xenobiologists.
4.  Changes location of Experimentor Room.
5.  Changes location of Circuitry Room.
6.  Adds Nanites Room roundstart.
7.  Moves Heater/Cooler in Science to Toxins.
8.  Changes layout of Genetics, moved into Science.
9.  Adds an office in Medbay; Perhaps Psychologist/Psychiatrist...
10.  Adds a roundstart Drone Printer
11.  Adds shutters to RD, CMO, and QM

newxenobioooo
newxenodormsmaint
newshitttt
newtoxinsforsure
newgenetics
newgenepsy
newshutters

## Why It's Good For The Game

Huge changes that are good changes, are good changes.

## Changelog
:cl:
add: Changes layout of Xenobiology
add: Changes maintenance below Xenobiology
add: Adds a dorm room for Xenobiologists.
add: Changes location of Experimentor Room.
add: Changes location of Circuitry Room.
add: Adds Nanites Room roundstart.
add: Moves Heater/Cooler in Science to Toxins.
add: Changes layout of Genetics, moved into Science.
add: Adds an office in Medbay; Perhaps Psychologist/Psychiatrist...
add: Adds roundstart Drone Printer
add: Adds shutters to RD, CMO, and QM.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
windows separating the cells would look 200% better double-stacked 
image

**Comment by Azarak** [comment]
I dont like this for a variety of reasons.
-The pens look too squeezed in and considering they're all see through this will yield in a overload of information, emoticons and noises from the slimes.
- I think it's uglier that way
- I dont like how we no longer have that space area south
- I dont like another maintenance door for an area that's supposed to be somehow containable in case of a monster outbreak

**Comment by CinderWC** [comment]
I approve of almost all of these changes. **EXCEPT**

i7M97n9
I feel that adding a second maintenance door and removing the space area there sort of messes with the style of the hallway that was there all this time.
When i used to main Cargo i kinda loved going through the hallway because it had a really cool atmosphere to it, and allowing you to just have that glimpse into xenobio after you have spent the rest of maint in almost utter darkness was a cool touch.

I dont feel that a second maint door into Xenobio is needed, nor do i want it as it ruins the atmospheric feel of that hallway

**Comment by ShadeAware** [comment]
The thought of this idea is pretty solid, and I sort of like the way its being done. BUT with that being said, this just... doesn't look visually appealing. Infact, its quite ugly.
My main gripes:
image
These look unnatural, and sort of mesh poorly with the rest of the structure in the room.

image
These just look... bad. Double-sided 1 side windows have never looked good on anything, and here its no different. Consider replacing it with a full metal wall as it was before.

image
This is less important on my list, but I really miss the space that was in this hallway. Also, that door is a bit too accessible for what should be a pretty high-security (or atleast, closely watched, as with the maintenance tunnel near the control consoles) area.

All in all, not a bad idea, but a fairly poor execution. Needs a lot of work.

**Comment by Trilbyspaceclone** [comment]
image
That one person that always plays Sci suggestion - This

**Comment by LimblessLayabout** [comment]
Since I was the one to propose it - Here's the TGstation layout we had originally intended to emulate; 
https://cdn.discordapp.com/attachments/683102192667721768/700826420871561387/dreamseeker_fcKKdkJgVl.png
Besides gaining 50% more rooms to separate slimes out into (a blessing for sorting), my thoughts were largely on 'visibility', as I find xenobio to be very walled in and 'in the dark' regarding station events most of the time, and in the event of a breakout, or some similar situation in the xeno department (kidnappings, xenos nesting, etc) I'd hoped to make it easier to see from Science mainhall through the length of the xeno department - not full vision, but significantly longer sight-lines.
In particular, this: https://cdn.discordapp.com/attachments/683102192667721768/700849719513055252/unknown.png
makes it easier to view into xeno's main area from science mainhall.
And this;
https://cdn.discordapp.com/attachments/683102192667721768/700850696605532321/unknown.png
was proposed in the hopes that, say, a single laser could travel from space, through the pens, through the window immediately above, all the way to science mainhall. Space sniper takes down RD with 1-in-a-million shot.
I'd really like this maint space-viewing deck to be considered part of the department, as this whole space sees very little utilization.

**Comment by CinderWC** [comment]
>fully functional ERP dorms room IN maintenance below xenobio which deleted a really cool looking shuttle wreck that could be refurbished for fun rp

>Same change in maint also entirely ruined a really cool looking hallway

>Geneticists being moved to the experimentor room an entire department away, so that freshly cloned people have to get through 3 locked doors to have mutations and quirks removed after cloning, not to forget that Geneticists are also then counting as Science, which then add to an already bloated department

>Adding a new room for Physicians, which dont even exist in code yet with **REINFORCED WALLS THAT BORDER THE MORGUE AND MAINT DAFUQ?**
unknown



Also, you cant tell me that any of this looks better as this just makes the station look more bland and fucking boring:

unknown

As an example: This is what Kathrin did to that one room near the recycler: It is a room that has to be made functional and shows clear signs of disrepair, your changes however add a FULLY FUNCTIONAL erp room for no real reason...
fQCj1la


Also what is up with these random padded floors in the patients room?
unknown

I feel that this entire PR just boils down to fixing something that isn't broken. None of these changes are needed whatsoever, and IF this is considered to actually be merged in the state it is now, i would like this to be a testmerge because i am 100% sure all the people that actually voted for this will end up **HATING** these changes and regret them immediatly (Just like the abysmal maint bar changes)

**Comment by Ghommie** [comment]
Someone told me to voice my opinion here so:
The new xenobio is uncanny, the clearer vision of the workplace could have been achieved by replacing the walls between pens with fulltile windows anyway.
The lounge/office beside the cloning/morgue are unpractical on so many levels. Never seen such a thing in any pop culture crime fiction either.

**Comment by jjpark-kb** [comment]
> Someone told me to voice my opinion here so:
> 
> * The new xenobio is uncanny, the clearer vision of the workplace could have been achieved by replacing walls between pens with fulltile windows.

I can understand that the look may not be appealing to some, apologies. The reason for the change though was not with visibility in mind, that would just be an unintended effect. The reason for the change was to add additional pens. From 6 > 9. Three more pens may not be a whole lot, but it does give xenobiologists more storage.

> * The lounge/office right beside the cloning/morgue is unpractical. Never seen such a thing in any pop culture crime fiction either.

Could you tell me either here or in Discord why this is impractical? We are eventually going to get a psychologist/psychiatrist role. I would love to make it practical and still have a certain feeling. Also, I am not sure about the whole pop culture crime fiction, could you explain it to me?

> * The padded flooring by the "transfer" room make the decals look unnatural, also way out of scope.

I should probably remove that. Thank you for reminding me.

> * Roundstart nanite machinery was removed for a good reason, at least upstream.

I understand they are extremely strong. But the office is still useless until people research the nanite programs. It would be nice to at least see if it can fit in. If not, it can later be changed to something else.

> * New genetics by sci looks bad with that window separating the two work stations.

I just wanted them to be somewhat split. I can remove the glass separating them. 
Thank you for the feedback. Please continue to give more as the PR progresses.

**Comment by Azarak** [comment]
Way too many changes and way too many things I dont like tbh

**Comment by CinderWC** [comment]
> 
> 
> Way too many changes and way too many things I dont like tbh

Yeah the PR has WAY too many controversial changes and they should all be split up into different PR's if i am fully honest here.
There is things that i REALLY like here like the new toxins, but there are WAY more things i dislike here than i like and i do not want to see this entire wallop merged as is

**Comment by Azarak** [comment]
Well a lot of the changes are pretty good. My main issues with it is xenobio, the ERP room and toxins. I'm not so sure how do I feel about genetics but the other changes I like.

I gave my feedback more in detail to Jake and let's see how it turns out

**Comment by Owai-Seek** [comment]
I have more opinions on the maint PR than this one, and honestly think that one should be reverted because it wasn't given time to simmer over testmerges, and 42% of the people who voted, voted -not- to go through with it, and many more didn't know it was happening until it was already merged, and many of whom dislike the changes. 

For -this- one however, I have these thoughts. (As I don't particularly interact with science all that much.)

- There was no vote to change Geneticist from Medical to Science Staff, and I very much feel than most people are going to be distracted with the cosmetics of the PR, and not realize this change is happening. Medical has trouble getting staff as-is, and geneticists are great for emergencies. They are almost always at their monitors trying to unlock new powers.
- Replaces the geneticist office with a lounge for a role we don't even have, and the look/feel is inconsistent with medbay as a whole.
Even if we do get that role, I -really- don't think it should be in medbay, or if it is, it needs to be tucked away from all the medical noise and bodies.
- The full ERP room is really -really- dumb, and the old hallway looked amazing. There were several viable ERP room candidates in that area before this change. The entire look of that hallway could have been preserved by moving it down by one tile.
- The circuits room is tiny, unwelcoming, and leaves no room for people to test things. AFAIK, the old circuits room was also used to set up extra machines and experimental tech if it wasn't being used for circuit testing.
-Also, yea, the floor is odd and I didn't even notice that on first pass. Seems kinda weird.

Below is an example of a bunch of places that could be retrofitted into maint dorms, and before you go telling me science doesn't have maint access, they have literally all of the tools necessary to cut into all of these places on-hand roundstart, and they can very easily make their own autolathe.

image

**Comment by jjpark-kb** [comment]
> **These are things that _need_ to be fixed**
> • RD bedroom/xenobio bedroom(?) is more or less in maint and is kinda of out of place. If blood cult ever gets enabled again, this will have to be removed due to balance. I did something like this before, giving maint a room with doors to bolt with a button. Guess what happened? Every blood cult round people made cult bases there and bolted themselves in. With Skyrat having metashields, this will downright break cults (Remnants of this can be found with the "Powerful Gamer Toggle" in furniture storage). If this bedroom has the bolt toggle and shutter IDs to the RD then it's less of an issue, but it's still really awkward and out of place.

I removed the door bolt. This should prevent that cult stuff, unless they modify the door in game. There are other rooms in maint that are similar in manner, so it should be fine to still be in.

> • Dividing windows between the geneticists is unnecessary

Ghommie suggested, so I have removed it.

> • Showroom floor under shower in cloning looks out of place. Left of it in medbay is a shower over white plating, it should just be consistent with that. If you want a shower drain, consider placing a passive vent connecting to nothing and renaming it.

Done. Replaced with normal white tile and added a "drain".
> • Check pixel_y offset for your random official poster spawners around cloning. It looks like it might be 30 or something, it should be 32.

Done. They were 30, now they are 32.

> • Floor lights cause burn damage on click. It's also inconsistent as we don't use floor lights on the map roundstart at all. Try using light tubes and put the mon the fulltile windows next to the disposal bins. We have lights on windows already so it'll be fine, that'll light the area up better than floor lights.

Other maps have floor lights round start. Removed them anyways and placed tubes on RGlass.

> • Genetics missing intercoms and fire alarms.

Fixed, thank you.

> • New toxins mixing area missing intercoms.

Fixed, thank you.

> • Experimenter room missing intercom.

Fixed, thank you.

> • Remove unnecessary double wall.
> image

Fixed, thank you.


> I have not tested the map, I haven't loaded it and tested disposals/atmos/wiring etcetera.

They should work just fine.

> **These are personal gripes and suggestions that _do not_ need to be fixed, but it'd be nice to see changed. These are not requested changes, just personal "it'd be cool if you could do X/Y/Z" stuff.**
> • Not a fan of having two break rooms/lounges opposite each other. The room to the right of cloning should be made into changing rooms for people who have cloned so they don't have to show their naked bits off to everyone in medbay.

It isnt two break rooms/lounges. I may change the room next to cloning into a changing room, I just havent decided yet though. Doctors should be fine with seeing genitals, since Doctors in real life have seen a lot of stuff, genitals is not much. Thank you for the feedback!

> • Not a fan of expanding xenobio, but as I don't play xenobio, I'll stay out of this one. Maybe consider letting xenobio make those scrubbers in the cells to harvest gas themselves? There's already one RPD, atmos pipe dispenser could replace the RPD and be shared for toxins mixing and xenobio. It's better than giving toxins a RPD anyway because weh use the darned pipe dispensers for once.

I have removed the scrubbers and pipes roundstart. You are right that they should make their own if they want to scrub.

> • I'm 50/50 on making geneticists part of science. Science is currently not a good place to specialise your character. Apart from robotics, the only thing to do after toxins is xenobio. @Owai-Seek mentioned that geneticists are still needed in medbay to fix brain traumas post-cloning but I'm not a medic main. Moving geneticists to science sounds like it should be an all map or no map deal, so you can actually move them from the medical jobs to science jobs and amend their access.

This PR is already large enough to concern others, so I will just keep it to changing Box for the time-being. Later, if this works, I will format genetics into a science job on other maps and amend their access. However, Their access works just fine on Box.

> • Normal wall to the RD's office from genetics instead of rwall. Not too fond because it's far too easy to go into genetics via maint, run down to where the air alarm is in the RD's office.

Fixed, thank you for the feedback.

**Comment by CinderWC** [comment]
>I removed the door bolt. This should prevent that cult stuff, unless they modify the door in game. There are other rooms in maint that are similar in manner, so it should be fine to still be in.

Remove the dorm room entirely, its out of place and looks goddamn stupid.
Bring back the old hallway in its stead

>I will format genetics into a science job on other maps and amend their access. However, Their access works just fine on Box.

How about you make an emojicracy about that already and stop ignoring Owai when he brings up the valid point: You have not made a very clear vote about it and only mentioned the change on the side. Make a **FULL ON DEDICATED** vote to it

**Comment by jjpark-kb** [comment]
> I have more opinions on the maint PR than this one, and honestly think that one should be reverted because it wasn't given time to simmer over testmerges, and 42% of the people who voted, voted -not- to go through with it, and many more didn't know it was happening until it was already merged, and many of whom dislike the changes.

Then dont bring that up, it isnt relevant to this PR.

> For -this- one however, I have these thoughts. (As I don't particularly interact with science all that much.)
> 
> * There was no vote to change Geneticist from Medical to Science Staff, and I very much feel than most people are going to be distracted with the cosmetics of the PR, and not realize this change is happening. Medical has trouble getting staff as-is, and geneticists are great for emergencies. They are almost always at their monitors trying to unlock new powers, and they can see when things are happening in medbay.

Changing their location does not mean changing their department. It will eventually be changed. I have linked to this Github so if they read the Vote, and even take the time to look at the Github, then they can see the change. It is not my issue if someone votes without reading. Similar to how you agree to terms and conditions without reading the law-language. Perhaps moving them can increase RP by forcing them to be pulled over by either the CMO or hailed over comms.

> * Replaces the geneticist office with a lounge for a role we don't even have, and the look/feel is inconsistent with medbay as a whole.

We are going to eventually add the role, this is not an issue. It fits perfectly in medbay in my opinion.

>   Even if we do get that role, I -really- don't think it should be in medbay, or if it is, it needs to be tucked away from all the medical noise and bodies. I can't imagine seeing corpses dragged in and out of cryo, or hearing people being defibbed and screaming outside is very good for the mind.

Again, this is not an issue. Do you want me to change the map even more than it is right now? I am currently focusing on Science, the change in medical was just a result in the change in Science. I will later change it perhaps.

> * The full ERP room is really -really- dumb, and the old hallway looked amazing. There were several viable ERP room candidates in that area before this change. The entire look of that hallway could have been preserved by moving it down by one tile.

Changed. Thanks for the feedback. It is now a lounge.

> * The circuits room is tiny, unwelcoming, and leaves no room for people to test things. AFAIK, the old circuits room was also used to set up extra machines and experimental tech if it wasn't being used for circuit testing.

Circuits was too large in the room. Yes, it was used for testing, but perhaps they can use the testing room in the room next door. I might even add a testing room later on. I do not want to make the PR larger.

> * Also, yea, the padded flooring in medical is odd and I didn't even notice that on first pass. Seems kinda weird.

Removed, thank you.

> Below is an example of a bunch of places that could be retrofitted into maint dorms, and before you go telling me science doesn't have maint access, they have literally all of the tools necessary to cut into all of these places on-hand roundstart, and they can very easily make their own autolathe.
> 
> image

Not required as I changed the dorm to something else. I would like to say that I made a science dorm, not a maint dorm. That is what makes this different.

**Comment by Strazyplus** [comment]
I liked the space bridge below xeno. what replaces it is not favorable and a ERP Room. ew just no, please. how about you complete the shuttle to be actually functional and but disrepair enough to be repaired without needing hardsuits make it an escape pod that you need to do some repairs on perhaps?

also the cloning room I love the edition of lockers but take down the walls separating the lockers to the cloners.  feels a bit cramped

**Comment by primezerozero** [comment]
Geneticist room is way too big. If it were even two tiles shorter, it'd feel better.

**Pull request merged**
