### PR TITLE
Revert "[MIRROR] Meta station atmos opening up"

### PR DESCRIPTION
**Pull request by Akrilla**
Reverts Skyrat-SS13/Skyrat13#1657

### CODE REVIEW

**Comment by Akrilla** [comment]
A mirror PR was put in, and very quickly players weren't a fan. This is just the auto generated PR when selecting revert.

**Comment by MrJWhit** [comment]
Could you be more specific in what you mean by "players weren't a fan"? I'm still looking for improvements and any feedback would be incredibly helpful.

**Comment by Akrilla** [comment]
Atmos techs felt it was more tedious/busy work than engaging for them. They enjoyed what was there before since it was a reasonable basepoint, and could be expanded/modified than needed, rather than "forced" to fill it out.

**Comment by MrJWhit** [comment]
All right then, thank you. As a heads up, there were a few adjustments on this PR that, if you revert it, should be re-introduced, because it's a bit wild.
-The vents/scrubbers in the atmos control room are actually connected to those waste/air pipes leading out of atmos _not_, the general distro/waste line.
-On the far left of the PR, there's an L-pipe where there should be a T-junction

**Pull request merged**
