### PR TITLE
Changes collar bans to use a trauma instead

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
No longer there's 2 types of those too, just one. It should retain the old collar bans

I didn't test it as I couldn't be bothered to set up a DB but im fairly sure this works

## Why It's Good For The Game
Collars weren't the best idea as they may come off as creepy, especially shock ones

## Changelog
:cl:
fix: Changed collar bans to use a trauma instead
/:cl:

### CODE REVIEW

**Comment by BobJogaIsForkinBanned** [comment]
Aww, why though? Now how can be bullied the pacified players?

**Comment by BobJogaIsForkinBanned** [comment]
On a serious note, this change is alright and i mostly agree with it.. The only gripes i have are the following:
- The subsystem will just keep curing and brain damaging the person, because it will just fire regardless of condition. This isn't a big complaint as we are not using the subsystem, but just a heads up.
- As a brain trauma, there are many many ways to cure it, and a trait would have been a safer option in my opinion.
- The old collars were completely removed from the code. I disagree with the complete removal from the code and think they should stay, even if only for admin shenanigans.

**Comment by CinderWC** [comment]
I like the idea of collarbans as it seems nice and Orwellian and dystopian to see megacorporations force collars like that on their workers

**Comment by Azarak** [comment]
@BobJogaIsForkinBanned The proc that's handling application of the trauma won't apply it if he already has it, subsystem is fine

**Comment by BurgerLUA** [comment]
Collar bans were fetish content. Unironically.

**Pull request merged**
