### PR TITLE
Tranquility gives pacify

### PR DESCRIPTION
**Pull request by Akrilla**
## About The Pull Request

Changes gondola transform to forced temporary pacify.

## Why It's Good For The Game

Forced transformation into a simplemob with no cure isn't very engaging.

## Changelog
:cl:
tweak: Tranquility now pacifies, without any transformation.
/:cl:

### CODE REVIEW

**Comment by BobJogaIsForkinBanned** [comment]
Dunno how i feel about this

**Comment by CinderWC** [comment]
Why is this needed?

**Comment by ShadeAware** [comment]
### SALT PR

**Comment by BurgerLUA** [comment]
> ### SALT PR

stop

**Comment by Akrilla** [comment]
Being tf'd forever into something isn't very engaging for the player.

**Comment by BobJogaIsForkinBanned** [comment]
> Being tf'd forever into something isn't very engaging for the player.

Tbh it's acceptable Yeah actually, i'm fine with it.

**Comment by Akrilla** [comment]
closed for burgers

**Pull request closed without merging**
