### PR TITLE
Changes to the ghost cafe, small CC changes, adds the stack fabricator device.

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request

This PR does quite a few things. While I prolly should've separated the features into different PRs, it was all made for the singular purpose of making the ghost cafe more appealing to those who don't wanna deal with the round or get ganked early and don't wanna respawn as another character.

The PR makes numerous changes to the ghost cafe and adds a new machine that dispenses a material stack dispenser (all credit for this goes to Kobe/Jjpark on Discord). The machine/item will be able to dispense stacks of any material you want, ranging from metal, to gold, to plasma, to whatever you can think of that you might need. It was suggested I give these to bluespace techs, but when I try to search for them in the files Dreammaker has a tantrum.

The changes to the ghost cafe and CC are pretty big, so I'll list them off in a list.
>Massive construction zone added to the north end. Please share with your fellow cafe goers. There's enough room for everyone if you share and manage space well.
>Added a ticket prize booth to  the arcade machine area, along with a slot machine line.
>Added a botanical chem dispenser to botany
>Added a disco area to the bar/diner
>Added a large dining table to the bar/diner
>Added a pool below the construction zone
>To the eastern end, you'll find a new zone built for combat exclusively. There's nuclear operative uplinks, weapons, armor, tools, and chem machines for all your bomb/deathmix making needs. To protect the other cafe goers against this, the zone uses the pacification tiles for those who exit it and kill zone tiles when you enter. There are also turnstiles to prevent people from throwing bombs or shooting into the cafe zone proper. There are windows looking into the room as well that are invulnerable.
>When you exit the spawn room in the cafe, where the sleeper is, you will hit a pacification tile. 
>South of the bar is a dodgeball court.
>There is a small medical area next to the dodgeball court.
>VR sleepers are in the hall on the way to dorms.
>A circuit imprinter and engineering lathe have been added to the north side by botany. The options for AI modules and computer boards has been removed from the imprinter.
>To the far south, there is a specialized, much smaller construction zone built for Vox exclusively. It has materials, two cannisters of N2, and an invisible atmos fan at the door. There is also indestructible windows here.
>On the way to the Vox Box area is a library zone with bookcases and a big table in case you wanna do stuff like truth or dare/dare dice or Tabletop RPGs. There's also a line of vending machines too.
>The south east end has a massive outdoors area connecting the ghost cafe zone to CC, with the default zone being a foresty area while the southern end is a snowland. The snowland is cold, so pack a winter coat (located at the entrance of the foresty zone in a closet).
>Upon passing through the woods, you can enter CC, though your access is limited. Your only available rooms are the kitchen, bar, and non-admin observatory of the Thunderdome. Everything else is locked off by what should be unbreakable doors. If you try to get further into CC, you risk a ban.

POSSIBLE ISSUES:
The foresty outdoors area might be devoid of breathable air. If this is the case, alert me ASAP. It's fine on my end, but anything can happen after this would get merged.
On top of that, it might not be possible that the cafe is 100% grief proof. I've done everything I can to ensure that people can't nuke the place or get weapons out of the combat zone. If I can't solve something, then do note that admins will likely ban you very quickly for griefing in the cafe, and if it gets bad enough I'll remove the thing entirely or bring it back to the original state. DO NOT BE THE ONE TO RUIN THIS FOR OTHERS.

## Why It's Good For The Game
People complained about the ghost cafe being boring, and people seemed to like my lavaland syndicate base changes and old station changes, so here. You now have everything yo ucould ever want. This provides people a way to escape frustrating rounds without having to switch servers, or a spot to vibe if they got ganked by antags and don't wanna respawn as a different character.

## Changelog
:cl:
add: Added a device and machine called the Rapid Stack Spawner, which can be used to obtain infinite materials (Thanks jjpark)
tweak: Made some sweeping edits and additions to the ghost cafe (see the PR description)
/:cl:

### CODE REVIEW

**Comment by Funce** [comment]
Wow, this is amazing! Nice work with it!

**Comment by Echopsychotic** [comment]
I really hope this isn't griefed or used to grief. I think this is great PR. I will if or when its test merged/merged also be giving feedback in regards.

**Comment by Arctaisia** [comment]
Yes yes yes yes yes yes yes, this is based and great, we should merge this as soon as possible

**Comment by Owai-Seek** [comment]
I don't think it's wise to expect people to use things in good faith/not abuse them, that rarely works out well. The biggest issues I see are the VR chambers (possible metagaming issues), plasma dispensing from the sheet dispensers, people shooting riot darts basically -everywhere-, and chem-dumping in the botany room with mutations now being possible.

Other than that, I guess it just feels like there's a lot of empty space? Worst case scenario I'd probably want to tweak the location of a few things if this gets passed to make it more aesthetically pleasing.

Oh, and the animals in the dorm area is a bit weird, maybe move them out to the forest?

**Comment by ForrestWick** [comment]
> I don't think it's wise to expect people to use things in good faith/not abuse them, that rarely works out well. The biggest issues I see are the VR chambers (possible metagaming issues), plasma dispensing from the sheet dispensers, people shooting riot darts basically -everywhere-, and chem-dumping in the botany room with mutations now being possible.
> 
> Other than that, I guess it just feels like there's a lot of empty space? Worst case scenario I'd probably want to tweak the location of a few things if this gets passed to make it more aesthetically pleasing.
> 
> Oh, and the animals in the dorm area is a bit weird, maybe move them out to the forest?

The animals in the dorm area are weird, but it's mostly for fun than anything. If it gets merged and you wanna make edits, feel free, but this is mostly just gonna be a temporary thing because I'm gonna delete the ghost cafe altogether, expand CC, and have THAT be the cafe tbh. That project will take a while, but still

**Comment by IrkallaEpsilon** [comment]
I am going to be a ghost cafe main now. Thank you :)

**Pull request merged**
