### PR TITLE
[READY] [Modular] Mech-fabs can now be attached to bluespace storage silos.

### PR DESCRIPTION
**Pull request by Useroth**
Port of https://github.com/quotefox/Hyper-Station-13/pull/104
## Changelog
:cl:
tweak: mechfabs are now bluespace silo compatible
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
fuck just merge this already jesus christ
even my admittedly shitty PRs get merged faster than this

**Comment by BobJoga** [comment]
WHY
IS THIS NOT MERG Ed

**Comment by BobJoga** [comment]
roboticists waiting for this to be merged be like
thatskeletonfunny

**Comment by ShadeAware** [comment]
Please God

**Comment by ShadeAware** [comment]
### AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Strazyplus** [comment]
> wonders why his synthtail PR still sitting for two days
>Sees this PR 
>ONGOD
source

**Pull request merged**
