### PR TITLE
[https://en.wikipedia.org/wiki/Semen]Probably fixes most of the reskinning problems caused by that last PR with Muhreen's sprites i don't know if it works no i won't test it fuck you

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

fixes some fucking issues with the last fucking PR
since i don't ever test my PRs anyways i wont test this one either
fuck you
maybe it works maybe it doesn't fuck you

## Why It's Good For The Game

[Fuck you](https://www.youtube.com/watch?v=XVON0vP8k4s)
fuck github you dont let me fucking embed shit go fuck yourself

## Checklist
- [x] I'm pretty sure this will work.
- [x] I compiled my code locally.
- [ ] I tested the general functionality locally.
- [ ] I thoroughly tested and reviewed my code.
- [x] Removed herobrine

## Modularization
- [ ] My code is not modular.
- [ ] My code is not modular, but the changes are minor and non-invasive.
- [ ] My code is partially modular.
- [x] My code is fully modular.
- [x] My code is spaghetti.
- [x] I fucked your mom.

## Changelog
:cl:
add: HoS suit and hats can be reskinned now. Same for warden suits and hats.
fix: Reskin bugs have been fixed, children of armor wont be affected by reskinning
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
changeeloog

**Comment by BobJoga** [comment]
> changeeloog

whats wrong with it 4chan told me its based and redpilled and redditors will go soy over it hahahaa

**Comment by Useroth** [comment]
Don't meme in changelogs that get saved and put ingame later.

**Comment by BobJoga** [comment]
> Don't meme in changelogs that get saved and put ingame later.

ok the channgelog isnt memed now

**Pull request merged**
