### PR TITLE
Glaurung removal

### PR DESCRIPTION
**Pull request by DarkWolfInsanity**
It's come to my attention that someone has been spawning my ash drake without my permission and giving control of them to randoms. As Glaurung is my character, I did not give permission for this. Thus I'm making this pull request to remove him from the server as your staff don't seem to respect a simple "don't play as other people's characters".

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I really have no idea why you would put your character into the codebase for general use, if you cared if other people got to play them. I mean, when you look at the PR for him, it doesn't say anything about this: https://github.com/Skyrat-SS13/Skyrat13/pull/1023. I don't even care about if it gets removed or not, that just seems fuckin weird.

**Comment by calibraptor** [comment]
Wasn't the entire point of it to allow player controlled drakes that wouldn't be blinded on lavaland?

Why shoehorn in your OC in the first place?

**Comment by SarmentiCampbell** [comment]
lmao

**Comment by BobJoga** [comment]
Wow i don't even know what to say.

**Comment by jjpark-kb** [comment]
Everyone else has said it in here:

>An admin spawned Ash Drake with no agression unless attacked. Mostly used for Admemery roleplay. Blaurung acts much like a standard megafauna, with AI when not possessed, a gps beacon, and loot when killed.

Once content is in the game, you can't control it anymore. People are free to do whatever they want to do with it.

**Comment by hugmeorelse** [comment]
We respect people's private content that gets introduced properly, whether it's for donator content and the like. However, you never mentioned in the first place this was just for you. You've said this in your original PR: "An admin spawned Ash Drake with no agression unless attacked. **Mostly used for Admemery roleplay.** Blaurung acts much like a standard megafauna, with AI when not possessed, a gps beacon, and loot when killed."

If it was just for you, we would have rejected the PR outright. You failed to mention this at all. Either, A) you lied by omission to get what your own private OC in the game. B) You're making this claim to troll or salt. Based on what some players here were thinking, they thought it was a dragon from the Lord of the Rings.

Either ways, it does not look good. We'll be happy to pull him from the game if it is due to A), however, this also means you will no longer be allowed to play on Skyrat any more if you're going to abuse the system for your benefit due to violating our Server Principles.

**Comment by hugmeorelse** [comment]
> It's come to my attention that someone has been spawning my ash drake without my permission and giving control of them to randoms. As Glaurung is my character, I did not give permission for this. Thus I'm making this pull request to remove him from the server as your staff don't seem to respect a simple "don't play as other people's characters".


@DarkWolfInsanity 
We respect people's private content that gets introduced properly, whether it's for donator content and the like. However, you never mentioned in the first place this was just for you. You've said this in your original PR: "An admin spawned Ash Drake with no agression unless attacked. Mostly used for Admemery roleplay. Blaurung acts much like a standard megafauna, with AI when not possessed, a gps beacon, and loot when killed." If it was just for you, we would have rejected the PR outright.

Either, A) you lied by omission to get what your own private OC in the game. B) You're making this claim to troll or salt.

Based on what some players here were thinking, they thought it was a dragon from the Lord of the Rings.

Either ways, it does not look good. We'll be happy to pull him from the game if it is due to A. However, this also means you will no longer be allowed to play on Skyrat any more if you're going to abuse the system for your benefit due to violating our Server Principles.

**Comment by ThatGuyFromThatPlace** [comment]
https://lotr.fandom.com/wiki/Glaurung
Not your OC, unless you're also admitting to shamelessly ripping off LOTR for an "**Original** character"
Secondly, trying to avoid being rude... The fact that you tried to put in your character as a mob and refuse the ability for others to play it, is, selfish at best

**Comment by DarkWolfInsanity** [comment]
Just fucking ban me and get it overwith. I spent weeks working up lore for Glaurung and lavalands through rp only for randoms to destroy it, so of course I would feel possessive of them. So i'll just say yes if it makes you all happy to get rid of me. Not like this community enjoyed having me around in the first place. Half the admins want me gone, the playerbase only cares about my characters and not myself. Who wouldn't be upset

**Comment by SarmentiCampbell** [comment]
Fucking hell.

**Comment by hugmeorelse** [comment]
> Just fucking ban me and get it overwith. I spent weeks working up lore for Glaurung and lavalands through rp only for randoms to destroy it, so of course I would feel possessive of them. So i'll just say yes if it makes you all happy to get rid of me. Not like this community enjoyed having me around in the first place. Half the admins want me gone, the playerbase only cares about my characters and not myself. Who wouldn't be upset

I am not banning you. You never stated any of this in the PR. That is the point many of us are making. You are acting rude over something that you never stated in your original PR and accusing us of things that laid beyond our knowledge. It is perplexing and confusing. Please take a moment to relax and think. 

If something else is going on, please DM me, and we'll talk it out.

**Pull request closed without merging**
