### PR TITLE
[DNM] A bunch of dogborg Sprite improvements, reworks & fixes & High Luminosity Eyes tweak!

### PR DESCRIPTION
**Pull request by Strazyplus**
## About The Pull Request

**DO NOT MERGE**
I am closing this PR because of last night. I was talking with admins about borgs speed problems and in a corner was a destroyed borg. it's wreck animation was playing correctly and it was one that was missing.

I have backed up my changes but I am purging my files and reapplying my work. This is to fix my GitHub set up but as well potentially avoid causing any corruption of the sprite files. the missing animations were MISSING on my end. my files were damaged.

**UPDATE!!**

because I am a newb I been doing all my branches on my master. and I was attempting to make another PR but merged it into this one! 

**HIGH LUMINOSITY EYES!**
They turn off if you lose consciousness. you can turn them back on when you regain consciousness. 
**THANKS PUTNAM!!**

This PR started as a collection of several small improvements to various dogborg sprites within the Widerobot.DMI file. I ended up spotting some missing assets and repaired them along the way.

**K9 DARK - NO MORE COW UDDER!**
For some reason the rear side of the K9 DARK Had redish rear side which kinda looked like a cow udder. from the side, the belly should be white, not red and looking like an udder. so I fixed this by recoloring.... 
K9UDDER

**ENGINEERING VALEBORG RECOLOR!**
I found the Engi Vale borg a bit too vibrant and an eye sore. so I decided to recolor it to be in-line the other vales especially the miner vale variant which is perfect imo. this makes the engineering borg look much nicer

VALEENGIBORG

**RESTORES MISSING VALE WRECK ANIMATIONS!**
at somepoint someone on citidel PR'd and broke almost all of the Valeborg wreck animations within the last two months and it went under the radar. I fixed them you are welcome

P4gDjq4Ps2

Minor improvements to all valeborg sprites. they had coloration problems on the neck which most of them had dark purple sprites as if they were copied off the service vale sprites... If I did not mention it I doubt anyone would have noticed.

## Why It's Good For The Game

High Luminosity Eyes 
if you are a synth lizard with a screen for a face. your screen will go black wew!!

restores missing animations 
Redo of the Engineering valeborg. they look much better now.
improves K9 Dark sprites to have less of a cow udder.
general sprite fixing.

## Changelog
:cl:
tweak: Added code to make High LUM eyes to disable when you lose conciousness.
tweak: tweaked K9Dark & Medihound Dark sprites
tweak: corrected coloration errors on all Valeborg sprites
tweak: Redone Vale Engineer borg sprite colors to be in-line of the other Valeborg color scheme.
fix: fixed missing animations on the majority of Valeborg wreck animations
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
👏

**Comment by Strazyplus** [comment]
u6Oq1yS

**Comment by CinderWC** [comment]
7ml7l04x70j31

**Comment by Strazyplus** [comment]
Gifs above of the wreck animation is not the final one so ignore if it looks incorrect.

**Pull request closed without merging**
