### PR TITLE
[MIRROR] Proto-Kinetic Glaives - a crusher reskin

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13003
--------------------
## About The Pull Request
light wip?
it's a crusher reskin (with a sick ass goliath hide grip)
more balanced than adding a second level to lavaland/clicking on wounded fauna for an ego-stroke and a heal
citadoes what downstreams don't :)

todo: parry
image

## Why It's Good For The Game
cool stick that can't be called a hammer
## Changelog
:cl:
add: Proto-kinetic glaives! Essentially a proto-kinetic crusher with a different blade, handguard, and goliath hide grip. Expensive, but elegant.
/:cl:

### CODE REVIEW

**Comment by Investigator77** [comment]
Sprite kinda looks like ass (Just kidding, not kinda, it ///looks like ass///). Paying for a reskin is cringe

**Comment by Owai-Seek** [comment]
Only looks "bad" on lighter floors, lavaland is generally a darker tileset. Seems fine to me if it's just a reskin / mining point drain.

image

**Comment by Investigator77** [comment]
The sprite lacks a lot of detail. If I don't like something, it doesn't have to be because it's from upstream.

**Comment by KasparoVy** [comment]
The design is dope and the sprite is close but if it has some more shading it'd be mint. Especially where the grip gets thicc

**Pull request closed without merging**
