### PR TITLE
Blob Buff/Nerf

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Doubles all blob health.
Doubles the mass requirement for blob takeover.
Restricts Blobs from spawning in tcomms.

## Why It's Good For The Game
Blob gets shat on easily by crew consistently because of highpop and it's an extremely late spawn, which means research usually has everything by this point.

I seriously do not recommend spawning blobs roundstart, admins, or else the crew will not have a good time.

## Changelog
:cl: BurgerBB
balance: Blobs now have double health, but require double the blob tiles to reach critical mass. Blobs can no longer spawn directly on telecoms.
/:cl:

### CODE REVIEW

**Comment by LimblessLayabout** [comment]
Wanted to propose - would it be possible (or sensible) for Blobs to always start with the same initial composition? This might be a healthy boon to blob by just letting them restrict their initial expansion (stealth), and build up a stock of initial resources for defense.

Networked Fibers |  Can only expand manually (by clicking). 
Nodes and core produce extra resources instead of producing Blob Tiles. 
Manual expansion near your Core moves it to that tile.

Also if nothing else makes it, let the doubled critical mass stay - this effectively just adds more playtime and that's good.

**Comment by Commandersand** [comment]
double the mass is EHHH
like, it's meant as a roundstart blob and i've never seen 1 even TWO blobs take over a station without deleting the nuke on other servers
honestly i think they just need a resource boost in the first 15 minutes of spawning

**Comment by KathrinBailey** [comment]
This should get testmerged and admins should bus this to test it. 2x health seems overkill for all blob parts, all the special blob, factory, core etc is perfectly fine.
In regards to spawning in tcomms, not much of an issue. A blob spawned in tcomms whilst I was CE. Oh no the blob broke stealth because I'm checking why tcomms is off. Oh look. I just quickly built another tcomms and by the time I was done, every had already killed the blob.
If you double blob health across the board, increasing their mass to win doesn't matter, as by the time they reach the old mass to win, it'd have snowballed so far out of control that there's no defeating the blob anyway.

**Comment by Akrilla** [comment]
Pretty huge buff, but I agree with high pop/late spawns it basically means you're going to encounter mechs and end game gear. Test merge might be best.

**Comment by BurgerLUA** [comment]
Any problems with the PR yet?

**Comment by Akrilla** [comment]
No issues but I don't think it solves the problem. It just delays the inevitable. The other PR in for blob buffs does some more things, I think a mix between the two would be best.

**Comment by BurgerLUA** [comment]
> No issues but I don't think it solves the problem, it just delays. The other PR in for blob buffs does some more things, I think a mix between the two would be best.

the hell are you talking about

it's supposed to delay the problem; and that problem is that blob dies to fast

this is literally what a health buff is supposed to do

**Comment by Akrilla** [comment]
So your point wasn't to increase winrate, but to just let the blob last longer? I mean if that was your goal, sure.

**Comment by BurgerLUA** [comment]
> So your point wasn't to increase winrate, but to just let the blob last longer? I mean if that was your goal, sure.

Winrate is increased with more health. More blob health means that it's harder to kill it. A harder to kill blob has more time to build things and doesn't have to spend too much time expanding. A better expanding blob means a higher chance of victory.

Blobs shouldn't be winning more than 25% of the time. My PR goal wasn't winrate but rather increasing the amount of time a blob gets to be blob.

**Comment by Akrilla** [comment]
The issue is though is that it gets pinned down even with more health, it's not able to expand faster than it's dying.

**Pull request merged**
