### PR TITLE
Requested mining stuff

### PR DESCRIPTION
**Pull request by BobJogaIsForkinBanned**
## About The Pull Request

Makes mining suits and hardsuits allowed to carry plasma cutters on their storage slot. Adds miner's salve patches to the vending thing for miners.
Requested by AshInTheWind#2295 on discord.

## Why It's Good For The Game

Miner convenience.

## Changelog
:cl:
add: Miner's salve patches on the mining vend.
tweak: Mining suits can now hold plasma cutters.
/:cl:

### CODE REVIEW

**Comment by Commandersand** [comment]
can you add jack hammers too? if they don't already count as pickaxes

**Comment by BobJogaIsForkinBanned** [comment]
> can you add jack hammers too? if they don't already count as pickaxes

If you mean to the vendor
no, RnD unlock

**Comment by JackSomethingOrOther** [comment]
I think they meant fitting jackhammers in your suit slot. I don't think those - or drills/picks/shovels - fit in the suit equipment slot.

**Comment by BobJogaIsForkinBanned** [comment]
> I think they meant fitting jackhammers in your suit slot. I don't think those - or drills/picks/shovels - fit in the suit equipment slot.

Still, fitting jackhammers in the suit slot? Kind of dumb. But since they're a subtype of pickaxe, it is already a thing if i'm not mistaken.

**Pull request closed without merging**
