### PR TITLE
[READY][ACTUALLY TESTED]Muhreen's "Epic" Clothing

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds a lot of reskinned variants for ingame armors and helmet. Adds reskinned variants to the security hardsuit and MK. I swat suit too. Amazing! Also changes the reskin obj proc to make reskinnable clothing y'know, possible(in a modular way!).

## Why It's Good For The Game

More variation = more fun!
fart
(dunmer wearing a press vest and a press helmet, nice)
nice
Look at how NICE those look.

## Changelog
:cl: Bob Joga and Muhreen (Investigator77)
add: Many armors and helmets are now reskinnable.
tweak: By default, exo-suits and seva-suits use the "improved" sprite by Muhreen.
code: Refactors the reskin obj proc to make reskinnable clothing a thing.
imageadd: Many new "epic" icons.
/:cl:

### CODE REVIEW

**Comment by Investigator77** [comment]
me when i spriteslave for 2 days

**Comment by BobJoga** [comment]
managed to test, it's fucking raw

**Comment by Investigator77** [comment]
Go to sleep already (or don't and make the hardsuits haha haha haha)

**Comment by BobJoga** [comment]
IT WORKS GUYS

**Comment by BobJoga** [comment]
> Go to sleep already (or don't and make the hardsuits haha haha haha)

IT FUCKING WORKS HARDSUITS INCLUDED IDIOT CUNT

**Pull request merged**
