### PR TITLE
Adds a S.W.A.T. node to the BEPIS, buffs blueshield armor

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Title.
The SWAT node obviously focuses on advanced sec gear.
Here's what it has to offer:
- Advanced night vision helmet, with better stats than a normal helmet
- Advanced armor, with better stats than a normal vest
- Black police baton (like a detective's baton)
- Gorilla gloves (combat tackle gloves)
- WT-550 (the gun itself)

Also buffed the blueshield's vest. Reason: It was literally worse than a default security vest.

## Why It's Good For The Game

More reason to sink money into the BEPIS, as well as glorious sec powercreep.

## Changelog
:cl:
add: Added a SWAT techweb node to the BEPIS, which contains improvements to security gear.
balance: Buffed the blueshield's armor vest to be slightly better than a default security vest.
/:cl:

### CODE REVIEW

**Review by Gandalf2k15 — APPROVED** [review]
Final checks complete, 5-day mandatory allowance for debate channels.

**Comment by YakumoChen** [comment]
:-1: absolutely not, most of this stuff is cargo-only and by moving it to science and making it printable you're just giving one less reason to use cargo, an already unloved enough department as-is.

**Comment by H0gberg** [comment]
I agree with Yakumo on this one, it really limits the use of cargo as if making those crates basically useless, however I do think that the blueshield armor fix is a very welcome one! Also, if we are adding the WT, I feel as if it should be under ballistic weaponry due to how it's basically a worse version of the magnetic rifle with a few niche use cases

**Comment by Gandalf2k15** [comment]
Current vote is overwhelmingly positive. Moving on to secondary judgment.

**Comment by Gandalf2k15** [comment]
Secondary judgment passed. Merging.

**Comment by Owai-Seek** [comment]
Merged within 48 hours. What a world.

**Pull request merged**
