### PR TITLE
The femur breaker can no longer be used to prefbreak people.

### PR DESCRIPTION
**Pull request by CameronWoof**
Undocumented change snuck into Bobmed. No changelog necessary.

### CODE REVIEW

**Comment by BobJoga** [comment]
I don't get what is a prefbreak about this

**Comment by CameronWoof** [comment]
I'm aware.

**Comment by MLGTASTICa** [comment]
applying brute to the groin is in no way a pref-break ?

**Comment by Gandalf2k15** [comment]
In my **opinion** this is no a pref-break and does not require fixing.

**Comment by Owai-Seek** [comment]
Being able to literally disable someones crotch via damage from a machine that shouldn't even be in the game to begin with is disgusting.

**Comment by Yawet330** [comment]
this isnt even prefbreaking though.

**Comment by SarmentiCampbell** [comment]
lmao this pr

**Comment by DarkWolfInsanity** [comment]
Though... shouldn't the femur breaker be doing damage to one of the legs? Not the groin?

**Comment by chefferz** [comment]
thank god my cock will be safe now

**Comment by chefferz** [comment]
**real question though. why was this changed to do damage to the groin in the first place?**

**Comment by Azarak** [comment]
The femur (/ˈfiːmər/, pl. femurs or femora /ˈfɛmərə/)[1][2], or thigh bone, is the proximal bone of the hindlimb in tetrapod vertebrates (for example, the largest bone of the human thigh). The head of the femur articulates with the acetabulum in the pelvic bone forming the hip joint, while the distal part of the femur articulates with the tibia and kneecap, forming the knee joint. By most measures the two (left and right) femurs are the strongest bones of the body, and in humans,[vague] the longest.

**Review by Azarak — APPROVED** [review]

**Comment by Azarak** [comment]
I dont think groin is a femur

**Pull request merged**
