### PR TITLE
[Not Modular] Medipens in ChemMaster

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Allows you to create 10u medipens in ChemMasters

## Why It's Good For The Game

We should have had this all along... Medipens are helpful in dire situations.

## Changelog
:cl:
add: Added medipens to ChemMasters
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
Doesn't this basically make it so you can make infinite sleepypens or instant healmixes? I'd rather medipens be refillable, honestly, not have any chemical available to them.

**Comment by ShadeAware** [comment]
I enjoy this, this has been a much needed addition for the LONGEST time. Plus, allows for some unique and interesting things for Paramedics and Traitors alike.

**Comment by KathrinBailey** [comment]
I really love the fuck out of this but there's a tiny concern.
Does this allow me to put mute toxin into the pens and bypass the progress bar that syringes have?
I know you can get sleepy pens, but those cost telecrystals.
Like I said, I absolutely love the shit out of this, but yeah I'm not sure if this allows me to just instantly inject chems into anyone with exposed flesh.

**Comment by ForrestWick** [comment]
Make a blacklist of chems and only allow a very select few to be put in. Seriously, you underestimate the potential for this to become out and out powercreep

**Comment by Feasel** [comment]
Coniine - Each tick does 1.75 toxin damage and refreshes 5 ticks of being unable to breathe. EXTREMELY slow metabolization  | Metabolism rate : 0.024 units per tick

Lexorin - Temporarily stops respiration and causes 5 oxyloss damage per tick. Even small doses are fatal, and will cause people to pass out quickly | Metabolism rate: 0.4 units per tick

Cyanide - Deals 1.25 toxin damage per tick, with 8% chance to stun for 4 seconds and take 2 additional toxin damage. Also 5% chance to lose breath for a moment. Metabolizes slowly. | Metabolism rate: 0.05 units per tick
--

I'll let these 3 sit here as the reasons why there's inject timers in the game.

**Comment by Feasel** [comment]
@ForrestWick
@KathrinBailey  

Y'all also forgot about potentially instant viro disease inject.

Uhh... wanna hardkill someone? Inject them with toxin that turns them into slimeball and then exstinguisher them. GG.

I can kinda go on and on tbh.

**Comment by Commandersand** [comment]
People rarely poison, even with medipens being able to be made i doubt they'll still use them anyways

**Comment by LimblessLayabout** [comment]
So basically making these forms of chemical attack _actually viable_? Because otherwise it's grenades or don't bother. Same reason I wanted stabby-pens honestly. I like this merge, and look forward to that huge table of very troublesome-to-use chems actually getting applied to the gameboard.

**Comment by KathrinBailey** [comment]
> So basically making these forms of chemical attack _actually viable_? Because otherwise it's grenades or don't bother. Same reason I wanted stabby-pens honestly. I like this merge, and look forward to that huge table of very troublesome-to-use chems actually getting applied to the gameboard.
> Edit; I'm essentially tired of meth-grenades being the #1 product of chemlab.

They already are viable though?
Traitors already have a refillable injector that doesn't use a progress bar, the sleepy pen. It's locked behind a TC cost for a reason. It lets you inject a small amount of chems with zero counter-play outside of wearing hardsuits 24/7.

Radio jammer? Sabotage tcomms? No. Just click someone with your mute toxin medipen, mute toxin is one of the easiest ghetto chem mixes to make.

Want to just outright win fights? Click them with a chloral pen. Wait for them to start slowing down. Click them with another chloral pen. Done, there's no counter, no escape, nothing you can do to survive.

This is why people are saying we need chems blacklisted/whitelisted, because otherwise security will be in hardsuits from shift start to shift end. Chemical warfare is absurdly powerful and the second best thing to chemical warfare is dual-wielding improv shotguns and one-clicking the HoS into crit.

**Comment by Commandersand** [comment]
it's not that bad, i've experience worse where you could instantly stun someone with 5 units of chloral in another server until the chloral was nerfed. 

I'd say lower the limit to 5 units, so if someone suspiciously pricks you, you have time to RUN.
Right now chemical warfare is just explosions/morphine syringe guns and poisons are just never used.
 I didn't read but uhh you should make it so chemicals can be see on examine without the purple goggles

**Comment by IronEleven** [comment]
Chemical warfare doesn't need a buff.

**Comment by Akrilla** [comment]
I'm okay with trying this, but will keep an eye on overall feedback

**Comment by Azarak** [comment]
Considering medipens pierce hardsuits I think it's a bad idea to have this, as this could lead to both ez healing in hardsuits or even stronger chem warfare, not counting the regular super easy uses.

For comparison I think only the emagged CMO's hypospray is both instant and piercing

**Comment by jjpark-kb** [comment]
uhh, excuse me skyratbot?

**Comment by ShadeAware** [comment]
Yo, merging with travis errors?
Pog.

**Comment by Akrilla** [comment]
workflow fuckup, not intended merge

**Pull request merged**
