### PR TITLE
Replaces shitty RNG permanent paralysis when failing with gripper gloves with a severe surgery-curable brain trauma.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Failing a leap with gripper gloves no longer has a 1% chance to permanently paralyze you. It now just gives you a severe brain trauma that can only be cured via brain surgery and/or lobotomy. This can include paralysis but not always.

## Why It's Good For The Game

From a gameplay perspective, it felt pretty fucking shitty that gripper gloves have a 1% chance to paralyze you permanently without a possible cure for the rest of the round. I don't even know if they're a /tg/ feature or a citadel feature, but regardless both of these coderbases seem to excessively enjoy adding extreme, irreversible punishments for doing silly things because "haha funny". I admit that in some instances perma effects are hilarious but in this case it just seems really dumb.

For disclaimer I don't use gripper gloves and I have never received this 1% chance before. I looked at the code after being curious about it and declared that that part of the feature is dumb as hell because it can easily be prevented and it only punishes new or unaware players.

## Oh god oh fuck.
I was told literally 2 seconds before I published this PR that there is a PR up for this, #2558, but I think mine is better because even then, having to do a lobotomy to cure your spine snapping is really silly.

## Changelog
:cl: BurgerBB
balance: Critical failures with gripper gloves no longer permanently paralyze you, but instead give you a severe random surgery-curable brain trauma.
/:cl:

### CODE REVIEW

**Comment by Weblure** [comment]
Holy shit, that was a thing? 

I'd suggest reducing the damage/probability if the user is wearing a helmet, but that'd probably be unbalanced since it's primarily sec that uses this item anyway.

**Comment by BurgerLUA** [comment]
> Holy shit, that was a thing?
> 
> I'd suggest reducing the damage/probability if the user is wearing a helmet, but that'd probably be unbalanced since it's primarily sec that uses this item anyway.

Wearing a helmet is actually a way to prevent this but I still think it can happen with the makeshift gloves.

**Comment by Weblure** [comment]
> Wearing a helmet is actually a way to prevent this but I still think it can happen with the makeshift gloves.

Oops you're right, I didn't look above the switch

**Comment by YakumoChen** [comment]
the spine snapping is a punishment because the tackle is effectively an instant hard stun if it works right, which is sort of silly. Many of the lobotomy traumas aren't even actually debilitating.

**Comment by kappa-sama** [comment]
this is already removed on upstream btw

**Comment by Weblure** [comment]
> this is already removed on upstream btw

image

**Comment by Weblure** [comment]
> this is already removed on upstream btw

image

**Comment by jjpark-kb** [comment]
Trying to keep up to date with mirrors. If you want to do this, please do after the mirror merge.

**Pull request closed without merging**
