### PR TITLE
Yeets Minesweeper

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Kills minesweeper all together. Farewell shit game, go play it on windows instead.

## Why It's Good For The Game
It should reduce lag because it can't be played!

## Changelog
:cl:
del: Yeets minesweeper, it's gone.
/:cl:

### CODE REVIEW

**Comment by RemervKeberb** [comment]
:(

**Comment by Arctaisia** [comment]
:<

**Comment by Tename** [comment]
Whats wrong with minesweeper?

**Comment by Azarak** [comment]
@Gandalf2k15 totally remove it maybe? Make it not spawn and such, having arcades that are non functional sucks

**Comment by Weblure** [comment]
Literally why?

**Comment by Gandalf2k15** [comment]
Upon request of high command.

**Comment by Weblure** [comment]
Welp, guess tokens are useless now.

**Pull request closed without merging**
