### PR TITLE
[Modular] [READY] From the Rim of Space to the ends of the Station (Power Armor for Robotics)

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Adds Power Armor, a new type of armored exoskeleton suit designed to offer excellent protection and mobility. Unfortunately, it doesn't do anything against the void of space, and struggles against more exotic forms of harm.

Can be researched after a number of late-stage techs, and assembled by Robotics using its unique parts, a 5 bluespace crystals and a quadratic capacitor using the Crafting Menu.

**Don't let it get EMP'd.**

Now without manual assembly. Instead, you use the crafting menu. Sorry, but was literally the only method that worked since nothing else wanted to cooperate ever. I've left some of the code in for it incase anyone else wants to take a look at it and revive it.

## Why It's Good For The Game
Robotics has long needed something else to assemble besides the standards Bots and Mechas. This is a good step on that front, and also gives them an option for protection that isn't just a big fuck-off Gygax or Durand.

## Changelog
:cl:
Add: Power Armor, a high-tech body enhancing suit comprised of flexible plasteel sheets and advanced components, self-powered using fluctuations in bluespace. Crafted with the crafting menu after all parts have been printed by robotics, along with 5 individual bluespace crystals and 1 quadratic capacitor. Keep it away from EMPs!
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
Travis can suck my dick because it compiles on local and `/proc./` works fine whereas `/proc/` fucks everything up in my experience.

**Comment by BobJoga** [comment]
epic moment

**Comment by ShadeAware** [comment]
@Azarak reeee the bot won't take away the [DNM] tag.

**Comment by ShadeAware** [comment]
GOD FUCKING DAMN IT YOU HAVE TO BE FUCKING KIDDING ME

**Comment by ShadeAware** [comment]
### BULLSHIT IT SHOULD NOT FUCKING CONFLICT ANYMORE.

**Pull request merged**
