### PR TITLE
Wrestling Belt to Uplink

### PR DESCRIPTION
**Pull request by IrkallaEpsilon**
WRESTLING

## About The Pull Request

Adds the wrestling belt to the uplink.

## Why It's Good For The Game

More gimicky martial arts. This one lets you wrestle like hulk hogan or something I guess.

## Changelog
:cl:
add: Nanotech Wrestling Belt (Champions Belt) to uplink.
/:cl:

### CODE REVIEW

**Comment by IrkallaEpsilon** [comment]
Does this automaticly account for discounts?

**Comment by Arturlang** [comment]
By the way all its ability icons are probably broke and pleeasee test it

**Comment by IrkallaEpsilon** [comment]
The abilities work, The piledriver is a bit wonky but the icons simply never existed in a proper form. If somebody can provide me icons and tell me how to add them I can do that.

**Comment by Akrilla** [comment]
needs those icons

**Comment by ShadeAware** [comment]
I can try my hand at some icons.

**Comment by Akrilla** [comment]
Gonna need to close this, can be reopened if there are icons.

**Pull request closed without merging**
