### PR TITLE
Moves the Security Protolathe into the Warden's Office on all rotation maps; Replaces Secoff's advanced taser with the alert-locked ERifle

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
I meant to do this in the original LabsSec PR, but it needed a further balance pass. This is said balance pass.
ALL Protolathes on all maps in **in rotation** have been moved to the Warden's Office. No more pocket-armory for Security Officers.
In exchange for this however, Security gets the Energy Rifle, a bulky energy-based gun which can fire 25 disabler shots and 12 (weak) lethal blasts. **Lethal functionality is locked to Blue Alert or higher security levels.**

## Why It's Good For The Game
Security running around with a small armory on their packs is bad, but they still need to be able to do their job against things that cannot be disabled (such as carp). This is a good middle ground to both of these issues.
No more pocket supersoldiers, but you can still do your job against things that require lethal force. A perfect balance.

## Changelog
:cl:
balance: All Security Lathes have been moved into the Warden's Office.
balance: Security Officers now get an Energy Rifle roundstart, essentially a bulkier disabler with a longer charge duration and ALERT LEVEL LOCKED lethal functionality.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
ok ill allow it

**Comment by Feasel** [comment]
I approve of this change. Enough's enough on people printing weapons 24/7 when this server is not LRP gamertime.

If people are curious why the warden's office over the armory, it's so the Warden can quickly curate weapons while sitting in his happy place while preventing antags from just "haha I bomb in and no more lathe + armory ;D"

100% approve of this change.

**Comment by MLGTASTICa** [comment]
Good change , however i'd make it so syndicate weapons (energy crossbow , decloner , holorifle) need a different protolathe from the normal security one.

**Comment by CameronWoof** [comment]
I like moving the protolathe, iffy on re-introducing the energy gun. I think the reasons for denying it were pretty solid and this doesn't address any of my concerns with them, namely how easy it is to subvert the alert-lock with a screwdriver and a multitool.

**Comment by H0gberg** [comment]
if you could like put wires within the gun so you can cut em would be cool so that you can subvert the lock for one wire, remove all the charge from the gun with one wire and another wire could like set the gun to just start randomly shooting and uhh another one shocks you or something

**Comment by YakumoChen** [comment]
I feel that the gun hack should be emag only, not something tools can do

**Pull request closed without merging**
