### PR TITLE
[Modular(?)] Supermatter Bluespace Cascade

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

Adds the Supermatter Cascade from /vg/.

## Why It's Good For The Game

Adds an additional turf that can allow admins to spawn in, and simulate an round-ending "blob".
Additional roleplay can be made with such a thing.

## Changelog
:cl:
add: Added Supermatter Cascade
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
>Secret
Anyone who takes a glance at the code can see what you're doing.

### SUPERMATTER CASCADE SUPERMATTER CASCADE OH GOD ITS THE BLUESPACE ITS LEAKING IN FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK-

**Comment by LimblessLayabout** [comment]
Oh this looks _exciting_.

**Comment by jjpark-kb** [comment]
closing this for now to keep the clutter down.

**Comment by jjpark-kb** [comment]
I solved the locker issue, so it deletes lockers and items appropriately.
Still need to solve unable to examining it, as well as making the deletion of the turfs update the others to HOPEFULLY replace the deleted turf.

**Pull request merged**
