### PR TITLE
[REVIEW PLEASE I BEG YOU] Virology shuffle + age descriptions on examine

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

This PR requires code changes from https://github.com/Skyrat-SS13/Skyrat13/pull/2930

Uplifted the limit of diseases on a person from 1 to  3, but made it so you can't stack the same symptoms with different diseases. The symptom just gets neutered.
Examine now shows vague info about a person's age.
Eternal Youth symptom now actually makes you become younger over time. **It doesn't make you ever go below 18.**
Added flesh melting symptom, which will melt your flesh until you turn into a variation of skeleton depending on the resistance of the disease.
Tweaked old radiation healing symptom into gamma healing symptom, which basically heals you depending on how much radiation you have in your body (does not make you immune to the effects of radiation, stacks up with the amount of radiation you have indefinitely).
Added radiation healing symptom, which heals your radiation away.
Added damage converter symptom, which slowly converts brute and burn damage into toxin damage.
Reshuffled and rebalanced some values around.

## Why It's Good For The Game

REJECT NANITES, RETURN TO VIROLOGY

## Changelog
:cl: Bob Joga, Paradise Station for the damage conversion symptom idea
add: Examine now shows vague info about a person's age.
tweak: Diseases are no longer capped at one per person, instead it's 3.
tweak: Eternal youth symptom now actually lowers your age over time.
balance: You cannot stack symptoms in virology anymore with different diseases that have the same symptoms.
balance: Shuffled around some stats on some virology symptoms
balance: Old radiation healing is now called gamma healing and really stacks up with the amount of rads you have
add: Added flesh melting symptom to virology
add: Added radiation healing symptom to virology (as in it heals radiation)
add: Added damage conversion symptom to virology
code: Repathed some virology symptom files
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.

Also, race change stuff is terrible.

**Comment by BobJoga** [comment]
> Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> 
> The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> 
> Also, race change stuff is terrible.

I did make the virus account for that. It doesn't ever go below 18.

**Comment by BobJoga** [comment]
> Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> 
> The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> 
> Also, race change stuff is terrible.

Oh yeah it is. I guess it's better if i just make it instantly gib you instead of being a cool niche symptom for interested virologists.

**Comment by hugmeorelse** [comment]
> > Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> > The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> > Also, race change stuff is terrible.
> 
> I did make the virus account for that. It doesn't ever go below 18.
> 
> The proc only accounts for toddlers and teenagers and etc for the sake of consistency, but it is never actually utilized on a human.

Why is there even a proc for toddlers and teenagers? Lmao.

**Comment by hugmeorelse** [comment]
> > Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> > The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> > Also, race change stuff is terrible.
> 
> I did make the virus account for that. It doesn't ever go below 18.
> 
> The proc only accounts for toddlers and teenagers and etc for the sake of consistency, but it is never actually utilized on a human.

Why is there even a proc for toddlers and teenagers? Lmao. Is this ported from Paradise?

**Comment by hugmeorelse** [comment]
> > Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> > The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> > Also, race change stuff is terrible.
> 
> I did make the virus account for that. It doesn't ever go below 18.
> 
> The proc only accounts for toddlers and teenagers and etc for the sake of consistency, but it is never actually utilized on a human.

Why is there even a proc for toddlers and teenagers? Lmao. Please take them out, even if it'll be unused. Is this ported from Paradise based on what I see here?

**Comment by hugmeorelse** [comment]
> > Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> > The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> > Also, race change stuff is terrible.
> 
> I did make the virus account for that. It doesn't ever go below 18.
> 
> The proc only accounts for toddlers and teenagers and etc for the sake of consistency, but it is never actually utilized on a human.

Why is there a proc for toddlers and teenagers? Is that from Paradise? Yeah, it doesn't really belong here at all. Lmao. Please take them out, even if it'll be unused, because that's a minefield of yikes.

**Comment by BobJoga** [comment]
> > > Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> > > The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> > > Also, race change stuff is terrible.
> > 
> > 
> > I did make the virus account for that. It doesn't ever go below 18.
> > The proc only accounts for toddlers and teenagers and etc for the sake of consistency, but it is never actually utilized on a human.
> 
> Why is there a proc for toddlers and teenagers? Is that from Paradise? Yeah, it doesn't really belong here at all. Lmao. Please take them out, even if it'll be unused, because that's some serious yikes. It's nothing on your end, but people are going to look at that and assume the worst, even if it's not even a thing on the server.

I have commented them out but i will take them out fully.

**Comment by BobJoga** [comment]
> > > Yea, let's not allow people to go below the age of 18 from a virus. That's just asking for trouble and gross shit.
> > > The youngest description there should be is young adult / early twenties. None of this toddler/child/teenager stuff.
> > > Also, race change stuff is terrible.
> > 
> > 
> > I did make the virus account for that. It doesn't ever go below 18.
> > The proc only accounts for toddlers and teenagers and etc for the sake of consistency, but it is never actually utilized on a human.
> 
> Why is there a proc for toddlers and teenagers? Is that from Paradise? Yeah, it doesn't really belong here at all. Lmao. Please take them out, even if it'll be unused, because that's some serious yikes. It's nothing on your end, but people are going to look at that and assume the worst, even if it's not even a thing on the server.

Took all of it out fully.

**Pull request closed without merging**
