### PR TITLE
[READY] General shotgun overhaul

### PR DESCRIPTION
**Pull request by Investigator77**
## About The Pull Request

This PR focuses on updating inhand shotgun sprites to the fancy 64x64 /tg/station shotguns, as well as changing some other sprites directly related to the update.

## Why It's Good For The Game

Detailed sprites are the best sprites.

## Changelog (so far)
:cl:
Ported 64x64 sprites for shotguns from /tg/station, made by actioninja in pull #45521.
Added shotgun icon code.
Changed certain shotguns descriptions.
Ported **beautiful** double barrel sprites from YogStation.
Added a pistol grip to the slick combat shotgun to better fit the alt-skin description.
Changed the stock of the combat shotgun
Touched up the riot shotgun.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
no, stop one PR can't be this good

**Comment by Investigator77** [comment]
pls delet dnm tag

**Comment by ShadeAware** [comment]
Changing the inhands feels... wrong to me, im not sure why

**Comment by ShadeAware** [comment]
The rest of this is **very** pog, though.

**Pull request merged**
