### PR TITLE
Removed debuff on the person initiating the clone cycle.

### PR DESCRIPTION
**Pull request by Jamini**
## About The Pull Request

Removes severe mood penalty from cloning another person.

## Why It's Good For The Game

Let's not discourage people from keeping others in the game.

## Changelog
:cl: Jamini/Linuxtesting
balance: removed mood debuff from cloning another person.
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/3520
redundant pr?

**Comment by Azarak** [comment]
https://github.com/Skyrat-SS13/Skyrat13/pull/3520 was commited to 4 minutes before this one, what a coincidence.

**Comment by ThatGuyFromThatPlace** [comment]
Cloning isn't "Keeping people in the game"
It's pressing the lazy reset button
It's a way to encourage actually reviving someone rather than throwing them in the trash and creating a copy of them to replace them. 
Cloning is terrible for both roleplay and balance, and, anyone who plays their character as "Haha death doesn't matter cause cloning" is ridiculous, as, cloning isn't even like resleeving. Cloning is making a copy of a character that then just replaces them. They're not the same person. They're a completely different individual

So, I would highly prefer to keep people feeling bad for making a copy of someone to replace them rather than actually reviving them. It makes sense. You would feel bad for effectively giving up on someone and making a new fake them.

**Comment by Azarak** [comment]
@ThatGuyFromThatPlace Revival surgery / SR is just as ridicluous, but people newer to medical can actually bring someone back thanks to cloning without studying the way of the blade for for whatever time period, and what people are doing is elitistic cloning vs revival dumb debates, which really piss me off.

**Pull request closed without merging**
