### PR TITLE
makes brig phys a sec job again.

### PR DESCRIPTION
**Pull request by Yawet330**
## About The Pull Request
Why the fuck were we punishing AFK's codewise instead of policy-wise lmao.

## Why It's Good For The Game
Literally makes brig phys count towards blueshield; and gives them the relevant security buffs towards certain items and drinks.

## Changelog
:cl:
tweak: brig phys is actually once more a security job.
/:cl:

### CODE REVIEW

**Comment by Harakoniwarhawk** [comment]
I'd be leery of this just because we already have issues with people ignoring the spawn text to play Officer as Brig Phys, making the role a security one again will just exasperate it IMO.

**Comment by Yawet330** [comment]
> I'd be leery of this just because we already have issues with people ignoring the spawn text to play Officer as Brig Phys, making the role a security one again will just exasperate it IMO.

This should be more of a policy and administrative concern; same as doctors using guns or lethals; its... an iffy situation and while I agree, doing it through code is an _eeesh_ because brig doctors still show up under the sec tab right now.

**Comment by Owai-Seek** [comment]
I don't think it's "literal" afking as much as it is that, brig physician isn't meant to be a security position. You're a medic that just happens to have access to security. You aren't supposed to be wielding guns, throwing flashbangs, or fighting crime, so you don't get "experience" (time) in the security role.

**Comment by RatFromTheJungle** [comment]
brig phys is closer to a medical doctor with brig access, then an officer with medical access.

**Comment by davidchan13** [comment]
Brig phys is medical's representative in security to provide treatment to prisoners and people in security's custody. They are not Security and are supposed to report to the CMO, not the HoS.

**Comment by Arctaisia** [comment]
I would say they're more medical than security, their job is to heal people, and prisoners, not enforce the law. They're there to keep security and the prisoners safe (Despite the fact that it doesn't happen all the time), and ofcourse, they report to the CMO, they're much more medical than security.

**Comment by ThatGuyFromThatPlace** [comment]
> Brig phys is medical's representative in security to provide treatment to prisoners and people in security's custody. They are not Security and are supposed to report to the CMO, not the HoS.

> I would say they're more medical than security, their job is to heal people, and prisoners, not enforce the law. They're there to keep security and the prisoners safe (Despite the fact that it doesn't happen all the time), and ofcourse, they report to the CMO, they're much more medical than security.

Them answering to only the CMO is false. It specifies that they answer to both the HOS and CMO

unknown

Also, I don't know what "exp_type" does, but, that's still marked to be for medical, so. This may not even have it put time towards Blueshield even with this PR

**Pull request closed without merging**
