### PR TITLE
Removes blood contract/Bottle of mayhem from bubblegum drops (replacement at a later point).

### PR DESCRIPTION
**Pull request by IrkallaEpsilon**
Removes blood contract

## About The Pull Request

Removes Blood contract from enraged bubblegum loot chest.  Same for bottle of mayhem.

## Why It's Good For The Game

An item that basicly lets everyone target one person and lets the one person murderize anyone who attacks them seems like a bad idea. Specially since of all times I have observed this being used it was either used to kill traitor permanently and cheaply or for shitty unwanted assassinate gimmicks result most of the time in a permanent kill. Bottle of Mayhem is similar but more localized.

## Changelog
:cl:
del: Removed Blood Contract from loot table. Same for bottle of mayhem. Replacements will be added soon by Bob.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I think it would be better if you came up with someway to rework it instead of just deleting content from the game. This feels like kind of a knee-jerk salt PR as well.

**Comment by IrkallaEpsilon** [comment]
Nice, my first github toxcity. I suggest you to suggest to rework it into something. I can change the phrasing on getting contracted but that doesnt change people from being stupid and go "Huh duh time to prevent any and all revival".

There are two things that cannot be fixed in humans. Lazyness and stupor.

**Comment by IrkallaEpsilon** [comment]
The "prevent them from being revived" happened out of all blood contracts I have witnessed so far and its every time people going angry in dchat at eachother followed by drama over discord. This simply cuts out the source till somebody, who is more versed in coding, can rework it. If you want to be angry at somebody be angry for me for making this PR. The item is designed with a TG mentality in mind.

**Comment by Azarak** [comment]
I agree with Irkalla, this item goes against our principles and causes a ton of issues whenever it's used. It may not seem like much from a player perspective but as an admin you get frustrated staff and players  complaining left and right where nobody is really at fault, just the item.

**Comment by BobJoga** [comment]
The item is useful and the wording never asks for the person to be killed more than once or prevented from revival. This PR is solely removing content and not replacing it with anything better.

**Comment by BobJoga** [comment]
> Nice, my first github toxcity. I suggest you to suggest to rework it into something. I can change the phrasing on getting contracted but that doesnt change people from being stupid and go "Huh duh time to prevent any and all revival".
> 
> There are two things that cannot be fixed in humans. Lazyness and stupor.

People not liking your PR is not toxicity. Get over it.

**Comment by IrkallaEpsilon** [comment]
"Knee jerk salt PR" is exactly text book toxcity. The message would have been conducted without that.

**Comment by Azarak** [comment]
No content is better than content that ruins the rounds. This item encourages NRP'ing the victim and the victim NRP'ing other people, and chances are it's being used on an antag that's highly capable in killing people, which then leads to tons of murders 4nr with nobody at fault, just upset people.

If the victim does end up getting killed they wont be revived because they're already a serial murderer and/or antag.

**Comment by BobJoga** [comment]
> "Knee jerk salt PR" is exactly text book toxcity. The message would have been conducted without that.
> 
> Again. Suggest what item to add, I am pretty sure there are many functional yet unused items in code. Perhaps for the hardmode add a demonheart or something. Could do that.

I am not removing the content, the burden of providing an idea for a substitute should not fall on me.

**Comment by IrkallaEpsilon** [comment]
Added demon heart if azarak approves of it as a replacement for the blood contract.

**Comment by IrkallaEpsilon** [comment]
After further discussion in devchat demonheart got removed in favor of bob adding something as replacement.

**Comment by IrkallaEpsilon** [comment]
Further discussion in devchat and with staff: Bottle of Mayhem has been proposed for removal aswell. Bob will probably find a replacement for that soon. Just have faith in him, it will get a suitable replacement.

**Pull request merged**
