### PR TITLE
Megafauna music preference

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

adds a preference toggle for megafauna music

## Why It's Good For The Game

BFG division will no longer rape your uninvited ears

## Changelog
:cl:
add: Megafauna music now uses a proper preference toggle.
/:cl:

### CODE REVIEW

**Comment by Yawet330** [comment]
unbased, having your game crash to BFG division was the best part of killing megafauna.

**Comment by BobJoga** [comment]
> unbased, having your game crash to BFG division was the best part of killing megafauna.

yes

**Comment by Gandalf2k15** [comment]
Resolve conflicts.

**Comment by angelomerp** [comment]
finally I can beat faunas without freezing my game for 2 seconds and watch my character get fucked by a bunch of goliath while a bubblegum slaps my ass to death

**Pull request merged**
