### PR TITLE
Adds Cheems

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

adds cheems ~~and the cheemgularity~~
cheemgularity got yeeted for now because error: maximum number of internal arrays exceeded (65535)
~~i intend for cheem to be a cargo pet in the future once i make or get good sprites, for now it's just code-wise and maybe if you get lucky in xenobiology~~
i got actually acceptable sprites for cheems, he'll be the new cargo pet

## Why It's Good For The Game

funny yellow cargo dog

## Changelog
:cl:
add: Added cheems as a cargo pet.
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
Because adding a 2020 meme dog is MRP

**Comment by BobJoga** [comment]
> Because adding a 2020 meme dog is MRP

it's the funny yellow doggy though

**Comment by ShadeAware** [comment]
Joke funny, humor man good. Killjoy man bad grunga, not know how to have funny with grugplay.

**Comment by jjpark-kb** [comment]
I am fine with a "Cheems" dog due to how cute it is. However, I am not fine with other pets getting axed because of it.

**Comment by BobJoga** [comment]
> I am fine with a "Cheems" dog due to how cute it is. However, I am not fine with other pets getting axed because of it.

I am completely okay with keeping the sloths. I can revert these changes and simply add without taking away.

**Comment by BobJoga** [comment]
its been 15 fucking days

**Pull request merged**
