### PR TITLE
[READY] The Cargo Utilitarian Update (Part One)

### PR DESCRIPTION
**Pull request by Investigator77**
## About The Pull Request

This is the first of many PRs that will go towards giving the server more of an identity, moving away from the super-generalized uniforms and bringing a different unique look to departments. This is the first of two parts, containing alternate uniforms for the Quartermaster and his technicians.

[https://imgur.com/a/YLeFMEm](url)
image
## Why It's Good For The Game

Regular jumpsuits are for gay babies + You can look cool.
On a more serious note, uniqueness.

## Changelog
:cl:
add: Cargo Technician's Gorka (Reskin)
add: Cargo Technician's Turtleneck (Reskin)
add: Cargo Technician's Utility Jumpsuit (Reskin)
add: Quartermaster's Gorka (Reskin)
add: Quartermaster's Turtleneck (Reskin)
/:cl:

### CODE REVIEW

**Comment by BobJoga** [comment]
epic pr

**Comment by H0gberg** [comment]
this is some fire ass shit

**Comment by Strazyplus** [comment]
You making nagatuar versions right? at least delete legs. I am still salty at whoever broke BlueShield clothes.

**Comment by KasparoVy** [comment]
These look mad dope.

**Pull request merged**
