### PR TITLE
[READY] Bugfixes and QOL Changes to many things + Cargo Access fixes for Blueshields

### PR DESCRIPTION
**Pull request by CinderWC**
## About The Pull Request
Title.

## Why It's Good For The Game
Bugfixes are good, QOL changes are petty but good too

## Changelog
:cl:
add: More blue corners to medbay
add: Added shutters to Teleporter Room
add: Added loot to Cargo Bay boxes
del: Removed striped lines infront of the theatre (Why is it dangerous?)
del: Removes duplicate desk lamp in Bar Backroom
tweak: Replaced Theatre Window floor with plating
tweak: Adjusted position of a locker in Sec Locker Room
tweak: Tweaked blue corners outside of medbay to make more sense and look nice
tweak: Broke the lightbulb in the Cargo Bay (To offset the new loot in the bay)
fix: Fixed the wire leading to the Pool APC, which was previously unconnected
fix: Fixed black and purple square plating turfs on Moon Outpost 19 (Xeno Gateway)
fix: https://github.com/Skyrat-SS13/Skyrat13/issues/1125
fix: https://github.com/Skyrat-SS13/Skyrat13/issues/1187
fix: https://github.com/Skyrat-SS13/Skyrat13/issues/1167
fix: https://github.com/Skyrat-SS13/Skyrat13/issues/1130
/:cl:

### CODE REVIEW

**Comment by CinderWC** [comment]
I will be closing my PR's as i no longer have a desire to work for the server.
This is not the community's fault but a personal issue i have with the Owner of the Server and i apologize for the people who have been looking forward to see these PR's merged.


rz9ScN8

**Comment by CinderWC** [comment]
SeMnF8P
NhlfAOr
GcMq9M9
sT26Djc

**Comment by KathrinBailey** [comment]
Also I forgot to mention, just for clarity, I added cargo to the cargo door so blueshields can get in, it's with the whole sec rebuild and it's live on the server.

**Comment by CinderWC** [comment]
@KathrinBailey It doesnt actually matter, we will conflict up the ass anyway

**Pull request merged**
