### PR TITLE
[Ready] Part 1/X: Better arcades

### PR DESCRIPTION
**Pull request by Akrilla**
## About The Pull Request

Minor port of Paradise arcade logic - removing all toy prizes from arcade machines, and letting them dispense tickets instead. A new prize machine has been added that you can then redeem your tickets for selected prizes. Prizes are at different tiers depending on how upgraded the machine is, so for the more expensive/interesting toys it'll need to be upgraded with better components.

## Why It's Good For The Game

Does away with limit of prizes you can win from a machine, and lets you get what you'd like! This is also the first of probably a couple PRs that'll slowly add in more of Paradise's arcade stuff. More interesting machines, toys, etc.

# TODO

- [x] Add in some of the toys that are still missing to the vendor 
- [x] Map in the prize counter into maps.

## Changelog
:cl:
tweak: Ports in Paradise-like arcade machines. No longer dispensing toys, and instead give tickets.
add: Added the prize counter, letting you redeem your won tickets from arcade machines.
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
Best bunny

**Comment by ShadeAware** [comment]
I like this.

**Comment by krumpmeboyz** [comment]
Only bugs I've noticed so far are that Pubby doesn't have one and that it's not on the imprinter, which are both so minor it's basically foolproof.

**Comment by Akrilla** [comment]
Yeah my bad I forgot to add it to pubby, and I'll add it to the imprinter too

**Comment by xXPawnStarrXx** [comment]
I already miss the hugs of the northstar, how am I supposed to head pat the shit outta catgirls?

**Comment by Akrilla** [comment]
ill add it just for you

**Pull request merged**
