### PR TITLE
Refurbished Centcomm Emergency Docking Area

### PR DESCRIPTION
**Pull request by calibraptor**
Here are my changes, in order of priority:

-Safezone and EORG area are now entirely separated by a neutral hallway. You no longer need to walk through the EORG warzone to reach safety.

-The safezone is larger and can accommodate significantly more people, it also has a dedicated spectator gallery for those who want to watch the EORG carnage.

-Some other QOL changes. Such as upgraded medical machinery, equipment, and cyborg rechargers. Medical mains rejoice.

Here's some screenshots.
https://i.imgur.com/ta2MPM8.png
gottem
https://i.imgur.com/kOihBH2.png

Also, yes, all the windows surrounding the EORG warzone are thunderdome windows, and thus unbreakable. There is also fans to stop any harmful atmos from leaking out.

### CODE REVIEW

**Comment by CameronWoof** [comment]
Very nice. Big improvement over other suggestions.

**Comment by jjpark-kb** [comment]
image
please dont do this.

**Comment by Owai-Seek** [comment]
I believe if you modify core files instead of modularization, you need to make it known that it's a skyrat change. I like the split hallway, and along with policy/rule changes to go along with this, I think it's a nice change. (assuming it doesn't brick anything, CC is funky.)

**Comment by calibraptor** [comment]
> 
> 
> image
> please dont do this.

Sure thing. I yeeted it.

**Comment by calibraptor** [comment]
All checks have passed, anybody want to take another look at this?

**Comment by jjpark-kb** [comment]
ill deal with this PR soon.

**Comment by jjpark-kb** [comment]
image
It seems nothing is stopping someone from just, doing this.

**Comment by jjpark-kb** [comment]
image
image
Yeaaa, no.

**Comment by jjpark-kb** [comment]
Ill do it myself.

**Comment by calibraptor** [comment]
> 
> 
> image
> image
> Yeaaa, no.
> You tried to "sneak" in another thing. Not satisfactory.

Um? The only thing I tried to 'sneak' in was a cheeky signature in the corner of the centcom z-level. Which I promptly removed upon request.

I didn't try to sneak in the circle hand, it's literally in the screenshot.

**Comment by calibraptor** [comment]
> 
> 
> image
> It seems nothing is stopping someone from just, doing this.

Those are indestructible thunderdome windows. If somebody intentionally finds a way to bypass it and grief within the safezone then that's what the admins are for. I could add space tiles inbetween but people would find a way to bypass those too.

I actually spent a lot of time working on this, so I'm going to ping other maintainers.

**Pull request closed without merging**
