### PR TITLE
IMP

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds a playable **IMP** hybrid species

image

They take 0.666x burn damage (haha)
They are vulnerable to cold (2.5x cold damage stuffies)
They need to breathe in CO2
They burn up when breathing any amount of oxygen
They take 1.1x brute damage
They take 0.9x stun
They see up to 4 tiles in the dark
They have an Urdakian language for maximum kar en tuking (restricted to imps only, might give to slaughter mobs soon TM)
Their heart does not decay
They do increased melee damage (5 to 10 damage instead of 1 to 10)
They bleed more but also regenerate blood more
They have the unstable trait by default
They can drink blood
They have a demon blood type which is **HYPER REALISTIC BLOOD**
They are **ULTRA-VIOLENT**
When breathing in large amounts of co2 they start metabolizing a small amount of omnizine, but go too large and you start taking damage from too much co2

I plan to color matrix them and give them accessories later but i'm fucking tired so for now you get standard **IMP**.

image

ngl gonna be ironic to see an **IMP** in da praetor suit

image

MORE **IMP**

also imp skulls set targets on fire now (as intended), only 3 firestacking though not very potent

## Why It's Good For The Game

we have xeno hybrids so why not i want to play an **IMP**

## Changelog
:cl:
add: Added Imp Hybrid as a species
add: Added Urdakian as a language for Imps and possibly other slaughter demon related things
add: Imp skull trophy now sets targets on fire for a small small amount of firestacking
/:cl:

### CODE REVIEW

**Comment by Yawet330** [comment]
this is based but whitelisted language stinky.

**Comment by BobJoga** [comment]
> this is based but whitelisted language stinky.

you understood wrong

**Comment by Yawet330** [comment]
> > this is based but whitelisted language stinky.
> 
> you understood wrong

i did and this was clarified on the discord.
Not a whitelist species or language wise, just restricting funny language to imps only.

**Comment by ShadeAware** [comment]
Based

**Comment by BobJoga** [comment]
i hate travis, this compiles fine locally

**Pull request closed without merging**
