### PR TITLE
Cheems fluff part 1: Junk food, headset, shomtgun, and immovable rod digestion

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

More cheems content!

**Junk food**
Cheems is now able to eat any kind of food. He likes dairy, fried and junk food - feeding him food of other types will make him spit it out furiously, but if he likes the food, he'll consume it, and it'll heal him.

**I used the shotgun. You know why?**
Cheems can now wield shotguns. Simply "attack" him with any intent other than harm while using a shotgun (both pump and double barrel work fine). To remove the shotgun, examine him and click on the appropriate text. Cheems can actually shoot the shotgun - you just need to drag him to a target, while near him, and the shotgun will process a shot. Every time cheems moves while wielding a shotgun, he'll play a snippet of kids with guns.

**Headset**
Cheems can now equip a headset. Simply "attack" him with any intent other than harm while using a headset. While using a headset, every time Cheems says something, he says it into the appropriate department channel or common if this is not possible. Examine him and click on the appropriate text to remove the headset.

**Immovable rod**
Cheems can now vore immovable rods. If he gets hit by one, he evolves into an anomalous cheems, and craps out an anomaly core. The anomalous cheems will have the rod stored inside him, and if he somehow dies, the rod comes out flying at the direction he was last facing.

## Why It's Good For The Game

funny dog mechanics

## Changelog
:cl:
add: Added a lot of cheems fluff. See PR #2479 for more info.
/:cl:

### CODE REVIEW

**Comment by xXPawnStarrXx** [comment]
My god, this is so stupid it's genuinely insulting.

**Comment by deathride58** [comment]
how do i give reddit gold on github

**Comment by Owai-Seek** [comment]
Terrible LRP mechanics for a pet that's already a meme.

Pets don't need shotguns.

I don't want to hear his stupid dialogue already, let alone throughout the station.

Rod is just, no. While more ways to take care of them would be nice, this is not the way.

**Comment by BobJoga** [comment]
> Terrible LRP mechanics for a pet that's already a meme.
> 
> Pets don't need shotguns.
> 
> I don't want to hear his stupid dialogue already, let alone throughout the station.
> 
> Rod is just, no. While more ways to take care of them would be nice, this is not the way.

bro you literally never comment anything positive on any PR ever

**Comment by BobJoga** [comment]
> My god, this is so stupid it's genuinely insulting.

thank you kind stranger

**Comment by BobJoga** [comment]
> Terrible LRP mechanics for a pet that's already a meme.
> 
> Pets don't need shotguns.
> 
> I don't want to hear his stupid dialogue already, let alone throughout the station.
> 
> Rod is just, no. While more ways to take care of them would be nice, this is not the way.

LRP mechanics that Ian has:
- Chasing food on the life proc, which is extremely inefficient.
- An entire had and vest system.
- Being turned into a cult version when nar'sied, which has even more garbage in the life proc.
- Puppies and reproduction mechanics. Guess what? This is used on the life proc of Lisa. *sigh
But apparently when i do LRP meme dog mechanics, that is bad.

**Comment by Owai-Seek** [comment]
- Dogs tend to eat any food they can get their mouths on, yea. That's a thing dogs do. Code efficiency-wise, I have no idea, because I hardly code.
- People put clothes and hats on their -actual- animals. I don't think people equip their dogs with shotguns.
- Cult Version, is well, flavor. I wouldn't care if it stays or goes considering how rare it is.
- The puppies and stuff are pretty bad, yea, same with Runtime/Space Cat, There should be a cap put on it similar to the monkey cube cap, and the rat cheese cap TG has.
- Ian's "Incessant Barking" Lines and emotes. Note, these are all things dog have been observed to do.
("barks", "woofs")
("barks!", "woofs!", "yaps.","pants.")
("shakes its head.", "chases its tail.","shivers.")
("dances around.","chases its tail!"))

- Cheems Speech Lines:
("Burbger...", "McDomnald...", "Whompper...", "Bimg Mac...", "Whemre are the miners?", "Revolutiom!",\
				"Pizza cramte.", "Collemctable hats...", "Research mining tech stupid sciemtists!", "Where's my rimpley?",\
				"Shomtgun crate.", "Free cargo!", "No horny.")

Saying I don't comment anything positive is a pretty broad statement to claim when this entire PR and pet is a LRP meme.

**Comment by Weblure** [comment]
> > Terrible LRP mechanics for a pet that's already a meme.
> > Pets don't need shotguns.
> > I don't want to hear his stupid dialogue already, let alone throughout the station.
> > Rod is just, no. While more ways to take care of them would be nice, this is not the way.
> 
> LRP mechanics that Ian has:
> 
> * Chasing food on the life proc, which is extremely inefficient.
> * An entire hat and vest system.
> * Being turned into a cult version when nar'sied, which has even more garbage in the life proc.
> * Puppies and reproduction mechanics. Guess what? This is used on the life proc of Lisa, calling it every 40 seconds and scanning 7 tiles around them, **something which is so inefficient and terrible that it was reason enough to remove some of the quirks i had made.** *sigh
> * Incessantly barking, along with incessant barking that changes depending on type of corgi and what they're wearing.
> 
> But apparently when i do LRP meme dog mechanics, that is bad.

If you seriously think the things you've listed about Ian are even close to being on par with what this PR is adding, you may want to take a moment to reconsider. 

The junk food thing is fine. Being able to heal him is a bit snowflakey since you can't really heal most other pets, but whatever. 

He doesn't need a headset, we already have Poly for that, and we don't need another pet spamming  comms. 

He doesn't need to be able to use a fucking shotgun, and we don't need a pet playing cancerous SFX. 

He doesn't need to eat rods, especially when he can be used to fucking *relocate* rods, which makes him into one of the most powergamey bullshit items on the station. Hmm, yes, let me just grab this dog and vore a fucking rod and then kill him while he's facing the AI sat, SM crystal, armory, etc, etc..

This PR is full of memey garbage that has no place on an HRP server and does not benefit the server in any healthy manner. If this is the type of content you're looking for, port this to Citadel and play there.

**Comment by Weblure** [comment]
Better yet, why don't we remove all the memey bullshit from cheems? A fat dog is fine, but it doesn't need to speak and say stupid meme shit that nobody will think is funny after a month. There's a reason meme shit shouldn't be added beyond subtle reference.

**Comment by Azarak** [comment]
What Weblure said

**Comment by Investigator77** [comment]
It's a good PR. Shotgun and rod is too much, but apart from those two, it's fine really.
If you remove the shotgun and the rod abilities from Cheems, I'm 100% sure it will fit.

**Comment by BobJoga** [comment]
> Better yet, why don't we remove all the memey bullshit from cheems? A fat dog is fine, but it doesn't need to speak and say stupid meme shit that nobody will think is funny after a month. There's a reason meme shit shouldn't be added beyond subtle reference.

List of "subtle" memery i can find in the code:
- Crab 17
- Gmod styled error icons
- Chaplain LRP meme bibles
- No ERP poster
- Chef CQC
- Cumming into reagent containers such as glasses
- Revolver plant that can be gotten via xenobio
- Ninja mask making you speak like a stereotypical japanese immigrant
- Baseball antag kit
- Lord singulo antag kit
- His grace
- Skeleton scream is literally the rattle me bones sound effect

I'm quite sure there is way more that i could find, but this is a simple overview alone. I'm quite sure no one would be disappointed if i removed those in an HRP server.

**Comment by Owai-Seek** [comment]
If you're actively seeking out LRP content why don't you attempt to fix it instead of using it to justify your meme PRs?

What you're trying to add isn't subtle, it's so on the nose I can smell it, and you're digging up a bunch of tiny crap that was already in the codebase from TG/Citadel to try and justify -new- meme additions.

If these things you're digging up are so bad, make separate PR's to remove/rectify them instead of using them as a "proof of memes" to unload more shit into the codebase.

**Comment by BobJoga** [comment]
> If you're actively seeking out LRP content why don't you attempt to fix it instead of using it to justify your meme PRs?
> 
> What you're trying to add isn't subtle, it's so on the nose I can smell it, and you're digging up a bunch of tiny crap that was already in the codebase from TG/Citadel to try and justify -new- meme additions.
> 
> If these things you're digging up are so bad, make separate PR's to remove/rectify them instead of using them as a "proof of memes" to unload more shit into the codebase.

Sure. Just don't complain on the PR removing them.

**Comment by Owai-Seek** [comment]
If you do just a few things at a time it'll probably be fine, but if you try to do a single massive meme removal people aren't going to be happy. That being said, this isn't a discussion for this PR so unless something else comes up I'm gonna tap out.

**Comment by Weblure** [comment]
> > Better yet, why don't we remove all the memey bullshit from cheems? A fat dog is fine, but it doesn't need to speak and say stupid meme shit that nobody will think is funny after a month. There's a reason meme shit shouldn't be added beyond subtle reference.
> 
> List of "subtle" memery i can find in the code:
> 
> * Crab 17
> * Gmod styled error icons
> * Chaplain LRP meme bibles
> * No ERP poster
> * Chef CQC
> * Cumming into reagent containers such as glasses
> * Revolver plant that can be gotten via xenobio
> * Ninja mask making you speak like a stereotypical japanese immigrant
> * Baseball antag kit
> * Lord singulo antag kit
> * His grace
> * Skeleton scream is literally the rattle me bones sound effect
> 
> I'm quite sure there is way more that i could find, but this is a simple overview alone. I'm quite sure no one would be disappointed if i removed those in an HRP server.

I literally said subtle memery is fine, especially when it's literally memes *about* the game and not autistic internet humor shit that has nothing to do with the game. Turning a pet into one of the most abusable roundstart weapons in the game is definitely not fine. Nice stretch, though. :^)

**Comment by BobJoga** [comment]
> > > Better yet, why don't we remove all the memey bullshit from cheems? A fat dog is fine, but it doesn't need to speak and say stupid meme shit that nobody will think is funny after a month. There's a reason meme shit shouldn't be added beyond subtle reference.
> > 
> > 
> > List of "subtle" memery i can find in the code:
> > 
> > * Crab 17
> > * Gmod styled error icons
> > * Chaplain LRP meme bibles
> > * No ERP poster
> > * Chef CQC
> > * Cumming into reagent containers such as glasses
> > * Revolver plant that can be gotten via xenobio
> > * Ninja mask making you speak like a stereotypical japanese immigrant
> > * Baseball antag kit
> > * Lord singulo antag kit
> > * His grace
> > * Skeleton scream is literally the rattle me bones sound effect
> > 
> > I'm quite sure there is way more that i could find, but this is a simple overview alone. I'm quite sure no one would be disappointed if i removed those in an HRP server.
> 
> I literally said subtle memery is fine, especially when it's literally memes _about_ the game and not autistic internet humor shit that has nothing to do with the game. Turning a pet into one of the most abusable roundstart weapons in the game is definitely not fine. Nice stretch, though. :^)

Ahh yes, Close Quarters Cooking and Tae-clown-do, the subtlest of memes.

**Pull request closed without merging**
