### PR TITLE
[WIP]Drifters

### PR DESCRIPTION
**Pull request by improvedname**
WIP

### CODE REVIEW

**Comment by BobJoga** [comment]
Oh boy it's gonna have conflicts with blueshield once that is merged...

**Comment by Akrilla** [comment]
Any further updates?

**Comment by improvedname** [comment]
This is gonna be parked here for a while

**Comment by CinderWC** [comment]
Considering the amount of conflicts that this is causing. And the fact that this has not received a single commit in a long time. I will be closing this PR

**Comment by Azarak** [comment]
Re-opening due to this supposedly still being under development

**Pull request closed without merging**
