### PR TITLE
FUCK imperial measurements

### PR DESCRIPTION
**Pull request by BobJoga**
## About The Pull Request

Adds a metric toggle to preferences, which changes imperial measurements into based and redpilled metric measurements. It works as you'd expect.

image

image

image

epic

## Why It's Good For The Game

Literally only americans use imperial. This is for the rest of the world.

## Changelog
:cl:
add: Added a toggle for metric measurements. Thank me later.
/:cl:

### CODE REVIEW

**Comment by Arctaisia** [comment]
I still have no idea where imperial is used because I always refer to a tile as 1m squared, but yes, fuck imperial, why the fuck does 3 grains of barely make sense for measurement, it's literaly saying 'My dick is 60 grains of barely long'

**Comment by Investigator77** [comment]
Based PR

**Comment by Arctaisia** [comment]
Although only big concern, for the dick size thingy, it seems to still have the inches value for the max size, which would be 5 inches by 20 inches, which would be around a 1:4 ratio, and is for all of them, but 1:10 seems like a spaghetti noodle in comparrison

**Comment by BobJoga** [comment]
> Although only big concern, for the dick size thingy, it seems to still have the inches value for the max size, which would be 5 inches by 20 inches, which would be around a 1:4 ratio, and is for all of them, but 1:10 seems like a spaghetti noodle in comparrison

The values are converted on the fly for those who use metric.

**Comment by RatFromTheJungle** [comment]
imagine not being able to use freedom measurements smh

**Pull request merged**
